[2단계 - 자동차 경주 미션] 코카콜라(강인태) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #100
Opened 2022-02-17 11:35 UTC by intae92

안녕하세요~ 로이님👍 2단계 미션 제출합니다.
step1에서 추가로 남겨주신 코멘트 잘 확인했습니다. 네이밍과 역할분리가 얼마나 중요한지 다시 한번 느꼈습니다. step2에서는 다음과 같은 상황을 고려했습니다. 많은 조언 부탁드립니다.

## step2 반영
1. 'support/commands.js' 파일에 Commands 분리, 테스트 코드 역할 분리 Given, When, Then
2. 게임이 끝난 후 2초 후에 축하 메시지 표출되는지 테스트 코드 작성
3. 자동차 경주 게임의 턴 진행시 1초의 텀 발생
4. 1초의 턴 동안 로딩 애니메이션 표출
5. 직관적인 네이밍 작성(여전히..어렵네요..)

## 궁금한점
- [step2반영-No.2] 2초 후에 축하 메시지 표출 되는 `테스트 코드를 setTimeout()으로 확인하는게 맞는지 궁금합니다 `cypress/intergration/racingcar.spec.js Line:67
cy.tick()으로 확인을 할려고 했는데 제가 원하는 동작으로 실행이 안되어서 setTimeout으로 구현했습니다.(제가 잘 몰라서 그러겠죠?ㅜㅜ)
테스트 코드에 setTimeout()으로 확인을 해도 되는지 궁금합니다. 
- [step2반영-No.3] `게임의 턴 진행시 1초의 텀을 async/await으로 비동기 처리를 했는데요.` view/renderResult.js Line:79
"일단 구현은 되야지!"라는 생각으로 코드를 작성했지만 너무 하위 함수를 내려가는? 느낌이 드네요...코드를 한눈에 파악하기 힘들꺼 같은 느낌이 듭니다. `어떤식으로? 코드를 짜야 깔끔할지 잘 모르겠습니다.` 질문을 드리면서도 명확하게 질문을 드려야 할 텐데 죄송합니다. 코드를 너무 난해하게 작성한거 같아요..ㅠㅠ
- 위의 질문과 비슷합니다. 코드가 난해하다고 느끼는 부분이 view/renderResult.js Line:60 domInit() 함수라고 생각이 드는데요
평소 React, styled-components에 익숙해서 Template literals으로 Element를 구현하는데요. 이번에는 게임 진행 시 1초의 텀에 로딩 애니메이션을 구현하기 위해 dom 객체를 document.createElement()으로 생성해서 기능을 구현했습니다. 
상황에 따라 다르겠지만 `document.createElement()으로 dom객체를 생성해서 제어 하는게 좋을지, Element.innerHTML =`` Template literals으로 DOM을 제어하는게 좋은지에 대해 어떻게 생각하시는지 궁금합니다. `

## 감사합니다!!!

2022-02-18 11:32 UTC, roy-jung requested changes
코카콜라님, 고생하셨습니다.
지난번 피드백 드린 내용 잘 반영된 것 확인했습니다.
테스트해보면서 문제상황이나 동작여부를 확인하고 싶은데 아쉽네요. 이번 기수 분들은 아직 github-page로 실제 가동할 수 있는 데모페이지를 제공하지 않고 있군요ㅠ 시간 나실때 github-page에 연동하는 방법을 알아보시면 좋겠어요.

아래는 질문하신 내용들에 대한 답변입니다.
- [cy.tick](https://docs.cypress.io/api/commands/tick#Yields) 공식문서를 살펴보면 최상단에 `cy.clock`이 반드시 먼저 호출되어 있어야 한다고 설명하고 있습니다. 이 녀석이 하는 일은 저도 써보지 않아 정확히는 모르겠는데, 정상적인 테스트가 안되는 경우가 있나보군요. 특정시간동안 '대기'를 하는 `cy.wait` 명령도 잘 동작하니 확인해 보세요.
- 가독성 높은 코드를 짜는 방법은, 지금처럼 계속 고민하면서 다양한 방법을 시도해보고, 다양한 패턴이나 다른 사람의 코드를 계속 접하는 수밖에 없어요. 그러다보면 시간에 따라 자연히 더 나은 방법을 찾아내시게 될거예요.
- createElement vs. innerHTML 관련해서는 별도 코멘트 남겼습니다.

코멘트 확인하시고 1차 피드백 반영해주시면 다음에 좀 더 살펴보도록 할게요!

2022-02-20 14:18 UTC, intae92 commented on src/js/core/playRacing.js
> +export const getGameResult = ({ carNames, tryCount }) => {
말씀 하신데로 생각해보니 '플레이'하는게 메인 이더라구요.
그런데 왜 'getGameResult'로 네이밍을 했냐면 게임 결과 값을 가지고 렌더링을 해야 한다고 생각해서 저렇게 지었던거 같아요
그래서 게임 플레이 로직을 class로 변경해서 game.play(), game().getResult()로 바꿔 볼려고 했지만 너무 많은걸 바꿔야 해서....일단 함수명만 변경했습니다.

2022-02-20 14:20 UTC, intae92 commented on src/js/view/loading.js
> +    <div></div>
div 4개는...각각 애니메이션 걸어서 좀 더 로딩 모션이 잘 보이게 만들었는데 다시 보니 불필요인거 같아 1개로 줄였습니다...

2022-02-20 14:20 UTC, intae92 commented
[데모페이지](https://intae92.github.io/javascript-racingcar/)
---
안녕하세요~ 로이님!
이번 피드백 반영이 Level1의 마지막 반영일꺼 같은데요, 우선 그 동안 리뷰를 해주셔서 감사했습니다.

다음과 같은 피드백을 반영했습니다.
- 데모페이지 생성
- innerHTML의 단점을 알려주셔서 나름 찾아 보고 코드에 반영했습니다.
- [innerHTML 단점을 알아보다가 웹페이지 텍스트에 접근하는 속성 및 메서드에 대해 알아보고 블로그에 정리했습니다.](https://kit-developer.tistory.com/27)
- 추가로 저번 코멘트 해주신 부분에 답변했습니다.

마지막으로 감사합니다.

2022-02-20 15:47 UTC, roy-jung approved these changes
콜라님 고생하셨습니다.
반영하신 내용 잘 확인했고, 데모페이지 올려주신것도 확인했습니다.

그런데 데모페이지를 몇 번 돌려보니, 정상적으로 카운트가 되지 않는 케이스가 종종 발생하네요.
예를들어 3회를 입력했는데 2회만에 끝난다거나, 10회를 입력했는데 6회만에 끝나는 등으로요..

추측하기로는, 계산 파트와 렌더 파트를 나누는 과정에서
계산쪽은 동기로 작업되어 게임시작 즉시 모든 계산이 끝나는 반면
렌더파트는 비동기로 진행되다보니 명령이 일부 누락되는 것이 아닐까...싶은데
시간 괜찮으실 때 좀더 면밀히 분석해서 디버깅 해보시는 게 좋을 것 같아요.

시간에 쫓겨가면서까지 완성도를 끌어올려야만 하는 것은 아니고
성장을 위한 과정상의 하나일 뿐이니, 부담된다면 건너뛰어도 괜찮습니다.
이번 미션에서는 step-1때부터 겪은 네이밍에 대한 고민, 더 가독성 있는 코드에 대한 고민, 더 좋은 구조에 대한 고민을 해본 것으로 충분하고, 앞으로도 이런 고민을 계속 하면서 성장하시게 될테니까요!!

아무튼 아직 마감까지 시간이 조금은 있으니, 디버깅 해보실 의향이 있다면 해보시도록 머지는 하지 않고 남겨두겠습니다. 월요일 오후에 머지할게요. 고생하셨습니다!

2022-02-20 15:47 UTC, roy-jung commented on src/js/core/checkTryCount.js
>  };
좀더 간단하게 표현해보시면 좋겠습니다.

2022-02-21 05:10 UTC, intae92 commented
로이님 리뷰 감사합니다.
말씀하신 사항 확인 후 반영하였습니다.
- 입력한 시도 횟 수 만큼 화면에 노출되지 않은 점 확인 했습니다. 제가 기획을 제 생각대로 해석을 했더군요...(정확히는 사용자 입장에서 생각을 하지 못했습니다.) 게임 진행 시, "모든 자동차가 전진 하지 않을 시!!!" 이 부분을 그냥 무시 하고 1초의 텀을 노출 시키지 않았네요..ㅠ
- 좀 더 사용자 입장에서 생각하도록 하겠습니다.

감사합니다!!!

2022-02-21 05:25 UTC, merged