[2단계 - 자동차 경주 구현] 꼬재(고재증) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #102
Opened 2022-02-18 04:31 UTC by kkojae91

안녕하세요 율리님! 🤗

1단계에서 말씀해주신 부분 반영하여 PR 보냅니다!

createElement, appendChild 등은 아무래도 가독성 측면이 좋지 않다고 판단이 되어 innerHTML은 insertAdjacentHTML로 변경했습니다.
insertAdjacentHTML은 기존 요소에 영향을 주지 않고 새롭게 삽입될 요소만을 파싱하여 자식요소로 추가한다 하여 선택했습니다. 또한 template을 랜더하는 과정에서 사용자 입력 값을 render 하는 부분은 textCotent를 사용해 크로스 사이트 스크립팅 공격을 예방했는데 괜찮은 방법일까요?! 😯

MVC 패턴에 대해서도 제가 이해한 내용을 간단히 요약해서 작성해보도록 하겠습니다. 부족하거나 추가적인 학습이 필요하다고 느껴지시면 말씀해주시면 감사하겠습니다! 😁

Model : 데이터 저장소
View : UI 관련
Controller : Model과 View를 연결하는 다리 역할

Model과 View는 다른 컴포넌트들에 대해 알지 못한다. 자기 자신이 무엇을 수행하는지만 알고 있다.
Controller는 자기 자신이외의 Model, View가 무엇을 수행하는지 알고 있고 View의 요청을 가공을 통해 Model에 저장하고 Model에 있는 데이터를 불러와 View를 통해 UI를 그린다.
 
제가 생각하는 MVC 패턴대로 작성을 했는데, View에서 getter와 setter의 양이 많아지고 Controller가 무거워지는 느낌이 있는 것 같아요... 😓

2단계 피드백도 잘 부탁드리겠습니다!! 🙏🏼

2022-02-18 22:56 UTC, glassyi commented on cypress/integration/racingcar.spec.js
> +}
👍  cypress에서도 잘 돌아가는거 확인했습니다. 함수로 분리한 부분 좋아요. 👏
이렇게 공통으로 사용할만한 함수는 commands 파일에 분리해서 사용할 수 있을 것 같아요. [custom-commands](https://docs.cypress.io/api/cypress-api/custom-commands#Syntax)
cypress/support/commands.js 파일에 주석처리 되어 있는 부분이 있으니 그걸로 참고하셔도 좋겠어요!

2022-02-18 23:14 UTC, glassyi commented on cypress/integration/racingcar.spec.js
> +    );
waitRepeatedly을 호출할 때 넘기는 인자가 많아서 이게 어떤 값인지 다시 waitRepeatedly함수를 확인해야 하고, 인자를 입력하는 순서를 알아야 하는 부분때문에 아래와 같이 객체로 묶어서 키, 값으로 전달할 수 있게 하는게 어떨까 해요~ 
```suggestion
    waitRepeatedly({
      selector: SELECTOR.$SPINNER,
      type: 'be.visible',
      delay: DELAY.RACING_PROGRESS,
      repeatCount: racingCount
    });
```

```js
function waitRepeatedly({selector, type, delay, repeatCount})
```
받는 파라미터가 2개 이상일 때 객체로 묶어서 인자로 넘기고 함수에서 받을 때 전달 받은 객체를 구조분해해서 사용할 수 있게 리팩토링해볼 수 있겠네요.

2022-02-19 00:14 UTC, glassyi commented on src/js/constants.js
> +export const DELAY = {
LATENCY 또는 DELAY_TIME 이 더 명확할것 같은데 어떨까요?

2022-02-19 00:16 UTC, glassyi commented on src/js/utils/utils.js
> +export function sleep(delay) {
sleep 보다는 delay가 더 보편적일것 같아요 🙂

2022-02-19 02:16 UTC, glassyi commented
> createElement, appendChild 등은 아무래도 가독성 측면이 좋지 않다고 판단이 되어 innerHTML은 insertAdjacentHTML로 변경했습니다.
> insertAdjacentHTML은 기존 요소에 영향을 주지 않고 새롭게 삽입될 요소만을 파싱하여 자식요소로 추가한다 하여 선택했습니다. 또한 template을 랜더하는 과정에서 사용자 입력 값을 render 하는 부분은 textCotent를 사용해 크로스 사이트 스크립팅 공격을 예방했는데 괜찮은 방법일까요?! 😯
> 
> MVC 패턴에 대해서도 제가 이해한 내용을 간단히 요약해서 작성해보도록 하겠습니다. 부족하거나 추가적인 학습이 필요하다고 느껴지시면 말씀해주시면 감사하겠습니다! 😁

1. 꼬재님이 적어주신것처럼 insertAdjacentHTML로 처리해주신 부분은 잘 하셨네요. 👍
2. XXS 의 기본 방어하는 방법은 스크립트 삽입하는 방식으로 주로 발생하기 때문에 태그 코드로 사용되는 < , > 와 같은 문자를 이스케이프 처리된 텍스트로 변경하는 거라고 하네요. 그래서 textCotent만 사용해서는 안되고 위와 같은 처리를 별도로 해줘야 하는데 저희는 일단 이런 방법이 있다 정도만 알고 다음에 이러한 처리가 필요한 상황에서 적용해 보심 될 것 같아요!


> Model과 View는 다른 컴포넌트들에 대해 알지 못한다. 자기 자신이 무엇을 수행하는지만 알고 있다.
Controller는 자기 자신이외의 Model, View가 무엇을 수행하는지 알고 있고 View의 요청을 가공을 통해 Model에 저장하고 Model에 있는 데이터를 불러와 View를 통해 UI를 그린다.

> 제가 생각하는 MVC 패턴대로 작성을 했는데, View에서 getter와 setter의 양이 많아지고 Controller가 무거워지는 느낌이 있는 것 같아요... 😓

꼬재님이 작성한 코드 내용에서 좀 더 고민했으면 하는 부분은요. View가 지금 하나로만 작성되어 있는데요, 이걸 자동차 경주 화면 하나로 보지말고 값 입력 폼 view, 레이싱 경기진행 view, 결과를 보여주는 view 대략 더 나눠볼 수 있지 않을까요? 하나의 view로 다 처리를 하려다 보니 코드가 길어지고 뭔가 정리가 안되는 느낌을 더 받는 것 같아요. 그럼 Controller도 view에게 지시할 때 특정 view를 가리켜 지시하면 될 것 같고요. 그리고 Controller에서 너무 뷰의 일을 다 가지고 있다는 느낌을 받았는데 
```js
this.view.render(selector, position, template)
```
이 부분도 사실 어디에, 어떤 위치에, 어떤 템플릿으로 그릴지는 뷰가 알아서 하고 Controller는 모델의 데이터 전달해줄게! 실행해! 라고 알려주는 편이 좋을 것 같다고 생각했어요. 이건 뷰가 나뉘면 자연스럽게 해결될 수 있을거라고 생각이 드네요. 😄

2022-02-19 02:47 UTC, glassyi commented on src/js/controller/RacingCarGame.js
>      this.model.carList = carNameList.map((name) => new Car(name));
어떤 값으로 모델의 데이터를 업데이트할지는 모델에서 해도 무방할 것 같네요.

2022-02-19 02:49 UTC, glassyi commented on src/js/utils/validations.js
> +}
`previousDistance < currentDistance` 만으로 충분히 어떤 조건을 말하는지 바로 알 수 있어서 따로 함수로 분리시키지 않아도 될것 같네요.

2022-02-19 05:37 UTC, kkojae91 commented on cypress/integration/racingcar.spec.js
> +}
넵 보내주신 링크 확인했습니다.
custom-commands로 변경하겠습니다! 🙂

2022-02-19 05:38 UTC, kkojae91 commented on cypress/integration/racingcar.spec.js
> +    );
넵.. 전달되는 인자가 많으면 객체로 묶어주는 방법이 가독성 측면에서 좋은 것 같아요!! 감사합니다.🙂

2022-02-19 05:47 UTC, kkojae91 commented on src/js/utils/utils.js
> +export function sleep(delay) {
넵 의미를 조금 더 보편적이고 명확하게 가져가보도록 할게요!!

2022-02-19 05:59 UTC, kkojae91 commented on cypress/integration/racingcar.spec.js
> +    cy.wait(racingCount * DELAY.RACING_PROGRESS + DELAY.WINNER_ALERT).then(
게임의 턴이 진행되는 시간은 따로 분리해두었습니다!
근데 축하 메세지를 보여주기 위해서는 자동차 경주 게임의 턴이 모두 종료가 되어야 하는데, 분리가 어려울 것 같아요!!
(혹은.. 제가 방법을 모르는 것일까요...?! 🥲)

지금 상황에서는 율리님이 말씀해주신 후자의 방법이 조금 더 좋은 선택인 것 같아요.
"자동차 경주 게임이 종료되고, 경주의 우승자가 결정되면 2초 후에 축하의 메시지를 보여준다." 와 같은 경기 결과가 나오면 축하 메세지를 보여준다의 느낌이 더 좋은 것 같아요!

2022-02-19 13:47 UTC, kkojae91 commented
> 2. XXS 의 기본 방어하는 방법은 스크립트 삽입하는 방식으로 주로 발생하기 때문에 태그 코드로 사용되는 < , > 와 같은 문자를 이스케이프 처리된 텍스트로 변경하는 거라고 하네요. 그래서 textCotent만 사용해서는 안되고 위와 같은 처리를 별도로 해줘야 하는데 저희는 일단 이런 방법이 있다 정도만 알고 다음에 이러한 처리가 필요한 상황에서 적용해 보심 될 것 같아요!

textContent를 사용하면 태그는 제외하고 삽입되니 해결이 되는 줄 알았어요.. 🥲 
DOMPurify 라이브러리를 사용하면 된다고 하는데 추가적으로 학습을 해봐야겠어요! 감사합니다! 🙏🏼


> 이 부분도 사실 어디에, 어떤 위치에, 어떤 템플릿으로 그릴지는 뷰가 알아서 하고 Controller는 View에게 실행해! 라고 알려주는 편이 좋을 것 같다고 생각했어요. 이건 뷰가 나뉘면 자연스럽게 해결될 수 있을거라고 생각이 드네요. 😄

율리님 이부분 설명이 너무 알아 듣기 쉬웠던 것 같아요! 방법이 맞는지 모르겠지만, view를 분리하고 controller에서 명령을 하게끔 작성하니 한결 정리된 듯한 느낌이 들어요! 감사합니다! 😊

추가적으로 디벨롭해야하는 부분이 있으면 말씀해주시면 감사하겠습니다!! 😯

2022-02-20 08:21 UTC, glassyi commented on src/js/index.js
> +new View();
index.js에서 View를 인스턴스 생성하는 이유가 뭔가요? 😲

2022-02-20 08:24 UTC, glassyi commented on src/js/index.js
> +  new RacingResultView()
Model 과 View들을 RacingCarGame의 constructor에 할당해서 사용하려는 꼬재님의 생각이 궁금해요~

2022-02-20 08:33 UTC, glassyi commented on src/js/model/Model.js
> +  #winnerNames = [];
private class filed를 쓰셨네요 👍  private class filed는 기존 class 속성과 어떤 차이가 있고, 이렇게 변경하고자 한 이유가 어떤 걸까요? 🙂

2022-02-20 08:52 UTC, glassyi commented on src/js/view/View.js
>      this.$app = $(SELECTOR.$APP);
어디에 프로그램 app의 root 요소로 할건지는 레이싱카 프로그램을 실행하는 최상위에서 root 셀렉터를 인자로 받거나, 지정하거나 하는게 좋지 않을까요?

2022-02-20 09:02 UTC, glassyi commented on src/js/view/View.js
>    removeElements(parentElements, selector) {
```js
if (!parentElements.length) {
      parentElements.removeChild($(selector));
      return;
    }
```
parentElements.length가 0인데 parentElements에 접근이 안되지 않을까요?

2022-02-20 09:24 UTC, glassyi commented on src/js/view/View.js
>    removeElements(parentElements, selector) {
parentElements가 querySellectorAll이 아니고 querySellector로 접근한 단일 요소인데 없을 경우 undefined 뜹니다. length가 0이거나 undefined일 때 조건이 성립해서 조건문이 실행되고 있는데요. 제 생각엔 방어코드로서 넣으신 것 같은데 조건 다시 확인해 주셔야 할 것 같아요. 😲

2022-02-20 09:59 UTC, glassyi commented on src/js/controller/RacingCarGame.js
> +        this.model.previousCarDistanceList[index] = car.distance;
꼬재님의 의도가 분명하다면 그것 또한 옳아요 ㅎㅎ 다만 저는 Model이 아닌 Car에서 distance를 관장하고 있다보니 Model에 이전Car distance를 관리하는 이유가 궁금해서 여쭤봤어요. 지금은 다시 컨트롤러가 가지고 있는것 같은데 Car에서 이전 distance를 저장하고 비교하는건 어떻게 생각하시나요? 그러면 굳이 모든 cars의 distance를 가진 배열이 필요 없어질것 같거든요.

2022-02-20 11:27 UTC, glassyi commented on cypress/integration/racingcar.spec.js
> +describe('로딩', () => {
'로딩' 보다 좀 더 이해하기 쉬운 설명이 없을까요?

2022-02-20 11:48 UTC, glassyi commented on src/js/utils/validations.js
> +}
변수 네이밍이 잘되어 있고 어떤 조건을 말하는지 의도를 바로 알 수 있어서 분리하지 않아도 될 것 같다고 말씀드린 거구요~ 꼭 단순 비교 조건에는 함수로 분리시키지 않아도 된다 라는 의미는 아닙니다~ 🙂  혹시나 의미를 잘못 받아 들였을 까봐 말씀드려요.

2022-02-20 12:22 UTC, glassyi requested changes
꼬재님! 😊  빠르게 피드백 반영해 주셨네요.
이전보다 확실히 기능의 역할 분리가 잘 되어졌어요! 👍 👍
테스트 코드들의 요구사항 문구도 더 명확하게 변경한 점 좋네요.
추가로 나머지 코멘트들과 질문 남겼으니 그 부분만 답변 및 확인 부탁드려요~

아래는 필수사항은 아니지만 여유가 되신 다면 시도해 봐도 좋을 부분들을 남겨요.
- 이번 미션에서 setTimeout을 활용해주셨는데요~ setTimeout과 함께 clearTimeout은 현재 코드에서 어떤식으로 적용할 수 있을지도 한번 고민해보면 좋겠네요.
- requestAnimationFrame을 활용하여 현재 delay 코드를 변환하는건 어떻게 해볼 수 있을지 시도해 보셔도 좋겠네요. 🙂

2022-02-20 12:25 UTC, kkojae91 commented on src/js/index.js
> +new View();
View 인스턴스를 생성해야, bindEventListener가 연결되는줄 알았던 것 같아요.. event 바인딩은 다른 뷰에서 하고 있으니 굳이 인스턴스를 생성하지 않아도 되겠군요!! 🙂

2022-02-20 12:30 UTC, kkojae91 commented on src/js/utils/validations.js
> +}
아하.. 넵!! 무슨 말인지 이해했습니다! 감사합니다! 🙂

2022-02-20 12:33 UTC, kkojae91 commented on src/js/controller/RacingCarGame.js
> +        this.model.previousCarDistanceList[index] = car.distance;
현재 커밋은 하지 않았지만 requestAnimationFrame을 사용하면서 변수를 클로저를 활용해서 previousDistance 배열을 가지고 있는것으로 변경했는데요.
Car에서 이전 distance를 저장하고 비교하는 것 중 더 나은 선택은 어떤게 될까요..?! 😯
율리님이 말씀하신것을 생각해봤는데, 컨트롤러가 가지고 있는것 또한 맞지 않는 방법인것 같아 궁금합니다!

2022-02-20 12:38 UTC, kkojae91 commented on src/js/index.js
> +  new RacingResultView()
필요한 곳에서 Model과 View들을 불러들이는 것보다, Controller에서 한 번에 Model과 View들을 관리하는게 더 수월하다고 판단이 되어 위와 같이 코드를 작성했어요!
혹시 잘못된 판단일까요??! 혹은 더 좋은 방법이 있을까요?! 😯

2022-02-20 12:39 UTC, kkojae91 commented on src/js/model/Model.js
> +  #winnerNames = [];
private class filed를 사용하면 외부에서 해당 데이터에 직접적으로 접근하여 값을 참조하거나 변경할 수 없다고 알고 있습니다. 조금 더 안전하게 데이터를 보호할 수 있어 private class filed로 변경했어요!

2022-02-20 12:49 UTC, kkojae91 commented on src/js/view/View.js
>      this.$app = $(SELECTOR.$APP);
최상위라 하면 index.js 를 말씀하시는 것일까요?
app 또한 View에 대상이라고 판단했고, 필요하지 않는 곳에서 부터 인자로 Controller로 넘겨주고 Controller에서 View로 넘기는 것은 비효율적인 방법은 아닌가요?! 
(제가 하는 말이 혹시 이해되지 않으실  수 있을것 같아 아래 코드로 작성해봤어요...! 혹은 제가 율리님 말씀을 잘못 이해하고 있는 것인가요..?!)
```javascript
// index.js
new Controller("#app");
```
```javascript
// Controller.js
constructor(rootSelector) {
  new View(rootSelector)
}
```
```javascript
// View.js
constructor(rootSelector) {
  const this.$app = $(rootSelector);
}
```
인자로 넘겨주는 것과 View에서 직접 해당 돔을 가지고 오는것과 어떤 차이가 있는지 궁금합니다!

2022-02-20 12:52 UTC, kkojae91 commented on src/js/view/View.js
>    removeElements(parentElements, selector) {
넵 아마도.. querySelectorAll로 잡힌 요소들과 querySelector로 잡은 요소를 한 함수에서 처리하고 싶은 마음이 있어 작성했었습니다.
이런 경우는 방어 코드를 작성하는 것 보다는 함수를 분리해서 가지고 가는게 더 좋을것 같네요! 수정하도록 하겠습니다!  😓

2022-02-20 12:52 UTC, kkojae91 commented on cypress/integration/racingcar.spec.js
> +describe('로딩', () => {
넵 조금 더 이해하기 쉬운 설명으로 변경해볼게요!!

2022-02-20 13:15 UTC, glassyi commented on src/js/controller/RacingCarGame.js
> +        this.model.previousCarDistanceList[index] = car.distance;
네. 저 또한 컨트롤러가 이전 distance 값들을 속성으로 가지고 있을 이유가 없을 것 같다고 생각이 드네요. 일단 꼬재님이 어떤식으로 requestAnimationFrame 사용하여 변경 하셨는지 궁금합니다. 🥺

2022-02-20 13:20 UTC, kkojae91 commented on src/js/controller/RacingCarGame.js
> +        this.model.previousCarDistanceList[index] = car.distance;
조금 전에 우선 구현된 것 푸쉬 했습니다...!! 뭔가 지저분한 것 같아 수정이 필요할 것 같긴하지만.... 확인해주시면 감사하겠습니당!! 🥲

2022-02-20 13:50 UTC, glassyi commented on src/js/index.js
> +  new RacingResultView()
아뇨~ 😄  잘못되지 않았습니다. 다만 작성하는 방법이 조금씩 다를뿐이죠. 꼬재님이 작성하신 새로운 인스턴스들을 받아서 사용하는 것도 그런 방법중에 하나라고 생각해요.

2022-02-20 14:03 UTC, glassyi commented on src/js/view/View.js
>      this.$app = $(SELECTOR.$APP);
음.. 지금 코드에 적절한 질문은 아니였네요. 🥲  전체적인 뷰의 화면 요소들이 html 파일에 있다보니 사실상 특정 root 셀렉터를 받아올 이유는 없겠네요. 레이싱카 앱에서 화면을 모두 그리게 된다면 그 때 필요하지 않을까 생각되어요. 참고만 해주세요. 😄

2022-02-20 14:08 UTC, glassyi commented on src/js/view/View.js
>      this.$app = $(SELECTOR.$APP);
그리고 View.js가 하위 뷰들의 공통적인 메소드들을 가지는 부모 클래스다 보니 속성값으로 고정된 app selector을 알고 있는게 맞을까하는 의구심이 들었습니다. 🙂

2022-02-20 15:00 UTC, kkojae91 commented on src/js/index.js
> +  new RacingResultView()
넵!! 다른 크루들 코드도 보면서 어떻게 작성하는지 봐야할 것 같아요!!

2022-02-20 15:02 UTC, kkojae91 commented on src/js/view/View.js
>      this.$app = $(SELECTOR.$APP);
넵 확인해주셔서 감사합니다!!
```html
<div id='app'></div>
```
위와 같이 html하위 요소가 없을 경우에는 율리님이 말씀하신 것 처럼 진행하면 좋을 것 같아요!! 😊 (맞겠죠..?!🥲 )

2022-02-21 10:28 UTC, glassyi commented on src/js/view/RacingResultView.js
> +        `${winners.join(DELIMETER.COMMA)}` + WINNER_MESSAGE.CELEBRATION
```js
`${winners.join(DELIMETER.COMMA)} ${WINNER_MESSAGE.CELEBRATION}`
```
이렇게 써도 될 것 같아요.

2022-02-21 10:31 UTC, glassyi commented on src/js/controller/RacingCarGame.js
> +  bindingEventListener() {
binding 으로 바꾼 이유가 있나요?

2022-02-21 14:05 UTC, glassyi approved these changes
꼬재님! 😀  이전 코멘트한 내용들을 대체로 잘 반영해주셔서 바로 머지하도록 할게요!
함수명이나 구조 관련해서는 미션을 거듭할수록 더 좋아지실거라 생각합니다!
이번 미션에서 제 코멘트들이 조금이나마 꼬재님에게 도움이 되었길 바래요!
고생하셨습니다~!

2022-02-21 14:05 UTC, merged