[2단계 - 자동차 경주 미션] 소피아(전소이) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #109
Opened 2022-02-18 08:44 UTC by soyi47

2022-02-19 07:59 UTC, hyoungnam requested changes
1. 코멘트 남겼으니 확인해주시면 좋을것 같습니다!!
2. section에 제목이 없어 div를 사용하는것은 옳지 않습니다. div는 의미요소가 없는 태그입니다. [Section](https://html.spec.whatwg.org/multipage/sections.html#the-section-element) htmlspec이 나와있는 문서로 해당 링크의 Note부분을 참고하시면 좋을것 같습니다. 문서에서 element들이 어떤 category이고 어떤 context에서 사용되는지, 그리고 content model이 무엇인지 알아보면 어떻게 마크업을 해야할지 도움될것 같네요~!
3. submit으로 바꾸었을때 어떻게 안되는지 예시를 보여주실수 있을까요?

추가적으로 지금 레이싱이 시작했을때 로딩 인디케이터가 두번 돌고나서 시작하는 상황입니다. 또한 시도횟수가 ‘2’라고 가정하고 레이싱이 시작되었을때, 레이싱카의 최대 전진횟수가 '1'인 상황이여서 개선이 필요할것 같네요

2022-02-19 07:59 UTC, hyoungnam commented on src/RacingGame.js
> +            this.view.updateProgress(this.racingCars.cars);
View 클래스가 RacingCar 클래스 변수에 직접 접근하도록 하는것이 맞을까요??

2022-02-19 07:59 UTC, hyoungnam commented on src/RacingGame.js
> +        this.view.showTrackSection(this.racingCars.cars);
위의 코멘트와 동일합니다

2022-02-19 07:59 UTC, hyoungnam commented on test/racingCar.spec.js
> +    context('결과 출력', () => {
어떤 결과인지 또는 어떤 시나리오인지 더 구체적인 이름이 명시되면 좋지 않을까요?

2022-02-19 07:59 UTC, hyoungnam commented on test/racingCar.spec.js
> +    context('입력 예외 처리', () => {
이 파일을 열었을때 입력 예외 처리보다 어떤 시나리오의 통합 테스트가 이루어지는지 먼저 읽어보고 확인해보고 싶지 않을까요? 입력 예외 처리보다 결과 출력 부분이 더 앞에 있는것이 좋지 않나 생각됩니다!

2022-02-19 07:59 UTC, hyoungnam commented on index.html
>          <h3 class="stage">🏆 최종 우승자: <span id="winners"></span> 🏆</h1>
저번에 이부분을 못잡았네욯ㅎㅎ <h3><h1>

2022-02-19 07:59 UTC, hyoungnam commented on src/userInputValue.js
> +    },
userInputValue 파일을 따로 만들 필요가 있는지 한번 고려해보는것도 좋을것 같네요

2022-02-19 08:02 UTC, soyi47 commented on index.html
>          <h3 class="stage">🏆 최종 우승자: <span id="winners"></span> 🏆</h1>
여기는 어떤 부분 말씀하시는 걸까요??

2022-02-19 08:06 UTC, soyi47 commented on index.html
> +      </form>
하나의 form으로 할까 고민하다가, view에 나타나는 순서가 다르기도 하고, 위에서 언급한대로 form submit 이벤트를 따로 주려고 하다 보니 이렇게 작성했습니다...!

2022-02-19 08:07 UTC, soyi47 commented on index.html
> +          <button class="form-button blue-button" type="button" id="car-name-submit-button">확인</button>
같은 css 적용이 필요한 요소들에는 같은 class를 주었고요. 개별로 DOM에 접근해야 할 필요가 있을 때 id를 주었습니다.

2022-02-19 08:08 UTC, soyi47 commented on src/userInputValue.js
> +    },
그러네요. reset은 view로 넘기고, 나머지 input value를 가져오는 로직의 위치는 다시 고민해보겠습니다.

2022-02-19 08:09 UTC, soyi47 commented on src/templates/template.js
>  const template = {
이 부분은 그냥 습관적으로,, 그렇게 한 것 같아요. View 폴더를 하나 만들고 template.js를 옮기는 방식 괜찮을까요?

2022-02-19 08:24 UTC, soyi47 commented on src/RacingGame.js
> +            this.view.updateProgress(this.racingCars.cars);
새로운 배열로 만들어서 넘겨주면 어떤가요?
```
this.view.updateProgress([...this.racingCars.cars]);
```

2022-02-19 09:52 UTC, hyoungnam commented on index.html
>          <h3 class="stage">🏆 최종 우승자: <span id="winners"></span> 🏆</h1>
`<h3></h1>` 입니다:)

2022-02-19 09:53 UTC, hyoungnam commented on src/templates/template.js
>  const template = {
넵 좋은 생각입니다~!

2022-02-19 09:54 UTC, hyoungnam commented on index.html
> +      </form>
넵 그대로 가도록해요~!

2022-02-19 09:57 UTC, hyoungnam commented on index.html
> +          <button class="form-button blue-button" type="button" id="car-name-submit-button">확인</button>
어떤 규칙이 있는것 같아 물어보았는데 적절하게 사용하시는것 같습니다! 😊

2022-02-19 09:58 UTC, hyoungnam commented on src/RacingGame.js
> +            this.view.updateProgress(this.racingCars.cars);
racingCars에서 따로 메소드를 만들어보는건 어떨까요?!?

2022-02-19 10:07 UTC, soyi47 commented on index.html
>          <h3 class="stage">🏆 최종 우승자: <span id="winners"></span> 🏆</h1>
아앗.. 감사합니다!

2022-02-19 11:19 UTC, soyi47 commented on src/View.js
>  export default class View {
RacingGameView 정도의 이름만 떠오르네요 😂

2022-02-19 11:54 UTC, hyoungnam commented on src/View.js
>  export default class View {
저도 그 이름이 적절한것 같네요 😊

2022-02-19 12:24 UTC, soyi47 commented on src/RacingGame.js
> +            this.view.updateProgress(this.racingCars.cars);
racingCars에서 cars를 private 변수로 만들고, getter를 추가하는 방식 어떤가요?

2022-02-19 13:05 UTC, soyi47 commented on index.html
> +        <label class="form-label">5자 이하의 자동차 이름을 콤마로 구분하여 입력해주세요.</label>
말씀 주신 대로 for 속성 찾아봤습니다.
input 요소와 연관짓기 위해서 label에 input의 id와 같은 값을 for 속성으로 넣을 수 있네요. 추가했습니다. 😊

2022-02-19 13:07 UTC, soyi47 commented on src/userInputValue.js
> +    },
나머지 input value는 racingGame에서 필요할 때 바로 가져오도록 옮겼습니다.

2022-02-19 13:15 UTC, soyi47 commented on test/racingCar.spec.js
> +    context('결과 출력', () => {
'게임 실행 결과 출력에 대한 테스트'로 변경했습니다!

2022-02-19 13:17 UTC, soyi47 commented on test/racingCar.spec.js
> +    context('입력 예외 처리', () => {
그럴 수 있겠네요. 다른 사람이 이용할 수 있다고는 생각을 못하고 작성했는데, 테스트를 이용할 다른 사용자의 입장도 잘 고려해서 짜야겠어요. 감사합니다!

2022-02-19 15:43 UTC, soyi47 commented on index.html
> +      <h2 hidden>게임 결과</h2>
더 알아보니 visibility: hidden은 렌더링 되어서 스크린 리더기가 읽어주고, 그냥 hidden 속성을 주면 렌더링을 하지 않는다고 하는데, 보통 이런 상황에서는 어떤 식으로 제목 태그를 넣어주나요?

2022-02-20 06:39 UTC, hyoungnam commented on src/RacingGame.js
> +            this.view.updateProgress(this.racingCars.cars);
넵 좋습니다 private 변수도 얘기하려고 했는데 앞서서 생각해주시네요:)

2022-02-20 06:42 UTC, hyoungnam commented on index.html
> +      <h2 hidden>게임 결과</h2>
음 지금 렌더링되지 않고 스크린 리더를 통해서 읽어지는 상황이 베스트 아닌가요???

2022-02-20 06:44 UTC, hyoungnam commented on test/racingCar.spec.js
> +        const playGameCorrectly = () => {
cypress command와 as를 활용해볼수있을것 같네요!!

2022-02-20 06:45 UTC, hyoungnam commented on src/util/util.js
> +const $ = (selector) => document.querySelector(selector);
```suggestion
const $ = (selector, node = document) => node.querySelector(selector);
```
이렇게 확장해보는건 어떨까요??? querySelector는 꼭 document에서 사용해야하는건 아니에요:)

2022-02-20 06:52 UTC, soyi47 commented on index.html
> +      <h2 hidden>게임 결과</h2>
아 hidden 속성을 주면 스크린 리더에서도 모두 숨겨진다고 나와있어서요!

하나의 표시 방식에서만 숨기려 할 땐 hidden 특성이 적합하지 않습니다. 임의의 요소에 hidden을 추가하면, 그 요소는 시각적 방식 외에도 스크린 리더 등 다른 모든 표시 방식에서 숨겨집니다.
https://developer.mozilla.org/ko/docs/Web/HTML/Global_attributes/hidden

2022-02-20 09:16 UTC, soyi47 commented on src/RacingGame.js
> +            this.view.updateProgress(this.racingCars.cars);
RacingCars 클래스와 Car 클래스의 멤버 변수 private으로 변경하고 getter로 접근 가능하도록 수정했습니다.

2022-02-20 09:17 UTC, soyi47 commented on src/util/util.js
> +const $ = (selector) => document.querySelector(selector);
좋습니다. 어떻게 잘 사용할 수 있을지 고민해서 적용해보겠습니다~

2022-02-20 09:53 UTC, hyoungnam commented on index.html
> +      <h2 hidden>게임 결과</h2>
[Techniques for hiding content](https://webaim.org/techniques/css/invisiblecontent/#techniques)
[콘텐츠 숨기기 및 업데이트](https://developers.google.com/web/fundamentals/accessibility/semantics-aria/hiding-and-updating-content?hl=ko) 
visibility: hidden도 마찬가지네요. 생각을 해보고 자료들을 보았을때 숨기는게 좋지 않네요. 저도 heading을 숨겨본적은 없었던것 같습니다

2022-02-20 09:57 UTC, hyoungnam commented on index.html
> +      <h2 hidden>게임 결과</h2>
[웹 접근성 유투브](https://www.youtube.com/channel/UCTI6h7Vb05Td63qHQ3wjySQ)
[대한항공 마크업 참고](https://www.koreanair.com/kr/ko)

웹 접근성을 공부하다보면 aria에 대한 얘기가 나올꺼에요. 접근성 관련 유투브 영상 있으니 참고하면 좋을꺼고 실제로 어떻게 잘 사용되는 사이트가 대한항공입니다. 국제항공 평가기준에 웹 접근성이 중요해서 굉장히 잘 잡혀있으니 개발자 도구 열고 한번 보면 재밌습니다ㅎㅎ
저도 회사에서 semantic하게 쓰려고 하고 SEO는 신경쓰지만 웹 접근성 마크업은 현실적으로 어려운 상황이라... 접근성에 대한 공부는 이런게 있구나 하는정도로만 공부하시고 나중에 정말 필요하면 그때 적용하시면 됩니다.

2022-02-20 10:05 UTC, soyi47 commented on index.html
> +      <h2 hidden>게임 결과</h2>
앗 그러네요 둘 다 똑같이 리더기에서 안 읽히는군요. 😂
자료 감사합니다. ㅎㅎ 한 번씩 훑어보고, 말씀 주신대로 상황이 주어질 때마다 조금씩 공부하고 고민해보겠습니다.

생각을 해보고 자료들을 보았을때 숨기는게 좋지 않네요. 저도 heading을 숨겨본적은 없었던것 같습니다 => 이 말씀은 안 heading은 숨기는 게 낫다...는 말씀일까요? 그렇다면 지금 heading을 어떻게 처리해야 할지 잘 떠오르지 않네요. 😂

2022-02-20 10:08 UTC, soyi47 commented on test/racingCar.spec.js
> +        const playGameCorrectly = () => {
이런 기능이 있었군요. 한번 적용해보겠습니다!

2022-02-20 10:36 UTC, hyoungnam commented on index.html
> +      <h2 hidden>게임 결과</h2>
음 heading을 없애도 되지 않을까요?

2022-02-20 10:40 UTC, soyi47 commented on index.html
> +      <h2 hidden>게임 결과</h2>
아 그러면 없애는 방향으로 수정해보겠습니다!

2022-02-20 11:51 UTC, soyi47 commented
안녕하세요, 노스님! 주말인데도 많은 코멘트 달아주셔서 감사합니다. 😂

말씀 주신 내용들 반영했습니다~

- turn count 의 경우 <input>에서 한번 validation check를 하긴 하는데, 값을 받은 후에도 한번 더 검사를 할 수 있도록 이전에 작성해둔 ValidationError를 잡는 try-catch문은 그대로 둔 상태입니다. 개인적으로는 더블 체크해서 나쁠 게 없다고 생각하는데, 그대로 두는 것도 괜찮은지 아니면 지워버리는 게 나은지, 보통은 어떻게 처리하는지 궁금합니다.

- 맨 처음 생겼던 '첫 번째 턴의 결과가 반영되지 않는 문제'의 원인은 정확하게 파악하지 못했습니다. setInterval의 콜백함수에서는 두번째 턴 ~ 마지막 턴까지 동작하도록 하고, setInterval 호출 전에 첫번째 턴을 돌렸더니, setInterval의 콜백함수에서 첫번째 턴을 돈 적이 없는 것처럼 모든 step 수를 0으로 가지고 시작하는 문제였습니다. 아직 자바스크립트 동작의 이론적인 부분을 잘 몰라서, 더 공부해보면서 다시 파악해보겠습니다. 😂

2022-02-21 09:29 UTC, hyoungnam requested changes
안녕하세요 소피아님!
데모페이지 통해서 시도 횟수에 따른 전진 확인하였습니다. 문제 끝까지 찾느라 너무 고생하셨고 멋지네요~! 또한 turn count 답변을 드리자면 input field를 통한 validation은 보조적 수단이고 js로 들어온 값에 대한 유효성 검사는 항상 이루어져야 합니다. 추가적으로 heading 부분 간단하게 코멘트 남긴게 있으니 확인해주세요.

2022-02-21 09:29 UTC, hyoungnam commented on index.html
> +        <h3 class="stage">🏆 최종 우승자: <span id="winners"></span> 🏆</h3>
<img width="1055" alt="스크린샷 2022-02-21 오후 6 17 08" src="https://user-images.githubusercontent.com/19677717/154924805-79f08404-3a9f-4c9e-9230-ca1f985d4ca1.png">
[Heading](https://developer.mozilla.org/ko/docs/Web/HTML/Element/Heading_Elements)

2022-02-21 10:49 UTC, soyi47 commented on index.html
> +        <h3 class="stage">🏆 최종 우승자: <span id="winners"></span> 🏆</h3>
아,, 읽어보고 나니 최종 우승자를 출력하는 태그가 꼭 heading 일 필요는 없다는 생각이 드네요. heading 태그를 쓰려면 h1, 아니면 p 태그를 써도 괜찮을까요? 어떤 방식이 더 적절할까요?

2022-02-21 11:32 UTC, hyoungnam commented on index.html
> +        <h3 class="stage">🏆 최종 우승자: <span id="winners"></span> 🏆</h3>
p가 적절할것 같네요!

2022-02-21 13:06 UTC, hyoungnam approved these changes
고생하셨습니다 소피아님!! 문제가 있던 부분 끝까지 잡으려고 했던 부분도 좋았고 코멘트도 잘 읽어주시고 즐거웠습니다. 다음 미션도 화이팅입니다:)

2022-02-21 13:06 UTC, merged

2022-02-21 13:59 UTC, soyi47 commented
감사합니다 노스님! 
주말에도 피드백 계속 주시고, 빠른 소통 위해서 먼저 DM 주셨던 부분도 감사드립니다. 열심히 해보겠습니다. 😁