[2단계 - 자동차 경주 구현] 돔하디(이동현) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #115
Opened 2022-02-18 09:49 UTC by DomMorello

시간이 부족해서 먼저 피드백을 받고자 PR 보냅니다.

동기 / 비동기를 구현하기 위해서 Promise를 활용해서 지연 실행을 구현했습니다.

피드백 주시면 수정해서 반영하겠습니다. 감사합니다.

2022-02-19 17:25 UTC, lsw1164 requested changes
안녕하세요 돔하디님, 2단계 미션 고생많으셨습니다! 

```
// src/view/showResult.js

  const resultContainer = result.children[0];
```
위의 방식처럼 인덱스 번호를 통해 직접 접근하는 방식은 아무래도 엘리먼트 순서가 바뀔 경우 할당되는 엘리먼트 예측이 어렵기 때문에 가급적이면 parentElement의 querySelector를 통해 접근하는 방식을 권장합니다.

다른 부분은 코멘트 참고 부탁드립니다 :)

2022-02-19 17:25 UTC, lsw1164 commented on src/view/showResult.js
> +  return Promise.resolve();
``return Promise.resolve();``는 생략하셔도 되겠습니다.

async function은 암시적으로 Promise를 반환하기 때문입니다!

2022-02-20 08:45 UTC, DomMorello commented
아주 기초적인 부분에서 많은 실수들이 아직도 발생하는 것을 다시 한 번 느끼고 있습니다.
특히, DOM 노드 탐색하는 부분은 앞으로 좋은 습관으로 가져가야 한다고 제대로 배운 것 같아서 좋았습니다.

추가적으로 반복횟수를 입력한 이후에 또 한 번 폼을 제출하면 경기 결과가 계속해서 중복 출력되는 버그를 발견해서
한 번 입력을 완료하면 disabled 시켜서 입력을 방지하고 다시 시작하기만 누를 수 있도록 수정했습니다.

미션동안 앞으로 쭉 가져가야할 좋은 기초습관들에 대해서 피드백 해주셔서 감사합니다. 많이 배웠습니다! :)

2022-02-20 16:42 UTC, lsw1164 approved these changes
안녕하세요 돔하디님, 전반적으로 피드백 반영해주셨군요 👍 
다음 미션부터는 Conversation 탭에 Comment에서도 대댓글로 더 소통하면 
피드백하기 좋을 거 같습니다! 수고 많으셨습니다. Approve 하겠습니다!

2022-02-21 14:04 UTC, merged