[2단계 - 자동차 경주 구현] 후이(최광희) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #121
Opened 2022-02-18 11:36 UTC by kwannee

안녕하세요 리뷰어님! 후이입니다.
바쁘신데도 시간 내주셔서 해주시는 소중한 리뷰 정말 정말 감사드립니다!

step2를 진행하기 이전에 먼저 기존 코드에 대한 리팩토링을 진행했습니다.
우선 view를 세분화하였습니다.
기존 view는 하나의 파일에서 모든 것을 처리하는 방식이라 가독성과 관리를 위해서 세분화를 하는 것이 좋겠다고 판단했습니다.
또한 class 내에 존재하지 않아도 되겠다고 생각한 메소드들을 외부로 분리했습니다.

그 후 step2의 구현을 진행했습니다.
한 번의 레이스를 진행하는 함수를 실행하는 setTimeOut을 Promise로 감싸 1초에 한번 레이스를 진행하도록 했고, 이를 for문을 돌며 await했습니다.

결과를 렌더하는 로직도 수정했습니다. 기존 레이싱 결과만큼 화살표를 repeat하던 로직에서, 각 자동차의 이름을 나타내면서 dataset으로 name을 가지는 div를 우선 insert하도록 바꿨습니다. 그 후 1초에 한번씩 결과를 받아오며 받은 결과를 해당 data-name인 div에 insert하는 식으로 구현했습니다.

이번에 살면서 처음으로 코드 리뷰를 받아본 것이었는데, 정말 큰 도움이 됐습니다. 사소한 피드백도 감사하게 받겠습니다!

2022-02-19 16:37 UTC, austinpark420 commented
cypress/screenshot/app.spec.js의 파일이 올라와있네요! 혹시 pr에 포함시키신 이유가 있을까요?

2022-02-19 17:02 UTC, austinpark420 commented
utils 디렉토리 안에 세분화해서 작업을 해주셨는데요! 세분화하는 것도 좋지만 관리포인트가 너무 많아지는 것 같습니다. 기준을 세우셔서 세분화되어 있는 utill 함수를 조금 합치셔도 될 것 같습니다!

2022-02-19 17:53 UTC, austinpark420 requested changes
안녕하세요 후이!

step2를 구현하시느라 고생 많으셨습니다!
이번에는 세분화하시는 부분에 대해서 많이 신경쓰신 것 같아요 👍 
그리고 new CustomEvent web API 사용 등 다양한 방법을 공부하시고 사용하신 것 같습니다!

코드 관련해서 리뷰남겼습니다.
혹시 제가 잘못 이해한 부분이 있으면 말씀부탁드려요!

그럼 즐거운 주말보내세요!!

2022-02-19 17:53 UTC, austinpark420 commented on src/js/view/View.js
> +  on = (event, handler) => {
on이라는 메소드 이름을 보고 어떤 일을 할지 추측하기 어려운 것 같습니다!

2022-02-19 17:53 UTC, austinpark420 commented on src/js/controller/RacingCarController.js
> +      this.CarNamesInputView.reset();
잘못된 값을 입력한 후에 input을 reset하는 이유가 궁금합니다! 해당 부분은 ux 부분에서 개인적으로 불편하게 느껴져서 여쭤봤습니다!

2022-02-19 17:53 UTC, austinpark420 commented on src/js/utils/validatior.js
> +  if (Number(count) < 0) {
count가 0일 때도 유효성 검사에서 걸러지도록 해야할 것 같아요!

2022-02-19 17:53 UTC, austinpark420 commented on src/js/view/View.js
> +    const customEvent = new CustomEvent(event, { detail: data });
new CutomEvent를 만들어서 사용하셨군요 👍

2022-02-19 17:53 UTC, austinpark420 commented on src/js/models/RacingCarModel.js
> +    this.prevRaceResult = {};
prevRaceResult 를 RacingCarModel 모델에서 꼭 필요한 궁금합니다!

2022-02-19 17:53 UTC, austinpark420 commented on src/js/models/RacingCarModel.js
> +      return acc;
return의 경우, 가독성을 위해서 위에 한줄을 띄고 입력하시는 것을 추천드려요!

2022-02-19 18:42 UTC, austinpark420 commented on src/js/utils/constants.js
>  export const ID = Object.freeze({
보통 constant는 constant 디렉토리를 따로 만들어서 관리해요!

2022-02-21 02:33 UTC, kwannee commented on src/js/models/RacingCarModel.js
>    setCars = (carNames) => {
알려주셔서 감사합니다!. bind가 편해서 무지성 화살표 함수 썼었는데 이런 이슈가 있는지 몰랐네요... 관련해서 더 찾아보고 학습로그 작성해 봐야겠네요!

2022-02-21 02:34 UTC, kwannee commented on src/js/view/View.js
> +  on = (event, handler) => {
onChange, onClick처럼 뭔가 이벤트 바인딩 하는 느낌을 주려고 on을 썼는데 좀 모호했던거 같습니다. onEvent라는 이름으로 바꿨습니다!

2022-02-21 02:36 UTC, kwannee commented on src/js/controller/RacingCarController.js
> +      this.CarNamesInputView.reset();
ux적인 측면을 생각해서 이렇게 한건데 생각해보니 카운트는 몰라도 이름은 내용이 긴데 하나 틀렸다고 다 지워버리면 어이가 없겠네요... 도움 안되는 친절만큼 난감한게 없죠. 앞으로 한번 더 깊게 ux에 대해 생각해 봐야겠습니다!

2022-02-21 02:37 UTC, kwannee commented on src/js/utils/validatior.js
> +  if (Number(count) < 0) {
넵 0 미만에서 0 이하로 수정했습니다!

2022-02-21 02:38 UTC, kwannee commented on src/js/view/View.js
> +    const customEvent = new CustomEvent(event, { detail: data });
이벤트 리스너를 view쪽에 두려다 보니까 이것저것 찾아보게 됐습니다. 더 좋은 방법이 있을지 찾아보고 있는데 혹시 괜찮은 방법이 있을까요?

2022-02-21 02:44 UTC, kwannee commented on src/js/models/RacingCarModel.js
> +    this.prevRaceResult = {};
직전 레이싱 기록을 저장해서 현재 레이싱이 끝난 후 기록과의 차이를 바탕으로 어떤 car가 전진했는지 알아내기 위함이었습니다. 
그런데 생각해보니 새로운 레이싱 시작 전에 지금까지의 레이싱 결과를 가져오면 그게 prevRaceResult인 것 같아서 로직을 변경했습니다. 
prevRaceResult를 지우고 관련 로직들을 다 걷어내니 코드가 훨씬 간결해 졌습니다! 
class에서 값을 둘 때는 항상 정말 필요한 값이 맞는지 고민해야겠습니다.

2022-02-21 02:46 UTC, kwannee commented on src/js/models/RacingCarModel.js
> +      return acc;
좋은 팁 감사합니다! 수정하였습니다.

2022-02-21 02:46 UTC, kwannee commented on src/js/utils/constants.js
>  export const ID = Object.freeze({
넵 디렉토리를 따로 만들어 분리하였습니다.

2022-02-21 02:48 UTC, kwannee commented
> cypress/screenshot/app.spec.js의 파일이 올라와있네요! 혹시 pr에 포함시키신 이유가 있을까요?
제가 깃에 익숙하지 않아서 pr에 올라가게 됐습니다 ㅠ...

2022-02-21 02:53 UTC, kwannee commented
> utils 디렉토리 안에 세분화해서 작업을 해주셨는데요! 세분화하는 것도 좋지만 관리포인트가 너무 많아지는 것 같습니다. 기준을 세우셔서 세분화되어 있는 utill 함수를 조금 합치셔도 될 것 같습니다!

맞습니다. 이번에 eslint를 처음 사용하게 됐는데 class 메소드 중에 내부에 this가 없으면 바깥으로 빼라고 다 빨간줄을 치더라고요... 
어떤 함수를 합쳐야 하나 고민했는데 감을 잘 못 잡겠습니다...
string.js와 template.js를 합쳐야 하나 생각해봤는데, 각자 하는 일이 다른 것 같아서 쉽사리 합치지 못했습니다...

2022-02-21 09:11 UTC, austinpark420 commented on src/js/view/View.js
> +    const customEvent = new CustomEvent(event, { detail: data });
저는 연슴삽아 CutomEvent를 사용하신거라고 생각했습니다! javascript 함수가 [일급함수](https://developer.mozilla.org/ko/docs/Glossary/First-class_Function)라는 특징을 이용하는 방법도 있을 것 같습니다.
다음 미션때 비슷한 상황이 있으면 적용해보시면 좋을 것 같습니다!

2022-02-21 09:13 UTC, austinpark420 approved these changes
자동차 경주 구현 미션을 수행하시느라 고생 많으셨습니다!
제가 많이 부족하지만 남긴 리뷰에 대해서 반영해주시려고 노력해주셔서 감사합니다.
다음 미션도 화이팅하세요! 👍

2022-02-21 09:13 UTC, merged