[2단계 - 자동차 경주 미션] 코이(정인교) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #122
Opened 2022-02-18 12:05 UTC by InKyoJeong

율리님 안녕하세요~!
setInterval로 화살표 진행상황을 표시하고, setTimeout과 async/await를 이용해서 결과 출력과 축하메세지를 구현해보았습니다.
파일들의 위치나 함수 위치, 함수역할에 대해 고민을 많이 해봤는데 그래도 어렵습니다..ㅎㅎ

기능 요구사항외에 달라진부분은
큰 시도횟수 입력시 예외 처리, 게임시작시 폼이 disable 상태가 되도록 추가하였고
거리순으로 자동차를 sort하는 부분은 게임 진행에 의미가 없을것같아 제거하였습니다.

[데모페이지](https://koy-racing-car.netlify.app/)

#### 2단계 🎯 기능 요구사항

- 자동차 경주 게임의 턴이 진행 될 때마다 1초의 텀(progressive 재생)을 두고 진행한다.
- 1초의 텀동안 로딩 애니메이션을 보여준다. 
- 정상적으로 게임의 턴이 다 동작된 후에는 결과를 보여주고, 2초 후에 축하의 alert 메세지를 띄운다.

2022-02-19 09:57 UTC, glassyi commented on cypress/integration/racingcar.spec.js
> +    cy.tick(count * DEFAULT_DELAY);
👍

2022-02-19 10:03 UTC, glassyi commented on cypress/integration/racingcar.spec.js
> +        'Please enter a valid value. The two nearest valid values are 1 and 2.',
코이님은 validationMessage가 영어로 나오나요? 저는 이 메세지가 한글로 출력되네요. 
"유효한 값을 입력해 주세요. 가장 근접한 유효 값 2개는 1 및 2입니다."

2022-02-19 10:04 UTC, glassyi commented on cypress/support/commands.js
> +});
공통으로 중복되어 쓰이는 부분은 Commands로 잘 분리하셨네요~

2022-02-19 10:05 UTC, glassyi commented on docs/README.md
> +- [x] 폼 모두 입력 완료되면 disable 상태로 변경
👍

2022-02-19 10:06 UTC, glassyi commented on index.html
> +        <form class="count-form hidden">
hidden attribute 사용 좋네요~ 👍

2022-02-19 10:12 UTC, glassyi commented on index.html
>              <input id="count-input" class="count-input" type="number" />
```html
<input id="name-input" class="name-input" type="text" />
```
id 와 class 명을 동일하게 쓰진 않았으면 하네요~ name-input 인풋도 마찬가지 입니다. 
지금 당장 id의 사용처가 없다면 id를 쓰지 않아도 될 것 같네요~

2022-02-19 10:18 UTC, glassyi commented on index.html
>              <input id="count-input" class="count-input" type="number" />
id명을 class와 다르게 주는게 헷갈리지 않을 것 같아요. 보통은 id와 class 네이밍 컨벤션을 다르게 가져가는데 우선은 동일한 네이밍만 피해서 수정해보는게 어떨까 하네요.

2022-02-19 10:44 UTC, glassyi commented on src/controller/handleNameInput.js
>      .map(name => name.trim());
이 코드가 generateCars model에도 동일하게 있어요. 중복되고 있다면 역할이 제대로 분리가 안되었다고 생각해야 할 것 같아요.

2022-02-19 11:17 UTC, glassyi commented on src/utils/handleElement.js
> +};
element의 show/hidden, disabled/enabled 처리 함수를 utils 폴더로 분리하신 이유가 있을까요?

2022-02-19 11:39 UTC, glassyi commented on src/view/resetView.js
> +  $('.winner-container').innerHTML = '';
특정 DOM의 하위 요소를 비울 때 innerHTML 보다는 Element.replaceChildren() 을 추천합니다~ innerHTML는 HTML 파싱 과정을 거치기 때문에 더 느린 성능을 가지고 있어요. 
[replaceChildren](https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceChildren)

2022-02-19 11:52 UTC, glassyi commented on src/view/showProgress.js
> +  const arrowProgress = setInterval(() => {
setInterval을 사용하셨네요! 여기서 setInterval대신 requestAnimationFrame을 사용해 보는건 어떨까요? 부드러운 animation을 위해서 requestAnimationFrame을 많이 사용하는데요. requestAnimationFrame과 setInterval의 차이가 무엇일지 한번 찾아보시면 좋겠어요! 알고 있다면 리마인드 차원에서 복기해도 좋구요.

2022-02-19 11:56 UTC, glassyi commented on style.css
> +
자주 쓰는 값을 전역 변수 처리한거 좋네요 👍

2022-02-19 12:14 UTC, glassyi commented
> 파일들의 위치나 함수 위치, 함수역할에 대해 고민을 많이 해봤는데 그래도 어렵습니다..ㅎㅎ

그 고민들이 여기저기 보이더라구요. 그래서 좀 더 구체적인 질문을 할게요! 
코이님이 생각하는 Model - View - Controller 의 역할이 무엇일까요? 그리고 그걸 코드에 어떻게 녹여내려고 했나요?

2022-02-19 12:20 UTC, glassyi commented on .gitignore
> +screenshots/
마지막에 라인 추가해 주세요~ 😅

2022-02-19 12:32 UTC, glassyi requested changes
코이님! step2 미션 고생하셨어요! 🙂
파일들의 위치나 함수 위치, 함수역할에 대해 고민을 많이 하셨다고 했는데
그런 고민을 많이 하면 할 수록 코이님의 코드를 작성하는 기준들이 조금씩 생기고 실력도 더 좋아지지 않을까 생각해요! 👏  
구조에 대한 조금 더 구체적인 질문과 함께 세부적인 코멘트 남겼으니
확인해 주시고 답변 부탁드려요!

2022-02-20 10:44 UTC, InKyoJeong commented on cypress/integration/racingcar.spec.js
> +        'Please enter a valid value. The two nearest valid values are 1 and 2.',
```
AssertionError: expected 'Please enter a valid value. The two nearest valid values are 1 and 2.' to equal '유효한 값을 입력해 주세요. 가장 근접한 유효 값 2개는 1 및 2입니다.'

2022-02-20 10:55 UTC, InKyoJeong commented on index.html
>              <input id="count-input" class="count-input" type="number" />
헷갈리지않게 다르게 주는게 맞겠네요!

2022-02-20 13:24 UTC, InKyoJeong commented on src/controller/handleNameInput.js
>      .map(name => name.trim());
그러네요.. 중복 부분을 어떻게 해야할지 고민해봐야겠어요

2022-02-20 14:57 UTC, InKyoJeong commented on src/view/resetView.js
> +  $('.winner-container').innerHTML = '';
이런 메서드가 있는지 몰랐네요. 감사합니다!

2022-02-20 15:12 UTC, InKyoJeong commented on src/utils/handleElement.js
> +};
비슷한 역할을 해서 묶어보았는데, 굳이 분리할 필요가 없었나..라는 생각도 드네요

2022-02-20 17:56 UTC, InKyoJeong commented on src/view/showProgress.js
> +  const arrowProgress = setInterval(() => {
왜 사용하는지는 이해했는데, 여기서 어떻게 사용하면 좋을지 잘 모르겠습니다. 끊김을 느끼지 않도록 1프레임마다 호출을 보장해주는 web api라고 이해했는데, 1초마다 전진하는 기능에서도 requestAnimationFrame을 사용하는 것이 맞는건가요?

2022-02-21 08:19 UTC, InKyoJeong commented
> > 파일들의 위치나 함수 위치, 함수역할에 대해 고민을 많이 해봤는데 그래도 어렵습니다..ㅎㅎ
> 
> 그 고민들이 여기저기 보이더라구요. 그래서 좀 더 구체적인 질문을 할게요! 코이님이 생각하는 Model - View - Controller 의 역할이 무엇일까요? 그리고 그걸 코드에 어떻게 녹여내려고 했나요? 🙂
 
model은 데이터를 담당하고, view는 화면을 그리는 역할을 담당하고, 
controller는 model 과 view를 조작하는 역할로 알고 있었고, mvc 를 이용해서 코드를 작성해보는건 처음인데요
그걸 어떻게 코드로 녹여야하는지 사실 아직 잘 와닿지가 않네요. 연습을 계속 해봐야할것같아요!

2022-02-21 14:47 UTC, glassyi approved these changes
코이님~ 🙂 몇가지 코멘트와 질문을 드렸는데 반영해준 부분들 확인했습니다!
코이님이 이번 미션을 진행하면서 고민한 부분들은 또 다음 미션을 통해서 더 개선되고 좋아질거라고 믿어요!! 
다음 미션도 잘 하실거라고 생각합니다. 👍  바로 머지하겠습니다~

2022-02-21 14:48 UTC, merged