[2단계 - 자동차 경주 구현] 콤피(류현승) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #129
Opened 2022-02-18 14:29 UTC by compy-ryu

안녕하세요🙇‍♂️ 리뷰어님!
드디어 저의 첫 코드 리뷰 요청을 드리게 되었습니다 😂

틀린 부분은 따끔하게(?) 리뷰해 주시면 감사하겠습니다!

## 이번 단계에서 고민해본 점
### 디렉토리 정리 방식에 대해
이번 미션을 진행하면서, "디렉토리를 어떻게 정리해야할까?"로 가장 고민을 많이한 것 같습니다.

그래서 일단 추후 유지/보수를 한다 가정 하였을 때
`utils`, `constants`, `template` 폴더에서 범용적으로 사용할만한 코드들은 각 폴더의 최상단에 위치하도록 하게 하고
자동차 게임에서만 사용되는 코드는 `RacingGame` 폴더를 만든 후 해당 폴더에 코드들을 정리해보았습니다.

프리코스를 진행할 때도 디렉토리를 정리하며 이게 맞나? 라는 고민이 매번 들었기에...
괜찮으시다면! 디렉토리 부분에 대해서도 개선사항이 있다면 리뷰 요청을 드려도 될까요!?

### MVC 패턴에서 이벤트 처리의 위치에 대해
> 이 부분은 하단 코멘트 확인 부탁드립니다!

감사합니다! 👍

2022-02-18 16:13 UTC, devJang commented
- LMS에서 미션 요청 버튼 클릭하셨나요?
- Git 충돌은 해결 중이신가요? 아니시면 Draft PR로 변경하여 WIP임을 명시해주세요!

2022-02-19 19:45 UTC, lsw1164 requested changes
안녕하세요 콤피님, MVC 패턴이 잘 녹아있는 코드네요 👍
 
디렉토리 구조 나누기에 신경을 많이 쓴 흔적이 보입니다.
디렉토리 구조는 개선점이 안보이네요 🤣

코멘트 몇가지 남겼으니 확인 부탁드려요!

2022-02-19 19:45 UTC, lsw1164 commented on test/app.spec.js
>    });
Cypress에서 커스텀 함수를 정의하는 방식인가요? 그냥 함수를 정의하는 거랑 어떤 차이가 있을까요?

2022-02-19 19:45 UTC, lsw1164 commented on src/js/constants/message.js
> +export { ERROR_MESSAGE, RESULT_MESSAGE };
명확한 네이밍 좋네요 👍

2022-02-19 19:45 UTC, lsw1164 commented on src/js/constants/selector.js
> +const replaceSelectorToDomID = (origin) => {
Selector에서 .과 #을 분리해주는군요 👍 

다만, replaceSelectorToDomID라는 함수 이름에는 DomID에 대해서만 로직을 수행할 거 같은데 
className도 관리해주고 있습니다. 어떻게 수정하면 좋을까요?

2022-02-19 19:45 UTC, lsw1164 commented on src/js/controllers/RacingGameController.js
> +  #racingGameView;
private 👍

2022-02-19 19:45 UTC, lsw1164 commented on src/js/controllers/RacingGameController.js
> +      return false;
그냥 return이 아니라 false를 return 해준 의도가 있을까요?

2022-02-19 19:45 UTC, lsw1164 commented on src/js/controllers/RacingGameController.js
> +    setTimeout(() => {
callback 함수를 넘기는 방식은 callback 깊이가 깊어질수록 가독성이 떨어지는 단점이 있습니다.

setTimeout을 활용해서 delay util 함수를 만들고
async/await 키워드를 활용해보면 어떨까요?

2022-02-19 19:45 UTC, lsw1164 commented on src/js/models/RacingCarInstance.js
>    }
캡슐화도 잘돼있고 RacingCar 객체가 적절한 역할을 수행하고 있네요 👍

2022-02-19 19:45 UTC, lsw1164 commented on src/js/utils/element-tools.js
>  const $$ = (selector) => document.querySelectorAll(selector);
selector 탐색을 root부터 하지 않고 특정 element 부터 탐색하는 방법은 없을까요?

2022-02-19 19:45 UTC, lsw1164 commented on src/js/utils/element-tools.js
> +const createElement = (tagName, nodeProperty = {}) => {
Property 할당까지 한 번에 👍

2022-02-19 19:45 UTC, lsw1164 commented on src/js/views/RacingGameView.js
> +  }
**컨트롤러 측에서 뷰가 어떤 값을 전달해주는지 매번 확인** 
컨트롤러가 뷰에 로직을 주입할 책임이 있기 때문에 당연히 확인해야 된다고 생각합니다 :)

뷰는 화면에 UI를 보여주고, 사용자와 접점이 있을 때 이벤트를 실행할 책임만 있습니다. 
이벤트 로직을 주입할 수 있는 창구만 열어두고 어떤 로직이 들어올지는 몰라도 되는거죠.

잘 분리해서 작성해주셨네요👍

2022-02-20 12:06 UTC, compy-ryu commented on test/app.spec.js
>    });
### 조사해본 결과! 아래와 같았습니다.

1. 커스텀 명령이 먼저 선언된 후 테스트 코드가 실행되어, 코드 라인의 순서에 상관없이 어떤 라인에서도 명령을 호출할 수 있습니다.
2. 전역으로 선언되어 같은 테스트 파일 내 서로 다른 테스트 분류에서 해당 명령을 사용할 수 있습니다.
3. Cypress 설정에서 supportFile 옵션을 활용하면 테스트 코드 전역에서 자주 사용하는 명령을 다른 파일로 분리할 수 있습니다.
4. prevSubject와 같은 옵션을 활용하여 아래와 같이 응용할 수 있습니다.

```javascript
Cypress.Commands.add('console', { prevSubject: true }, (subject) => {
  console.log('선택된 객체 : ', subject);
  return subject;
});

if('해당 선택자로 선택된 엘리먼트들을 콘솔에 출력하고, 해당 버튼들은 확인 이라는 내용을 가지고 있어야한다.', () => {
    cy.get(SELECTOR.CAR_NAME_BUTTON).console().contains('확인');
});
```

주로 3번과 4번 같은 이유로 사용하지 않을까! 조심스럽게 추측해보겠습니다! 🙄
그냥 지나칠 뻔했던 부분인데 알려주셔서 감사합니다 👍

2022-02-20 12:08 UTC, compy-ryu commented on src/js/controllers/RacingGameController.js
> +      return false;
아뇨!
jQuery로 자바스크립트로 시작했다보니... 습관으로 남아있었던 것 같습니다...😂

주의하도록 하겠습니다!

2022-02-20 13:04 UTC, compy-ryu reviewed
안녕하세요!
주말인데도 불구하고 세세하게 리뷰해 주셔서 정말 감사합니다 👍
말씀주신 리뷰대로 코드를 전반적으로 수정해보았습니다!

자세한 사항은 아래 코멘트로 정리해보았습니다!

2022-02-20 13:45 UTC, compy-ryu commented
git 대소문자 변경사항 무시 설정으로 인해
파일 한개가 정상적으로 업로드 되지않아 데모 페이지가 작동되지 않았습니다 😭

10시 25분경 급히 수정 완료하였습니다.. 죄송합니다..! 🙇‍♂️

2022-02-20 16:31 UTC, lsw1164 requested changes

2022-02-20 16:31 UTC, lsw1164 commented on src/js/views/RacingGameView.js
> +  }
static은 해당 객체의 모든 인스턴스에서 공통으로 쓸 수 있을 때 정의합니다. 
당장 지금 단계에서는 RacingGameView가 1개 밖에 없어서 상관없을 수 있지만, 
만약 RacingGameView 인스턴스가 여러개 있고 각 RacingGameView마다 서로 다른 이벤트를 바인드 해야된다면 
static 으로 작성하면 안되겠습니다.

2022-02-20 16:31 UTC, lsw1164 commented on test/app.spec.js
> +    cy.clock();
``cy.clock();`` 
어떤 의도로 작성해주셨을까요?

2022-02-20 16:31 UTC, lsw1164 commented on src/js/controllers/RacingGameController.js
> +  }
requestAnimationFrame에서 사용해도 좋습니다 :)

Progress 멋지네요 👍

2022-02-20 16:31 UTC, lsw1164 commented on src/js/utils/element-tools.js
> +const $$ = (selector) => $APP.querySelectorAll(selector);
#app 말고 다른 엘리먼트에서도 탐색할 수 있을까요? 파라미터로 받아도 좋을 거 같습니다 :)

2022-02-21 06:51 UTC, compy-ryu reviewed
안녕하세요! 말씀 주신 피드백에 맞추어 아래와 같이 개선해보았습니다!
### 코드 리뷰 피드백 사항
* [x] 잘못된 static 사용 수정
* [x] selector 유틸 사용성 개선
* [x] 테스트 코드에서 사용하지 않는 코드 제거 (`cy.clock()`)

### 추가 개선사항
* [x] 웹 접근성 고려해보기
* [x] 데이터셋 이름 조금 더 알아보기 쉽게 이름 변경하기

개선 중 궁금증이 한가지 또... 생겨서 조심스럽게 여쭤봅니다 😂...!
자세한 사항은 아래 코멘트 확인해주시면 감사하겠습니다!

감사합니다 🙇‍♂️

2022-02-21 06:51 UTC, compy-ryu commented on test/app.spec.js
>    });
>`cy.clock();`
>어떤 의도로 작성해주셨을까요?

처음 `setInterval`과 `CSS3 Animation`을 사용했을 때 `cy.tick()` 사용하여 테스트를 하려했습니다만
계속 작동이 되지 않아 몸부림 치던 과정 중 실수로 남겨둔 코드입니다..!! 😂

해당 라인 제거하였습니다!

2022-02-21 06:51 UTC, compy-ryu commented on src/js/views/RacingGameView.js
> +  }
>static은 해당 객체의 모든 인스턴스에서 공통으로 쓸 수 있을 때 정의합니다.
>당장 지금 단계에서는 RacingGameView가 1개 밖에 없어서 상관없을 수 있지만,
>만약 RacingGameView 인스턴스가 여러개 있고 각 RacingGameView마다 서로 다른 이벤트를 바인드 해야된다면
>static 으로 작성하면 안되겠습니다.

그런 의도로 사용되는군요..! 제가 잘못 이해하고 있었네요!
배워갑니다! 🙇‍♂️

2022-02-21 06:51 UTC, compy-ryu commented on src/js/utils/element-tools.js
> +};
> \#app 말고 다른 엘리먼트에서도 탐색할 수 있을까요? 파라미터로 받아도 좋을 거 같습니다 :)

말씀해주신 피드백을 본 후, 처음에는 아래와 같이 구현했었습니다.

```javascript
const $ = (parentTarget, childSelector = null) => {
  const target = childSelector || parentTarget;
  let $parent = childSelector ? parentTarget : $APP;
  
  if (childSelector && typeof $parent === 'string') {
    $parent = document.querySelector($parent);
  }

  return $parent.querySelector(target);
};

```
하지만 파라미터로 여러가지 타입을 받는 것은
클린코드에서 타입 체킹을 피하라! 라는 내용을 보았고, 타입스크립트의 존재를 들어보았을 때.. 좋지 않은 코드인 것 같아.
지금 코드와 같이 Element 타입만 받도록 일단 변경하였습니다.

하지만 자바스크립트의 유연한 데이터 타입도 장점이 될 수는 있다 생각해서...

위 예시처럼 서버 통신 없이, 프론트엔드에서만 사용하는 함수에서는 어느정도 유연하게 사용해도 괜찮을까요?
아니면 지금 코드와 같이 파라미터에서는 데이터 타입을 무조건 한가지만 고려하고 받는 것이 좋을까요?

2022-02-21 10:50 UTC, jhy979 commented on src/js/controllers/RacingGameController.js
> +  }
와 감탄하고 갑니다...

2022-02-21 14:22 UTC, lsw1164 approved these changes
콤피님 수고 많으셨습니다 👍 
Approve 하겠습니다!

2022-02-21 14:22 UTC, lsw1164 commented on src/js/utils/element-tools.js
> +};
확실히 타입이 로직 중간에 바뀌는 부분은 잘 개선하셨네요 👍 
처음에 작성하신 로직은 parentTarget와 childSelector가 string타입인지 dom객체인지 중간에 바뀌니까 헷갈리겠네요 😅

2022-02-21 14:23 UTC, merged