[2단계 - 자동차 경주 구현] 나인(장호영) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #136
Opened 2022-02-19 05:30 UTC by jhy979

자동차 경주 게임 2단계 PR 제출합니다.
주말 늦게 PR과 리뷰요청을 눌러서 죄송합니다....!

### 어려웠던 점
- 비동기 처리를 처음 해봐서 굉장히 애를 먹었습니다.

- 시간과 관련된 테스트 코드를 작성하는데 아직도 어려운 부분이 많습니다.

- `cy.wait()` 가 제가 원하는대로 동작하지 않는 것 같습니다.

### 고민해야할 사항
- semantic한 태그를 사용할 수 있도록 공부가 필요해요.

- 콜백 함수에 대한 이해가 필요해요.

- 스타일은 css에서만 담당할 수 있도록 하는 방안을 생각해봐야 합니다.

---
- 더 고민하고 코드를 작성하고 싶었는데 너무 늦게 제출할 수가 없어서 미리 제출합니다. 감사합니다!

2022-02-19 20:28 UTC, lsw1164 requested changes
cy.wait는 어떤 점에서 원하는대로 동작하지 않았는지 적어주시면 
저도 같이 고민해보겠습니다!

코멘트 몇가지 남겨봤습니다. 참고 부탁드릴게요 :)
고민하고 계신 부분도 반영해주시면 다음 리뷰에서 다시 보겠습니다 👍

2022-02-19 20:28 UTC, lsw1164 commented on js/controller/controller.js
> +      }, TIMER.DELAY_AFTER_END);
setTimeout을 활용해서 특정 시간 동안 기다리는 util 함수를 만들어보면 어떨까요?
Promise를 반환해서 async/await를 쓸 수 있다면 callback 함수를 쓰지 않아도 될 거 같습니다 :)

2022-02-19 20:28 UTC, lsw1164 commented on js/view/view.js
> +    $(SELECTOR.CAR_RACING_COUNT_BUTTON).style.backgroundColor = 'gray';
disabled 될 때 css도 css파일 안에서 설정해주면 어떨까요?

https://developer.mozilla.org/ko/docs/Web/CSS/:disabled

2022-02-19 20:28 UTC, lsw1164 commented on js/view/view.js
> +      }, TIMER.DELAY_MOVE);
callback 함수가 깊어지면 의도를 파악하기 어려워집니다.
상위 스코프랑 중복되는 변수명은 피하는 게 좋습니다. ( position )

callback 내부 내용이 복잡하다면 함수로 추출하면 어떨까요?

2022-02-19 20:28 UTC, lsw1164 commented on js/view/view.js
> +    $$('#loader').forEach((loader) => (loader.style.display = 'none'));
```
.d-none {
  display: none;
}
```
d-none이라는 css class를 만들고 element의 classList에서 
해당 class을 추가/제거하는 방식으로 바꿔보면 어떨까요?

2022-02-20 04:45 UTC, jhy979 commented on js/controller/controller.js
> +    this.displayProgress(this.model.carPosition).then(() => {
- async /await 에 대해 학습하고 콜백함수를 안 쓰는 방향으로 코딩해봤습니다.

- 제가 짜면서도 콜백 지옥이 곧 생기겠구나 싶었는데 이런 좋은 방법이 있었네요 👍

2022-02-20 04:53 UTC, jhy979 commented on js/controller/controller.js
> +      }, TIMER.DELAY_AFTER_END);
- setTimeout에서 Promise를 반환하는 `delay 함수`를 `timer.js`에서 생성했습니다.

- 작성해보니 `controller.js`에서는 setTimeout의 콜백함수가 필요없게 되어 코드 가독성에서도 좋은 것 같습니다. 👍

2022-02-20 05:10 UTC, jhy979 commented on js/view/view.js
> +    $(SELECTOR.CAR_RACING_COUNT_BUTTON).style.backgroundColor = 'gray';
- `:hover`에 대해서는 알고 있었는데 ' : ' 라는 기호가 의사 클래스 선택자라는 것을 처음 알았어요.

- 아직도 많이 고쳐야할 부분이 많지만 스타일을 온전히 css에게 맡기는 방식을 배워가는 것 같아요.👍

2022-02-20 05:46 UTC, jhy979 commented on js/view/view.js
> +      }, TIMER.DELAY_MOVE);
- 사실 이 함수가 제가 봐도 이해가 잘 안 갔습니다.

- 위에서 리뷰해주신 내용을 바탕으로 콜백함수, promise,  async/await에 대해 공부하고 나니 손도 못 댈 것 같았던 이 지저분한 함수를 리팩토링할 수 있었어요. 감사합니다 👍 

## 궁금한 사항
```js
 async doRacing(carPosition) {
    return new Promise((resolve) => {
      const moveCarsTimer = setInterval(() => {
        this.decideGo(carPosition);
        this.decideStopRacing(carPosition, resolve, moveCarsTimer);
      }, TIMER.DELAY_MOVE);
    });
  }
```
- 함수를 분리하다보니 `this.decideStopRacing(carPosition, resolve, moveCarsTimer);` 에서 resolve함수를 인자로 받아서 외부에서 `promise resolve`를 처리하고 있습니다. 동작에는 문제가 없지만 이렇게 로직을 작성해도 괜찮을까요?

2022-02-20 06:01 UTC, jhy979 commented on js/view/view.js
> +    $$('#loader').forEach((loader) => (loader.style.display = 'none'));
- 맞아요! 옛날에 강의에서 들었는데 새까맣게 잊고 있었네요. 이렇게 하면 스타일을 온전히 css에서 작성할 수 있겠네요!

- `d-none`이 뭔가 했는데 알고보니 `display-none` 이네요. 여기서도 네이밍의 중요성을 느끼네요 ㅎㅎ

2022-02-20 06:09 UTC, jhy979 commented
## 궁금한 사항이 생겼습니다👍 

### 원본 배열을 변경하는 forEach?

- 아래는 `decideGo`라는 함수입니다. carPosition을 받아서 forEach문을 돌고 있는데요!

- 보시다시피 `carPosition[idx]--;` 을 통해 forEach문의 주체가 되는 carPosition의 값을 바꾸고 있습니다.

- 동작은 잘 하지만 이런 식으로 작성해도 무방한가요? 
- ~~(반복문을 돌고 있는 와중에 값을 변경하는 것이 개인적으로 불안정한 상태인 것 같습니다.)~~


```js
decideGo(carPosition) {
    carPosition.forEach((position, idx) => {
      if (position > 0) {
        $(`#car-progress-result-${idx}`).insertAdjacentHTML('afterbegin', '️️⬇️');
        carPosition[idx]--; // 괜찮을까요??
      }
    });
  }
```
---

### 개행 괜찮을까요?

```js
  renderInitial() {
    hideElement($(SELECTOR.GAME_RESTART));
    hideElement($(SELECTOR.CAR_RACING_COUNT_WRAPPER));

    $(SELECTOR.CAR_NAMES).textContent = '';
    $(SELECTOR.CAR_RACING_WINNER).textContent = '';
    $(SELECTOR.CAR_PROGRESS).textContent = '';

    $(SELECTOR.CAR_NAMES_INPUT).value = '';
    $(SELECTOR.CAR_RACING_COUNT_INPUT).value = '';

    $(SELECTOR.CAR_RACING_COUNT_BUTTON).disabled = false;
    $(SELECTOR.CAR_NAMES_BUTTON).disabled = false;
  }
```
- 이런 식으로 개행을 분리하는 것이 의미없는 개행인가요? 아니면 하면 더 플러스가 되는 개행일까요?

2022-02-20 07:46 UTC, jhy979 commented
## Cypress Wait 
### 1. page loaded
- page loaded가 발생하여 테스트 코드가 진행하던 중간에 `새로고침을 한 상태로 넘어가 버립니다.`
```
AssertionError: Timed out retrying after 4000ms: Expected to find content: '⬇️️' within the element: <div#car-progress> but never did.
```
![자동차의 전진이 정상적으로 작동하는지 검증합니다 -- 주어진 횟수 동안 n 대의 자동차는 전진 또는 멈출 수 있다 (failed)](https://user-images.githubusercontent.com/32920566/154833199-a748f4c7-a8db-445f-8c3e-bd73244ace77.png)


### 2. 게임이 멈춤
- 테스트 코드 그대로 브라우저에서 시도하면 그대로 동작하는데 

- 테스트 코드에서는 `게임이 멈춘 것처럼` 로딩바가 계속 돌면서 멈춰있고 다음 단계로 진행하지 않습니다.
```
AssertionError: expected stub to have been called with arguments "자동차 경주 결과가 나왔습니다. 우승하신 분들 축하드려요!", but it was never called
```

![최종 우승자를 검증합니다 -- 자동차 경주 게임을 정상적으로 완료하고 2초 뒤에 축하 메시지를 확인할 수 있다 (failed)](https://user-images.githubusercontent.com/32920566/154833200-9a7a40bc-3c2a-405c-8631-77d889c02649.png)

---

### 그래서 tick으로 바꿔봤더니
- `2.게임이 멈춤` 현상은 제거되어 관련 테스트가 통과하였으나

- `1.page loaded` 는 그대로 발생하여 문제가 해결되지 않았습니다.


--- 
- 어떠한 과정에서 문제인 건지.. 도저히 감이 오지 않습니다.
- 자동으로 자원을 반환한다고 하지만 혹시나 clock.restore()이 안 되어서 자원 반환이 되지 않아 문제가 생겼나 해서 호출해봤지만 문제가 해결되지 않았습니다.

2022-02-20 12:54 UTC, lsw1164 commented on js/view/view.js
> +      }, TIMER.DELAY_MOVE);
async 메서드의 끝은 가급적이면 그 메서드 내에서 해결하는 게 낫다는 생각입니다. 
Promise 시작은 doRacing에서 하고 끝내는 resolve는 다른 메서드에서 호출한다면 복잡도가 올라갑니다.
특별한 경우가 아니라면 Promise 시작과 끝은 해당 메서드 내에서 관리하는 게 좋겠습니다.
```js
export const repeatAction = (action, intervalMs, canRepeat) => {
  return new Promise((resolve) => {
    const timer = setInterval(() => {
      if (!canRepeat()) {
        clearInterval(timer);
        resolve();
        return;
      }
      action?.();
    }, intervalMs);
  });
};
```
이런식으로 util 함수를 만들어서 분리해볼 거 같습니다.

```js
  doRacing(carPosition) {
    return repeatAction(
      () => this.decideGo(carPosition),
      TIMER.DELAY_MOVE,
      () => Validator.isNowRacing(carPosition)
    );
  }
```
그럼 이런식으로 줄여볼 수 있겠네요.

2022-02-20 13:30 UTC, lsw1164 commented
## 원본 배열을 변경하는 forEach?

값을 '직접' 바꾸는 건 문제가 된다고 생각합니다.
일단 carPosition이라는 상태값이 Model 객체 내부에 있는 상태값의 참조가 맞을까요?
만약 그렇다면 carPosition의 상태값을 직접 바꾸는 주체는 Model이 되는 게 맞습니다.

객체의 상태를 외부에서 직접 바꾸게되면 캡슐화가 안됐다고 할 수 있습니다.
Model 객체 내부에 있는 상태값을 바꾸고 싶다면 Model 객체에게 적절한 메세지를 보내고
Model 객체 스스로 메서드를 수행하면서 상태를 바꿀 수 있도록 설계하는 방법이 
객체의 자율성을 지키는 방향입니다.

만약 외부에서 상태값을 마음대로 바꿀 수 있게 열어두면 
외부 객체들에서 Model 객체 내부 상태값을 모두 알아야 되겠습니다.
이는 좋은 설계라고 보기 어렵습니다. 

'캡슐화' 키워드로 학습 추천드립니다 :)


## 개행 괜찮을까요?

네, 관련 있는 부분을 개행으로 나누는 건 가독성에 도움이 된다고 생각합니다 :)


## 템플릿 리터럴의 스타일?
vscode에 관련 플러그인을 찾아봤는데 포매터까지 지원하는 플러그인은 저도 못봤습니다 ㅠ

대안으로 이 플러그인을 사용해보시는 건 어떠신가요? 
포매팅까진 아니더라도 Syntax highlighting을 지원합니다.
https://marketplace.visualstudio.com/items?itemName=Tobermory.es6-string-html


## async에 대한 잘못된 이해?

'자동으로 프로미스를 반환' 이라는 말은 맞습니다. 
하지만, doRacing 메서드에서 반환하는 값은 바로 resolve하는 Promise입니다.
내부에 await 키워드로 기다리는 코드가 따로 없기 때문입니다.
그렇다면 지금 doRacing을 호출하는 renderProgress에서 아무리 await를 해줘도 
renderProgress 입장에서는 기다릴 게 없기 때문에 바로 다음 라인을 실행할겁니다.

async/await, Promise 상당히 깊이 있는 개념이라 한 번에 이해하기 어렵습니다. 
제가 추천하는 방법은 JS 원리를 알려주는 개념서를 하나 구매하셔서 관련 내용을 깊게 정리해보시는 걸 추천드립니다. 
(저 같은 경우 You don't know JS 라는 책을 통해 이해했습니다)

## Conflict 문제 발생
이건 base가 달라서 생기는 충돌 문제입니다.
step1 merge가 일어나면서 나인님이 fork 받은 브랜치랑 upstream 브랜치의 싱크가 깨졌을겁니다.

1안 매 step마다 upstream 브랜치와 싱크를 맞춘 상태에서 미션을 시작하는 게 제일 깔끔한 방법이 되겠습니다.
2안 하지만, 이미 싱크가 깨졌으니 git rebase -i 를 통해 해결
(commit의 base를 맞추고 합치고 전부 다시 재정렬하는 과정이라 상당히 괴로운 과정이 될 거 같습니다 ㄷㄷ)
3안 rebase가 어렵다면 upstream 브랜치 기반으로 branch를 새로 만들고 git cherry-pick을 통해 step2 commit을 전부 다시 한다.

2022-02-20 13:52 UTC, lsw1164 commented
> 


```js
  it('주어진 횟수 동안 n 대의 자동차는 전진 또는 멈출 수 있다.', () => {
    cy.clock();
    cy.get(SELECTOR.CAR_RACING_COUNT_INPUT).type(5);
    cy.get(SELECTOR.CAR_RACING_COUNT_BUTTON).click();
    cy.wait(5000).then(() => {
      cy.get(SELECTOR.CAR_PROGRESS).contains('⬇️️');
    });
  })
```
1. ⬇️️를 포함해야 된다고 테스트를 써주셨지만, 확률적으로 전진 못하면 ⬇️️를 포함하지 않습니다. 
2. cy.clock(); 은 어떤 의도로 작성해주신 코드일까요?

2022-02-20 14:20 UTC, jhy979 commented
> 을 '직접' 바꾸는 건 문제가 된다고 생각합니다. 일단 carPosition이라는 상태값이 Model 객체 내부에 있는 상태값의 참조가 맞을까요? 만약 그렇다면 carPosition의 상태값을 직접 바꾸는 주체는 Model이 되는 게 맞습니다.
> 
> 객체의 상태를 외부에서 직접 바꾸게되면 캡슐화가 안됐다고 할 수 있습니다. Model 객체 내부에 있는 상태값을 바꾸고 싶다면 Model 객체에게 적절한 메세지를 보내고 Model 객체 스스로 메서드를 수행하면서 상태를 바꿀 수 있도록 설계하는 방법이 객체의 자율성을 지키는 방향입니다.
> 
> 만약 외부에서 상태값을 마음대로 바꿀 수 있게 열어두면 외부 객체들에서 Model 객체 내부 상태값을 모두 알아야 되겠습니다. 이는 좋은 설계라고 보기 어렵습니다.
> 
> '캡슐화' 키워드로 학습 추천드립니다 :)

2022-02-20 14:53 UTC, jhy979 commented on js/view/view.js
> +      }, TIMER.DELAY_MOVE);
- 아하 이해했습니다! 이렇게 하면 resolve를 new Promise 안에서 실행할 수 있을 것 같아요.

- 그런데 일자무식의 입장에서 의문이 하나 듭니다. 

- 이렇게 유틸 함수로 분리하면 이 함수만을 위한 유틸 함수를 생성하는 것 같은 생각이 들어요. 재사용성이 희박한 유틸 함수를 만드는 것에서 낭비가 아닐까요??

2022-02-20 15:11 UTC, jhy979 commented
### 원본 배열을 변경하는 forEach?
- 1차적으로 forEach에 대상이 되는 배열이 forEach 내부에서 바뀌는 것이 적절하지 못하고

- 2차적으로 view에서 model의 데이터를 변경하여 MVC 패턴이 위배되는 행위를 하고 있음을 이해했습니다.

- view에서는 단순히 렌더링, model에서는 데이터 변경 함수를 따로 작성하고 controller에서 이를 연결하여 원하는 결과를 낼 수 있도록 다시 수정해보겠습니다.

### 템플릿 리터럴의 스타일?
- 오 이런 플러그인이 있었군요!

- 검색해도 찾지 못했었는데 직접 찾아주셔서 감사합니다👍 

### async에 대한 잘못된 이해?
- console.log() 로 `doRacing` 함수를 출력해보니 말씀하신대로 fulfilled 상태로 반환이 되는 것을 확인했습니다.

- 하루종일 async와 await에 관하여 유튜브 영상도 많이 보고 어느정도 이해했다고 생각했는데 아직 너무 어렵습니다ㅠㅠ

- `You don't know JS` 책 제목이 정말 저한테 하는 것 같네요... 주문해서 바로 반복 학습해보겠습니다👍 

### Conflict 문제 발생
- git에 대해 이해가 절실하다고 생각이 드는 대목입니다.. 

- git과 관련된 강의를 이번 주에 들었었는데도 말씀해주신 내용들에 대해서 굉장히 무지하다고 생각이 듭니다.

- 이 부분에 대해서는 리트님께서 주신 키워드들로 다시 공부를 해보겠습니다. 감사합니다👍 

## Cypress wait 

### 1. ⬇️️를 포함해야 된다고 테스트를 써주셨지만, 확률적으로 전진 못하면 ⬇️️를 포함하지 않습니다.
- 맞습니다.. 그래서 여러 번 반복하여 확률을 높이는 방식을 생각했으나 제가 생각해도 `확률에 기대는 적절하지 못한 테스트 코드`라고 생각합니다.

- 이 부분은 조금 더 생각하여 작성해보겠습니다. (랜덤 값을 고정하거나 model안에서 자동차들이 5이상의 랜덤값을 가지도록 수정)

### 2. cy.clock(); 은 어떤 의도로 작성해주신 코드일까요?

- 이 부분은 제가 cy.tick()과 cy.wait()에 대한 이해가 부족하여 잘못 코딩한 부분입니다. 현재는 문서를 보고 사용법을 다시 익혀봤는데요, 아래처럼 작성하면 같은 동작을 기대해봐도 되는 걸까요?

```js
it('주어진 횟수 동안 n 대의 자동차는 전진 또는 멈출 수 있다.', () => {
    cy.clock();
    // some logic 
    cy.tick(5000).then(() => {
         // some logic 
    });
  })
```

```js
it('주어진 횟수 동안 n 대의 자동차는 전진 또는 멈출 수 있다.', () => {
     // some logic 
    cy.wait(5000).then(() => {
        // some logic 
    });
  })
```

2022-02-20 16:51 UTC, lsw1164 commented on js/view/view.js
> +      }, TIMER.DELAY_MOVE);
repeatAction 같은 경우 단순히 함수를 특정 텀을 두고 반복해서 실행해주는 기능이죠.
다른 객체에서도 접근해서 사용할만한 기능이라 생각했습니다 :)

하지만, 나인님 말씀대로 지금은 한 곳에서만 쓰는 함수라서 꼭 util로 빼지 않아도 되겠네요

2022-02-20 22:55 UTC, jhy979 commented on js/view/view.js
> +      }, TIMER.DELAY_MOVE);
- 말씀하신대로 repeatAction을 따로 빼고 코드를 돌려보니 이제서야 이해가 됩니다.

- 분명 재사용성이 있는 유틸 함수가 맞네요👍 

- 제가 콜백함수에 대한 이해가 부족해서 재사용이 힘들 것 같다고 생각했었네요😅😅

2022-02-21 14:09 UTC, lsw1164 commented
>이 부분은 제가 cy.tick()과 cy.wait()에 대한 이해가 부족하여 잘못 코딩한 부분입니다. 현재는 문서를 보고 사용법을 다시 익혀봤는데요, 아래처럼 작성하면 같은 동작을 기대해봐도 되는 걸까요?

네, 현재 코드에서는 기능적으로 동일하네요 :)

2022-02-21 14:10 UTC, lsw1164 approved these changes
나인님, 코드가 많이 개선됐네요👍 
Approve 하겠습니다!

2022-02-21 14:10 UTC, merged