[2단계 - 자동차 경주 미션] 빅터(이우승) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #137
Opened 2022-02-19 06:14 UTC by woose28

헤인티 안녕하세요!
먼저 주말에 리뷰 요청을 드리게 돼서 너무나 죄송합니다..!

2단계 미션은 기능 구현 전에 리팩토링 과정을 수행했습니다.

### 수행한 리팩토링
- MVC 패턴에 맞도록 코드 수정
- 플로우에 따라 새로 보이는 요소를 `display: block`으로 조절하는 대신 요소를 렌더링 하는 방식으로 수정
- 입력 값을 검증하는 함수는 `validator` 디렉터리로 분리했으며, 에러는 `try... catch` 구문을 활용해서 처리하도록 수정했습니다.

### 질문 사항
- MVC 패턴에 맞게 적절히 구조가 잡혔는지 궁금합니다. 
- src/template/index.js 파일 안에 함수와 변수들의 이름이 적절한지 의견을 듣고 싶습니다.
  - 파일 안에 있는 함수와 변수의 이름에 동일한 접두사인 `template`를 사용하는 게 맞는지 궁금합니다.
  - 아니면, 함수의 이름에는 `getTemplate` 등의 접두사를 사용하여 이름을 짓는 게 적절할까요?

이번 2단계도 잘 부탁드립니다!!
감사합니다 :-)

2022-02-19 17:06 UTC, HyeonaKwon requested changes
안녕하세요 빅터! 2단계도 금방 구현하셨네요!
별다른 피드백은 없어도 될 것 같습니다 ㅎㅎ mvc 패턴 관련과 변수명 관련 코멘트 중심으로 봐주세요~! 미션 수행하느라 고생하셨습니다!

질문내용
> MVC 패턴에 맞게 적절히 구조가 잡혔는지 궁금합니다.

저는 충분히 잘하신 것 같습니다! 다만 코멘트에도 남겼다시피 몇가지 코멘트만 참고해주세요~

> src/template/index.js 파일 안에 함수와 변수들의 이름이 적절한지 의견을 듣고 싶습니다.
파일 안에 있는 함수와 변수의 이름에 동일한 접두사인 template를 사용하는 게 맞는지 궁금합니다.
아니면, 함수의 이름에는 getTemplate 등의 접두사를 사용하여 이름을 짓는 게 적절할까요?

요건 저도 고민이 많이 되는 부분이긴 해요 😂 제 개인적인 스타일은 변수라면 ~~~Template, 함수라면 get~~~Template() 이긴 합니다. template 을 붙이지 않으면 외부에서 봤을 때 어떤 값이 나오는지 알기 어려울 때가 종종 있거든요!

2022-02-19 17:07 UTC, HyeonaKwon commented
아 그리고 코드 가독성이 정말 좋네요! 👍  저는 코드를 잘 짜는 것도 중요하지만 남들이 보기 좋은 코드를 짜는 것도 중요하고 능력이라고 생각해요 ㅎㅎ 계속 유지하면 좋을 것 같습니다!

2022-02-20 02:38 UTC, woose28 commented on cypress/integration/racingcar.spec.js
> +});
- 오 공식 문서에 명시되어 있는 내용인데 이 부분을 놓쳤었네요..! 감사합니다👍👍
- 생성했던 custom command의 위치는 코멘트해 주신 대로 변경을 하겠습니다!

2022-02-20 03:09 UTC, woose28 commented on src/index.js
> +      this.model.racingCount = racingCountNumber;
- 코드를 보니까 controller가 model에게 위임하는 느낌이 아니라 직접 관여하는 느낌이네요!
- 제안해 주신 대로 수정을 하겠습니다ㅎㅎ

2022-02-20 03:10 UTC, woose28 commented on src/index.js
> +    this.view.reset();
`컨트롤러가 모델과 뷰에게 ~~~을 해!` 이 말이 정말 와닿는 거 같아요ㅎㅎ 마음에 새겨두겠습니다😊

2022-02-20 03:34 UTC, woose28 commented on src/view/RacingCarGameView.js
> +  // 해당 함수에는 carNamesForm 내부 Input과 Button만 활성화시킴
- 바로 위에 메서드인 `deactivateForm`과 이름을 맞춰야 한다는 생각 때문에 이 생각을 못 했네요!
- 제안해 주신 이름을 사용하면 주석 없이도 의도가 잘 드러나는 거 같아요. 수정하겠습니다ㅎㅎ

2022-02-20 03:43 UTC, woose28 commented on src/view/RacingCarGameView.js
> +    this.$spinnerContainers = null;
- 해당 부분은 지금 바로 DOM 요소를 가져오지 않아도, 나중에 이런 DOM 요소도 사용된다는 의도를 전달하려고 생성자에서 null로 초기화를 미리 했습니다..!
- 말씀해 주신 대로 null로 초기화를 한다면 에러를 방지할 수 있도록 처리를 해야겠네요ㅎㅎ
- 이 부분은 `1) 지금처럼 null로 초기화하고, 사용하는 부분에서 예외처리를 할지` 또는 `2) 생성자에서 미리 null로 초기화하지 않을지` 두 방법 모두 고민해 보겠습니다.

2022-02-20 03:45 UTC, woose28 commented on src/validator/index.js
> +};
- is~~~() 이런 함수만 boolean 값을 리턴하는 관행이 있는 줄 알았는데, check~~~() 이라는 함수도 이런 관행이 있었군요!
- boolean 값을 반환하도록 수정을 하겠습니다ㅎㅎ

2022-02-20 03:54 UTC, woose28 commented on src/index.js
> +    }, RULES.RESULT_MESSAGE_WAITING_TIME);
- 미션의 기능 요구사항에 `정상적으로 게임의 턴이 다 동작된 후에는 결과를 보여주고, 2초 후에 축하의 alert 메세지를 띄운다.` 이 조건이 있어서 alert에 timeout을 걸었습니다!
- 해당 방법이 적절하지 않은 방법인가요..? 또한 적절하지 않은 방법이라면 관련된 키워드를 알려주시면 공부를 하겠습니다!!(짐작 가는 키워드나 개념이 없어서요🥲)

2022-02-20 03:58 UTC, woose28 commented on src/index.js
> +        this.view.renderRacingCarProgress(index);
- 이 부분은 86번 라인에 view관련된 코드가 있어서 controller에 있는 것이 적절하다는 판단을 했습니다.
- model로 로직을 옮기고 view에 적절하게 렌더링 요청을 할 수 있는 방법을 고민해 보겠습니다!

2022-02-20 05:56 UTC, woose28 commented on src/index.js
> +      validator.checkVCarNames(carNameList);
- 으앗ㅋㅋㅋㅋㅋㅋㅋㅋ 이건 오타입니다!!
- 이것도 수정을 하겠습니다ㅎㅎ

2022-02-20 06:07 UTC, woose28 commented on src/index.js
> +new RacingCarGameController();
- 오... 이런 생각은 전혀 하지 못했습니다. 제안해 주신 대로 수정 하겠습니다ㅎㅎ
- 앞으로 서비스 최상단에 있는 index.js의 역할에 대해서 기억하고 작업하겠습니다!

2022-02-21 02:25 UTC, woose28 commented on src/index.js
> +    this.view.setRestartBtnEventHandler(this.handleRestartBtnClickEvent.bind(this));
제안해 주신 대로 은닉화를 도입했습니다!

### 은닉화 도입 목록
- RacingCarGameView
  - activateNameForm 메서드

- RacingCarGameModel
  - racingCarList 멤버 변수
  - racingCount 멤버 변수

- Car
  - name 멤버 변수
  - distance 멤버 변수

2022-02-21 02:40 UTC, woose28 commented on src/index.js
> +        this.view.renderRacingCarProgress(index);
- 각 자동차 전진 여부를 판단하고 데이터를 저장하는 코드는 model로 분리했습니다.
  - [분리한 코드 링크](https://github.com/woowacourse/javascript-racingcar/pull/137/files#diff-e554476a0dd4dfdbafbbb2b4e6976048c2c366f355c25f732cdc93900faefa2fR50-R61)
- 자동차의 전진 여부에 따라 진행 상태를 렌더링하는 코드는 view로 분리리했습니다.
  - [분리한 코드 링크](bc636984affc047da7e9a40ea9d0a9e65444c9601d0187aa5b6b2f869acd8cd0R97)

2022-02-21 02:41 UTC, woose28 commented
처음 pr을 올릴 때 데모 페이지 배포 중 에러를 만나 보여드리지 못했으나, 오늘 다행히 이슈를 해결해서 링크를 첨부하겠습니다!
[데모 페이지](https://woose28.github.io/javascript-racingcar/)

코멘트 해주신 부분들은 수정을 해서 업데이트 했습니다!

이번 미션에서도 꼼꼼히 리뷰 해주셔서 감사합니다🙏🙏

2022-02-21 02:48 UTC, woose28 commented on src/validator/index.js
> +};
현재 검증 함수 내부가 에러를 던지는 구조로 구현이 되어 있어서 boolean 값을 반환하도록 수정하는 것이 쉽지 않다고 판단을 했습니다..! 그래서 boolean 값을 반환하도록 수정하는 대신, 함수 이름을 validate~~~() 형식으로 수정을 했는데 적절한 수정 방향일까요..ㅎㅎ?

2022-02-21 03:03 UTC, woose28 commented on src/view/RacingCarGameView.js
> +    this.$spinnerContainers = null;
- `null을 넣는게 맞는지`가 가장 고민이 많았습니다. `생성자에서 미리 멤버 변수를 초기화하면 읽은 사람에게 도움이 되지 않을까?`라는 생각이 아직 조금 더 강해서 기존 방식대로 null로 초기화를 진행했습니다..!
  - 아직 이 부분에 확신이 없어서, 차라리 null로 처리하지 않는 게 더 적절한 방식일까요? 
- 예외 처리는 null로 초기화 시킨 멤버 변수를 사용하는 부분에서 `1) 조건문을 활용해서 값 확인`, `2)옵셔널 체이닝을 이용해서 확인` 등의 방식을 활용해서 진행했습니다.

2022-02-21 08:27 UTC, HyeonaKwon commented on src/index.js
> +    }, RULES.RESULT_MESSAGE_WAITING_TIME);
아!! 아닙니당ㅎㅎ 비동기로 얼럿 메세지를 띄우려고 하시는 줄 알았어요!

2022-02-21 08:28 UTC, HyeonaKwon commented on src/validator/index.js
> +};
넵 좋습니다 !! 다른 방안을 생각해보는 태도 너무 좋네요 !! 💯

2022-02-21 08:39 UTC, HyeonaKwon commented on src/view/RacingCarGameView.js
> +    this.$spinnerContainers = null;
null 을 넣어야하는 상황에서는 null 을 넣는 것이 맞습니다. 저는 빅터의 방법도 좋아요ㅎㅎ 저라도 null 로 하고 예외처리를 하고 싶었을 것 같아요!
수정하신 부분 확인했습니다~ 다만 이런 경우에는 null 일 때 뒤의 로직을 실행하는 것이 맞는가, 아니면 return 해서 로직 실행을 하지 못하도록 막는게 맞는가 를 고민해보는게 좋습니다!

2022-02-21 08:56 UTC, HyeonaKwon commented on src/index.js
> +        this.view.renderRacingCarProgress(index);
헉 저 때문에 코드가 더 복잡해진건 아닌가 싶어서 조금 죄송스럽네요 😅
저였다면 model 이 움직인 여부를 return 하고 그 값에 따라 바로 view 에 그렸을 것 같아요!

```javascript
// Car
class Car {
  moveForward() {
    if (randomNumber >= RULES.MOVE_CONDITION_NUMBER) {
        this.#distance = this.#distance + 1;
        return true;
    }

    return false;
  }
}


// CarGameModel
playOneGame() {
    const results = this.#racingCarList.map((car) => car.moveForward());
    return results;
}


// RacingCarGameController
startRacingGame() {
    ...
    const results = this.model.playOneGame();
    this.view.renderRacingCarProgress(results);
}


// RacingCarGameView
renderRacingCarProgress(playResults) {
    ...
    playResults.forEach((hasForwarded, index) => {
      if (hasForwarded) {
        this.$racingCarProgress[index].insertAdjacentHTML('beforeend', templateProgress);
      }
    });
  }
```

추가로 자바스크립트에서의 객체는 read-only 상태가 아닌 이상 충분히 가공될 수 있어요! 그렇기 때문에 view 에게 model 의 객체를 넘기는건 위험합니다! 필요한 정보만 가공해서 넘기면 좋을 것 같아요!
(제가 짠 코드가 정답은 아니라.. 그냥 참고로만 봐주세요!)

2022-02-21 09:00 UTC, HyeonaKwon approved these changes
수정사항 모두 확인하였습니다 빅터! 
데모 페이지까지 만들어주셔서 감사해요~ 들어가봐서 테스트도 해봤는데 잘 동작하네요! 테스트 해보면서 보완되었으면 좋겠다 생각했던건 count form 이 활성화되면서 자동으로 count input 에 포커스가 이동되었으면 좋겠다는 생각을 했어요! 요거는 다음 미션 진행하면서 적용해보면 좋을 것 같아요ㅎㅎ

첫 미션인데도 MVC 패턴을 잘 지켜주시고 제 피드백을 찰떡같이 반영해주셔서 감사합니다! 고생 많으셨어요~

2022-02-21 09:00 UTC, merged