[2단계 - 자동차 경주 미션] 동키콩(주동혁) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #138
Opened 2022-02-19 06:45 UTC by JUDONGHYEOK

1단계에 반영하지 못한 코드를 리팩토링하고 2단계의 기능을 추가하였습니다. 1단계를 리팩토링했을 때는 분명 구조가 나름 괜찮은 것 같았는데 복잡한기능도 아닌데 추가를 하다보니 구조가 상당히 깨진 모습을 확인할 수 있었습니다. 많은 고민과 코드를 썼다 지웠다 하다보니 커밋을 잘 나누질 못한것 같네요. 또 2단계를 하다가 몇 가지 궁금한 점들이 생겨 질문드립니다!!

#### 1. 기능을 추가하다보니 View로직이 길어져 ProgressView를 분리하였는데요 이것이 올바른 접근인지 궁금하네요 😢 
> 2단계 기능들이 거의 view와 관련된 내용들이 많다고 여겨졌는데요 따라서 이러한 기능들을 모두 RacingView에 넣으려고 하니 RacingView 파일의 길이가 너무 길어지더라구요. 그래서 뭔가 분리를 하고 싶었는데 RacingView내에서 RacingProgressView인스턴스를 생성해서 접근하는 것이 올바른 접근인지 궁금해서 질문드립니다.

#### 2. getter와 setter의 올바른 사용법이 궁금합니다.
> 제가 사용바와 같을 때 직접접근과 큰 차이가 없는 것 같은데 이와 같이 사용하는게 맞는건지 의문이 들어서 질문드립니다...

#### 3. 1초마다 car들의 postion을 업데이트하는 뷰에서 ProgressView를 아예 지웠다 다시 렌더링 하는 방식으로 하는데 이것이 맞는지 확신이 들지 않습니다.
> 초기에 구현을 할때에는 car들의 Move상황을 boolean타입으로 받고 화살표를 추가하는 방식으로 구현을 하였는데요 이렇게 구현 하다보니 불가피하게 그 전에 렌더링 되었던 노드를 배열의 인덱스로 접근하는 상황이 발생하게 되더라구요. 데이터가 온전히 들어가긴 하였지만 중간에 어떤 보안적인 공격을 받을시에 배열의 인덱스가 꼬이게 되면 중요 데이터인 postion렌더링이 꼬이게 될 것 같아 코드의 안정성을 위해서 그렇게 구현을 하였는데 맞는 것인지 의문이 드네요...

#### 4. requestAnimationFrame의 올바른 사용법이 궁금합니다.
> 저는 requestAnimationFrame을 Js에서 animation을 조작하게 한다라고 생각하여 단순히 spinner가 돌아가는 모션을 구현하는데 사용하였는데요 다른 분들의 코드를 보니 1초마다 RacingProgress가 업데이트되는 행동 자체를 애니메이션으로 판단할 수도 있겠다 라는 생각이 들어서 제가 사용하는 것이 올바르게 사용하고 있는 것인지 궁금해서 질문드립니다.

 정말 많이 부족한 코드지만 잘 봐주셔서 정말 감사드립니다. 🙇‍♂️  질문을 하면서도 이게 해야 될 질문인가 싶은데요. 항상 친절하게 답변해 주셔서 정말 감사드립니다. 고쳐야할 점이 산더미인 코드인데요 피드백 주시면 감사하게 고치도록 하겠습니다!!! 🔥🔥🔥

2022-02-19 15:18 UTC, EungyuCho requested changes
안녕하세요 동키콩님~ step2 진행하시느라 고생 많으셨습니다 ㅎㅎ

커밋을 나누는 부분은 의식하면서 코드를 작성하다보면 분명 차차 개선될거라 생각합니다.
작성하시면서 구조가 깨진 것 같다고 말씀해주셨는데 어떤 부분을 보면서 그렇게 느끼셨는지 궁금하네요!

미션을 진행하시면서 다양한 고민을 해주셔서 정말 좋은 질문들을 해주신 것 같아요! 💡

> 1. 기능을 추가하다보니 View로직이 길어져 ProgressView를 분리하였는데요 이것이 올바른 접근인지 궁금하네요 

`View`가 복잡해진다고 느껴지신다면 분리하셔도 된다고 생각되네요.
하지만 이 폴더구조로 파일을 쌓다보면 실제 프로젝트에서는 `view` 파일이 일관성 없이 모여있어 어떤 페이지에 대한 하위페이지인지 알아보기 힘든 경우가 많아 유지보수면에서 힘들어지곤합니다 💦 
따라서 페이지(스크린)별로 폴더를 분리하시는 방법을 추천드립니다!
```
view
└─── RacingView/
     ├─── index.js (기존 RacingView.js)
     └─── RacingProgresssView.js
```

> 2. getter와 setter의 올바른 사용법이 궁금합니다. 제가 사용바와 같을 때 직접접근과 큰 차이가 없는 것 같은데 이와 같이 사용하는게 맞는건지 의문이 들어서 질문드립니다...

`getter`와 `setter`가 왜 필요할까요? 말씀하신대로 직접 접근으로 해결할 수 있는데 굳이 `getter`와 `setter`로 접근해야 할 이유가 무엇일까요?

동키콩님이 처음 작성하신 자동차 게임에는 시도할 횟수에 대한 입력창과 버튼이 비활성화가 되어있는데 이 부분이 없다면 어떨까요? 차 이름을 입력하고나서 횟수를 입력하는 정상적인 프로세스가 아닌 횟수를 먼저 입력할 수 있는 프로세스를 생각해서 예외처리를 진행해줘야합니다.

`getter`와 `setter`도 똑같은 맥락이라고 생각합니다.
해당 클래스에서 외부에서 직접 할당해서 변경되지 않아야 할 데이터를 `private` 접근자로 관리하고 개발자가 지정한 방식으로만 데이터를 얻거나 설정할 수 있게 하는데 의의가 있다고 봅니다~
OOP에 관련된 내용이라 이 [글](https://velog.io/@kairase024/%EC%BA%A1%EC%8A%90%ED%99%94%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B0%80)을 통해 `getter`와 `setter`를 이해하셨으면 좋겠네요 😄 

> 3. 1초마다 car들의 postion을 업데이트하는 뷰에서 ProgressView를 아예 지웠다 다시 렌더링 하는 방식으로 하는데 이것이 맞는지 확신이 들지 않습니다. 배열의 인덱스가 꼬이게 되면 중요 데이터인 postion렌더링이 꼬이게 될 것 같아 코드의 안정성을 위해서 그렇게 구현을 하였는데 맞는 것인지 의문이 드네요...

모두 지웠다가 다시 렌더링하는 방향보단 기존처럼 화살표를 추가하는 방향성이 맞다고 생각되네요.
배열의 `index`를 키로 사용하시는 부분이 많이 걱정이 되시는 것 같은데 이 부분을 해결해보시는게 더 맞는 방향 같네요. 차를 생성할 때 유일한 id를 생성하거나 이름을 id로 사용하는것도 괜찮은 것 같아요!

생성한 id를 레일마다 [dataset](https://developer.mozilla.org/ko/docs/Learn/HTML/Howto/Use_data_attributes)을 통해 어떤 차에 대한 레일인지 저장해두고 `querySelector`와 `append`를 사용해서 구현해보시는걸 권장드립니다!

> 4. requestAnimationFrame의 올바른 사용법이 궁금합니다. 1초마다 RacingProgress가 업데이트되는 행동 자체를 애니메이션으로 판단할 수도 있겠다 라는 생각이 들어서 제가 사용하는 것이 올바르게 사용하고 있는 것인지 궁금해서 질문드립니다.

`rAF`를 왜 사용하는지 기존 타이머 함수와 어떤 점이 다른지 #110 에서 확인해주시면 감사하겠습니다~
해당 코멘트에서 어떤 경우에 사용하면 될지 대략적인 힌트를 얻으실 수 있을거라 생각됩니다!
말씀하신대로 1초마다 동작하는 업데이트에도 `rAF`를 사용하실 수 있는데 모든 기술이 항상 양날의 검이 있기때문에 적절한 도구를 찾는 과정이 중요하다고 생각됩니다 ㅎㅎ

리페인트 시점에 업데이트 하기위해 모니터 주사율만큼 실행되는 만큼 60hz 기준으로 1초에 60번 해당 함수가 호출되는 걸 의미하는데 해당 특성과 장기적인 관점을 생각하면 저는 1초마다 전진하는 기능에서는 '사용하지 않는다'를 택할 것 같네요~

작성해주신 스피너를 돌리는 함수는 그대로 사용하셔도 되고 조금 더 다뤄보고 싶으시다면 스피너의 `degree`를 상태로 만들어서 스피너의 속도를 줄여보시는것도 도움이 될 것 같네요!

추가로 아래에 코멘트를 추가로 남겼는데 해당 부분도 확인해주시고 개선하실만한 부분을 반영부탁드려요!
다음 리뷰 요청때 뵙겠습니다!! 고생하셔셨습니다~

2022-02-19 15:18 UTC, EungyuCho commented on src/utils/validation.js
`validateCarNames`에서 `input`을 검증하는 부분에서 `isValidLength`에서 길이가 1~5인지 검증하면 되지 않을까요?
그러면 `isContainedNull`는 필요없을 것 같아요 (이전 PR에 포함된 부분이라 위에서 코드라인을 잡았어요 💦 )

2022-02-19 15:18 UTC, EungyuCho commented on src/view/RacingProgresView.js
> +  }
본문에서 `getter` 코멘트 드린 관점에서 한번 더 생각해보실만한 부분같아요~
`vscode`상에서 해당 인스턴스의 메서드로 `node`와 `$racingProgressNode`를 모두 노출시켜주는데 어떤 방향성이 맞는지 고민해봅시다 ㅎㅎ

2022-02-19 15:18 UTC, EungyuCho commented on index.html
> +      <h2 hidden id="racing-form-title">레이싱 게임에 대한 입력폼</h2>
피드백 잘 반영해주셨네요!~ 👍

2022-02-19 15:18 UTC, EungyuCho commented on src/utils/dom-utils.js
> +    $circle.src = '../../public/assets/img/loading.png';
`circle`이 맞는 네이밍일까요? 🤔

2022-02-19 15:18 UTC, EungyuCho commented on cypress/integration/racingCar.spec.js
> +    const racingCount = 4;
테스트 관련 상수들을 `support`폴더에 `constants.js`파일을 생성해서 관리해보는건 어떨까요? (support/index.js에서 import 필수)
그리고 변수명을 대문자로 설정하는게 맞는 방향같아요~

2022-02-20 04:49 UTC, JUDONGHYEOK commented on src/view/RacingView.js
> +    alert(`🎉 축하합니다. 최종 우승자는 ${winnerList.join(', ')}입니다! 🎉`);
아 그렇군요 결과 렌더링을 우선하고 alert에 2초 딜레이를 주는 방식으로 수정하였습니다! 요구사항을 꼼꼼히 읽어야겠네요! 😓

2022-02-20 05:00 UTC, JUDONGHYEOK commented on src/utils/random.js
>        CAR.RANDOM_MAXIMUM_NUMBER
아 뭔가 재사용하지 않을까란 막연한 생각으로 util에 추가했던 것 같네요 리뷰어님 피드백을 보니 car model 내부에 위치해도 될 것 같습니다 car Model 내로 해당 로직을 옮기는 방식으로 수정하겠습니다!

2022-02-20 06:03 UTC, JUDONGHYEOK commented on src/model/RacingGame.js
> +  }
setter함수가 위와 같이 사용되면 되겠군요!! 프로퍼티에 대한 검증이 필요할 때 setter가 유용할 것 같다는 느낌이 듭니다!

2022-02-20 06:10 UTC, JUDONGHYEOK commented on src/utils/dom-utils.js
> +    requestAnimationFrame(DomUtils.animationCallBack($carProgressStatus, 2000));
아 미처 발견하지 못했네요 더욱 꼼꼼히 살펴보고 PR하겠습니다...

2022-02-20 06:19 UTC, JUDONGHYEOK commented on src/utils/validation.js
>    if (!isInteger(count)) {
역시 js 내장메서드는 끝이 없는것 같네요 자주 학습하고 사용해봐야겠네요 감사합니다 😃

2022-02-20 06:39 UTC, JUDONGHYEOK commented on src/utils/dom-utils.js
> +    $circle.src = '../../public/assets/img/loading.png';
`circle`이 해당 엘리먼트를 말하기엔 너무 포괄적인 의미인 것 같습니다. `$spinnerImg`로 바꿨는데 어떻게 생각하시나요??

2022-02-20 06:40 UTC, JUDONGHYEOK commented on src/style/style.css
> +}
`img`가 새로 추가되면 유지보수에 확실히 문제가 생기겠네요 클래스로 수정하였습니다!!

2022-02-20 16:22 UTC, JUDONGHYEOK commented on src/view/RacingProgresView.js
> +  }
`$racingProgressNode`를 외부에서 직접접근하여 수정할 경우 큰 오류가 발생할 것 같네요 private화 하여 직접접근을 막았습니다. `getter`와 `setter`의 감이 잡히는 것 같네요 감사합니다!!

2022-02-20 16:30 UTC, JUDONGHYEOK commented on src/utils/validation.js
공백의 경우와 validLength를 벗어난 경우를 다른 메세지로 표현하고 싶어서 그렇게 구현했던 것 같은데 생각해보니 1자 이상 5자이하로 표현을 해도 무방할 것 같네요 수정하도록 하겠습니다!!

2022-02-20 16:40 UTC, JUDONGHYEOK commented on cypress/integration/racingCar.spec.js
> +    const racingCount = 4;
변수가 계속 반복되어 고민중이었는데 그런 방법이 있었군요 감사합니다!

2022-02-20 16:52 UTC, JUDONGHYEOK commented
정말 답변 하나하나에 너무나도 많은 정보들을 얻어가네요 진심으로 감사드립니다!!

 피드백 해주신대로 렌더링 과정을 전부 지웠다 다시 렌더링 하는 방식에서 movedCarsName리스트를 파라미터로 전달받아 dataset에 있는 name과 비교하여 리스트에 속하는 경우 화살표를 추가하는 방식으로 렌더링 방식을 변경하였습니다. 또 spinner 또한 round*1000초를 애니메이션을 실행하고 자체적으로 remove하는 방식으로 구현하였습니다!!
 또한 view 폴더 내에서 RacingView폴더를 만들어 애플리케이션이 확장할 경우를 대비하였습니다!!

코멘트 남겨주신부분들에 대해서도 리팩토링을 모두 진행하였습니다. 깔끔하지 못했던 코드인데 피드백을 반영하니 어느정도 읽기에 더 나아진 것 같습니다. 감사합니다!! 또다른 피드백이 있으시면 마구마구 해주시면 감사하겠습니다!! 😃

2022-02-21 03:46 UTC, EungyuCho commented on src/utils/dom-utils.js
> +    $circle.src = '../../public/assets/img/loading.png';
적절한 것 같습니다~

2022-02-21 03:47 UTC, EungyuCho commented on cypress/integration/racingCar.spec.js
> +    const racingCount = 4;
음.. 선택하기 나름이지만 저는 분리를 진행할 것 같네요.
어떤 부분에서 `invalid`인지 변수명에 담아서 분리할 것 같아요 ㅎ

2022-02-21 04:16 UTC, EungyuCho requested changes
동키콩님 안녕하세요~

피드백 반영하신 부분확인해서 추가적인 코멘트를 몇개 더 작성했습니다.
동키콩님 말씀대로 코드가 눈에 띄게 좋아지는 것 같네요 ㅎㅎ
프로젝트가 커질 가능성을 대비해서 폴더를 분리한 부분도 눈에 띄고 `getter`과 `setter`에 대해서도 한층 더 익숙해졌다는 점이 코드에 녹아났어요!

잘 반영해주셔서 감사하고 코멘트 확인 후에 다시 뵐게요! 👍

2022-02-21 04:16 UTC, EungyuCho commented on src/index.js
> +import RacingView from './view/RacingView/index.js';
이 파일에 `controller.app()`으로 게임에 관련된 컨트롤러를 초기화해주셨는데 조금 더 적합한 네이밍은 없을까요?

2022-02-21 04:16 UTC, EungyuCho commented on src/utils/validation.js
> +  );
좋네요! 개선 전보다 직관적입니다 😄

2022-02-21 04:16 UTC, EungyuCho commented on src/view/RacingView/index.js
> +    }, TIME.DELAY_RACE_RESULT);
필수 구현사항은 아니지만 경고창이 뜨기전에 다시 시작을 하면 해당 축하메세지가 뜨지않게 추가적으로 구현해보실 수 있을까요?

2022-02-21 04:16 UTC, EungyuCho commented on src/view/RacingView/RacingProgresView.js
> +      });
잘 구현해주셨네요! 👏

2022-02-21 04:16 UTC, EungyuCho commented on src/model/Car.js
> +  }
`this.canMove`로 클래스에 새로운 필드를 만드시는 것 보다는 바로 리턴을 해주는 방향성이 낫다고 생각이 드는데 어떻게 생각하실까요?
그리고 해당 메서드도 `private`상태여도 무방하다고 생각이드네요!~

2022-02-21 06:26 UTC, JUDONGHYEOK commented on src/model/RacingGame.js
> +
아 그러면 캡슐화가 더욱 분명해지겠군요 감사합니다 바로 수정하겠습니다. 😄

2022-02-21 07:00 UTC, JUDONGHYEOK commented on src/model/Car.js
> +  }
새로운 필드를 만든 이유는 차가 움직인 여부를 racingGame에서 확인하기 위해 위와 같이 구현하였는데 옳지 않은방법일까요?

2022-02-21 07:06 UTC, JUDONGHYEOK commented on src/index.js
> +import RacingView from './view/RacingView/index.js';
`app`이라는 이름이 굉장히 모호한 것 같습니다. `initRacingGame()`은 어떤가요?

2022-02-21 07:09 UTC, JUDONGHYEOK commented on src/view/RacingView/index.js
> +    }, TIME.DELAY_RACE_RESULT);
오 그런식으로도 기능을 개선해나갈수 있군요 감사합니다 한 번 도전해보겠습니다!!

2022-02-21 07:25 UTC, EungyuCho commented on src/model/Car.js
> +  }
> 새로운 필드를 만든 이유는 차가 움직인 여부를 racingGame에서 확인하기 위해 위와 같이 구현하였는데 옳지 않은방법일까요?

아닙니다~ 동키콩님이 `racingGame`에서 가지고 있어도 좋을 상태라고 판단하셨다면 현재 그대로 사용하셔도 무방합니다 ㅎㅎ
저는 추가로 사용하지 않을 데이터인 줄 알았네요 💦

2022-02-21 07:27 UTC, EungyuCho commented on src/index.js
> +import RacingView from './view/RacingView/index.js';
`initRacingGame` 나쁘지 않은 것 같아요~
만약 해당 함수를 호출할 때 `racingGame`이라는 정보가 알 필요가 없다면 `init`만으로도 충분해보입니다!

2022-02-21 07:43 UTC, JUDONGHYEOK commented
적어주신 피드백들 모두 너무너무 감사드립니다 OOP는 공부하면 할수록 어려워지는것 같네요... 적어주신 피드백과 참조해주신 글들 보면서 많은 도움이 되었습니다!!

 judgeMove같은 경우 canMove필드가 네이밍이 모호한 것같아 move에서 isMoved필드를 제어하는 방식으로 변경하였습니다! 추가로 네이밍변경과 말씀해주신 축하메세지가 뜨기전 다시시작 버튼을 누른 경우에 대해 축하메세지 timeout을 clear하는 방향으로 구현하였습니다.

 많이 부족한 코드지만 적어주신 피드백과 코멘트들 덕분에 깔끔해진 것 같습니다!! 감사합니다!

2022-02-21 13:53 UTC, EungyuCho approved these changes
안녕하세요 동키콩님!

피드백도 모두 반영해주시고 추가적으로 별도의 피드백이 없었는데도 잘 바꿔주셨네요!

> 아 추가적으로 혹시 OOP관련해서 도서 추천좀 해주실 수 있을까요??

OOP를 책으로 공부한건 자바의정석밖에 없다보니 추천드리기 조심스럽네요 ㅎㅎㅎ;
다른분들께 추천받은 [객체지향의 사실과 오해](http://www.yes24.com/Product/Goods/18249021?Acode=101)을 추천드리겠습니다~ 

2주간 정말 고생하셨습니다~
코드 커밋 컨벤션이 일관성있게 작성되있었고 좋은 질문들을 많이 해주셔서 코멘트가 오고가는동안 재밌었습니다 😄 

이후 미션에서도 잘 해나가실거라 생각합니다! 👏
승인하겠습니다~

2022-02-21 13:53 UTC, merged