[2단계 - 자동차 경주 미션] 결(김윤진) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #141
Opened 2022-02-19 11:06 UTC by yunjin-kim

[데모페이지](https://yunjin-kim.github.io/javascript-racingcar/)

안녕하세요! YB님

1단계 피드백인 로직을 분리하는데 집중해보았습니다
데이터를 관리하는 클래스
화면을 관리하는 클래스
두 클래스를 연결해주는 클래스를 만들어서 메서드 간의 의존성을 줄일려고 노력해봤습니다

2단계가 시작하면서 구조를 고민해가면서 코드를 짰지만 아직 맘에 들지는 않는 것 같네요..

너무 늦게 제출해서 아쉽고 죄송하네요🥲

2022-02-19 15:01 UTC, youngbeomrhee requested changes
결님 안녕하세요 구현하시느라 고생 많으셨습니다
피드백 드린 내용을 반영해주신 영역 잘 확인했습니다
다만 기존 피드백과 새로운 요구사항 중 필수요구사항에 해당하는 부분이 반영되지 않은 영역들이 있어 다시 수정요청 드립니다

추가적으로 시간이 되신다면 아래 개선사항도 고민해 보시면 좋을 것 같습니다
- 이 프로그램은 크게 봤을 때 입력, 경주, 우승자 표시 이렇게 3개의 도메인으로 구성되어 있다고 봅니다. 기존 코드를 MVC 패턴으로 하나씩의 파일로 분리해 주셨지만 그 안에서도 한 번 더 분리해 보시기를 권해 드립니다
- 사용자가 오류를 발생시킬 수 있는 영역에 대한 제약사항을 추가해 보시면 보다 나은 사용자 경험을 제공할 수 있을 것 같습니다. 현재는 아무런 제약사항이 없기 때문에 쉽게 프로그램을 다운시킬 수 있습니다. (예: 너무 많은 사용자 입력, 게임횟수에 지나치게 큰 값 입력)

고지가 얼마 남지 않았습니다 조금만 더 화이팅입니다

2022-02-20 07:50 UTC, yunjin-kim reviewed
안녕하세요 YB님
좋은 코드 리뷰 감사드립니다
한가지, Car class에 대한 리뷰 확인 부탁드립니다!

2022-02-20 07:50 UTC, yunjin-kim commented on cypress/integration/app.spec.js
> +it("정상적으로 게임의 턴이 다 동작된 후에는 결과를 보여주고, 2초 후에 축하의 alert 메세지를 띄운다", () => {
수정완료입니다!

2022-02-20 07:50 UTC, yunjin-kim commented on cypress/integration/app.spec.js
> +    cy.on("window:alert", alertStub);
수정완료입니다!

2022-02-20 09:31 UTC, youngbeomrhee requested changes
결님 안녕하세요 피드백 반영하느라 고생하셨습니다
질문주신 사용하지 않는 코드 정리에 대해서 답변 드렸으니 확인 부탁 드립니다
코드가 정리되면 일단 필수요구사항은 모두 구현됐으니 Approve 해드릴 수 있을 것 같습니다
아쉬운 점은 직전 리뷰에서 추가 개선점에 대해서 말씀을 드렸지만 그에 대한 반영이나 언급이 전혀 없다는 점인데요
시간이 가능하다면 직전 피드백에 리뷰드린 선택적 개선사항도 좀 더 고민해 보시면 좋을 것 같습니다
리뷰드린 내용에 대해 다른 생각을 가지고 계시거나 수행이 어려운 상황이라면 말씀주시면 좋을 것 같습니다

2022-02-20 09:31 UTC, youngbeomrhee commented on cypress/integration/app.spec.js
> +    cy.on("window:alert", alertStub);
예 요구사항 잘 반영해 주셨네요 고생하셨습니다

2022-02-20 09:31 UTC, youngbeomrhee commented on src/class/Car.js
> +class Car {
기존의 src/Car.js를 src/class/Car.js로 이관하시면서 더이상 사용되지 않는 src/Car.js가 삭제되지 않은 것으로 보입니다

2022-02-20 11:46 UTC, yunjin-kim reviewed
안녕하세요 YB님

빠르게 고칠 수 있는 코드를 먼저 고치고 구조를 바꾸는 리펙토링은 시간이 걸릴 것 같아
고친 코드부터 먼저 피드백 받으려 했으나 그에 대한 저의 의사소통이 부족했던 같네요...
죄송합니다🥲

처음 리뷰에 대한 피드백을 반영해서 코드를 수정했습니다
view 클래스를 도메인 별로 분리하고 input에 입력할 수 있는 값의 제약사항을 추가했습니다

추가로 질문 2개가 있습니다
Model 클래스, 데이터를 조작하는 클래스를 분리함에 대해 어떻게 생각하시나요?
같은 클래스에서 메서드의 임시변수를 this or const 로 선언하는데에 있어 YB님의 기준이 있으신가요?

좋은 피드백 너무 감사드립니다!
[최종데모페이지](https://yunjin-kim.github.io/javascript-racingcar/)

2022-02-21 14:14 UTC, youngbeomrhee approved these changes
결님 안녕하세요 미션 마무리 하시느라 고생하셨습니다
피드백 드린대로 코드를 좀 더 분리하고 예외상황에 대해서 더 고민해서 리팩토링을 진행해 주셨네요 고생 많으셨습니다

질문 주신 사항에 답변 드리자면 Model 클래스를 데이터를 담는 역할과 조작하는 역할로 기본적으로 크게 분리할 수 있을 것 같습니다. 지금은 요구사항이 단순하고 다루는 데이터가 적다보니 하나의 파일로 구현이 가능하지만 실제 업무에서는 훨씬 더 복잡한 경우가 많으므로 그 안에서도 기준을 잡고 보다 더 세분화해서 구현해 보시면 좋을 것 같습니다
그리고 두 번째 질문주신 클래스에서 메서드의 임시변수를 this와 const로 선언하는 경우의 기준은 기본적으로 해당 변수의 scope(유효범위)가 될 것 같습니다. 그리고 this로 선언되서 해당 클래스의 전역으로 사용할 변수라면 한 곳에 모아서 선언해야 사용될 변수를 한 눈에 확인할 수 있을 것 같습니다. 작성하신 코드에서 대부분의 로직 전역으로 관리해서 모든 흐름을 제어하고 있는데요. 역할별로 위임해서 this를 줄이는 훈련을 해보시면 좋을 것 같습니다

리뷰를 주고받는 시간이 의미있는 경험이 됐으면 하는 마음이 앞서 다소 깐깐하고 직설적으로 리뷰를 드린 것 같아 죄송한 마음이 드네요 
고생 많으셨고요 남은 과정 잘 마무리 하셔서 좋은 곳에 개발자로서 첫 발을 잘 내딛으셨으면 합니다 :)

2022-02-21 14:14 UTC, merged

2022-02-21 14:23 UTC, yunjin-kim commented on index.html
> +                  placeholder="최대 5대의 자동차까지 입력할 수 있습니다"
YB님 안녕하세요!

첫번째로
"Model 클래스를 데이터를 담는 역할과 조작하는 역할로 기본적으로 크게 분리할 수 있을 것 같습니다"
와 생각지도 못했네요 👏👏👏

두번째로 
this 와 const 쓰는 기준이 명확해진 것 같습니다. 감사합니다

"다소 깐깐하고 직설적으로 리뷰", 저는 더 좋았던 것 같습니다
한 번 더 고민해보게 리뷰 해주셔서 감사합니다
YB님의 건강한 개발 생활 기원합니다😃