[2단계 - 자동차 경주 미션] 위니(김예지) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #147
Opened 2022-02-20 03:24 UTC by rladpwl0512

안녕하세요, 2단계 과제 제출합니다. 
너무 늦게, 주말에 제출 드려서 정말 죄송합니다. (저한테 갑작스러운 일이 생겨서, 해결한다고 정신이 없었네요... 사실 지금도 해결중입니다🥲)

지난주에 구조에 대한 질문에 대해 피드백을 주셨는데, 아직 정확히 mvc 패턴에 대한 이해가 부족한 것 같아서 제대로 구조를 개선하지 못한 것 같은 아쉬움이 있습니다. 더 공부해보고 반영하겠습니다! 
2단계에서 제가 반영한 것은 다음과 같습니다. 

### 🎯 &nbsp;구현 기능 목록 (level 2)
- [x] 자동차 경주 게임의 턴이 진행 될 때마다 1초의 텀(progressive 재생)을 두고 진행한다.
  - [x] 1초의 텀동안 로딩 애니메이션을 보여준다.
  애니메이션 구현을 위해 setInterval, setTimeout, requestAnimationFrame 을 활용한다.
- [x] 정상적으로 게임의 턴이 다 동작된 후에는 결과(우승자)를 보여준다. 
- [x] 결과(우승자)를 보여준 후, 2초 후에 축하의 alert 메세지를 띄운다.
- [x] E2E 테스트 작성(구현 기능 목록에 대한 테스트)
  - [x] 게임이 끝난 후, 우승자를 알림창으로 확인할 수 있어야한다.

### 데모메시지
https://rladpwl0512.github.io/javascript-racingcar/

2022-02-20 14:53 UTC, inwalter99 requested changes
위니님 너무 고생많으셨습니다.

갑작스러운 일은 잘 해결되셨는 지 잘 모르겠네요 ㅠㅠ 그럼에도 불구하고 저는 저의 역할에 최선을 다해보겠습니다..!
제가 드리는 피드백은 정답도 아니고 100% 받아들여야하는 부분은 아니니 너무 부담갖지 않고 적절히 보시면 좋겠습니다!

우선 이번 미션은 MVC 를 구현하거나 이해하란 말은 없었기 때문에 그 부분에 너무 매몰되지 않으시길 바랍니다! 부트캠프 특성상 다른 크루가 뭔가 그럴듯하게 하면 나도 그래야할 거 같고, 저게 정답같아 보이는데 위니님만의 방법, 속도를 지키는 게 부트캠프에서 가장 중요한 거 같아요. 1단계에서 위니님께서 MVC 패턴을 말씀주셔서 저도 그에 대한 코멘트를 드린거고, 이어서 2단계에서 그에 대한 코멘트를 드린 것일뿐이에요! 만약에 다른 부분이 미흡한 게 느껴지신다면 절대절대 MVC 는 패스하시길 추천드릴게요. 앞으로 기회는 너무 많습니다 9ㅅ9 
그래서 코멘트를 조금 더 가이드를 드려보는 방향으로 작성해봤어요. 한 번 보시고 생각해보시면 좋을 거 같습니다.

1단계 때에 비해 구조적으로 변경된 부분들이 좀 보이긴 하는데, 아마 위니님께서 개선하시면서 좀 더 적절하다고 생각하신 방향으로 개선한 게 아닐까 생각됩니다. 저도 마찬가지로 심지어 현업에서도 어제 짠 코드가 맘에 안들어서 이리저리 바꾸고 그러기도 합니다 -.- 과감한 시도하신 거 너무 칭찬드리고요. 위에 말씀드린 내용 적절히 반영해보시면 좋겠습니다!

전반적으로 1단계에 비해 개선된 점이 너무 많아서 좋아요~!

2022-02-20 14:53 UTC, inwalter99 commented on src/view/viewSpinner.js
> +}
https://github.com/woowacourse/javascript-racingcar/pull/147/files#diff-500d565712f6a3f8e4e4861994f100453f69bd2d265515c75b4591f78375de62R27 에서 `hideSpinner(document.querySelectorAll('.spinner'))`이렇게 호출을 하고 있는데, Controller 입장에서는 View 에게 '스피너를 숨겨줘!'만 해주면 좋을 거 같습니다. 'DOM 을 가져와 스피너를 숨기는 것'까지 View 는 제공을 해주고, 그 실행은 Controller 에서 하면 되고요
```suggestion
// hideSpinners();
export function hideSpinners() {
  const spinners = document.querySelectorAll('.spinner')
  spinners.forEach(spinner => {
    spinner.classList.add('display-none');
  });
}
```

2022-02-20 14:53 UTC, inwalter99 commented on src/controller/playRace.js
> +  alertWinners(getWinners(cars));
함수를 두 번 호출하지 않아도 좋을 거 같아요~
```suggestion
  const winners = getWinners(cars)
  showWinners(winners)
  alertWinners(winners)
```

2022-02-20 14:53 UTC, inwalter99 commented on src/view/viewSpinner.js
> +    spinner.classList.add('display-none');
display none 을 해도 (게임이 종료되어도) 위에서 실행한 애니메이션이 계속해서 돌고 있지 않을까요?

2022-02-20 14:53 UTC, inwalter99 commented on src/controller/playRace.js
> +  });
지금 당장 cars 나 count 를 담고 있는 모델이나 그 외 어떠한 것이 없기 때문에 DOM 에서 cars 의 개수를 가져와 랜덤하게 화살표를 '그려주고 있고'
getWinners 에서 

지금 보면 
Controller 가 Car 를 변경시켜, View 를 그려주는 게 **아니라**
Controller 가 View 를 다 그린 다음, getWinners 할 때 그려놓은 결과를 가져와 계산해서 Car 를 결과론적으로 변경시키는 거 같습니다. 

대략적으로 아래와 같이 플로우가 진행되어야할 거 같습니다. 지금은 플로우도, 구조도 적절하지 않다는 생각입니다 ;ㅁ;

- 게임판 그리기 (addGameProcessTemplate)
- Controller 가 게임을 진행 시킴 (updateGameProcess)
    - 턴 진행하면서 Model 에게 요청해 cars 을 변경
    - 변경 시킨 결과를 View 에게 요청해 그림
- endGame
    - Controller 에서 model 을 분석해 winners 를 계산
    - winners 를 그려달라고 요청 showWinners, alertWinners

2022-02-20 14:53 UTC, inwalter99 commented on src/view/viewSpinner.js
> +}
8ㅅ8 로딩이 그려지나요?! 저는 왜 안그려지지

https://user-images.githubusercontent.com/28642472/154848251-692c636e-6936-4908-b6d8-de6d7f1d0349.mov

2022-02-20 15:02 UTC, rladpwl0512 commented on src/view/viewSpinner.js
> +}
vs code에서 live server를 돌렸을때는 괜찮은데, 깃헙에서는 제대로 뜨지 않는 것 같네요...! 어디서 잘못됐는지 확인해보도록 하겠습니다 :)

2022-02-20 15:05 UTC, rladpwl0512 commented on src/controller/playRace.js
> +  });
정말 중구난방이네요...🤣 기능구현 자체에 포커스를 둔다고 이 부분을 신경쓰지 못한 것 같습니다! 
이부분도 개선하도록 하겠습니다~ 
적어주신 것과 같이, 함수 역할과 흐름을 생각하는게 좋겠네요!

2022-02-20 15:06 UTC, rladpwl0512 commented on src/view/viewSpinner.js
> +    spinner.classList.add('display-none');
이 부분 고민하고 있었는데, 피드백 주셔서 감사합니다☺️

2022-02-21 06:43 UTC, rladpwl0512 commented on src/view/viewSpinner.js
> +}
제가 경로를 제대로 작성하지 않아서 생긴 에러였습니다! 해당 부분 고쳐서, 지금은 잘 그려집니다 👍

2022-02-21 07:32 UTC, rladpwl0512 commented
리뷰어님 이번에도 꼼꼼한 피드백 감사합니다 😌
피드백을 반영했으나, 구조에 대한 부분은 계속해서 개선 중입니다. 
피드백 주신 것 처럼, mvc에 따른 구조도 플로우도 뒤죽박죽인 부분들이 많아서 이 부분들 계속해서 개선하도록 하겠습니다! 
(마감 시간인 6시 전까지 가능할지는 확실치 않네요😅 꽤 많은 부분들을 바꿔야할 것 같아서요. 노력해보겠습니다!)

이번 리뷰에서도 정말 많이 배웠습니다! 감사합니다.

2022-02-21 13:06 UTC, inwalter99 approved these changes
위니님 고생하셨습니다!
여기까지 머지해보도록 하겠습니다.

일단 가장 인상 깊었던 건, 마지막 커밋 [a7c3a65](https://github.com/woowacourse/javascript-racingcar/pull/147/commits/a7c3a65b5c7fbfaf9e60a465946f728f126bd1eb) 이 개인적으론 가장 좋았습니다.
아무리 코드를 잘 짜고 해도 커밋이 잘 나뉘어져있지 않고, 무분별하게 커밋을 하면 협업하는 데 히스토리 파악하는데 정말 어렵거든요. 근데 [a7c3a65](https://github.com/woowacourse/javascript-racingcar/pull/147/commits/a7c3a65b5c7fbfaf9e60a465946f728f126bd1eb) 이 커밋은 제가 생각하는 가장 이상적인 구조를 갖고 있네요! 커밋만 보고 안의 코드를 유추할 수 있었어요! 칭찬 백 개
```js
제목: WHAT 무엇을 했는지

본문: WHY 왜 이 커밋을 작성하게 되었는지, 왜 그렇게 했는지
```

마무리하고 계신 걸로 알고 있지만ㅜ 늦은 밤까지 화이팅입니다!!
이번 미션에서 미처 놓친 부분들은 자연스럽게 다음 미션들에서 채워질 예정이니 너무 붙잡고 늘어지신 마시고 이번 미션에서 배운 것들 잘 정리하고 다음 미션으로 가도 좋아요!

2022-02-21 13:06 UTC, merged