[1단계 - 자동차 경주 구현] 윤생(이윤성) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #154
Opened 2023-02-09 08:03 UTC by 2yunseong

2023-02-09 15:36 UTC, Puterism requested changes
안녕하세요 윤생 😃 
이번 미션의 리뷰어를 맡게 된 체프라고 합니다. 반갑습니다!

첫번째 미션 구현하시느라 고생 많으셨어요. 전체적으로 깔끔하게 코드를 짜주셔서 떠오르는 피드백이 많지 않았네요 😅  피드백과 더불어 질문을 몇 가지 남겨놓았으니 확인 부탁드릴게요.

추가로 package-lock.json과 yarn.lock 파일이 같이 있어서 yarn과 npm을 둘 다 사용하는 것으로 보여져요. 패키지 관리자는 하나만 사용하시는 것이 좋으니 통일 부탁드릴게요! (왜 그런지도 생각해보시면 좋을 것 같네요!)

2023-02-09 15:36 UTC, Puterism commented on src/GameManager.js
> +    return winners;
우승자를 판정하는 로직은 sort와 filter, map을 이용해서 깔끔하게 잘 짜주신 것 같아요! 좋습니다 👍

2023-02-09 15:36 UTC, Puterism commented on src/GameManager.js
> +module.exports = GameManager;
ES6 문법으로 export하지 않은 이유가 혹시 있으셨을까요?

2023-02-09 15:36 UTC, Puterism commented on __tests__/GameManager.test.js
> +    expect(gameManager.judgeWinners([...cars])).toEqual(winners);
toBe와 toEqual을 둘 다 사용해주셨는데요. toBe와 toEqual의 차이점은 무엇일까요?

2023-02-09 15:36 UTC, Puterism commented on __tests__/Validation.test.js
> +describe('Validation Test', () => {
입력값 유효성 검사 테스트까지 진행하시다니 좋네요 👍

2023-02-09 15:36 UTC, Puterism commented on src/utils/Validation.js
> +    return carNames.every((name) => name.length > 0 && name.length <= 5);
이렇게 숫자값 그대로 코드에 사용되는 것을 매직 넘버라고 하는데요.
매직 넘버 0과 5에 대해서도 상수화를 진행해주시면 좋을 것 같아요!

2023-02-09 15:36 UTC, Puterism commented on src/utils/Validation.js
> +    return carNames.every((name) => name.length > 0 && name.length <= 5);
every와 some의 차이점은 무엇일까요?

2023-02-10 08:03 UTC, 2yunseong reviewed
안녕하세요 체프!  인사가 늦었네요 🚰 ·̫🚰	
먼저 PR메세지를 먼저 작성했어야 했는데 그러지 못한 점 죄송합니다 ㅠㅠ 다음 번에는 주의해서 작성할께요.
많은 고민거리나 생각할 주제를 던져주셔서 너무 감사드립니다!
거기에 이어 제가 몇가지 질문이랑 답변을 남겼습니다!!
즐거운 금요일과 함께 주말도 잘 보내시길 바랍니다 :D

2023-02-10 13:48 UTC, Puterism commented on src/Car.js
> +  }
저도 언어에서 제공하는 getter 기능을 사용하는 게 더 좋을 것 같다는 생각에 동의합니다 :)

2023-02-10 13:55 UTC, 2yunseong commented on src/Car.js
> +  }
답변 감사합니다~!

2023-02-10 14:01 UTC, Puterism commented on src/utils/Validation.js
> +    return carNames.every((name) => name.length > 0 && name.length <= 5);
저도 잘 모르겠어서 조사해봤는데요. 다행히 방법이 있는 것 같네요. `Intl.Segmenter`에 대해서 알아보시면 좋을 것 같습니다.

2023-02-10 14:18 UTC, Puterism commented on src/Car.js
> +  }
저는 개인적으로 `이동할지/안할지의 결정` 또한 GameManager가 가지고 있어야 한다고 생각했어요. GameManager가 차를 움직이게 할지 말지를 결정할 수 있는 주체가 되는 것이 좋다고 생각했거든요.

물론 정답은 없습니다. 차 객체가 어디까지 책임을 가지게 할 것인가에 따라서 달라질 것 같아요. 결정은 윤생이 해주시면 됩니다 :)

2023-02-10 16:19 UTC, 2yunseong commented on src/Car.js
> +  }
어떤 경우가 더 나을 것인지 고민해봐야겠네요! 감사합니다 체프:D

2023-02-11 11:06 UTC, Puterism approved these changes
수고 많으셨습니다! 다음 2단계에서 뵈어요~

2023-02-11 11:06 UTC, merged

2023-02-12 08:33 UTC, 2yunseong commented
넵!! 감사합니다~~