[1단계 - 자동차 경주 구현] 유스(정수영) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #157
Opened 2023-02-09 08:05 UTC by suyoungj

안녕하세요 브콜!
5기 프론트엔드 크루로 합류하게 된 유스입니다.

2023-02-09 18:33 UTC, Tanney-102 requested changes
안녕하세요 유스! 리뷰어 브콜입니다🥦
첫 미션 진행하느라 고생많으셨어요~

Car, CarManager 클래스에 도메인 관련 로직이 모여있도록 잘 구현해주신 것 같아요~
이것만으로 이번 미션에서 필요한 내용의 절반 이상은 얻으신 듯 싶지만 몇가지 더 살펴보면 좋을만한 부분들 코멘트 드렸습니다!

질문에 답변드립니다.
> 도메인, UI 로직을 각각 객체 또는 클래스로 분리해 보았는데, 적절히 분리되었는지 브콜의 의견이 궁금합니다.

의도하신대로 잘 분리해주신 것 같습니다👍
뷰는 뷰만 드리도록, Car와 CarManager는 자동차의 동작만을 나타내도록 잘 작성해주신 것 같아요.

> - 도메인 로직과 관련된 상수를 어떻게 관리하시는지 궁금합니다. 떠오르는 방법들은 다음과 같습니다.
>      - 동일한 파일 내에서 관리 / 같은 폴더 내에 별도의 파일에 관리 / 별도의 폴더 내에 별도의 파일에 관리
>      - 또는 다른 방법이 있을까요?

개인적으로는 관련있는 로직과 최대한 붙어있는 걸 선호합니다.
다만 해당 상수가 어떤 모듈들 사이에서 공유되느냐에 따라 스코프는 정하기 나름일 것 같습니다.
특정 모듈과 관련있는 상수라면 같은 파일 혹은 같은 폴더에서 관리해도 충분하겠지만 여러 모듈과 관련될 수 있는 상수라면 더 상위 폴더에서 관리될 필요가 있겠죠~

> - 적절한 테스트 케이스 개수에 대한 궁금증입니다.
>     - 주어진 시간 내에 최대한 많은 케이스에 대해 작성하시는지, 미리 적절한 케이스들을 작성하고 해당 케이스에 대해서만 테스트를 작성하시는지 궁금합니다.

모든 케이스가 표현되는 게 좋다고 생각합니다.
테스트 케이스는 함수나 모듈이 구체적으로 어떻게 동작하는지를 서술하는 일종의 스펙입니다.
스펙을 작성하는데 적절한 케이스 개수가 따로 있을지 잘 모르겠습니다🤔

2023-02-09 18:33 UTC, Tanney-102 commented on src/App.js
> +      OutputView.printErrorMessage(error.message);
이 함수는 validInput인지 판단(true/false 반환) 하는 것과 에러메시지를 보여주는 것 두가지 일을 하는군요!

2023-02-09 18:33 UTC, Tanney-102 commented on src/App.js
> +  }
지금은 InputCarNames 호출만으로 모든 동작이 수행됩니다.
사용처에서는 `input car names`라는 동작을 시켰는데, try count, start race까지 모두 수행을 하고 있어요.
지금 상황에서 각 함수는 정말 한 가지 일을 하고 있다고 봐도 될까요?

2023-02-11 01:07 UTC, suyoungj commented
정성스러운 리뷰 감사합니다 브콜! 🥦

더 나은 구조와 코드를 고민하면서 피드백을 반영해 보았습니다.
이전보다 많이 개선된것 같아 뿌듯하네요.
궁금한 점은 코멘트로 남겨두었습니다.

주말 잘 보내세요!

2023-02-11 01:07 UTC, suyoungj commented on README.md
> +### 페어 : 유스, 부엉이
감사합니다! 열심히 쓴 보람이 있군요 😂

2023-02-11 01:07 UTC, suyoungj commented on __tests__/Car.test.js
> +    expect(car instanceof Car).toEqual(true);
무의미한 테스트라 생각되어 제거했습니다 🗑 
[Commit](https://github.com/suyoungj/javascript-racingcar/commit/112af5e2919bee23cee18a72a384e4af4208038c)

2023-02-11 01:07 UTC, suyoungj commented on __tests__/Car.test.js
> +  test('무작위 값이 4 이상인 경우 자동차를 전진', () => {
신경쓰지 못한 부분이네요! 피드백 감사합니다.
test.each를 활용하여 모든 값에 대해 테스트하도록 수정했습니다 ✅ 
[Commit](https://github.com/suyoungj/javascript-racingcar/commit/112af5e2919bee23cee18a72a384e4af4208038c)

2023-02-11 01:07 UTC, suyoungj commented on __tests__/CarManager.test.js
> +  });
무의미한 테스트라 생각되어 제거했습니다 🗑 
[Commit](https://github.com/suyoungj/javascript-racingcar/commit/5f87f045a05a0350d5d065445e840c2bf4a3ccf6)

2023-02-11 01:07 UTC, suyoungj commented on __tests__/CarManager.test.js
> +  });
반영 완료했습니다 ✅ 테스트 케이스를 꼼꼼히 작성하도록 신경쓰겠습니다! 
[Commit](https://github.com/suyoungj/javascript-racingcar/commit/16476722bddd5f02c63b4292bdd3cebf8bf16e3b)

2023-02-11 01:07 UTC, suyoungj commented on __tests__/CarManager.test.js
> +    test('우승자가 한 명인 경우', () => {
여기서 보니 쓰다 만 느낌이 물씬 나네요 😅
조건에 따른 결과를 명확히 알 수 있도록 수정했습니다 ✅ 
[Commit](https://github.com/suyoungj/javascript-racingcar/commit/4b1b01c1fbc916b519d4e8c120ece9d9b19774c4)

2023-02-11 01:07 UTC, suyoungj commented on __tests__/Validator.test.js
> +describe('자동차 이름을 위한 입력값의 유효성 검사', () => {
Validator를 CarNamesInputValidator, TryCountInputValidator로 분리한 후,
예외 처리와 정상 동작 모두 테스트하도록 수정했습니다 ✅
[Commit](https://github.com/suyoungj/javascript-racingcar/commit/c707e2abfecf6175852d81f40474c1631ead2611)
[Commit](https://github.com/suyoungj/javascript-racingcar/commit/b4b30b583a3454769492b3b99998eb6564c79451)

2023-02-11 01:08 UTC, suyoungj commented on src/constants/validation.js
> +const VALID_CHARACTER_REGEX = /^[a-z|A-Z|가-힣|,]+$/g;
반영 완료했습니다 ✅ 겉핥기식으로 공부한 티가 여기서 나네요..😅 
[Commit](https://github.com/suyoungj/javascript-racingcar/commit/8d8f9fc856b2b6e45cbd511242b9f1d8f3f42fc0)

2023-02-11 01:08 UTC, suyoungj commented on src/utils/RandomNumberGenerator.js
> +  },
특정 도메인에 국한되지 않도록 min, max를 인자로 받는 방식으로 수정했습니다 ✅ [Commit](https://github.com/suyoungj/javascript-racingcar/commit/1162102bb2163f6517e3f38a19a52cee94d70102)

2023-02-11 01:08 UTC, suyoungj commented on src/Car.js
> +    return randomNumber >= 4;
전진 기능의 기준이 되는 숫자라는 의미를 명확히 할 수 있도록 별도의 상수로 분리했습니다 ✅ 
[Commit](https://github.com/suyoungj/javascript-racingcar/commit/ddc390e2b400484a3634fc293059b6c8bc458871)

2023-02-11 01:08 UTC, suyoungj commented on src/CarManager.js
> +    });
반영 완료했습니다 ✅ 익숙해지도록 노력하겠습니다! 
[Commit](https://github.com/suyoungj/javascript-racingcar/commit/540c0d763abea87e248242ee3c6af2a480e436b9)

2023-02-11 01:08 UTC, suyoungj commented on src/CarManager.js
> +      singleCar.tryProgress(RandomNumberGenerator.generate());
저도 이 부분에 대해 고민이 많았는데요!
제가 이렇게 작성한 이유는 자동차 전진 기능이 `랜덤한 값을 기반`으로 하기 때문입니다.
자동차 전진 기능은 도메인의 핵심 로직이라고 생각하는데, 랜덤한 값으로 인해 테스트가 어려웠습니다.
따라서 CarManager가 랜덤한 값을 주입하도록 리팩토링하였습니다.
이를 활용하여 Car에서 자동차 전진 기능에 대한 테스트를 수월하게 작성할 수 있었습니다.

```js
test.each([4, 5, 6, 7, 8, 9])(
	`무작위 값이 ${Car.PROGRESS_CONDITION_NUMBER} 이상인 경우 자동차는 전진한다.`,
	conditionNumber => {
		const car = new Car('유스');

		car.tryProgress(conditionNumber);

		expect(car.getProgressCount()).toBe(1);
	},
);

test.each([0, 1, 2, 3])(
	`무작위 값이 ${Car.PROGRESS_CONDITION_NUMBER} 미만인 경우 자동차는 전진하지 않는다.`,
	conditionNumber => {
		const car = new Car('유스');

		car.tryProgress(conditionNumber);

		expect(car.getProgressCount()).toBe(0);
	},
);
```

결론적으로 저는 CarManager의 역할을 명확히 하는것보다, 도메인 핵심 로직의 테스트를 용이하게 하는 것이 더 중요하다고 생각했습니다.
제가 이해한 바가 맞는지, 그렇다면 이에 대한 브콜의 의견도 궁금하네요!
좋은 의견 감사합니다.

2023-02-11 01:08 UTC, suyoungj commented on src/App.js
> +      OutputView.printErrorMessage(error.message);
두 가지 일을 하지 않도록 리팩토링 해보았습니다 🚀 
[Commit](https://github.com/suyoungj/javascript-racingcar/commit/d2067e9dd62b061e7dcb39beebff37449a22028c)

2023-02-11 01:08 UTC, suyoungj commented on src/App.js
> +  }
기능 구현에 급급해 분리에 신경쓰지 못했네요 😂
[readline/promise](https://nodejs.org/dist/latest-v18.x/docs/api/readline.html#promises-api)를 활용하여 개선해 보았습니다 🚀
[Commit](https://github.com/suyoungj/javascript-racingcar/commit/df20f1217717cdfc25b7e7b6a75cd555c7651bc2)
[Commit](https://github.com/suyoungj/javascript-racingcar/commit/52dd0e6428d30782f0bf675ec2036db4bb6c7a96)

2023-02-11 09:10 UTC, Tanney-102 commented on src/utils/RandomNumberGenerator.js
> +  },
굿굿이네요~

2023-02-11 09:19 UTC, Tanney-102 commented on src/CarManager.js
> +      singleCar.tryProgress(RandomNumberGenerator.generate());
오 굉장히 좋은 의견입니다!
다만 이미 carManager(지금의 racingGame)를 테스트 하는 과정에서 ramdom 값을 이미 목킹하고 있다는 점에서 크게 테스트 난이도가 달라질만한 점이 있을지 잘 모르겠어요!

또 테스트를 용이하게 하는 것도 중요하지만 도메인의 핵심이되는 로직이 여러 모듈에 걸쳐 나눠져있는 것도 가만히 두기에는 조금 찝찝하네요~
car 객체를 완전히 분리하고 테스트가 용이하게 하시려는 목적이라면 전진여부를 '판단'하는 로직을 아예 racingGame으로 옮기고 car는 전진할지 말지만 boolean으로 받아 처리하도록 해도 좋을 것 같습니다.

2023-02-11 14:17 UTC, Tanney-102 approved these changes
안녕하세요 유스~
리뷰를 꼼꼼하게 반영해주셨네요!!
질문 주신 부분 관련하여 추가 코멘트 남겼어요!
우선 머지할테니 다음 스텝에서 조금 더 고민해보시면 좋겠습니다 ㅎㅎ
고생많으셨어요!

2023-02-11 14:18 UTC, merged