[1단계 - 자동차 경주 구현] 참새(김규) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #165
Opened 2023-02-09 08:15 UTC by WaiNaat

감사합니다.

2023-02-10 11:20 UTC, pocojang requested changes
안녕하세요!
@wainaat 👋 
반갑습니다

저는 리뷰어 포코라고합니다.

---


## 리뷰

### 테스트

- 테스트 코드가 전반적으로 허술해보이기도 하지만 온보딩이니까 괜찮을 것 같네요
- 테스트에서 다루는 데이터들이.. 중첩 배열이 너무 과하다못해 암호화 수준으로 보입니다.
  - 이런 경우... 데이터를 순회하고 CRUD하며 제어하는 로직이 상당히 지저분해질 것 같습니다.

### 클래스

- 클래스를 언제? 왜? 어떻게? 사용하는지 기준이 있으면 좋겠습니다.
- 클래스를 사용하면 제공되는 다양한 키워드 `private`, `static`등을 적재적소에 활용할 수 있도록 MDN 문서를 읽어보셨으면 좋겠어요

### 임시 변수

- 임시 변수에 의존적인 코드가 많아서 `let` ZERO를 실천해보시는게 어떨까 싶어요
- 굳이 `let`이 없어도 되고.. 임시 변수도 필요 없어 보이는 경우가 많답니다.


### JavaScript 활용하기

- 어떠한 언어를 사용한다면 그 언어를 잘 활용하는게 중요합니다.
- 언어의 명세나 API를 줄줄 외울 필요는 없지만 제공되는 기능을 잘 사용하셨으면 좋겠습니다!


---

이외에는 코멘트 리뷰 확인해주세요~
코드 수정 후 다시 리뷰 요청해주세요!

2023-02-10 11:20 UTC, pocojang commented on src/RacingGame.js
> +  findWinner() {
`Winner`를 찾는 것만 하는게 그 목적이 맞는걸까요?

2023-02-10 11:20 UTC, pocojang commented on src/Config.js
> +  RESULT: '\n실행 결과',
`\n`과 같은 개행하는 행위까지 메세지로 모아놓을 필요가 있을까요?

2023-02-10 11:20 UTC, pocojang commented on src/Config.js
> +  INPUT_CAR_NAMES:
`PascalCase.SNAKE_CASE`와 같은 네이밍을 선호하시는 이유가 있나요?

2023-02-10 11:20 UTC, pocojang commented on src/RacingGame.js
> +        OutputView.printResult(this);
`this`를 통째로 넘기는 것은 불안전하다는 생각이 드는데 어떠실까요?

2023-02-10 11:20 UTC, pocojang commented on src/Car.js
> +  static generateRandomNumber() {
`static`으로 관리하면서 내부 메서드로 관리해야하는 이유가 있을까요?

2023-02-10 11:20 UTC, pocojang commented on __tests__/App.test.js
> +describe('최종 동작 테스트', () => {
여기서는 `indent`가 유난히 많이 들어가는군요..!

2023-02-10 11:20 UTC, pocojang commented on src/Car.js
> +    if (Car.generateRandomNumber() >= Settings.MOVING_NUMBER) {
`Car.generateRandomNumber() >= Settings.MOVING_NUMBER`이 조건을 명시적으로 나타낼 수 없을까요?

2023-02-10 11:20 UTC, pocojang commented on src/Validator.js
> +  bigNumber(attempts) {
`big`이라는 정의는 어떻게 될까요?
얼마나 큰 수인지 엄청난 큰 수인지 사람마다 생각하는 기준이 다를 것 같고 상수로 분리되어있지만 그래도 이 `big`이라는 정의가 프로젝트가 커질때 더 애매해질 것 같다는 생각이 드네요

2023-02-10 17:26 UTC, WaiNaat reviewed
안녕하세요 포코!
바쁘실 텐데 제 코드를 리뷰해주셔서 감사합니다.

테스트 코드는 제가 단위 테스트 개념을 제대로 이해하지 못해서 입출력을 포함한 프로그램 전체에 대한 테스트를 만들다 보니 많이 복잡해진 것 같습니다..

평소에 알고리즘 문제를 풀다 보니 클래스를 전문적으로 사용할 일이 많이 없어서 그쪽에 상대적으로 약한 것 같습니다. 공부해서 돌아올게요!

언어에 관한 것도 무언가를 구현하기 전에 이미 있는 기능인지 확인하는 습관을 들여보겠습니다.

2023-02-10 17:26 UTC, WaiNaat commented on src/Validator.js
> +  bigNumber(attempts) {
```suggestion
  numberInRange(attempts, min, max) {
```
주관적인 이름은 지양하겠습니다!

2023-02-10 17:26 UTC, WaiNaat commented on src/Validator.js
> +    if (attempts%1 !== 0) {
```suggestion
    if (attempts % 1 !== 0) {
```
정수인지 검사하고 싶어서 적은 코드인데 띄어쓰기를 신경쓰지 못했어요...
정수 판별은 `Numbers.isInteger()` 또는 `Numbers.isSafeInteger()`를 사용하는 게 더 좋았을 것 같습니다.

추가적으로 위의 정규 표현식에서 정수 여부를 검사할 수 있기 때문에 불필요한 함수이기도 합니다.

2023-02-10 19:39 UTC, WaiNaat commented on src/RacingGame.js
> +  findWinner() {
이 부분은 제가 질문을 잘 이해하지 못했어요 죄송합니다
혹시 메소드 이름에서 무언가를 return한다는 암시를 더 주는게 좋을까요??

2023-02-11 08:04 UTC, pocojang commented on src/RacingGame.js
> +    this.carList.forEach((car) => {
그럴 수 있죠~~ 차근차근 나아가봅시다!

2023-02-11 08:27 UTC, pocojang approved these changes
@WaiNaat 
리뷰 요청이 엄청나게 빠르시네요! 놀랐습니다.
남은 코멘트 리뷰는 스텝 2에서 다뤄주셔도 좋을 것 같습니다.
본 PR에 추가적으로 남겨도 괜찮고요!

마지막으로 몇 가지 의견 남기면서 이만 머지하도록 할게요~

---

## 리뷰

### 임시 변수 활용 줄이기

지금 습관을 잡아놓으셔야 선언형 프로그래밍 => 함수형 프로그래밍 학습에도 익숙해집니다.
또한 레벨2에서도 혹은 현업에서도 리액트를 활용할 가능성이 클텐데요.
리액트 조차 선언형 프로그래밍을 선호하니까 그 합당한 이유가 이해되지 않더라도 적당한 습관을 형성해보시는게 좋답니다.

### 데이터 복잡도 고려하기

간단한 데이터는 다루기도 편합니다 :)
복잡한 데이터를 그대로 사용하시면 복잡하게 CRUD해야합니다..
그러면 스노우볼처럼 어려운 상황이 계속 연달아 발생되거든요!!

복잡한 데이터도 간단하게 표현하고 관리하도록 노력해보셨으면 좋겠어요


### 개행

함수 내부에 모든 로직을 아무런 개행없이 빽빽하게 채워놔서 너무나 보기 힘듭니다..
이건 프리코스에 채점을 위해 여전히 지키고 계신건가요?
적당한 계획과 규칙적인 개행으로 하고 싶은 말을 표현하시는 것도 좋답니다 :)

---

그럼 스텝2에서 다시 만나요 👋

2023-02-11 08:27 UTC, pocojang commented on src/Config.js
> +  INPUT_CAR_NAMES:
좋아요 :)
그런 관점이면 좋습니다!
`TypeScript`의 `Enum`, 다양한 회사의 컨벤션 가이드도 참고해보시면 좋습니다.
또 하나의 힌트는 이런 상수를 리액트의 상태 등으로 가져가게 된다면 직렬화 <=> 역직렬화 비용이 들 수 있으니 참고해보세용

2023-02-11 08:27 UTC, pocojang commented on src/RacingGame.js
> +  findWinner() {
`findWinner()`라는 네이밍을 봤을 때 같은 클래스내의 메서드 중 `findMaxPosition()`과 비슷한 역할을 할 것 같은데 너무나 많은 일을 하는 것 같아요
@WaiNaat 어떻게 생각하시나요?
일관성이 부족해보일 수 있는거죠

2023-02-11 08:27 UTC, pocojang commented on src/RacingGame.js
> +    return status;
음.. 굳이 임시변수가 필요할까요?

2023-02-11 08:27 UTC, pocojang commented on src/UI/Console.js
> +    const rl = makeNewReadlineInterface();
메서드도 `readLine()`, 내부의 변수도 `rl`이면은 그 맥락이 헷갈리지 않을까요?
`const newRl = makeNewReadlineInterface();` 이런 형식은 어떨런지..

2023-02-11 08:27 UTC, pocojang commented on src/UI/InputView.js
> +const InputView = {
좋은 아이디어에요!
사실 제 의견일뿐 그대로 수행하실 필요는 없어요.
누군가에게는 오히려 성급한 최적화 즉. YAGNI(You aren't gonna need it)일 수 있거든요
그러니 선택도 책임도 @WaiNaat 스스로 잘해보세요!

2023-02-11 08:27 UTC, pocojang commented on src/UI/OutputView.js
> +    Console.print('');
빈 문자열은 어떤 이유로 있을까요?

2023-02-11 08:27 UTC, pocojang commented on src/UI/OutputView.js
> +    Object.entries(gameStatus).forEach(([carName, position]) => {
딱 2개의 값을 취급하는데도 `[carName, position]`와 같은 형태로 주고 받는 이유가 있을까요?

2023-02-11 08:27 UTC, pocojang commented on src/UI/InputView.js
> +      return input;
이렇게 반환하는 이유가 뭘까요?

2023-02-11 08:27 UTC, pocojang commented on src/UI/Console.js
> +    console.log(message);
`InputView`와 같이 활용하지 않는 다른 이유가 있을까요?

2023-02-11 08:27 UTC, pocojang commented on __tests__/App.test.js
> +  ])('정상', async (questions, randoms, result) => {
보기가 넘 힘들어요 😢 
배열을 몇 중 배열로 관리하시는데...
이런 경우 CRUD 비용도 많이 들고 유지 보수도 어렵고 향후 렌더링 비용도 많이 들 수 있습니다ㅠㅠ

2023-02-11 08:27 UTC, merged

2023-02-12 02:31 UTC, WaiNaat commented on src/Config.js
> +  INPUT_CAR_NAMES:
그 부분도 찾아볼게요 감사합니다!

2023-02-12 02:31 UTC, WaiNaat commented on src/RacingGame.js
> +  findWinner() {
아하 잘 살펴보면 `findWinner()`에서 하는 일을 
- `maxPosition`찾기
- 현재 위치가 `maxPosition`인 자동차 목록 만들기

이렇게 나눌 수 있겠네요
`findWinner()` 대신 `findCarsAtPosition(position)` 이런 식으로 위치를 인자로 넘겨받아서 찾는 방식으로 바꾸는 게 좋을 것 같습니다

2023-02-12 02:31 UTC, WaiNaat commented on src/UI/OutputView.js
> +    Console.print('');
```javascript
print(message) {
  console.log(message);
}
```
`Console.print()`가 위와 같은 느낌으로 되어있어서 인자로 아무것도 주어지지 않으면 `undefined`를 출력하는데, 빈 줄을 출력하기 위해서 넣었습니다.

`print()` 내부에서 예외처리를 통해서 주어진 게 아무것도 없으면 빈 문자열을 출력하도록 유도하는 게 더 나을 것 같아요.

2023-02-12 02:31 UTC, WaiNaat commented on src/UI/Console.js
> +    console.log(message);
프리코스 때 `Console`을 따로 제공받아서 사용했던 기억이 있어서 `InputView` 밖으로 분리해 보았습니다.

2023-02-12 03:01 UTC, WaiNaat commented on __tests__/App.test.js
> +  ])('정상', async (questions, randoms, result) => {
다음부터는 태스트 단위도 더 작게 나누고 혹시 전체를 테스트해야 하면 더 좋은 방법이 없는지 찾아보겠습니다ㅠㅠ