[1단계 - 자동차 경주 구현] 엽토(김건엽) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #167
Opened 2023-02-09 08:17 UTC by yeopto

안녕하세요 티케😀 
장거리 여행 고생 많으셨어요!
첫 미션이라 많이 부족하지만 코드리뷰 잘 부탁드립니다!!!
피드백을 적극적으로 수용하겠습니다!! 많이 알려주시면  정~말 정말 감사하겠습니다🫡

2023-02-10 06:44 UTC, devhyun637 commented on .eslintrc.js
> +};
오늘 피드백을 받으셨겠지만~ EOL

2023-02-10 06:45 UTC, devhyun637 commented on .eslintrc.js
> +  extends: ["eslint:recommended", "airbnb-base", "prettier"],
왜 "airbnb-base"를 선택하셨을까요?

2023-02-10 06:46 UTC, devhyun637 commented on .prettierrc.js
> +  printWidth: 80, // 한 줄 최대 문자 수
크 주석 👍👍👍

요새는 브라우저가 충분히 넓어서 80보다 더 넓은 걸 선호하는 경우도 있답니다. 80은 오히려 좁다고 느낄수도..?

2023-02-10 07:52 UTC, devhyun637 requested changes
안녕하세요 엽토~ 리뷰어 티케입니다. 🧚‍♀️ 
_사실 푸만능, 엽토, 첵스에게 쓰는 이 전반적인 리뷰 내용은  공통부분이 많습니다. 이해해주셔서 감사합니다_ 

저도 리뷰어가 처음이라, 많이 긴장이 되고 걱정 반 설렘 반이에요! 저야말로 잘부탁드립니다~ 리뷰를 보면서 무조건 적용하거나 받아들이기보다는 늘 의심하면서 비판적으로 받아주세요! 저도 잘 모르는 부분이 있을 수 있고, 엽토가 어떠한 의도에서 개발했는지가 훨씬 중요하니깐요. 많이 들어보셨겠지만, 개발에는 정답이 없습니다 :) 또 개인적으로 이해가 안 가면 질문도 남겨주시고 공개적인 곳이 부담스러우면 DM도 좋아요! 같이 고민해 나가보아요 🧡

첫 미션이 시간이 짧았을 텐데, 여러 가지 병행하면서 이렇게나 빠른 리뷰를 올려주시다니 영광입니다!
리뷰를 하면서 pretter, MVC, 여러가지 자료구조를 사용한 점이 인상깊었습니다 👍👍 예외상황에 대한 구현목록을 써주신것도 좋았고, 그대로 테스트한것까지 완-벽⭐️ 커밋 메세지도 깔끔하네요! 매우 좋아요 :) 상수화도 꼼꼼히 하셨더라구요~ 관련 리뷰는 구체적인 코멘트를 참고해주세요 :)

### [전반적인 리뷰]
1. PR 메세지, README
어떤 작업을 했는지 이 프로젝트가 무엇인지에 대한 설명이 README 파일에 담겨있으면 좋았을 것 같아요. 저희 오픈소스나 라이브러리 찾아볼 때 리드미를 통해서 어떤 프로젝트도 어떻게 사용할 수 있는지 파악하는 거랑 같은 맥락이에요. 리뷰미를 꾸며봅시다 💦
또, 현업에서 일하다 보면 어떤 작업을 했는지 PR만 보고 파악하는 건 너무 어려워져서 저희 팀은 PR 템플릿을 통해서 자세하게 어떤 작업을 했는지 명시하는 작업을 하고 있어요. 우테코 미션도 동일하게 리뷰어들이 모든 미션에 대해 인지를 하려고 노력하지만 처음보는 사람들에게 리뷰를 맡긴다는 생각으로 엽토가 어떤 작업을 했고, 어떤 부분을 신경써서 했고, 구조는 어떻게 만들었으며, 어떤 점이 궁금했다, 어떤 점이 어려웠다, 실행했을 때의 이미지 등등 작업 내역과 소감을 담아주시면 좋을 것 같아요. 엽토가 어떤 것에 더 신경썻는지 알면 저도 그것에 맞춰서 리뷰를 줄 수 있을 것 같고, 첫 미션이 어땠는지 소감도 궁금하네요 :)
또 README에 내용이 없는경우 저는 package.json을 보는 편인데요, package.json은 이 프로젝트에 어떤 라이브러리 의존성이 있고, 어떻게 시행되고 등등의 많은 정보를 담고 있기 때문이죠. 그 부분에 대한 수정이 아에 존재하지 않는데 한번 공부를 해보시면 어떨까요?

2. 노드 패키지의 lock 파일이 2개 있던데.. 어떤걸 사용하시는 걸까요 :) 불필요한 파일은 삭제해주세요

3. 클래스
모든 것을 클래스로 만드셨는데 특별한 이유가 있을까요? 또 static만 있는 클래스란 어떤 의미를 가지는 걸까요?

2023-02-10 07:52 UTC, devhyun637 commented on docs/REQUIREMENTS.md
> +## 예외 처리
예외상황이 좋은 것 같아요. 다만, 예외상황이 발생했을 때의 처리는 기능구현목록에 없네용

2023-02-10 07:52 UTC, devhyun637 commented on src/index.js
> +class Index {
엽토가 생각하는 클래스는 무엇인가요? Index를 클래스로 만든 이유와 이 상황에서 얻을 수 있는 이점은 무엇일까요?

2023-02-10 07:52 UTC, devhyun637 commented on src/Controller/RaceController.js
> +      this.getTryCount(cars);
이름을 받는 곳에서 시도 횟수도 받는건 조금 어색해보여요

2023-02-10 07:52 UTC, devhyun637 commented on src/Models/Car.js
> +  move(number) {
early return을 활용해보는건 어떨까요?

2023-02-10 07:52 UTC, devhyun637 commented on src/Utils/Console.js
> +class Console {
전부 static인 클래스라.. 왜 클래스로 만들었을까요?

2023-02-10 07:52 UTC, devhyun637 commented on src/Utils/Validator.js
> +  static validateCarName(name) {
validateNamesOfCars, validateCarName? 둘이 비슷해보이는데 어떤 차이가 있을까요? 
각각 어떤 메서드인지 추가적인 설명이 있으면 좋을 것 같아요.

2023-02-10 07:52 UTC, devhyun637 commented on src/Utils/Validator.js
> +class Validator {
너무 도메인 종속적인 유효검사 내용이라서, 유틸에 있는게 맞는지 다시 고민을 해보면 좋을 것 같아요.

2023-02-10 07:52 UTC, devhyun637 commented on src/Utils/Validator.js
> +    if (new Set(names).size !== names.length) {
Set을 활용한 것 좋네요 👍

2023-02-10 07:52 UTC, devhyun637 commented on src/Utils/Validator.js
> +    if (!/^[A-Z|a-z|ㄱ-ㅎ|ㅏ-ㅣ|가-힣]*$/.test(name)) {
왜 '한글'만 가능한 것일까요..?
저는 테스트1, 테스트2 이런 네이밍도 쓰고 싶은데..

2023-02-10 07:52 UTC, devhyun637 commented on src/Utils/Validator.js
> +    if ([CONSTANTS.empty, CONSTANTS.undefinedType].includes(name)) {
가독성을 높여볼까요? If문은 어떤 것들을 false라고 인식하는지, 너무 과도한 상수화를 하지는 않았는지를 고민해보면서 리팩토링 해보아요 :)

2023-02-10 07:52 UTC, devhyun637 commented on src/Controller/RaceController.js
> +        Validator.validateCarName(name);
두개의 유효성 차이가 어떤 것일까요..? 

또 변수를 선언하는 위치에 대해서 컨벤션이 있으면 좋을 것 같아요. 보통은 변수는 함수의 가장 맨 위에 선언해 두는 편이긴 하죠 :) 엽토는 어떤 컨벤션을 가지고 있나요?

2023-02-10 07:52 UTC, devhyun637 commented on src/View/InputView.js
> +      this.readCarName.bind(this),
벌써 bind를 활용하시다니 👍

2023-02-10 07:52 UTC, devhyun637 commented on src/Controller/RaceController.js
> +    for (let i = 0; i < count; i += 1) {
for문 말고 내장함수를 사용해보는건 어떨까요?

2023-02-10 07:52 UTC, devhyun637 commented on src/Models/Race.js
> +    const result = new Map();
오 Map을 활용해주셨군요! 👍👍
막간을 이용한(필수아님) 질문! Map, Set은 어떤 차이가 있을까요?

2023-02-10 07:52 UTC, devhyun637 commented on src/Constant/RaceMessage.js
> +  winnerResult: '가 최종 우승했습니다.',
```suggestion
  winnerResult: '(이)가 최종 우승했습니다.',
```

2023-02-10 07:52 UTC, devhyun637 commented on src/View/OutputView.js
> +    result.forEach((value, key) => {
map의 forEach를 사용하셨군요! 좋습니다

2023-02-10 07:52 UTC, devhyun637 commented on src/Utils/DataParseUtils.js
> +class DataParseUtils {
오호.. 클래스로 만든 이유가 궁금하네요~ 그리고 이 공통으로 쓰인다고 해서 '유틸'이라고 불릴 수 있는 것인가도 고민해보면 좋을 것 같아요!

2023-02-10 07:52 UTC, devhyun637 commented on src/Utils/Console.js
> +  static readLine(query, callback) {
query보다 더 구체적인 네이밍은 없을까요?

2023-02-10 07:52 UTC, devhyun637 commented on src/Utils/Console.js
> +    console.log(message);
에러 상황에서 정의해둔 에러메세지(영어)가 콘솔에 찍히지 않고 있네용 :)

2023-02-10 07:52 UTC, devhyun637 commented on src/Controller/RaceController.js
> +  handleRace(count) {
너무 포괄적인 네이밍같아요. Race를 핸들한다는 건 어떤 의미일까요?

2023-02-10 07:52 UTC, devhyun637 commented on src/Controller/RaceController.js
> +  getCarName() {
getter여야 하는 이유는 무엇인가요?

2023-02-10 07:52 UTC, devhyun637 commented on __tests__/Validator.test.js
> +    '자동차 이름이 한글이나 영문이 아닌 경우 예외처리한다.',
한글로만 한 이유가 궁금해요. 한글로만 하려면 사용자에게 미리 알려야하지 않을까요?
예를들어 
한글로만 이루어진 이름을 입력해주세요. (ex. 갑,을)

2023-02-10 07:52 UTC, devhyun637 commented on __tests__/Validator.test.js
> +    '시도 횟수가 1이상이 아니면 예외처리한다',
복붙의 남아있는 잔재같은데 설명을 수정해볼까요?

2023-02-10 08:06 UTC, yeopto commented on .eslintrc.js
> +  extends: ["eslint:recommended", "airbnb-base", "prettier"],
프로그래밍 요구사항에 "코드 스타일 가이드에 따라 컨벤션을 준수하며 개발한다"가 있었습니다. 코드 스타일 가이드에 airbnb의 컨벤션을 따른다고 되어있어서 선택했습니다. 전반적인 리뷰에서 말씀해주셨던 것처럼 이 프로젝트에 대한 설명이 있었다면 이런 궁금증을 해결해드릴 수 있었을 것 같다는 생각이 드네요!

2023-02-10 08:07 UTC, yeopto commented on .eslintrc.js
> +};
아 깜빡했습니다.. ㅎㅎ

2023-02-10 08:47 UTC, yeopto commented on __tests__/Car.test.js
> +test('Car Class 테스트', () => {
테스트 설명이 너무 부족했던 것 같습니다!!

2023-02-10 08:55 UTC, yeopto commented on __tests__/Validator.test.js
> +    '자동차 이름이 한글이나 영문이 아닌 경우 예외처리한다.',
예시에 'pobi,crong,honux'라고 되어있었는데요, 1차원적으로 사람이름이 들어와야한다고 생각을 했어요. 지금 생각해보니 결국 자동차 이름일텐데 제가 만들어버린 필요없는 예외란 생각이 드네요. 예를들어 bmw 520d 처럼 테스트 입력값에서 '한123'은 굳이 에러를 던질 필요가 없을 것 같습니다. 제가 요구사항을 잘못 파악했네요ㅠ

2023-02-10 08:59 UTC, yeopto commented on __tests__/Validator.test.js
> +    '시도 횟수가 1이상이 아니면 예외처리한다',
😱

2023-02-10 09:21 UTC, devhyun637 commented
엽토! 리뷰중에서 우선적으로 아래 코멘트부터 봐주시고, 나머지는 Step2에서 진행하겠습니다~

https://github.com/woowacourse/javascript-racingcar/pull/167#discussion_r1102335845
https://github.com/woowacourse/javascript-racingcar/pull/167#discussion_r1102343574
https://github.com/woowacourse/javascript-racingcar/pull/167#discussion_r1102351298
https://github.com/woowacourse/javascript-racingcar/pull/167#discussion_r1102361856
https://github.com/woowacourse/javascript-racingcar/pull/167#discussion_r1102383393
https://github.com/woowacourse/javascript-racingcar/pull/167#discussion_r1102384363
https://github.com/woowacourse/javascript-racingcar/pull/167#discussion_r1102387301
https://github.com/woowacourse/javascript-racingcar/pull/167#discussion_r1102388052

2023-02-10 09:26 UTC, yeopto commented on src/Constant/Constants.js
> +const CONSTANTS = {
저도 평상시에 후자가 가독성 측면에서 훨씬 더 직관적이라고 생각했습니다. 하지만 문자열로 내버려둔다면 하드코딩이지 않나? 라는 생각을 했는데요. 하드코딩에 대한 범위를 어디까지 생각해야할지 궁금하네요. 정답은 없는걸까요?

2023-02-10 09:33 UTC, yeopto commented on docs/REQUIREMENTS.md
> +## 예외 처리
이 코멘트에 대해 이해가 잘 가지 않아서 질문드립니다! 예외상황이 발생했을 때의 처리하는 것을 기능구현목록에 추가하라는 말씀이신가요?!

2023-02-10 09:49 UTC, yeopto commented on src/Utils/Validator.js
> +    if (!/^[A-Z|a-z|ㄱ-ㅎ|ㅏ-ㅣ|가-힣]*$/.test(name)) {
아까 테스트 코드에 남기신 코멘트군요! 수정하겠습니다!

2023-02-10 09:57 UTC, yeopto commented on src/Utils/Console.js
> +    console.log(message);
Console.print() 메서드는 message를 인자로 받아 출력만 해주는 메서드입니다! 혹시 에러메세지가 콘솔에 찍히지 않는다는 것이 무슨 말씀인지 다시 한번 설명해주실 수 있을까요?

2023-02-10 10:12 UTC, yeopto commented on src/Controller/RaceController.js
> +  handleRace(count) {
레이스하고 결과를 보여준다라는 것을 포괄적으로 변수명을 지어줬네요. 한 메서드에 두가지의 행위가 있는 것 같아서 분리를 해주고 싶었는데, 한번 진행 시 한번 출력해주어야하는데 분리하면 어떻게 해야할지 생각나지 않았습니다.

2023-02-10 10:15 UTC, yeopto commented
티케! 우선적으로 봐달라고 하신 코멘트들 중 제가 이해를 하지 못한 것을 제외하고 코드에 반영했습니다!

2023-02-10 11:02 UTC, devhyun637 commented on .eslintrc.js
> +};
EOL을 수동으로 처리하는 것 외에 자동화할 수 있는 방법은 뭐가 있을지 고민해보면 좋을 것 같아요~

2023-02-10 11:16 UTC, yeopto commented on .eslintrc.js
> +};
prettier 설정으로 endOfLine을 'auto'로 해주었습니다. 이것도 수동으로 보아야할까요?

2023-02-10 11:20 UTC, devhyun637 requested changes
다음부터는 적용한 부분에 대해서 정리하거나, 아니면 이모지로 엽토만의 표시를 리뷰 코멘트에 남겨주면 리뷰어입장에서 보기 좋을 것 같아요 :) 

꼭 이렇게 하라는 건 아니지만, 이런 아주 좋은 예시도 있다~ 정도 봐주시면 좋을 것 같아요. (이모지 혹은 댓글만으로도 충분합니다)
<img width="30%" alt="스크린샷 2023-02-10 오후 8 09 39" src="https://user-images.githubusercontent.com/59258239/218079455-a36fb5b2-deab-4aef-8ada-c11bb27ef800.png"><img width="30%" alt="스크린샷 2023-02-10 오후 8 10 08" src="https://user-images.githubusercontent.com/59258239/218079476-034585d3-346d-4a39-8595-8f18038e66e0.png"><img width="30%" alt="스크린샷 2023-02-10 오후 8 10 24" src="https://user-images.githubusercontent.com/59258239/218079487-babdc3f8-d5e6-4ef2-9ff5-1729d45b1dc5.png">


> _노드 패키지의 lock 파일이 2개 있던데.. 어떤걸 사용하시는 걸까요 :) 불필요한 파일은 삭제해주세요_

위 리뷰만 완료되면 Step1은 머지하겠습니다.

적용해주신 부분들 중, 다시 코멘트를 남겼는데 엽토의 리뷰적용 속도가 빨라서 한번 더 request-changes를 보내는데, Step2에 가서 적용해주셔도 됩니다. 노드패키지 관련 피드백이 마무리 되면 Step2에서 코드리뷰 적용하며 리팩토링을 할지 아니면 Step1에서 한번 더 저랑 핑퐁을 할지 결정해주시면 됩니다~

2023-02-10 11:20 UTC, devhyun637 commented on __tests__/Car.test.js
> +test('Car Class move 메서드 테스트', () => {
test는 동작을 설명해주는 게 좋지 않을까요?

2023-02-10 11:20 UTC, devhyun637 commented on src/Constant/Constants.js
> +const CONSTANTS = {
쉼표, 콜론, 빈문자열같은 경우에는 누가 변경한다고 해서 변하지 않는 값들이겠죠? 이런건 굳이 상수화할필욘 없다고 전 생각합니다

2023-02-10 11:20 UTC, devhyun637 commented on docs/REQUIREMENTS.md
> +- [x] 이름에 숫자만 있거나 이름이 문자라면 예외처리한다.
이름이 문자라면 왜 예외처리를 하시나요..!

2023-02-10 11:20 UTC, devhyun637 commented on src/Controller/RaceController.js
> +  handleRaceAndShowResult(count) {
네이밍에서 벌써 느껴지는 두가지 역할을 하는 함수 🤔

2023-02-10 12:41 UTC, yeopto commented
코멘트 하나씩 보면서 해결한 것은 리코멘트남기고 잘 이해하지 못했다하는 것은 이해하지 못해서 질문 드린다고 리코멘트를 남기면 되는줄 알았습니다. 처음 코드리뷰를 해봐서 많이 서툴렀던 것 같습니다. 무엇을 반영했는지 정확히 말씀을 드렸어야했는데.. 정말 죄송합니다!!! lock 파일이 두개인 이유는 오늘 공통 피드백 시간에 공원이 미션 처음 만들때 깜빡하고 yarn lock 파일을 올리신 것 같더라구요 리뷰어 분들께 말씀드리라고 했었습니다! 그래서 yarn.lock을 지우고 반영했습니다!

### 1단계 피드백 반영 목록

- [x] pakage-lock.json 과 yarn.lock 두개가 존재하여 yarn.lock을 삭제하다. [관련커밋](https://github.com/woowacourse/javascript-racingcar/pull/167/commits/2f08f215d18805556ffd3f4b0e92d346eab1f92a)
- [x] EOL 수동으로 처리하기 위해 prettier 설정하다. [관련커밋](https://github.com/woowacourse/javascript-racingcar/pull/167/commits/575f4cb106eee78dc5641f3e109f5e32e7295987) [관련커밋](https://github.com/woowacourse/javascript-racingcar/pull/167/commits/cf10bd2a88d00f795b55927f94444209c41a75aa)
- [x] 쉼표, 콜론등 변하지 않는 값을 상수화하지 않다. [관련커밋](https://github.com/woowacourse/javascript-racingcar/pull/167/commits/c07fbde4e4aa4d1407a07f09c429f7ed9619b7cc)
- [x] 영문, 한글만이 아닌 '테스트123'처럼 숫자도 함께 사용할 수 있도록 자동차 이름 예외처리를 수정하다. (테스트 input 값도 함께 수정) [관련커밋](https://github.com/woowacourse/javascript-racingcar/pull/167/commits/9924ec67d222aa2298209e564f59db59639b1f94)
- [x] docs에 잘못된 예외처리 내용을 수정하다. (문자 -> 특수문자) [관련커밋](https://github.com/woowacourse/javascript-racingcar/pull/167/commits/03b85ce15f6105e465ed644853563d7034c00a92)

Step 2에서 남은 피드백들을 꼼꼼히 확인하여 리팩토링 하도록 하겠습니다. 리뷰요청 두번이나 불편하게 해드린 점 정말 죄송합니다.. 그리고 꼼꼼한 피드백 주셔서 정말 감사합니다!

2023-02-11 04:55 UTC, devhyun637 commented
>  처음 코드리뷰를 해봐서 많이 서툴렀던 것 같습니다. 무엇을 반영했는지 정확히 말씀을 드렸어야했는데.. 정말 죄송합니다!!! 

전~~혀 아니에요! 죄송할 일 아니고, 이렇게 정리를 해두면 당장 낼모레 엽토가 작업을 할때라도 도움이 되어서 알려드린 팁이에요!
그리고 다른 리뷰어들을 배정받았을때도 빠르게 리뷰를 주고받을 수 있는 저만의(?) 팁이라고 공유하고 싶었습니다!

> 리뷰요청 두번이나 불편하게 해드린 점 정말 죄송합니다

자동차 미션은 일주일이라서 빠르게 2단계로 넘어가야하는 부분이 있지만, 피드백 반영이 빨라서 리뷰요청을 한번 더 드린거랍니다~ 죄송할 일이 정말 아니고! 리뷰는 원래 두번정도 주고받아요 :)  피드백 반영 빠르게 잘 해주셔서 감사합니다~ 수고하셨어요!

2023-02-11 04:56 UTC, merged

2023-02-11 07:18 UTC, yeopto commented
넵 알겠습니다!! 티케도 고생많으셨어요! 2단계에서 다시 뵈어요!