[1단계 - 자동차 경주 구현] 제로(강인영) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #170
Opened 2023-02-09 08:21 UTC by inyeong-kang

2023-02-10 08:40 UTC, JeongBin0227 requested changes
안녕하세요 제로~ 이번 제로의 첫 리뷰를 맡게 된 케빈입니다! 만나서 반갑습니다 🙂

첫 미션을 수행하면서 많이 혼란스럽고, 어려움이 있었을수도 있는데, 너무 잘 하신 PR 올려주셔서 감사하고 너무 고생많으셨습니다.

먼저 질문에 대한 답변부터 드리면,

> Class와 Object의 차이가 궁금합니다. (각각 사용되어야 하는 특별한 경우가 있는는 것인지? Model 같은 경우에는 Class를 사용하는 것이 바람직해 보이는데, Object를 쓰는 것이 좋은 경우가 따로 있는지 궁금합니다.)

→ 클래스형 함수랑 함수형 프로그래밍에 대해서 질문주신거 같아요! 사실 이러한 패러다임은 무조건 좋고 나쁘다가 존재하지 않습니다. 제로가 Model 같은 경우 Class를 사용하는것이 더 바람직하다고 말씀해주셨는데, 분명 그렇게 생각하신 이유가 있을거라 생각합니다. 이러한 패러다임에 대해 장단점을 먼저 공부해보고 다시한번더 언제 어떤걸 써야할지 고민해보는게 좋을거 같습니다. 그리고 다음리뷰때 제로가 학습이 된 상태에서 이번 질문을 다시한번더 같이 얘기해보는게 좋을거 같아요. 결국 중요한건 이러한 패러다임을 잘 이해하고 상황에 맞게 적절하게 사용하여 모듈화 수준이 높고 재사용성이 좋은 프로그래밍을 하는것이 중요합니다.

> jest.fn()을 할당하는 변수가 일반 함수(`calculateRandomNumber`)였는데, `TypeError: Assignment to constant variable`라는 에러가 발생했습니다. 이를 어떻게 해결할지 고민하다가.. **Mission-Utils의 Random.js**([https://github.com/woowacourse-projects/javascript-mission-utils/blob/main/src/random.js](https://github.com/woowacourse-projects/javascript-mission-utils/blob/main/src/random.js)) 처럼 `class calculateRandomNumber` 로 변경하였더니 해결되었습니다!혹시 jest.fn()을 할당하는 변수는 class 함수이어야 하는건가요..? (설명을 다소 애매모호하게 한 점 양해 부탁드립니다..😂)

→ 상황을 좀더 정확히 봐야 알겠지만, 제로가 말해준 `TypeError: Assignment to constant variable` 를 보면, 값이 변하는 상황이나 범위(scope) 에 관련한 문제인데, const 로 선언후 사용해서 문제가 생긴게 아닐까 생각됩니다. 이부분은 추후 직접 디버깅후 다시 코멘트로 남겨드리겠습니다. util에 Random만 class 를 활용해주셔서 의아했는데, 이러한 이유가 있었군요

우선 첫 pr 이니까 가볍게 제가 리뷰 남겨드린 부분을 보면서 좋은 코드에 대해서 공부해보면 좋을거 같아요. 그리고 개인적으로 모든분들이 다 비슷비슷한 구조로 개발을 하시고 있다는 생각이 들더라고요. 이런 부분을 따라해서 내것으로 만드는 것도 중요하지만, 다음 미션에서는 제로가 직접 구조를 설계해보고 더 좋은 방식은 없는지 고민해보는 시간도 있으면 더 좋을거 같아요!

질문 주신것처럼 계속해서 사용하고 있는것에 대해 의문을 가지고, `왜` 에 집중해서 공부하시는 모습이 인상적입니다.  다음 프로젝트에서는 제로가 코드를 짜다가 어려움이 있거나, 제대로 하고 있는건지 의문점이 생길때, 어떤 생각으로 구조화하고 코드를 짰는지 코멘트로 남겨놓으면더 좋을거 같아요. 코드에는 정답이 없기때문에 거기에 대해서도 코드 리뷰를 통해 같이 얘기 해볼 수 있을 거 같아요 👍 다음 프로젝트에서 말씀해주신것처럼 서로 더 성장된 모습으로 만나요~ 고생하셨습니다!

2023-02-10 08:40 UTC, JeongBin0227 commented on __tests__/Move.test.js
> +    expect(isMove(number)).toBe(expected);
toBe를 쓴곳도 있고, toEqual 를 쓰신곳도 있는데 정확한 차이를 알고 의도해서 쓰신걸까요?

2023-02-10 08:44 UTC, inyeong-kang commented on .prettierrc.js
> +  quoteProps: "as-needed",
이 부분은 저의 페어 @Gilpop8663 가 자세한 주석을 첨부해주신건데 저도 그 상세함에 감탄했습니다👏

2023-02-12 16:44 UTC, inyeong-kang commented
> 안녕하세요 제로~ 이번 제로의 첫 리뷰를 맡게 된 케빈입니다! 만나서 반갑습니다 🙂
> 
> 첫 미션을 수행하면서 많이 혼란스럽고, 어려움이 있었을수도 있는데, 너무 잘 하신 PR 올려주셔서 감사하고 너무 고생많으셨습니다.
> 
> 먼저 질문에 대한 답변부터 드리면,
> 
> > Class와 Object의 차이가 궁금합니다. (각각 사용되어야 하는 특별한 경우가 있는는 것인지? Model 같은 경우에는 Class를 사용하는 것이 바람직해 보이는데, Object를 쓰는 것이 좋은 경우가 따로 있는지 궁금합니다.)
> 
> → 클래스형 함수랑 함수형 프로그래밍에 대해서 질문주신거 같아요! 사실 이러한 패러다임은 무조건 좋고 나쁘다가 존재하지 않습니다. 제로가 Model 같은 경우 Class를 사용하는것이 더 바람직하다고 말씀해주셨는데, 분명 그렇게 생각하신 이유가 있을거라 생각합니다. 이러한 패러다임에 대해 장단점을 먼저 공부해보고 다시한번더 언제 어떤걸 써야할지 고민해보는게 좋을거 같습니다. 그리고 다음리뷰때 제로가 학습이 된 상태에서 이번 질문을 다시한번더 같이 얘기해보는게 좋을거 같아요. 결국 중요한건 이러한 패러다임을 잘 이해하고 상황에 맞게 적절하게 사용하여 모듈화 수준이 높고 재사용성이 좋은 프로그래밍을 하는것이 중요합니다.
> 
> > jest.fn()을 할당하는 변수가 일반 함수(`calculateRandomNumber`)였는데, `TypeError: Assignment to constant variable`라는 에러가 발생했습니다. 이를 어떻게 해결할지 고민하다가.. **Mission-Utils의 Random.js**(https://github.com/woowacourse-projects/javascript-mission-utils/blob/main/src/random.js) 처럼 `class calculateRandomNumber` 로 변경하였더니 해결되었습니다!혹시 jest.fn()을 할당하는 변수는 class 함수이어야 하는건가요..? (설명을 다소 애매모호하게 한 점 양해 부탁드립니다..😂)
> 
> → 상황을 좀더 정확히 봐야 알겠지만, 제로가 말해준 `TypeError: Assignment to constant variable` 를 보면, 값이 변하는 상황이나 범위(scope) 에 관련한 문제인데, const 로 선언후 사용해서 문제가 생긴게 아닐까 생각됩니다. 이부분은 추후 직접 디버깅후 다시 코멘트로 남겨드리겠습니다. util에 Random만 class 를 활용해주셔서 의아했는데, 이러한 이유가 있었군요
> 
> 우선 첫 pr 이니까 가볍게 제가 리뷰 남겨드린 부분을 보면서 좋은 코드에 대해서 공부해보면 좋을거 같아요. 그리고 개인적으로 모든분들이 다 비슷비슷한 구조로 개발을 하시고 있다는 생각이 들더라고요. 이런 부분을 따라해서 내것으로 만드는 것도 중요하지만, 다음 미션에서는 제로가 직접 구조를 설계해보고 더 좋은 방식은 없는지 고민해보는 시간도 있으면 더 좋을거 같아요!
> 
> 질문 주신것처럼 계속해서 사용하고 있는것에 대해 의문을 가지고, `왜` 에 집중해서 공부하시는 모습이 인상적입니다. 다음 프로젝트에서는 제로가 코드를 짜다가 어려움이 있거나, 제대로 하고 있는건지 의문점이 생길때, 어떤 생각으로 구조화하고 코드를 짰는지 코멘트로 남겨놓으면더 좋을거 같아요. 코드에는 정답이 없기때문에 거기에 대해서도 코드 리뷰를 통해 같이 얘기 해볼 수 있을 거 같아요 👍 다음 프로젝트에서 말씀해주신것처럼 서로 더 성장된 모습으로 만나요~ 고생하셨습니다!

안녕하세요 케빈! 말씀해주신 것처럼, 제가 `어떻게`에 대한 지식은 쌓고 있는 중이지만, `왜`에 대한 생각은 매순간 해보려고 노력 중입니다😀 정말로 코드에는 정답이 없지만, 코드를 작성한 자신은 '그렇게 작성한 이유'에 대해서 가장 잘 알고 있어야 한다고 느꼈습니다..!
솔직한 고백으로, 많은 사람들이 비슷한 구조로 작성했기 때문에, 또는 프리코스 때 이러한 구조로 연습해온 것이 익숙하기 때문에, 같은 말을 이유로 스스로 코드 구조를 생각해내는 것을 주저했던 것 같아요🤔 다음 프로젝트에서는 제 생각이 좀 더 드러난 코드를 작성해보고 싶네요! 
피드백 감사합니다😊👍

2023-02-12 16:53 UTC, inyeong-kang commented on .prettierignore
> +node_modules/
마지막 줄에서 개행하는 것(EOL)이 왜 prettier 옵션에 포함되어 있는지 궁금했었는데, 첨부해주신 링크에서 이 옵션이 제대로 적용되지 않아 발생하는 이슈에 대해 이해할 수 있었습니다! 감사합니다

2023-02-12 17:41 UTC, inyeong-kang commented on src/Validation.js
> +class Validation {
페어와 1단계에 대한 회고를 해보고, 스스로 서치를 해보면서 class와 function의 차이에 대해 정리해보았습니다. 
1. 메모리 사용에 있어서는 class 사용이 효율적이다.
2. 개발하는 내용에 따라 factory function이 보다 안전할 수도 있다. 
(class는 상속 받은 모든 method를 사용하는 반면, factory는 구성을 하기 때문에 method를 선별적으로 사용할 수 있다.)
3. class는 this 문법을 사용할 수 있다. (이로 인해 컨텍스트 손실 문제가 발생할 수 있다.)

이러한 특징들을 바탕으로, Validation은 메모리가 불필요하고, 유효성 검사를 할 때마다 static 메서드로 클래스 본체를 호출하는 것 역시 불필요함을 느꼈습니다. 말씀해주신 이유도 제가 이해한 바와 비슷한 맥락이라고 생각됩니다!
class로 function을 통일하고자 Validation 역시 class를 선택했었는데, 배운 내용 을 토대로 리팩토링해보겠습니다!

2023-02-12 17:59 UTC, inyeong-kang commented on src/Validation.js
> +    carNames.forEach((name) => {
수정 완료했습니다✅

2023-02-12 17:59 UTC, inyeong-kang commented on src/Validation.js
> +  static isNotNumber(attempt) {
수정 완료했습니다✅

2023-02-12 18:12 UTC, inyeong-kang commented on __tests__/Application.test.js
> +  test('기능 테스트', () => {
수정 완료했습니다✅

2023-02-12 18:12 UTC, inyeong-kang commented on __tests__/Application.test.js
> +  test('기능 테스트2', () => {
수정 완료했습니다✅

2023-02-12 18:12 UTC, inyeong-kang commented on __tests__/Car.test.js
> +  test('getName 함수 테스트', () => {
수정 완료했습니다✅

2023-02-12 18:12 UTC, inyeong-kang commented on __tests__/Move.test.js
> +  test('calculateRandomNumber 함수 테스트', () => {
수정 완료했습니다✅

2023-02-12 18:19 UTC, inyeong-kang commented on src/Validation.js
> +    if (Validation.isNotNumber(attempt) || Validation.isNotInteger(attempt)) {
훨씬 깔끔하네요💡😃 
수정 완료했습니다✅

2023-02-12 18:31 UTC, inyeong-kang commented on src/constants/index.js
> +const GAME_NUMBER = Object.freeze({
const 와 Object.freeze를 함께 사용해서 Immutable한 객체를 선언하고자 했습니다! (객체를 불변하게 만들어서 타입핑 실수를 줄이고자 했습니다..!)

2023-02-12 18:33 UTC, inyeong-kang commented on src/constants/index.js
> +  },
실행 예시(`pobi, honux가 최종 우승했습니다.`)와 같이 복수의 우승자도 출력되도록 하였습니다!

2023-02-12 18:39 UTC, inyeong-kang commented on src/Validation.js
> +    const regex = GAME_STRING.alphabetExpression;
수정 완료했습니다✅

2023-02-12 18:50 UTC, inyeong-kang commented on src/Validation.js
> +    });
수정 완료했습니다✅

2023-02-12 18:50 UTC, inyeong-kang commented on src/controller/controller.js
> +      carNames.forEach((name) => {
수정 완료했습니다✅

2023-02-12 18:51 UTC, inyeong-kang commented on src/constants/index.js
> +  alphabetExpression: /[^a-zA-Z]/,
수정 완료했습니다✅

2023-02-12 18:59 UTC, inyeong-kang commented on src/utils/index.js
> +class Random {
테스트 코드를 위해서 class의 메서드로 변경하였습니다..! 그런데 리팩터링 요구 사항 중에 `테스트 코드에서 jest.fn()을 사용하지 않는다` 가 있어서 삭제하였습니다🤔😅
 
> jest.fn()을 할당하는 변수가 일반 함수(calculateRandomNumber)였는데, TypeError: Assignment to constant variable
> 라는 에러가 발생했습니다. 이를 어떻게 해결할지 고민하다가.. Mission-Utils의 Random.js(https://github.com/woowacourse-projects/javascript-mission-utils/blob/main/src/random.js) 처럼 class calculateRandomNumber 로 변경하였더니 해결되었습니다!

2023-02-12 20:33 UTC, inyeong-kang commented on src/controller/controller.js
> +      this.showGameProgress();
수정 완료했습니다✅

2023-02-12 20:42 UTC, inyeong-kang commented on __tests__/Move.test.js
> +    expect(isMove(number)).toBe(expected);
toBe는 2개의 value값이 같은지 확인할 때, toEqual은 배열이나 객체 안의 value들이 같은지 확인할 때 사용된다고 생각했습니다! 
Jest 공식문서를 다시 한번 읽어보니 
* `toBe`는 두 객체 인스턴스가 같은 메모리에 있고 같은 내용인지 확인하는데 사용
* `toEqual`은 두 객체 인스턴스가 같은 내용이 같은지 확인하는데 사용
이라고 설명되어 있네요..! 제가 제대로 이해한 것이 맞을까요??

2023-02-13 08:08 UTC, JeongBin0227 approved these changes
안녕하세요 제로~ 

2단계 작업을 위해 1단계는 머지 하도록 하겠습니다. 
이번 단계에서 질문 주신 부분이나 피드백은 2단계 코드리뷰에서 다시 남겨드리겠습니다 고생많으셨습니다! :)

2023-02-13 08:08 UTC, merged