[1단계 - 자동차 경주 구현] 루루(송지은) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #172
Opened 2023-02-09 08:26 UTC by hafnium1923

2023-02-09 15:32 UTC, HyeonaKwon reviewed
안녕하세요, 이번 리뷰를 맡은 헤인티입니다. 앞으로 잘 부탁드려요! 😃  
다음부터 PR 요청할 때에는 설명 비우지 않고 채워서 보내주시면 좋을 것 같습니다!  

#### 리뷰
1. 용어를 한번 정리하고 개발을 진행하면 좋을 것 같아요. cars/carNames, RaceResult/raceRoundResults 등등 하나의 용어만 사용해보면 좋겠습니다!
2. 어떤건 class, 어떤건 const 인 객체로 구현하셨는데 어떤 기준으로 구현하신건지 궁금합니다!
3. App 이 CarRaceGame 에서 할 일까지 다 하고 있는 것 같은데요! 예시로 네이밍만 보면 CarRaceGame 이 CarRace 를 가지고 있을 것 같은데 App 이 두 개 모두 들고 있죠? App 과 CarRaceGame 의 차이를 생각해보면 좋을 것 같습니다.
4. 전체적으로 함수 인자에 await 인 함수의 실행 결과값을 넘기고 있는데요, 리뷰에도 남겼듯이 구분을 해주면 좋을 것 같습니다.
5. 전체적으로 readline 에 얽혀있어 순수하지 못하다는 느낌이 들어요! readline 은 App 또는 CarRaceGame 이 호출하고 나머지 객체(또는 클래스) 는 입력 값만 받아서 자기 할일을 하게 하면 코드도 간결해지고 테스트코드도 간결해질 것 같아서요!

2023-02-09 15:32 UTC, HyeonaKwon commented on src/domain/App.js
> +      this.#carRace.setCarNames(await InputView.readCarNames(MESSAGES.carText));
함수의 인자로 await 를 넘기는 것보다 구분을 해주는게 좋을 것 같아요!  
```suggestion
      const carNames = await InputView.readCarNames(MESSAGES.carText);
      this.#carRace.setCarNames(carNames);
```

2023-02-09 15:32 UTC, HyeonaKwon commented on src/domain/App.js
> +      const temp = CarRaceGame.updateRace(this.#carRace.getCarDistances());
변수 이름은 의미있게 네이밍되면 좋겠어요!

2023-02-09 15:32 UTC, HyeonaKwon commented on __tests__/CarError.test.js
> +});
제가 잘 몰라서 드리는 질문일 수도 있는데, 테스트코드인데도 readLine 을 활용해야 하나요? InputView 에 바로 입력값을 넘길 수 있도록 구현하면 훨씬 간단해질 것 같은데요!

2023-02-09 15:38 UTC, HyeonaKwon requested changes
제가 Comment 로 잘못 눌러서 리뷰 남겼습니다.. 😂  
남긴 코멘트 확인해주세요~!

2023-02-11 12:58 UTC, hafnium1923 commented on __tests__/CarError.test.js
> +const mockQuestions = (answers) => {
네 반영하겠습니다

2023-02-11 12:59 UTC, hafnium1923 commented on src/view/OutputView.js
> +    console.log();
네.. 매 라운드별 출력할 때  한줄 띄고 다시 라운드 출력하려고 마지막에 console.log 추가했습니다.

2023-02-11 13:02 UTC, hafnium1923 commented on src/domain/App.js
> +      this.#carRace.setCarNames(await InputView.readCarNames(MESSAGES.carText));
네 await로 값 받아올 때는 변수에 저장한 다음에 넘기도록 하겠습니다!

2023-02-11 13:03 UTC, hafnium1923 commented on src/domain/App.js
> +      const temp = CarRaceGame.updateRace(this.#carRace.getCarDistances());
시간이 없어 빠르게 하다보니 수정하는 것을 놓친 것 같습니다. 다음부터는 조금 더 신경써서 확인하도록 하겠습니다!

2023-02-11 13:05 UTC, hafnium1923 commented on __tests__/CarError.test.js
> +});
테스트 코드 작성을 해본 경험이 별로 없어 프리코스의 테스트 코드를 참고하다 보니 readLine을 사용하게 되었습니다.. readLine을 사용하지 않고 작성 해보는 것을 연습해보도록 하겠습니다!

2023-02-11 15:31 UTC, hafnium1923 commented
안녕하세요! 루루라고 합니다😊 다음 리뷰 요청부터는 모르는 것 열심히 작성해서 질문하도록하겠습니다!! 안그래도 모르는 게 많았는데 막상 시간 지나서 다시 질문 하려고 하니 기억이 안나 너무너무 아쉽습니다😢 앞으로도 잘 부탁드리겠습니다 헤인티😍

1. 용어를 한번 정리하고 개발을 진행하면 좋을 것 같아요. cars/carNames, RaceResult/raceRoundResults 등등 하나의 용어만 사용해보면 좋겠습니다! 
> 코드를 작성할 때는 다 다른 것을 지칭한다고 생각했었는데 다시 보니 하나로 통합해도 되는 변수명이었다는 생각이 듭니다! 이번에는 열심히 코드 보면서 통합해보았는데,, 놓친게 있을지 걱정이되네요

2. 어떤건 class, 어떤건 const 인 객체로 구현하셨는데 어떤 기준으로 구현하신건지 궁금합니다!
> App은 컨트롤러의 개념으로 만들었습니다. 그래서 class로 구현했고 carRace는 이 미션에서의 작은 데이터 저장소로써 만들었는데 요구 사항이 추가된다면 여러 데이터가 만들어 질 수도 있다고 생각해 class로 구현했습니다.
나머지는 각 기능 별로 나눈 객체들인데 여러곳에서 호출해서 사용 할 수 있을 것 같아 const로 구현해보았습니다. 
아직 class와 const의 개념이 제대로 확립되지 않아 저도 제가 코딩하면서 언제 어떤 것을 써야하는지 많이 헷갈립니다. 혹시 관련된 개념에 도움되는 책이나 학습강의가 있다면 추천해주실 수 있나요?

3. App 이 CarRaceGame 에서 할 일까지 다 하고 있는 것 같은데요! 예시로 네이밍만 보면 CarRaceGame 이 CarRace 를 가지고 있을 것 같은데 App 이 두 개 모두 들고 있죠? App 과 CarRaceGame 의 차이를 생각해보면 좋을 것 같습니다.
> 이부분은 제가 페어와 코딩하며 궁금했던 부분이었는데, 페어의 말로는 모든 파일들은 컨트롤러를 통해서 이어져야 하며 컨트롤러에서 객체 간 데이터를 전해줘야 한다고 하더라구요! 그래서 carRace와 carRaceGame 둘 다 개별 객체라 컨트롤러를 통해서 연결되게 구현했습니다. 어떤 상황에서 컨트롤러를 통한 연결이 아닌 객체끼리 import 해도 되는건지 궁금합니다.
+ car에 대한 정보와 그 정보를 변화 시키는 것이 하나의 객체에 있어야 밖에서 정보에 접근을 못하게 되어 좀 더 객체답게 사용되는 것 같아 carRace를 없애고 carRaceGame에 합쳤는데, 이렇게 하는 것이 맞을까요?
 
4. 전체적으로 함수 인자에 await 인 함수의 실행 결과값을 넘기고 있는데요, 리뷰에도 남겼듯이 구분을 해주면 좋을 것 같습니다.
> 반영해두었습니다!

5.전체적으로 readline 에 얽혀있어 순수하지 못하다는 느낌이 들어요! readline 은 App 또는 CarRaceGame 이 호출하고 나머지 객체(또는 클래스) 는 입력 값만 받아서 자기 할일을 하게 하면 코드도 간결해지고 테스트코드도 간결해질 것 같아서요!
> readLine은 입력 값 받는 것이라서 InputView에서만 사용하고 있는데, 얽혀있어서 순수하지 못하다는 것이 어떤 것을 의미하시는지 모르겠습니다..😢 일단 readLine에서 오류 검사를 하고 있는 부분을 말씀하시는 것 같아서 분리해두었는데 제대로 이해한 게 맞을까요?? 또한, 오류 검사를 분류 하긴 했는데 시도한 횟수가 정확히 입력되고 나서 readLine을 닫으려면 if구문이 필요해 조건절은 사용했습니다.

#### 추가 질문
- 제가 그동안 MVC 패턴을 사용 해본 적이 한번도 없어서 미션 시작하면서 페어와 패턴 사용에 대해 토론하는 시간이 길었습니다. 저는 MVC패턴을 적용하는 것은 실제로 웹 view가 있을 때 사용하는 것이라고 생각했거든요. 그래서 이런 작은 프로그램을 만들 때도 console을 view로 생각해 패턴을 적용 해야 하는 건지, 그것이 아니라면 언제 MVC 패턴을 적용 하는 건지 궁금합니다.

2023-02-11 15:38 UTC, HyeonaKwon commented on src/view/OutputView.js
> +    console.log();
네네 다음부터는 Array 의 내장객체를 이용해보면 좋겠네요! 예시코드는 아래와 같이 드리겠습니다!

```javascript
const roundResult1 = carNames.map().join();
const roundResult2 = carNames.map().join();
...

// ================================ 위의 코드를 아래로 바꾼다면?
const roundResult = (...).join('\n');
```

roundResult1, roundResult2, ... 을 이용해서 roundResult 로 어떻게 만들지도 생각해보시면 좋을 것 같습니다!

2023-02-11 16:44 UTC, HyeonaKwon requested changes
안녕하세요 루루! 질문 답변 및 추가 피드백 드립니다! 😃

#### 질문

> 1. 아직 class와 const의 개념이 제대로 확립되지 않아 저도 제가 코딩하면서 언제 어떤 것을 써야하는지 많이 헷갈립니다. 혹시 관련된 개념에 도움되는 책이나 학습강의가 있다면 추천해주실 수 있나요?  

루루가 구현하신 객체는 class 를 모방한 함수 모음이 아닐까? 싶은데요! 실제로는 개별 함수를 export 하는 방식으로 쓰일거예요!

```javascript
export const A = () => {};
export const B = () => {};
```
함수형 프로그래밍에 대해서 공부해보시면 좋을 것 같습니다!
제가 말한 요지는 class vs const 가 아니라 class vs object 로 나눠서 구현한 이유가 궁금했습니다.


> 2. carRace와 carRaceGame 둘 다 개별 객체라 컨트롤러를 통해서 연결되게 구현했습니다. 어떤 상황에서 컨트롤러를 통한 연결이 아닌 객체끼리 import 해도 되는건지 궁금합니다.   

객체끼리 임포트 한다는게 어떤 의미인지는 모르겠으나..! 멤버변수로 합성해서 사용해도 되냐는 질문이 맞을까요..?  
일단 코드 보면서 생각이 들었던 점은, App 이 너무 많은 일을 하고 있다는 생각이 들었어요. **App 은 한 프로그램(서비스) 가 어떻게 작동하는지**를 명확히 나타내야 해요! 그런데 지금은 어떻게 작동하는지 가 아니라 프로그램 전체의 비즈니스 로직을 가지고 있는 듯 합니다. App 은 컨트롤러가 아니라 말 그대로 **앱** 을 나타내는 코드가 있어야 해요! 루루 코드로 보면 CarRaceGame 이 컨트롤러가 되어야하지 않을까 싶습니다.  
또한 carRace 와 carRaceGame 의 네이밍을 보면 carRaceGame 이 여러개의 carRace 를 가지지 않을까? 유추하게 되는데요. 전혀 연관되지 않은 클래스더라구요! 그래서 연관관계가 맞는 것인지 질문드린것이었어요! 클래스끼리 어떤 연관관계를 가지게 되는지 코딩하기 전에 그림을 그려보고 시작해보는 것도 좋을 것 같습니다~


> readLine은 입력 값 받는 것이라서 InputView에서만 사용하고 있는데, 얽혀있어서 순수하지 못하다는 것이 어떤 것을 의미하시는지 모르겠습니다..😢  

요거는 테스트 코드에 대한 내용이었어요! 유효성 체크가 잘 동작하는지를 확인하기 위해 inputView 에서 readline 을 통해 입력값을 받아와야하는 것이 순수하지 못하다고 생각했습니다! 지금은 잘 수정된 것 같네요 👍


> 제가 그동안 MVC 패턴을 사용 해본 적이 한번도 없어서 미션 시작하면서 페어와 패턴 사용에 대해 토론하는 시간이 길었습니다. 저는 MVC패턴을 적용하는 것은 실제로 웹 view가 있을 때 사용하는 것이라고 생각했거든요. 그래서 이런 작은 프로그램을 만들 때도 console을 view로 생각해 패턴을 적용 해야 하는 건지, 그것이 아니라면 언제 MVC 패턴을 적용 하는 건지 궁금합니다.  

현업에서 MVC 패턴을 이용할 일이 많지는 않습니다! 그리고 지금은 MVC 패턴이 뭔지를 체험하기 위해 진행되는 미션이 아닐까 싶어요~! MVC 패턴은 이런거구나~, MVC 패턴은 어떤 어떤 역할이 존재하는구나~ 와 같이 가볍게 생각하고 학습하시는 쪽이 좋을 것 같아요!  


#### 피드백
제가 따로 남긴 테스트 코드에 대한 피드백만 다시 적용해서 요청해주시면 1단계는 마무리해도 될 것 같아요!
2단계에서는 App 을 어떻게 간단하게 나타낼 수 있을까? 를 생각해보시면 좋을 것 같아요 👍

2023-02-11 16:44 UTC, HyeonaKwon commented on __tests__/CarError.test.js
> +});
readline 에 대한 디펜던시가 없어져서 코드가 깔끔해졌네요! 그런데 이 파일에 대해서 여러 의견이 있습니다.

1. 테스트 제목은 "예외가 발생한다" 이지만 실제로는 0 이라는 값과 같은지를 확인하고 있습니다.
2. 보통 check~~~() 함수의 경우 true/false 인 boolean 값을 리턴해준다는 암묵적인 네이밍인데요, boolean 값을 리턴하도록 수정해보면 어떨까요?
3. expect() 앞 하이픈(-) 은 뭘까요?

생각해보면 이 파일이 "에러" 에 대한 테스트가 맞을까요? 유효성에 대한 테스트는 아닐지요!

2023-02-11 16:44 UTC, HyeonaKwon commented on __tests__/CarRaceGame.test.js
> +});
큰 거리 업데이트에 대한 테스트 가 맞지 않을까요? 라운드는 두 턴밖에 안하는걸요! 😂

2023-02-11 16:44 UTC, HyeonaKwon commented on src/domain/App.js
> +  }
깔끔한 코드는 좋은데요! 2단계에서는 에러 메세지를 좀 더 세분화해보면 어떨까 싶습니다!
예를 들어 readCarNames() 에서 던지는 에러가 throw new Error('1개 이상의 자동차 이름을 입력해주세요.') 라고 던졌다면 아래와 같이 사용자에게 노출해줄 수 있습니다.

```javascript
  try {
      const carNames = await InputView.readCarNames(MESSAGES.carText);
      ...
    } catch (e) {
      OutputView.printMessage(e.message);
      ...
    }
```

실제로 현업에서는 다양한 상황에서 정확한 문제가 무엇인지를 사용자에게 알려줘야하기 때문에 에러메세지가 다양합니다! 다양한 메세지를 어떻게 알려줄 수 있을까를 생각해보면 좋을 것 같아요 😃

2023-02-11 16:44 UTC, HyeonaKwon commented on src/domain/ErrorHandler.js
> +  },
위에서도 말씀드렸듯이 check~~~() 라면 boolean 을 리턴할 수 있도록 보장되면 좋을 것 같아요!
때에 따라 내부에서 throw new Error(...) 를 해도 되구요!

2023-02-12 12:32 UTC, hafnium1923 commented on src/view/OutputView.js
> +    console.log();
join을 사용해서 해보았습니다! map은 처음 사용해보아서 조금 더 공부해보고 적용해보도록하겠습니다. 감사합니다!

2023-02-12 12:32 UTC, hafnium1923 commented on __tests__/CarError.test.js
> +});
1,2. 불린 값으로 반환하게 바꿨습니다! 예외처리 할 때 Error을 던져서 에러라고 생각한 것 같습니다. 헤인티말처럼 에러보다는 유효성에 대한 검사가 맞다고 생각합니다. 테스트 파일이랑 테스트 별 이름에도 적용했습니다.

3. 하이픈.. 코드 작성할 때 오타로 들어간 것 같아요 문제없이 코드가 작동해서 발견을 못했습니다 바로 지웠습니다.

2023-02-12 12:32 UTC, hafnium1923 commented on __tests__/CarRaceGame.test.js
> +});
앗.. 맞네요..! 해당 테스트 제목은 수정했고, 큰 숫자 라운드 진행시 테스트도 다시 작성해보았습니다ㅎ

2023-02-12 12:32 UTC, hafnium1923 commented on src/domain/App.js
> +  }
안그래도 자동차가 하나 밖에 입력되지 않았을 때, 아예 입력이 되지 않았을 때, 글자 수가 초과되었을 때, 자동차 이름이 중복되었을 때 등등 여러 오류가 있어서 어떻게 처리하면 좋을지 고민하고 있었습니다. 2단계에서는 분리해서 적용해보겠습니다!!

2023-02-12 12:32 UTC, hafnium1923 commented on src/domain/ErrorHandler.js
> +  },
일단은 불린 값으로 return 되도록 했습니다. 에러를 던지는 것에 관해서는 제가 app에서 try-catch로 에러를 잡고있는데,  페어랑 진행했을 때 inputview에서 호출한 Errorhandler에서 에러를 던지면 app의 try-catch에서 안잡혀서 어쩔 수 없이 inputView에서 에러를 던지도록 구현했습니다. 이 부분에 관해서는 조금 더 공부해서 반영 할 수 있다면 반영해보도록 할게요!

2023-02-12 12:40 UTC, hafnium1923 commented
안녕하세요 헤인티!! 작성해주신 답변 잘 읽어보았습니다. 함수형 프로그래밍에 대해서 열심히 공부해보겠습니다. 
개념이 많이 부족해서 그런지 헤인티가 질문해주신 class vs object 로 나눠서 구현한 이유에 대해서 저도 왜 그렇게 했는지(?)
모르겠더라구요.. 애초에 class와 object가 어떻게 다른지도 모르고 있어서.. 미션을 하면 할수록 스스로 부족한 부분이 너무나도 눈에 잘 보이는 것 같습니다..😢 열심히 공부해서 헤인티의 답변에 머뭇거리지 않고 제 생각을 말하게 된다면 좋겠어요!

다른 피드백에 대한 부분은 반영해서 커밋했습니다. 헤인티의 피드백을 보니 제가 너무 일차원적으로 코드를 짜고 있구나.. 하고 생각했던 것 같아요. 말씀해주신 것 처럼 입력 값 오류에 대한 메시지 분할, App과 컨트롤러에 대한 것은 2차 피드백에 반영할 수 있도록 노력하겠습니다.

주말인데도 감사드려요
좋은 밤 보내세요!!!🫧🫧😊

2023-02-12 15:25 UTC, HyeonaKwon approved these changes
루루 안녕하세요! 주말인데도 고생하시네요 🥹  
앞으로 더 성장하면 되죠! 아직 첫번째 미션이니 상심하지 마시구 자신감 가지고 더 공부해보아요 💪🏻  
2단계에서는 피드백에서 얘기 나눈 것들을 적용해서 만나면 좋을 것 같아요! 고생 많으셨습니다.

2023-02-12 15:25 UTC, merged