[1단계 - 자동차 경주 구현] 쿠마(박영진) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #180
Opened 2023-02-09 08:38 UTC by yogjin

파노 안녕하세요!

페어와 헤어지기 전에 리팩토링을 하고싶었지만 시간이 부족해서 일단 PR 먼저 날렸습니다ㅠ 죄송합니다

지금은 `Controller.js` 코드를 리팩토링 하고 싶은데요,

2023-02-09 15:39 UTC, jho2301 requested changes
안녕하세요 쿠마
리뷰어 파노입니다.

취업하셨다가 다시 돌아오셨나요? 
전반적으로 꼼꼼한 코드와 테스트에 대한 이해도가 돋보였던 것 같아요

전반적인 피드백으로는 구조에 대해서 좀 더 고민을 좀 더 해보시면 좋겠다고 생각이 들었어요.
구조는 고수준(서비스로직)에서 저수준(입출력)으로 단방향의 비순환하는 형태를 그려야겠습니다.
그 과정에서 각 계층은 자신보다 저수준의 계층을 알지 못해야하구요.
1. MVC의 형태로 봤을 때 모델, 뷰, 컨트롤러가 각각 어떤 수준의 추상화 정도를 가지게 될까요?
2. 어쨌든 컨트롤러는 뷰의 api를 사용해야할텐데, 어떻게 단방향으로 의존성 그래프를 구성해볼 수 있을까요?

화이팅입니다!

2023-02-09 15:39 UTC, jho2301 commented on src/model/Car.js
> +  }
move 메서드 자체의 시그니쳐만 봤을때 move를 했을 때 이동할 수도 있고 이동하지 않을 수도 있는 스펙인데, 
이동여부를 사용자에게 알려주면 사용자가 그에 맞게 핸들링할 수 있지 않을까요? 
알려주지 않고 함수가 종료된다면 사용자는 다른 방법을 사용해서 자동차가 움직였는지 판단해야할 것 같습니다

2023-02-09 15:39 UTC, jho2301 commented on src/controller/Controller.js
> +  #showResult() {
클래스 내 접근지정자 사용이 일관되도록 개선해보면 좋을 것 같아요

2023-02-09 15:39 UTC, jho2301 commented on src/controller/Controller.js
> +    });
요거는 재미삼아서 ㅎㅎ
print의 퍼포먼스가 굉장히 좋지 않다고 가정했을 때 최소한만 호출해야한다면 어떻게 개선해볼 수 있을까요?

2023-02-09 15:39 UTC, jho2301 commented on __tests__/Car.test.js
> +  });
크.. 난수 생성 메서드에 몽키패칭 좋네요, 테스트 좀 하더분이시군요  😮

2023-02-09 15:39 UTC, jho2301 commented on __tests__/Car.test.js
> +  it(`자동차가 전진하는 조건은 ${GAME.MOVE_CONDITION.min}에서 ${
(소소, 주관) 개인적인 생각인데 테스트이름이 한글이라면 test로 사용하는게 낫지 않나라구 생각해요. it은 영어로 name인자가 `should ~~` 요런식으로 이어져야 의미가 있다고 생각하는 편입니다

2023-02-11 05:48 UTC, yogjin commented on __tests__/Car.test.js
> +const Car = require('../src/model/Car');
기존에 생각해보지 않았던 모듈시스템에 대해 알아볼 수 있어서 좋았습니다!
## Node.js의 모듈시스템
기존에는 `CJS` 만 지원했지만, 추후에 `ESM`도 추가되어 둘 다 사용할 수 있습니다.
`CJS`는 `module.exports`/`require` 키워드를 사용하고, `ESM`은 `export`/`import` 키워드를 사용해 모듈을 이용합니다.

## 동작 방식의 차이❓
`CJS`는 동기적으로 동작하여 런타임에서만 모듈 관계를 파악할 수 있습니다. 따라서 빌드타임에 정적 분석이 어렵습니다.
하지만 `ESM`은 비동기적으로 동작하여 빌드타임에 정적 분석으로 모듈 간 의존 관계를 파악할 수 있습니다.
따라서 `ESM`은 `Tree-shaking`을 적용하기 쉽습니다.

이것 말고도 `ESM`은 `Top-level await`을 지원하지만 `CJS`는 지원하지 않는 등 사용할 수 있는 문법의 차이도 많이 있습니다.
따라서 설계와 동작이 다른 두 모듈 시스템은 호환하여 사용하기 어렵습니다.

## 새로운 라이브러리를 만들때 고려할 점✨
웹 브라우저 환경에서는 `ESM`을 사용합니다,
`Node.js` 진영에서는 `CJS`가 주류입니다. (`ESM`이 `CJS` 보다 진보된 모듈시스템이고, `Node.js` 에서 사용할 수 있긴 하지만 많은 레거시 라이브러리들은 `CJS`로 개발되었고, 아직도 많이 사용중이기 때문입니다)

따라서 새로운 라이브러리가 브라우저 환경(`ESM`)과 Node.js(`CJS`) 환경 둘 다 지원하도록 만들면 좋습니다!

[CJS/ESM 호환 모듈 만드는법](https://nodejs.org/api/packages.html#dual-commonjses-module-packages)을 보면서 직접 라이브러리를 만들어보고 싶었지만 아직은 많이 어렵고, 시간이 없어서 키워드(`package.json`의 `exports` field 이용)를 안 것으로 만족했습니다😭

[`toss` 의 `slash` 라이브러리](https://github.com/toss/slash/blob/1495cb5624e4f64cbce31801605e4851c544d776/packages/react/lottie/package.json#L54:L59)도 이 방법을 이용해 CJS,ESM,Typescript 까지 호환하는 것을 확인할 수 있었습니다😯

2023-02-11 06:14 UTC, yogjin commented on __tests__/Car.test.js
> +  it(`자동차가 전진하는 조건은 ${GAME.MOVE_CONDITION.min}에서 ${
아..! `it`은 `should ~` 와 함께 사용해서 읽기 쉽게 하려고 사용하는거군요,, 😮
그런 숨겨진 의미가 있었네요.
저도 일관성을 위해서 `test`로 수정해야겠어요😆

2023-02-11 06:29 UTC, yogjin commented on __tests__/Car.test.js
> +  });
**몽키패칭**이라는 키워드를 처음들어봤어요😮 
이렇게 또 하나 알아가네요! 감사합니다!!

2023-02-11 07:10 UTC, yogjin commented on src/controller/Controller.js
> +    });
`print`가 반복문에서 계속 호출되고 있어서 퍼포먼스가 떨어지겠네요.
```javascript
    let result = [];
    this.#histories.forEach((history) => {
      result.push(Array.from(history, OUTPUT.result).join(''));
    });
    OutputView.print(result.join('\n'));
```
이렇게 출력해야 할 메시지를 따로 담은 후 
한번에 `print`하여 개선할 수 있을 것 같습니다!

2023-02-11 07:22 UTC, yogjin commented on src/validation/input.js
> +    return handleError(ERROR.carNameLength);
저는 이런 장점이 있다고 생각합니다.
+ 재사용성이 좋다. (같은 에러메시지를 사용해야 하는 경우에 가져다 쓰면 되기 때문에)
+ 수정에 대응하기 쉽다.
+ 에러메시지의 컨벤션을 맞추기 쉽다
+ 코드를 읽을 때, 작성할 때 상수명만 보고 어떤 에러인지 확인이 쉽다.

2023-02-11 07:31 UTC, yogjin commented on src/utils/common.js
> +};
상수를 깊은동결하기 위해 만들었습니다.
처음에는 단순 `Object.freeze()` 만 사용했고, 
상수는 대문자로 작성되기 때문에 상수 객체의 내부 객체 프로퍼티가 변경될 일이 거의 없을 것이라고 생각했지만.. 
상수의 변경을 좀 더 꼼꼼하게  막기 위해서 객체 프로퍼티가 변경되는 것까지 고려했습니다.

2023-02-11 07:45 UTC, yogjin commented on src/model/Car.js
> +    if (randomNumber < GAME.MOVE_CONDITION.mid) {
[uppercase에 대한 airbnb 컨벤션](https://github.com/airbnb/javascript#naming--uppercase)을 보고 나름대로 해석하여
상수를 만들 때 객체라면 `uppercase`를 유지하고 상수 키 자체에는 `camelCase`를 적용해보았습니다.
개인적으로는 코드의 가독성이 높아지고 작성에도 용이하다고 생각하는데,
파노는 어떻게 생각하는지 궁금합니다!

2023-02-11 09:07 UTC, yogjin commented on src/view/InputView.js
> +  },
앗 그렇네요😮 굳이 한번 더 감쌀 필요가 없죠..!
개발할때 해당 메서드가 비동기적으로 동작한다는 것을 시각적으로? 드러나게 하려고 `async` 키워드를 붙였던 것 같은데.. 
그러다 보니 저렇게 작성한 것 같아요. 찝어주셔서 감사합니다😆

+찾아보니 메서드에 대한 설명을 드러내기 위해서는  `jsdoc` 을 사용하면 되겠네요!

2023-02-11 09:14 UTC, yogjin commented on src/utils/common.js
> +const deepClone = (obj) => JSON.parse(JSON.stringify(obj));
헉.. deepClone을 지원하는 내장 API가 있었군요.
알려주셔서 감사합니다🙂

2023-02-11 10:27 UTC, yogjin commented on src/validation/input.js
> +};
잘못 구현했네요..!
Number.isInteger()를 이용하여 수정했습니다.

2023-02-11 10:32 UTC, yogjin commented on src/controller/Controller.js
> +  #showResult() {
`play()` 이후의 동작은 따로 호출하지 못하도록 (외부에서는 `play()` 만 보이도록) 수정했습니다.

2023-02-12 02:09 UTC, yogjin commented on src/utils/constants.js
> +});
그렇네요! `MESSAGE` 객체를 따로 만들어서 `INPUT`, `OUTPUT`을 넣어주었습니다.

문자열 포매팅 함수를 상수와 함께 관리한 이유는 실제 출력되는 메시지를 한곳에 모아놓고 싶어서입니다.
생각해보니 메서드는 상수와 어울리지 않는 것 같네요.
`Controller.js`를 리팩토링해서 `OutputView.js`에서 출력을 처리하도록 했습니다.

2023-02-12 02:12 UTC, yogjin commented on src/controller/Controller.js
> +class Controller {
`CarGame` 으로 지어봤습니다 🚘

2023-02-12 02:43 UTC, yogjin commented on .prettierrc.json
> +}
default 옵션이 엄청 많았군요..!
다음부터는 협업 전 스타일 컨벤션을 제대로 정할 수 있겠어요. 감사합니다

2023-02-12 04:12 UTC, yogjin commented on src/App.js
> +}
다른 View를 사용하려면 Controller를 변경해야겠네요.
외부에서 view를 주입받는 것으로 Controller의 constructor를 수정했습니다.
비슷하게 다른 Car(Model)를 사용하고 싶을 때도 외부에서 받게 수정하면 좋겠네요.

2023-02-12 04:17 UTC, yogjin commented on src/model/Car.js
> +  }
이동여부 반환!
그 생각을 못했었네요. 
이동 여부에 따라 불린값을 반환하도록 반영했습니다.

2023-02-12 09:23 UTC, yogjin commented on src/controller/Controller.js
> +  }
`play`에서 자동차게임의 로직들을 순서대로 호출하도록 수정했습니다.
`makeCars`는 `setCars`에 포함되어도 될 것 같아 중첩함수로 선언하여 호출하도록 수정했습니다.
이렇게 중첩함수를 사용하는 게 괜찮은지 궁금합니다.

2023-02-12 10:22 UTC, yogjin commented on src/validation/input.js
> +};
1. 일단 에러를 날리고, 요구사항에서 그 에러메시지를 출력하라고 하니까 그냥 별 생각없이 try catch를 썼던거 같아요 반성합니다😭. validator에서 한번에 try catch를 하는것이 더 나을까요? 
2.  `validation/input.js` 을 `InputValidator` class로 만들어서 `handleError` 메서드를 외부에서 받아 사용하는 것으로 만들고, terminalInputValidator.js, webInputValidator.js를 만들어서 웹과 터미널 두 군데서 이용할 수 있도록 개선해보았습니다. 
3. `false`, `true` 반환하는 역할을 handleError, check~ 메서드가 대신해주고 있었는데, 한눈에 보기 쉽게 validate~ 메서드에서 하도록 했습니다. 
에러 핸들링을 어떤 곳에서 어떻게 해야하는지.. 어렵네요🧐

2023-02-12 10:47 UTC, yogjin commented
파노 안녕하세요! 
늦은 리뷰요청 죄송합니다ㅠ
파노의 꼼꼼한 리뷰덕분에 공부하면서 많은걸 느끼고 배울 수 있었습니다!

리팩터링 주요 변경점은 다음과 같습니다.
## ❗️Changes
- ce4e891ad00282d81f2cfc394fcfc20ec2d12dd1: constants.js 의 `MESSAGE.OUTPUT` 내부에 있던 메서드 로직을 `OutputView`으로 분리
- 82b6f377581d28975d5715b560023598a0bf1fde: 하나의 `View`에 의존하지 않고 상황에 따라 다른 `View`를 갖는 `CarGame`을 만들 수 있도록 수정
- 33f4e72c2a7f229c768236be98fda7802f915e54: try catch 문을 `validate~` 메서드로 이동하고, 각 `check~` 메서드에서 throw Error 하도록 수정
- 49b558a6ae69688ca370494dff9c2e2a3913a6b0: `play()`에서 자동차게임의 로직을 순서대로 호출하도록 수정
- 2f69a1786732aae07bbd7004a9da6adfb2f2df3e: validation이 사용하는 환경(web, terminal)에 맞게 에러메시지를 출력하도록`handleError`를 받아서 사용하는 것으로 수정

또한 각 리팩터링을 하면서 했던 고민과 생각을 conversation에 댓글로 남겨놓았습니다.
감사합니다!😊

2023-02-12 11:13 UTC, yogjin commented
> 1. MVC의 형태로 봤을 때 모델, 뷰, 컨트롤러가 상대적으로 어떤 수준을 가지게 될까요?
> 2. 어쨌든 컨트롤러는 뷰의 api를 사용해야할텐데, 어떻게 단방향으로 의존성 그래프를 구성해볼 수 있을까요?

이 질문에 대해 나름대로 생각을 해봤습니다!
1. 컨트롤러가 도메인로직의 핵심을 담당하기 때문에 가장 고수준인 것 같아요.
   뷰와 모델은 서로 몰라야하고, 컨트롤러에서 제어해야 한다고 생각해서 같은 저수준으로 봐야할 거 같아요.
2. 단방향으로 의존성 그래프를 구성한다는 것의 의미를 잘 파악하지 못했어요.. 대충 이해하기로는 컨트롤러가 뷰를 의존하고, 뷰가 컨트롤러에 의존하지 않게(모르게) 해야할 것 같습니다.

2023-02-12 12:41 UTC, jho2301 commented on __tests__/Car.test.js
> +const Car = require('../src/model/Car');
오 구체적으로 조사해주셨네요! 블로그 아티클로도 공유해주시면 훨씬 좋을 것 같아요

2023-02-12 12:46 UTC, jho2301 commented on src/controller/Controller.js
> +  }
makeCars가 setCars에서만 호출된다고 확신할 수 있다면 사용해주신 방법도 설득력이 있다고 생각해요

2023-02-12 12:51 UTC, jho2301 commented on src/validation/input.js
> +};
우선 확정적으로 에러를 던지는데 try catch를 사용하는게 어색했어요. 
무지성으로 직해를 해보면 'try문안에서 일단 코드를 실행(시도)해보고 여기서 에러가 발생하면 catch문에서 에러를 잡을게' 요렇게 받아들여보시면 어떨까요? ㅎㅎ
에러를 던지는게 의도라면 validate는 에러를 던지고 사용하는 쪽에서 발생할지 모를 에러에 대해서 제어하는게 자연스러울 것 같네요.
그렇다 boolean으로 에러가 났는지 안났는지 알려줄 필요도 없을 것 같아요

2023-02-12 12:52 UTC, jho2301 commented on src/view/InputView.js
> +  },
ts환경에서 주로 개발하실테니 타입추론이 되어서 그닥 상관은 없긴할텐데
js환경이라면 jsdoc도 좋고, async키워드만 붙여줘도 좋을 것 같네요!

2023-02-12 12:57 UTC, jho2301 commented on src/model/Car.js
> +    if (randomNumber < GAME.MOVE_CONDITION.mid) {
이미 객체가 uppercase이므로 굳이 자식도 uppercase 일 필요가 없다는 거군요! 그렇다면 저도 좋은 것 같습니다~!

2023-02-12 13:03 UTC, jho2301 commented on src/controller/Controller.js
> +    });
꼬리물기이긴하지만 예시코드를 올려주셔서 코멘트를 달아보자면 

```ts
   const result = this.#histories.map((history) =>  Array.from(history, OUTPUT.result).join('\n');

   OutputView.print(result);
```

let 없이 구성해볼 수 있을 것 같아요

2023-02-12 13:19 UTC, jho2301 commented
지금 다시 보니까 질문 드린 내용이 오바한 것 같네요
입출력에 가까울 수록 저수준이라는 생각 아래에서 저는 모델이 가장 고수준이 아닌가 생각해요. 모델은 도메인 데이터와 데이터를 다루는 서비스로직 메서드를 담은 일반객체기 때문에 어떤 환경에서든 이식이 가능합니다. 
하지만 컨트롤러는 터미널이라는 내용을 알아야하는 좀 더 구체화된 어플리케이션 코드가 있기때문에 상대적으로 저수준이라고 생각했습니다. ㅎㅎ
요런 생각도 있구나하고 넘겨주시면 감사할 것 같아요

2023-02-12 13:22 UTC, jho2301 approved these changes
안녕하세요 쿠마
질문드린 내용에 대해서 고민해보셨다는게 잘 느껴지는 코멘트였습니다~
질문드린 부분에 대한 제 생각은 위에 남겨보았어요
2단계에서 뵐게요!

2023-02-12 13:22 UTC, merged