[1단계 - 자동차 경주 구현] 첵스(최혜령) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #182
Opened 2023-02-09 08:39 UTC by HyeryongChoi

안녕하세요! 슬링키와 페어 프로그래밍을 한 첵스입니다😄
우테코 시작 후 첫 미션이라 많이 부족하지만 리뷰 잘 부탁드리고 미리 감사드립니다!

**궁금한 점❓**
- 테스트하기 쉬운 코드가 좋은 코드인 것 같다는 생각을 했는데, 개발하면서 테스트를 위해 코드를 리팩터링 하는 것이 좋은 방향인지 궁금합니다.

2023-02-10 08:56 UTC, devhyun637 requested changes
안녕하세요 첵스~ 리뷰어 티케입니다. 🧚‍♀️
사실 푸만능, 엽토, 첵스에게 쓰는 이 전반적인 리뷰 내용은 공통부분이 많습니다. 이해해주셔서 감사합니다

저도 리뷰어가 처음이라, 많이 긴장이 되고 걱정 반 설렘 반이에요! 저야말로 잘부탁드립니다~ 리뷰를 보면서 무조건 적용하거나 받아들이기보다는 늘 의심하면서 비판적으로 받아주세요! 저도 잘 모르는 부분이 있을 수 있고, 첵스가 어떠한 의도에서 개발했는지가 훨씬 중요하니깐요. 많이 들어보셨겠지만, 개발에는 정답이 없습니다 :) 또 개인적으로 이해가 안 가면 질문도 남겨주시고 공개적인 곳이 부담스러우면 DM도 좋아요! 같이 고민해 나가보아요 🧡

첫 미션이 시간이 짧았을 텐데, 여러 가지 병행하면서 이렇게나 빠른 리뷰를 올려주시다니 영광입니다!
리뷰를 하면서 기능에 집중된 테스트가 인상적이었습니다 👍👍 또 pipe나 유틸함수의 접근 방법 또한 좋았습니다. 커밋메세지 어떤 부분에서 작업을 했는지 써둔것도 좋은 것 같아요~ 

[전반적인 리뷰]
1. PR 메세지, README
어떤 작업을 했는지 이 프로젝트가 무엇인지에 대한 설명이 README 파일에 담겨있으면 좋았을 것 같아요. 저희 오픈소스나 라이브러리 찾아볼 때 리드미를 통해서 어떤 프로젝트도 어떻게 사용할 수 있는지 파악하는 거랑 같은 맥락이에요. 리뷰미를 꾸며봅시다 💦
또, 현업에서 일하다 보면 어떤 작업을 했는지 PR만 보고 파악하는 건 너무 어려워져서 저희 팀은 PR 템플릿을 통해서 자세하게 어떤 작업을 했는지 명시하는 작업을 하고 있어요. 우테코 미션도 동일하게 리뷰어들이 모든 미션에 대해 인지를 하려고 노력하지만 처음보는 사람들에게 리뷰를 맡긴다는 생각으로 첵스가 어떤 작업을 했고, 어떤 부분을 신경써서 했고, 구조는 어떻게 만들었으며, 어떤 점이 궁금했다, 어떤 점이 어려웠다, 실행했을 때의 이미지 등등 작업 내역과 소감을 담아주시면 좋을 것 같아요. 첵스가 어떤 것에 더 신경썻는지 알면 저도 그것에 맞춰서 리뷰를 줄 수 있을 것 같고, 첫 미션이 어땠는지 소감도 궁금하네요 :)
또 README에 내용이 없는경우 저는 package.json을 보는 편인데요, package.json은 이 프로젝트에 어떤 라이브러리 의존성이 있고, 어떻게 시행되고 등등의 많은 정보를 담고 있기 때문이죠. 그 부분에 대한 수정이 아에 존재하지 않는데 한번 공부를 해보시면 어떨까요?

2. index.js의 기능이 어떤 것인지 찾아보시면 좋을 것 같아요. 관련 리뷰는 하단의 리뷰를 확인해주세요!

3. 클래스
클래스와 함수를 적절히 활용해주셨어요! 👍👍 어떤 기준을 가지고 하였는지 알 수 있을까요?
또 static만 있는 클래스는 어떤 의미일까요?

2023-02-10 08:56 UTC, devhyun637 commented on src/App.js
> +const CarGameController = require('./controllers/CarGameController');
index가 쓰이지 않고 있네요:) 인덱스는 프로젝트에서 어떤 역할을 할까요?
npm을 실행시키면 npm은 src의 index를 찾아서 프로그램을 시행시킨답니다. 

하지만 첵스의 프로젝트는 App을 시행시켜야하더라구요. App파일에가서 `node App`을 하면 되는걸까요?

2023-02-10 08:56 UTC, devhyun637 commented on src/App.js
> +  play() {
여백이 있으면 더 가독성이 좋아질 것 같아요 :)

2023-02-10 08:56 UTC, devhyun637 commented on docs/REQUIREMENTS.md
> +# 👍 자동차 경주
기능 목록과 구조 좋습니다. :) 내용이 기능목록 + 구조가 함께 있는데 기능 + 구조 + 시행방법을 담은 README.md를 만들어보면 어떨까요?

2023-02-10 08:56 UTC, devhyun637 commented on src/views/InputView.js
> +    return new Promise((resolve) => {
오 Promise로 하셨군요. 비동기로 처리하게 된 이유가 궁금합니다.

2023-02-10 08:56 UTC, devhyun637 commented on src/controllers/CarGameController.js
> +      }
예외처리를 해주셨군요 👍👍

2023-02-10 08:56 UTC, devhyun637 commented on src/utils/CarNameParse.js
> +function CarNameParse(str) {
str은 유틸성 함수에 적합한 파라미터 네이밍이지만, CarNameParse가 유틸성 함수인가에 대해서는 저는 살짝 회의적인데 첵스의 생각이 궁금합니다

2023-02-10 08:56 UTC, devhyun637 commented on src/utils/CarNameParse.js
> +  let carNames = str.split(',');
한번 let을 사용하지 않고 바로 사용해볼까요?

2023-02-10 08:56 UTC, devhyun637 commented on src/utils/CarNameParse.js
> +function CarNameParse(str) {
함수의네이밍이 파스칼케이스로 한 이유는 무엇일까요? 또 함수는 보통 동작을 나타내는 단어부터 시작하는게 일반적인데, 어떤 규칙을 가지고 만들었나요?

2023-02-10 08:56 UTC, devhyun637 commented on src/utils/Validator.js
> +  static validateInvalidInput(names) {
왜 InvalidInput일까요? 더 구체적인 역할을 가진 함수면 좋겠어요

2023-02-10 08:56 UTC, devhyun637 commented on src/utils/Validator.js
> +  static validateNumericInput(tryCount) {
tryCount말고 count, number로 파라미터명을 해도 좋을 것 같아요 :) 도메인 종속적인 유틸함수가 아니려면..

2023-02-10 08:56 UTC, devhyun637 commented on src/utils/constants.js
> +const INPUT_MESSAGE = Object.freeze({
상수화 좋습니다~

2023-02-10 08:56 UTC, devhyun637 commented on src/utils/constants.js
> +  START_POINT: ':',
이런건 굳이 상수로 안하는게 더 가독성이 좋을 것 같아요

2023-02-10 08:56 UTC, devhyun637 commented on src/controllers/CarGameController.js
> +    return this.readTryCount();
carDate를 저장하는 것인줄 알았지만... TryCount까지 시행하군요

2023-02-10 08:56 UTC, devhyun637 commented on src/controllers/CarGameController.js
> +        Validator.validatePositiveNumber(input);
여기는 왜 pipe 안하는것이죠..?

2023-02-10 08:56 UTC, devhyun637 commented on src/models/CarGame.js
> +    for (let count = 0; count < tryCount; count++) {
내장함수를 이용해볼까요?

2023-02-10 08:56 UTC, devhyun637 commented on src/models/CarGame.js
> +      this.#moveList.push([...moveData]);
굳이 다시풀어서 넣어주시는 이유는 무엇인가요?

2023-02-10 08:56 UTC, devhyun637 commented on src/models/CarGame.js
> +  }
carNames 변수를 만들지 않고 바로 리턴해보면 어떨까요?

2023-02-10 08:56 UTC, devhyun637 commented on src/models/CarGame.js
> +      return [...datas];
화살표 함수 안에 return밖에 없다면 축약이 가능하죠 :)

2023-02-10 08:56 UTC, devhyun637 commented on src/models/CarGame.js
> +    return [...winners];
Math.max를 이용해서 조건문 하나를 줄여볼 수 있을 것 같아요~

2023-02-10 08:56 UTC, devhyun637 commented on src/controllers/CarGameController.js
> +    return this.gameEnd();
return을 해야할까요?

2023-02-10 08:56 UTC, devhyun637 commented on src/controllers/CarGameController.js
> +    return this.readTryCount();
왜 return을 써주셨을까용?

2023-02-10 08:56 UTC, devhyun637 commented on __tests__/Car.test.js
> +  test('4이상이면 자동차가 이동한다.', () => {
👍

2023-02-10 08:56 UTC, devhyun637 commented on src/utils/numberTodistanceString.js
> +  }
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/String/repeat

요런것을 활용해보면 어떨까요?

2023-02-10 09:16 UTC, devhyun637 commented
리뷰 중 
https://github.com/woowacourse/javascript-racingcar/pull/182#discussion_r1102414637
https://github.com/woowacourse/javascript-racingcar/pull/182#discussion_r1102429900
https://github.com/woowacourse/javascript-racingcar/pull/182#discussion_r1102441327
https://github.com/woowacourse/javascript-racingcar/pull/182#discussion_r1102441125

4개의 코멘트만 우선적으로 봐주시고, 리뷰 재요청주세요!
나머지는 Step2에서 진행하면 좋을 것 같습니다.

2023-02-11 04:53 UTC, HyeryongChoi commented on src/App.js
> +const CarGameController = require('./controllers/CarGameController');
index의 기능을 생각하지 못했네요 ㅠㅠ 찾아보니 프로그램의 진입점 역할을 하는 것 같아서 `npm start`를 했을 때 프로그램이 실행되도록 수정했습니다!

2023-02-11 05:19 UTC, HyeryongChoi commented on src/controllers/CarGameController.js
> +    return this.readTryCount();
‘이 메서드의 최종 반환값이 이 함수다’(다음 순서로 readTryCount가 실행된다)라는 걸 명확하게 해줄 수 있지 않을까 하여 `return`을 작성하였습니다.
그리고 또 다른 이유로는 페어와 이야기하면서 알게 된 내용인데요!
함수가 호출되면 Execution Context가 콜 스택에 하나씩 쌓이는 것으로 알고 있습니다.
다만 함수 내부에서 함수를 또 호출하면 Execution Context가 계속해서 쌓이게 될 텐데, 이렇게 되면 언젠가는 `Maximum call stack size exceeded` 오류가 발생할 것이라고 생각했습니다. 특히 이 게임에서 입력값을 잘못 입력하다보면 언젠가는 이 오류가 발생할 것이라고 생각했습니다. `return`을 쓰면 당장 현재 함수의 Execution Context는 pop 될 것이기에, `Maximum call stack size exceeded` 오류를 `InputView` 메서드 때문에 막을 수는 없지만 조금은 이 오류 발생을 늦출 수 있지 않을까 하는 생각이 들어 작성하였습니다!

혹시 이렇게 `return`을 사용하는 것이 안티패턴이라면 어떤 이유에서 좋지 않은 코드인지 궁금합니다!

2023-02-11 05:29 UTC, HyeryongChoi commented on src/utils/constants.js
> +  ENTER_CAR_NAME: '경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).\n',
사용자에게 친절하지 못한.. 프로그램을 만들었네요 반성합니다..🥹 자동차 이름은 영어, 한글, 숫자도 사용 가능하도록 수정해 보겠습니다!

2023-02-11 06:53 UTC, HyeryongChoi commented on src/utils/CarNameParse.js
> +function CarNameParse(str) {
아앗.. 이 부분은 `CarNameParser`를 함수로 바꾸면서 네이밍 컨벤션을 생각 안하고 바꿔버렸네요 ㅠㅠ.. `ParseCarName`으로 수정하겠습니다! 그리고 티케의 리뷰를 보고, 다시 생각해보니 제 생각에도 함수명에 `Car`가 들어간 이상 `CarNameParse`가 유틸성 함수와는 좀 거리가 있는 것 같네요! 이 부분도 수정해 보겠습니다~

2023-02-11 07:06 UTC, HyeryongChoi commented on src/controllers/CarGameController.js
> +        const parsedCarName = CarNameParse(input);
네이밍이 정말 중요하다고 생각하는데 막상 구현할 때는 놓치는 부분이 생기네요ㅜ 수정하겠습니다!

2023-02-11 07:41 UTC, HyeryongChoi commented on src/utils/Validator.js
> +class Validator {
`object`리터럴과 `class`의 차이를 잘 모르고 `class`의 `static`메서드는 인스턴스를 만들지 않고도 사용할 수 있기 때문에 `class`를 사용했는데요! 찾아보니 `object`리터럴 방식은 **정의함과 동시에 인스턴스가 자동 생성**되는 대신 **인스턴스를 여러 개 만들 수 없다**는 특징이 있네요..! `Validator`는 인스턴스를 여러 개 만들 필요가 없으니까 `class` 대신  `object`리터럴로 수정해보겠습니다!

2023-02-11 08:01 UTC, HyeryongChoi commented on src/models/CarGame.js
> +      this.#moveList.push([...moveData]);
참조타입인 배열에 의도하지 않은 값 변경이 일어나지 않도록 전달할 때 새로운 배열을 만들어 넘겨주었습니다!
`moveData`는 임시적인 데이터인데 복사본을 만들어 넘겨주는 것은 불필요한 로직일까요?

2023-02-11 08:28 UTC, HyeryongChoi commented
안녕하세요 티케! 꼼꼼하고 섬세한 코드리뷰 정말 감사드립니다.
우선적으로 반영할 코멘트들 먼저 코드에 반영했는데요~ 나머지 피드백은 step2에 반영하여 적용하도록 하겠습니다!
코드리뷰를 받고 리팩터링 하면서, 깊게 생각하지 못하고 넘어갔던 부분을 다시 되짚어보고 더 많이 배우는 것 같아서 너무 좋습니다😄

### 📝 코드리뷰 피드백 반영 목록
- [x] 가독성을 고려한 개행 추가
- [ ] CarNameParse 메서드명 수정 등 리팩터링
- [x] 네이밍 단수, 복수 고려하여 수정
- [ ] Validator object리터럴 방식으로 수정
- [ ] validateLength를 이름 하나의 길이를 검사하는 방식으로 수정
- [x] validateOverlap 메서드명 오타 수정
- [ ] validateInvalidInput 구체적인 역할이 나타나도록 메서드명 수정
- [x] 자동차 이름에 영어 뿐만 아니라 한글, 숫자도 사용 가능하도록 수정
- [x] -, : 등 불필요한 상수화 삭제
- [x] 불필요한 return 삭제
- [ ] functionPipe사용에 대한 코드 일관성 맞추기
- [ ] moveCars에서 내장함수를 사용하여 리팩터링
- [x] getMoveDatas메서드 중괄호 생략
- [ ] getWinners에서 Math.max 사용하여 리팩터링
- [x] numberToDistance에서 repeat사용하여 리팩터링

2023-02-11 08:31 UTC, HyeryongChoi commented on src/utils/numberTodistanceString.js
> +  }
너무 좋은 것 같습니다. 코드가 훨씬 간결해지네요😆

2023-02-12 10:43 UTC, devhyun637 approved these changes
안녕하세요 첵스~! 피드백 반영과 함께 반영한 목록을 정리해주셔서 감사합니다~ 제가 DM으로 보냈지만, 제가 월요일까지는(현지는 일요일이지만 한국시간으로 월요일에 돌아가서..) 리뷰에 대한 피드백과 질문에 대해서 자세히 읽고 답변을 달기 어려워, Step2미션에서 다시 이야기를 나눠보기로 해요! 첫 미션에서 크리티컬하게 기능이 안되거나 테스트에 문제가 있었던 건 아니라서 쭉 리팩토링을 해주시면 될 것 같습니다~ 그럼 Step2에서 만나요!

2023-02-12 10:43 UTC, merged

2023-02-12 16:50 UTC, HyeryongChoi commented on src/models/CarGame.js
> +    for (let count = 0; count < tryCount; count++) {
이 부분은 어떻게 바꿔야 할지 잘 모르겠습니다😭