[1단계 - 자동차 경주 구현] 타미(김태은) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #189
Opened 2023-02-09 08:46 UTC by xodms0309

안녕하세요, 레고와 함께 페어프로그래밍을 진행한 타미입니다.
지금까지 코드를 작성하면서 '패턴'을 고려해본 적이 없는데 이번 미션에서는 mvc 패턴을 적용해보았습니다. 이 부분에서 많은 피드백 주셨으면 좋겠습니다🙂

코드를 짜면서 궁금했던 점은
- 테스트를 하게 되면서 코드를 리팩토링 하게 되는 경우가 있는데 이런 행동이 괜찮은지 궁금합니다.
- 함수나 변수 네이밍을 쉽게 지을 수 있는 팁이 있을까요?

코드 리뷰을 통해 많이 얻어가고 싶습니다! 감사합니다 🙂

2023-02-11 10:10 UTC, InSeong-So requested changes
안녕하세요, 타미😁 리뷰어 파랑입니다.
패턴을 고려하여 클래스적인 설계, 객체 단위의 함수 집합을 구성하려는 시도가 많이 보였어요. 코드 잘 읽었습니다.

> 테스트를 하게 되면서 코드를 리팩토링 하게 되는 경우가 있는데 이런 행동이 괜찮은지 궁금합니다.
- 어느 시점에 구성하는 테스트냐에 따라 크게 차이가 있을 것 같고, 근본적인 답변으론 리팩토링이 이뤄지는 것은 수시가 되어야 하기 때문에 좋은 행동이라고 할 수 있습니다.
- 개발 전 테스트 케이스를 수립하여 "성공하는 테스트" -> "실패하는 테스트"로 이어지는 형태의 기능 구현이라면 당연히 리팩토링이 이뤄질 것이고, 개발 후 테스트 코드를 작성하는 것이라면 해당 함수를 리팩토링하면서 전체 앱의 구조가 크게 바뀌고 있지는 않은지 유심히 고찰해야 합니다.

> 함수나 변수 네이밍을 쉽게 지을 수 있는 팁이 있을까요?
- "내가 다른 사람의 코드를 읽을 때"를 고민하다보면 금방 컨벤션이 생길 거에요!
- 저는 보통 타입에 따라 네이밍을 결정하거나 용도를 생각한 컨벤션을 만들어 두었는데, boolean 타입인 경우 is, has, not, invalid, valid 등의 prefix를 가져가고 다른 원시 타입이면 "계산"에 초점을 맞추어 parse, generate, convert, fetch, action 등의 동사를 prefix로 가져갑니다. 그 외의 참조 타입은 원시 타입과 비슷하나 use, inject 등의 프레임워크 레벨에서 보편화된 명칭을 가져가는 편이에요.
- 현재는 한글 변수명을 적극적으로 도입하여 도메인 로직이나 API 통신 및 상수는 한글로, 그 외 컴포넌트 종속적인 로직은 앞서 말한 영어 변수명을 컨벤션에 맞게 작성하고 있답니다.

고생 많으셨습니다! 좋은 피드백이 되었으면 좋겠네요👍

2023-02-11 10:10 UTC, InSeong-So commented on src/View/OutputView.js
> +      );
템플릿 리터럴을 사용해보면 좋겠습니다. 해당 구문의 가독성을 높일 수 있을 것 같아요.
또한 사본 배열을 반환하는 map 함수보다는 forEach 같은 단순 반복 함수 등이 어떨까 싶습니다.

2023-02-11 10:10 UTC, InSeong-So commented on src/index.js
> +
App 클래스가 필요할까요? 컨트롤러 클래스의 역할을 갖고 있는 느낌이네요.

2023-02-11 10:10 UTC, InSeong-So commented on src/utils/Random.js
> +      );
이 함수는 유틸리티로 분리하여 `createRandomNumber`, `generateRandomNumber`로도 유용하게 쓸 수 있어보여요!

2023-02-11 14:30 UTC, xodms0309 commented on __tests__/Car.test.js
> +      mockQuestions(['aa,bb,cc', '3']);
오 그렇네요 ㅎㅎ 이렇게 리팩토링 해봤습니다
[81c9e7d](https://github.com/woowacourse/javascript-racingcar/pull/189/commits/81c9e7d69da8a742051f71ccceaeb605b022697a)

2023-02-11 14:31 UTC, xodms0309 commented on __tests__/Validation.test.js
> +  );
이렇게 리팩토링 해봤습니다!
[2cfdd35](https://github.com/woowacourse/javascript-racingcar/pull/189/commits/2cfdd35dea0cbd26c328e865465efe94d033fbcc)

2023-02-11 14:32 UTC, xodms0309 commented on src/Controller/Controller.js
> +  }
이렇게 하면 굳이 init을 만들어줄 필요가 없겠네요...! 이것도 수정했습니다!
[09f67ea](https://github.com/woowacourse/javascript-racingcar/pull/189/commits/09f67eaa3bd548f10a0dde2cbbc470f1dad37746)

2023-02-11 14:39 UTC, xodms0309 commented on src/Controller/Controller.js
> +  }
화살표 함수는 선언 될 때 this가 상위 스코프로 정해지기 때문에 객체가 주입되는 시점을 추론하지 않아도 되어서 화살표 함수를 사용하면 되는걸로 이해했는데 제가 이해한 바가 맞을까요?!
[4e1ecb7](https://github.com/woowacourse/javascript-racingcar/pull/189/commits/4e1ecb7666f8b18056f75678505b01450585dd03)

2023-02-11 14:40 UTC, xodms0309 commented on src/Model/Race.js
> +    }
저도 최대한 for, while문을 지양하려고 노력중인데 도저히 생각이 안나서 while문을 써버렸습니다 🥲 이번에 리팩토링 하면서 모두 map으로 바꿔봤습니다!
[48ff77d](https://github.com/woowacourse/javascript-racingcar/pull/189/commits/48ff77dffd5281c27676f1148324eb7180fb54a9)

2023-02-11 14:42 UTC, xodms0309 commented on src/Model/Race.js
> +    }, []);
이 부분도 윗 커밋에서 수정했습니다 :)

2023-02-11 14:43 UTC, xodms0309 commented on src/Validation.js
> +    }
early return 하니까 훨씬 더 가독성이 좋아지네요. Validation도 파랑이 주신 리뷰를 바탕으로 전체적으로 리팩토링 해봤습니다!
[8d1e3f5](https://github.com/woowacourse/javascript-racingcar/pull/189/commits/8d1e3f571217f5af6708e73821a97a12bbe81d37)

2023-02-11 14:43 UTC, xodms0309 commented on src/index.js
> +
실행을 위한 클래스입니다!

2023-02-11 14:44 UTC, xodms0309 commented on src/utils/Random.js
> +      );
이 부분도 이렇게 리팩토링 해봤습니다!
[e329673](https://github.com/woowacourse/javascript-racingcar/pull/189/commits/e3296736a97e9ef5c61d01b2b37cf79552c80d00)

2023-02-11 14:51 UTC, xodms0309 commented
안녕하세요 파랑! 리뷰를 읽으면서 제가 앞으로 코드를 작성하면서 들여야할 습관들을 많이 찝어주신 것 같아서 재미있게 읽고 리팩토링 해봤습니다. 제 질문들도 친절하게 답변 해주셔서 감사해요👍

2023-02-12 09:19 UTC, InSeong-So commented on src/Controller/Controller.js
> +  }
맞습니다☺ 그렇게 되면 bind 함수로 this 인스턴스를 주입하지 않아도 실행 시점에 추론할 수 있죠!

2023-02-12 09:20 UTC, InSeong-So commented on src/index.js
> +
실행을 위한 클래스이나, App 클래스가 갖고 있는 내부 메서드나 필드가 컨트롤러와 동일하기 때문에 불필요한 wrap으로 느껴진 것 같아요. 다음 스탭에서는 App 클래스가 좀 더 풍부한 기능을 갖는다면 좋겠습니다🤤

2023-02-12 09:22 UTC, InSeong-So approved these changes
피드백을 진행해준 내용으로 커밋을 링크해주셔서 편하게 읽었습니다☺
내부적으로 API 사용법이 많이 변경되었을텐데 고생 많으셨어요!

다음 스탭에서 뵙겠습니다💪

2023-02-12 09:22 UTC, merged