[2단계 - 자동차 경주 리팩터링] - 해온(백솔비) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #203
Opened 2023-02-12 13:54 UTC by hae-on

안녕하세요 카일! 
2단계 리팩터링을 하고 다시 올려봅니다..!
생각보다 오래 걸렸네요 🥲

1. get과 set을 사용해보았습니다.
2. model 파일명을 domain으로 변경하였습니다. 
3. jest.fn()을 사용한 테스트를 모두 삭제하였습니다.
4. 1단계 요구사항에서 빠진 부분(사용자가 잘못된 입력 값을 작성한 경우 에러 메시지를 보여주고, 다시 입력할 수 있게 한다)을 추가하였습니다.
5. 불필요한 주석을 삭제하였습니다.

크게 이정도로 수정해보았습니다!
이번에도 잘 부탁드립니다~☺️

2023-02-13 13:29 UTC, GwangYeol-Im requested changes
2단계 미션도 수고 많으셨습니다, 전반적으로 레이어에 대한 고민이 많이 담긴 코드로 보입니다. 👍

코멘트에도 남겨두긴 했지만, 하나의 파일 안에서 메서드는 일관된 추상화의 흐름으로 읽히는 것이 이해하기 좋을 듯합니다. 위 -> 아래 혹은 아래 -> 위 방향은 스타일 차이라 어떻게 쓰여도 상관 없으니 일관성만 잘 지켜주시길 바랍니다 :)

2023-02-13 13:29 UTC, GwangYeol-Im commented on src/controller/RacingController.js
> +      this.#racingGame.tryCount = tryCount;
여기도 마찬가지로 유효성 검사전에 set을 해주고 있군요 🤔

2023-02-13 13:29 UTC, GwangYeol-Im commented on src/domain/RacingGame.js
> +  makeCarsNameList(cars) {
`carName`이 아닌 `car` 자체를 set해주는 역할 아닐까요~?

2023-02-13 13:29 UTC, GwangYeol-Im commented on src/utils/InputValidator.js
> +  }
가급적 함수의 추상화 정도를 일관된 흐름으로 작성하시는 것을 추천드립니다. 어떤 함수가 어떤 함수를 사용하는지 순서가 일관되지 않으면 코드를 읽는 입장에서 참조되는 곳을 계속 찾아가면서 논리의 흐름을 추론해야하기 때문입니다!

2023-02-13 13:29 UTC, GwangYeol-Im commented on src/domain/RacingGame.js
> +  set tryCount(tryCount) {
단순히 setter 처리에서 그치지 않고 이곳에서도 예외처리를 해주면 더 안정성을 높일 수 있을 것 같아요. 사용자의 입력과 관련된 메서드 같은 경우는 그 입력값을 예상할 수 없기 때문에 더욱 꼼꼼한 예외처리가 요구되는 경우가 잦습니다~

더군다나 현재 구현해주신 로직 방향에서는 유효성 검사 전에 `tryCount`가 들어올 것이기 때문에, 실제 앱이라면 런타임 에러를 던질 가능성이 있습니다.

2023-02-14 04:30 UTC, hae-on commented
1. InputValidator의 메서드 순서를 바꾸어보았습니다.
2. 유효성 검사 이후 set을 하도록 순서를 바꾸어보았습니다.
3. makeCarsNameList의 메서드를 set car로 바꾸어보았습니다.

유효성 검사를 하고 set을 해주는게 좋은 방향이었는데 일단 형식을 맞추고 유효성 검사를 해야한다는 생각에 이렇게 짜게 된 거 같아요! 
어떻게 작성을 해야 더 논리적인 코드인지 알게 될 수 있었던 시간이었습니다!
알맞게 고친지 모르겠지만 혹시 잘못 고친거라면 또 말씀해주세요! 감사합니다~~😄

2023-02-14 11:26 UTC, merged