[2단계 - 자동차 경주 리팩터링] - 루루(송지은) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #221
Opened 2023-02-13 03:56 UTC by hafnium1923

안녕하세요 헤인티! 좋은 점심 보내시고 계신가요?!😊 
2단계 요구사항이랑 1단계에서 말씀하신 부분 고쳐보았어요!

1. App 은 한 프로그램(서비스) 가 어떻게 작동하는지를 명확히 나타내야 해요! 
> 저는 이것을 시작 버튼이 있어야 한다고 해석해서 컨트롤러를 따로 파일로 만들었고 App의 play()에서 컨트롤러의 start()를 호출하게 만들었어요. index에서는 프로그램을 실행할 수 있도록 코드를 넣었구요! 이렇게 하는게 맞을까요?

2. 2단계에서는 에러 메세지를 좀 더 세분화해보면 어떨까 싶습니다!
>유효성을 검사하는 부분을 좀 더 세분화 시켰습니다. 한대만 입력되었을 때, 같은 이름을 입력했을 때 경우를 추가했고 inputView의 reject부분에서 에러를 보내면서 해당 경우 별 메시지를 같이 보내도록 해보았어요!

2단계 요구사항
-  도메인 로직은 domain/ 하위로, UI 관련 로직은 view/ 하위에서 관리한다.
- domain/ 하위의 모듈은 view/ 하위의 모듈을 의존하지 않아야 한다.
- 도메인 로직 내에서 테스트하기 어려운 부분을 분리하고, 테스트 가능한 부분에 대해서만 단위 테스트를 작성한다.
- 테스트 코드에서 jest.fn()을 사용하지 않는다.
>이 부분은 1단계 리팩터링 하면서 고쳐진 것 같아서 코드 확인만 진행했어요.

이번 리뷰도 잘 부탁드리겠습니다! 감사해요😍😍

2023-02-13 15:24 UTC, HyeonaKwon requested changes
루루 안녕하세요! 2단계는 순탄하게 진행되셨나요? 😊  
App.js 관련 이야기는 나중에 React 를 경험한 후에 이해가 되실거예요! 요렇게 경험하신 것도 아주 좋습니다!

제가 남긴 코멘트만 확인 부탁드립니다! 고생 많으셨어요~!

2023-02-13 15:24 UTC, HyeonaKwon commented on __tests__/CarValidation.test.js
> +  test("자동차 이름이 중복도면 안된다", () => {
```suggestion
  test("자동차 이름이 중복되면 안된다", () => {
```

:smiley:

2023-02-13 15:24 UTC, HyeonaKwon commented on src/controller/CarRaceController.js
> +class carRaceController {
```suggestion
class CarRaceController {
```

클래스명은 파스칼케이스로 네이밍해주세요~!

2023-02-13 15:24 UTC, HyeonaKwon commented on src/controller/CarRaceController.js
> +  async start() {
`#` 을 제거한 이유는 무엇일까요?

2023-02-13 15:24 UTC, HyeonaKwon commented on src/domain/ErrorHandler.js
> +    return false;
```suggestion
    return cars.length === 1;
```

2023-02-13 15:24 UTC, HyeonaKwon commented on src/domain/ErrorHandler.js
> +    return false;
이 친구도 간단하게 고쳐볼까요?

2023-02-13 15:24 UTC, HyeonaKwon commented on src/domain/ErrorHandler.js
>      return true;
마찬가지예요!

2023-02-13 15:24 UTC, HyeonaKwon commented on src/index.js
> +new App().play();
EOF 발생하지 않도록 prettier 적용해볼까요?

2023-02-13 15:24 UTC, HyeonaKwon commented on src/constant/Constant.js
> +  carTextError: "[ERROR] 자동차 이름은 1자 이상 5자 이하로 입력해주세요.\n",
관련 테스트코드 추가 부탁드립니다~!

2023-02-14 01:46 UTC, hafnium1923 commented on src/controller/CarRaceController.js
> +class carRaceController {
넵! 알겠습니다!

2023-02-14 01:48 UTC, hafnium1923 commented on src/controller/CarRaceController.js
> +  async start() {
app.play에서 start를 호출하게 구현해서놔서 삭제했습니다..

2023-02-14 01:59 UTC, hafnium1923 commented on src/constant/Constant.js
> +  carTextError: "[ERROR] 자동차 이름은 1자 이상 5자 이하로 입력해주세요.\n",
유효성 테스트 파일에 
'자동차 이름이 다섯글자를 넘어서면 유효한 값이 아니다' 와
'자동차 이름 입력이 없으면 유효한 값이 아니다'
로 유효성 테스트를 넣었는데 정상기능 테스트를 말씀하시는 걸까요?!

2023-02-14 02:17 UTC, hafnium1923 commented
마지막 테스트 코드에 대한 부분만 빼고 다른건 다 반영했습니다! 이번 리뷰도 감사드립니다😍

2023-02-14 14:53 UTC, HyeonaKwon approved these changes
EOF 막기위해 프리티어 config 파일같은걸 추가하기를 기대했는데 아니었네요! 🥲
다음 미션에서는 컨피그 파일 추가해보시면 좋을 것 같아요! 
1단계 미션 구현하느라 고생하셨습니다~!

2023-02-14 14:53 UTC, merged