Step2 PR test
woowacourse/javascript-racingcar pull request #231
Opened 2023-02-13 06:04 UTC by ukkodeveloper

2023-02-13 15:54 UTC, HyeonaKwon requested changes
우코 안녕하세요! 코드 가독성이 많이 좋아진 것 같네요 :+1:

코멘트에 리뷰 남겼고 전체적인 리뷰만 정리해볼게요!

#### 질문
1. 우와 우코! 너무 좋은 학습의 방향이에요! 적어주신 내용 모두 다 좋습니다 ㅎㅎ 일단 private 이 필요한 이유를 생각해볼까요? 우코가 예시로 말씀하신 private position 의 경우 number 타입으로 position 값을 외부에 알려준다고 해서 외부에서 position 을 고칠 수는 없습니다! setter 가 있지 않은 이상 말이에요. 하지만 private 객체의 경우 getter 를 통해 객체를 알려주면 주소를 알려준 것이기 때문에 고칠 수 있겠죠?  
[primitive type](https://developer.mozilla.org/en-US/docs/Glossary/Primitive) 같은 것도 학습해보면 좋을 것 같네요!  
결국 멤버변수 자체가 private 인지가 중요한게 아니라 getter 와 setter 를 어떻게 구현하는지도 중요하다는 말을 전하고 싶습니다.

2. 바깥에서 사용하지 않는 메소드니 모두 private 으로 만들자! 가 과연 좋은 방향일까요? 바깥에서 메소드를 사용하는 곳이 없지! 가 아니라 바깥에서 메소드를 사용하면 안되지! 가 되어야하지 않을까요? 이렇게 생각해보면 멤버함수를 어떻게 관리해야할지 규칙을 정할 수 있을 것 같네요!

3. 오 아직은 간단한 프로그램을 구현하셔서 차이를 잘 못 느끼실 것 같아요! 아래의 예시만 해도 두 네이밍을 다르게 할 수 있습니다. 앞으로 더 많은 미션들이 있으니 해당 미션들에서 직접 경험하시는게 좋을 것 같아요!
```javascript
const human = new Human();
const redCar = new Car({color: 'red' });
const blueCar = new Car({color: 'blue' });

human.buyCar(redCar);
human.buyCar(blueCar);

// Human class 내 buyCar 함수
buyCar (targetCar) {
  this.cars.push(targetCar);
}
```

#### 리뷰
1. 전체적으로 EOF 를 방지하기 위한 방법을 추가 부탁드립니다.
5. 전체적으로 에러를 발생시키는 메소드에 대한 처리가 없는 것 같습니다. "제 코드 상으로는 에러를 발생한다해도 에러를 발생시키는 곳이 없어요!" 라고 말하는건 개발자로서 책임감이 없는 것 같아요! 우코가 개발한 후 해당 서비스를 다른 사람이 인수인계 받아 구현하는 과정에서 생각지 못한 에러가 추가될 수 있어요! 휴먼에러는 어디에서나 존재하니까요. 그래서 애초부터 에러처리를 추가하고 진행하는게 좋습니다!

2023-02-13 15:54 UTC, HyeonaKwon commented on __tests__/InputValidator.test.js
> +    });
toThrow() 가 빠진 것 같네요?!

2023-02-13 15:54 UTC, HyeonaKwon commented on src/controller/Controller.js
> +    this.#racingCarGame = new RacingCarGame(carNameList, numberOfTrials);
여기서 발생한 에러는 누가 책임질까요?

2023-02-13 15:54 UTC, HyeonaKwon commented on src/model/ResultContainer.js
> +module.exports = ResultContainer;
EOF 해결할 수 있는 방법을 추가해주세요~!

2023-02-13 15:54 UTC, HyeonaKwon commented on src/model/RacingCarGame.js
> +    return new ResultContainer(roundResultList, winnerList);
여기서 발생하는 Error 는 누가 책임질까요?

2023-02-13 15:54 UTC, HyeonaKwon commented on src/model/ResultContainer.js
> +module.exports = ResultContainer;
생성자만 존재하는 클래스가 있어야하는 이유가 있을까요? 객체나 함수를 사용하지 않고 클래스를 사용할 때는 언제일까요?

2023-02-13 15:54 UTC, HyeonaKwon commented on src/view/InputValidator.js
> +    }
세 가지 validation 을 통과했을 때는 validateCarNameList 을 사용하는 사용처에게 성공했다고 알려줘야 하지 않을까요? return 값을 활용해볼까요?  

그리고 함수에서 아무것도 리턴하지 않았을 때는 어떤 값이 return 될까요?

2023-02-13 15:54 UTC, HyeonaKwon commented on src/view/InputValidator.js
> +    }
이 함수도 마찬가지입니다!

2023-02-13 15:54 UTC, HyeonaKwon commented on src/view/OutputView.js
> +    }
이 에러는 누가 책임질까요?

2023-02-14 13:14 UTC, ukkodeveloper commented
> 전체적으로 에러를 발생시키는 메소드에 대한 처리가 없는 것 같습니다. "제 코드 상으로는 에러를 발생한다해도 에러를 발생시키는 곳이 없어요!" 라고 말하는건 개발자로서 책임감이 없는 것 같아요! 우코가 개발한 후 해당 서비스를 다른 사람이 인수인계 받아 구현하는 과정에서 생각지 못한 에러가 추가될 수 있어요! 휴먼에러는 어디에서나 존재하니까요. 그래서 애초부터 에러처리를 추가하고 진행하는게 좋습니다!

피드백 주신 내용이 명확히 이해가 되지 않습니다. 에러를 던지는 코드는 있는데 try catch 로 처리를 하지 않아서 문제인 것인지, 다양한 곳에서 에러가 발생할 수 있으니 중복해서 재차 에러 검증을 하라는 것인지 모르겠습니다.

따라서 코드에 대한 추가 설명을 드리자면, TypeError 메세지를 인자로 받는 Error 객체의 경우는 개발자에게 알리기 위한 에러라고 생각하고 만들었습니다. 즉, 만약 이러한 클래스 혹은 자료구조의 데이터를 받지 않는다면 이 함수는 어차피 제 기능을 못 할 것이니 진작에 차단하는 것이죠. 마치 Math.max()에 배열을 넣으면 안되는 것처럼 말입니다. 

무얼 보고 만든 것이 아니라 이러한 방식이 확실하진 않지만 제가 에러를 발생시키는 코드에 대한 의도를 알려드리고 싶었습니다. 빌드조차 되지 않아야 런타임이 아닌 컴파일 단계에서 잘못되었음을 알려줄 수 있기 때문에 따로 에러 핸들링은 하지 않은 것입니다. 

그리고 코드 리뷰해주신 거 정말 감사합니다. 주말동안 계속 private과 객체, 그리고 테스트코드에 대한 생각 때문에 고민이었는데 많은 부분 정리가 된 것 같습니다. 에러에 관한 피드백도 조금만 설명 덧붙여주시면 정말 감사하겠습니다!!! 감사해요!

2023-02-14 13:16 UTC, ukkodeveloper commented on src/view/InputValidator.js
> +    }
inputView에서 보시면  this.#inputValidator.validateNumberOfTrials(numberOfTrials); 이 함수에서 해당 에러는 처리하는 걸로 알고 있습니다. 혹시 제 생각이 다르다면 다시 말씀해주시면 감사하겠습니다.
```js
static async readNumberOfTrials() {
    try {
      const input = await Console.question(INPUT_MESSAGE.numberOfTrials);
      const numberOfTrials = this.#preprocessNumberOfTrials(input);
      this.#inputValidator.validateNumberOfTrials(numberOfTrials);
      return numberOfTrials;
    } catch (err) {
      Console.print(err.message);
      return this.readNumberOfTrials();
    }
  }
```

2023-02-14 15:05 UTC, HyeonaKwon commented on src/controller/Controller.js
> +    this.#racingCarGame = new RacingCarGame(carNameList, numberOfTrials);
윗 두줄(16~17) 이 아니라 18라인의 RacingCarGame 생성자에서도 에러를 던지고 있는데 해당 에러는 누가 잡느냐는 이야기였습니다!

2023-02-14 15:11 UTC, HyeonaKwon commented on src/model/ResultContainer.js
> +module.exports = ResultContainer;
아하! 타입을 지키고 싶었다 이 말씀이시군요?! 요거는 추후에 typescript 를 적용하게 되면 자연스럽게 해결되긴 하겠네요. 다만 생성자 내부에서 this 에 속성을 추가하고 계신데요, 클래스의 경우 멤버변수가 어떤 것들이 있는지 한 눈에 알아볼 수 있게 생성자 위에 멤버변수를 선언해주었으면 더 좋았을 것 같습니다!

2023-02-14 15:19 UTC, HyeonaKwon commented on src/view/InputValidator.js
> +    }
제가 생각한 것도 return true 였는데요, 우코가 적어주신 내용 읽어보니 타당성 있군요! 왜냐면 유효성 검사 함수는 if 문에서 컨디션 체크 값으로 사용할 때가 많으니 boolean 값을 리턴해주는게 좋지 않을까 싶었습니다.

2023-02-14 15:19 UTC, HyeonaKwon commented on src/view/InputValidator.js
> +    }
요것도 return 값에 대한 이야기였습니다!

2023-02-14 15:22 UTC, HyeonaKwon approved these changes
안녕하세요 우코! 코멘트 남겨주신거 모두 확인했습니다 :)
에러처리의 경우 다시 코멘트 남긴대로 의도적으로 남겨주신 에러에 대한 이야기였는데요! 과연 그게 다른 개발자가 잘못 사용한다고 해서 빌드타임에 잡힐지는 모르겠네요?! 아직은 typescript 가 아닌 javascript 이니 말이죠.
남긴 코멘트 봐주시면 될 것 같구, 공부하신 내용 / 우코 생각 정리해서 남겨주셔서 감사해요. 덕분에 저도 생각해볼 수 있는 주제들이 되었습니다! 고생 많으셨어요 👍

2023-02-14 15:23 UTC, merged

2023-02-14 23:28 UTC, ukkodeveloper reviewed
이번 미션 피드백해주셔서 정말 감사합니다. 프리코스동안 생각했던 거, 궁금했던 거를 최대한 구현해서 물어봐야겠다고 생각했는데 기대보다 더 더 많은 걸 얻었던 것 같아요! 다음에 또 뵐 수 있었으면 좋겠습니다. 감사해요

2023-02-14 23:28 UTC, ukkodeveloper commented on src/model/RacingCarGame.js
> +    return new ResultContainer(roundResultList, winnerList);
생각해보니 javascript는 트랜스파일(컴파일) 단계가 없다보니 바로 런타임이네요...! 제가 생각이 짧았습니다. 말씀해주신대로 타입스크립때 적용해보도록 하겠습니다.

2023-02-14 23:28 UTC, ukkodeveloper commented on src/controller/Controller.js
> +    this.#racingCarGame = new RacingCarGame(carNameList, numberOfTrials);
이해했습니다!! 제가 완전 잘못 이해하고 있었군요!