[1단계 - 자동차 경주] 마스터위(명재위) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #255
Opened 2024-02-15 08:11 UTC by Jaymyong66

2024-02-15 22:58 UTC, GwangYeol-Im requested changes
안녕하세요 마스터위~ 전반적으로 각 레이어의 성격을 잘 분리해서 코드를 작성하려고 노력하신 부분이 인상 깊었습니다 👍 세부적인 리뷰는 코멘트 확인 부탁드리고 질문에 대한 답변 남기고 마무리 할게요!

질문의 2, 3, 4번은 이렇게 작성해주신 의도를 첨부해주시면 좋을 것 같습니다. 코드를 작성하는 방식에 획일화된 정답은 없기 때문에 본인이 생각하신 바를 토대로 상대방을 설득한다는 마음으로 고민해보면 좋을 것 같습니다.

> 처음 개발 환경 설정 시, eslint 에러로 작동하지 않았습니다.
eslint-plugin-prettier의 버전과 현재 pakage.json의 prettier의 버전이 맞지 않아 최근 버전으로 올렸습니다. 혹시 이럴 때, 의존성 문제를 어떻게 해결하는지 궁금합니다. (prettier를 최근 버전으로 올리는 것이 제한될 경우)

문제의 원인이 라이브러리의 버전 간 호환성이 맞지 않아 의존성 문제가 생기는 것이니 한 쪽을 내리든, 다른 한 쪽을 올리든 두 라이브러리의 호환성을 맞춰주는 것이 주된 해결책이라고 보여집니다. 그래서 지금처럼 대처해주신 방향이 괜찮다고 생각이 드네요!

> 파일 구조를 어떻게 잡아야 할지에 대한 고민이 많았습니다. ... 이러한 로직을 Race 도메인에 두는 것보다 RaceService를 추가해 분리하는 것이 낫다고 판단하였습니다. 다만 한 파일에 두는 것보다 다른 파일을 열어 같이 보아야 한다는 것에서 가독성 문제가 있지 않나 생각했습니다.

의도하신 바와 같이 분리하는 것도 나쁘지 않아보입니다. 다만 두 개 이상의 파일을 열어보는 것에 가독성이 우려되신다면 관련성이 높은 코드끼리는 한 파일에 두면 되지 않을까 싶습니다.

2024-02-15 22:58 UTC, GwangYeol-Im commented on __tests__/domain/Car.test.js
> +    const randoms = [MOVING_FORWARD, MOVING_FORWARD, STOP, STOP];
다른 곳에서도 이 값을 쓰는 경우가 있어 보이는데, 재사용을 위한 관리가 필요하지 않을까요? 만일 `test` 폴더 내에서만 필요한 상수라면 이 폴더 내에 `constants`를 만들어 관리하는 것도 방법이 될 것 같습니다.

2024-02-15 22:58 UTC, GwangYeol-Im commented on src/domain/Car.js
> +  }
차가 움직이는 조건은 race 내의 규칙으로 볼 수 있기 때문에 `Car`는 움직이는 책임만을 가지고 이것을 언제 움직일지는 외부에서 결정을 해주는 것이 자연스러울 것 같습니다!

2024-02-15 22:58 UTC, GwangYeol-Im commented on src/statics/messages.js
- 개행 (\n)이나 error prefix ([ERROR])는 메시지와 분리해서 사용해도 괜찮을 것 같다는 생각이 드네요~ 메시지 변경 시 좀 더 유연하게 대처할 수 있지 않을까 싶습니다.
- 메시지 내에서도 상수화를 해봄직한 값들이 존재하는 것 같은데 template literal을 이용해 처리해보는 건 어떨까요?

2024-02-15 22:58 UTC, GwangYeol-Im commented on src/utils/retryOnInvalidInput.js
> +export const retryOnInvalidInput = async func => {
좋은 시도네요 👍

2024-02-15 22:58 UTC, GwangYeol-Im commented on src/utils/Random.js
> +  static #validateRange(min, max) {
static private field로 선언하신 의도가 궁금하네요!

2024-02-15 22:58 UTC, GwangYeol-Im commented on src/service/RaceService.js
> +class RaceController {
클래스명과 파일명을 맞춰줘야할 것 같아요~

2024-02-15 22:58 UTC, GwangYeol-Im commented on src/service/RaceController.js
이 파일과 `/domain/Race.js`를 나눈 건 좋지만 단순 계산 로직을 맡는 객체의 이름이 `RaceController`인 것은 조금 어색해보입니다!

2024-02-16 11:12 UTC, Jaymyong66 commented on __tests__/domain/Car.test.js
> +    const randoms = [MOVING_FORWARD, MOVING_FORWARD, STOP, STOP];
[테스트 코드 상수화 커밋](https://github.com/woowacourse/javascript-racingcar/pull/255/commits/44797d05ec524c3520622a25720e6d0a988eda76)과 [테스트 코드 상수 파일 분리, randomCase 상수화 커밋](https://github.com/woowacourse/javascript-racingcar/pull/255/commits/4dd29da2efc033deaade073e0f752dfa8d8cd55d) 을 통해 수정해보았습니다!

2024-02-16 11:16 UTC, Jaymyong66 commented on src/statics/messages.js
다음 두 커밋을 통해 변경해보았습니다. [error message의 error prefix를 메시지와 분리](https://github.com/woowacourse/javascript-racingcar/pull/255/commits/5871ce86ccd7e698ae7eb25cbf8239344c93445a), [메시지 내에서 template literal 적용](https://github.com/woowacourse/javascript-racingcar/pull/255/commits/3ac38327236a1a677e2c9739841669de0d1ee8b2)

다만 제가 변경한 것이 말씀해주신 의도와 같은 부분인지는 확실하지 않네요.. 혹시 아니라면 한번만 다시 알려주시면 감사하겠습니다!
개행을 메시지와 분리하여 사용한다는 것도 제대로 이해한 것이 맞는지 모르겠습니다..!

2024-02-16 11:18 UTC, Jaymyong66 commented on src/service/RaceService.js
> +class RaceController {
[RaceService 클래스명과 파일명 일치시키기](https://github.com/woowacourse/javascript-racingcar/pull/255/commits/d661c8d08c5e1cc285910d1e6ff992e7d60f4871) 에서 반영하였습니다. 감사합니다!

2024-02-16 11:19 UTC, Jaymyong66 commented on src/service/RaceController.js
[RaceController 파일명을 RaceCalculator로 변경 후 도메인 폴더 하위로 이동](https://github.com/woowacourse/javascript-racingcar/pull/255/commits/872d8e49f7b67623709ad76f1f25889adca50a28)
처럼 변경해보았습니다. 
도메인 관련 연산을 한다고 생각하여 폴더 이동 또한 하였습니다.

2024-02-16 11:39 UTC, Jaymyong66 commented
안녕하세요 카일!
저도 보지 못했던 세세한 클래스명도 봐주시다니.. 정말 꼼꼼히 리뷰해주신 것 같아 너무 감사드립니다. 먼저 이전에 남겼던 질문에 대한 보충 설명을 하고, 코멘트에 답변을 해보도록 하겠습니다! 

Car객체의 move 함수를 Race로 옮기는 과정에서 테스트 코드에 대해 발생한 의문에 대해서는 좀 더 정리하여 전달드리겠습니다.
살펴보니 2단계 리뷰에서 관련 내용을 건드리는 것 같더라구요! 
우선은 리뷰 요청 드리고 주말에 더 정리해보는 것으로 마무리해도 될까요?! 😎

좋은 주말 보내시길 바랍니다~!

> 최종 코드에선 validator들을 한 파일에서 관리하도록 하였습니다.
> 고민했던 사항은 관련 validator를 해당 Car 또는 Race 도메인에 함께 넣는 것이 좋을지에 대한 조언을 주시면 감사합니다!
 다음 질문을 드린 이유는 가독성과 추후 유지보수 측면에서 어떻게 하는 것이 편할지였습니다. 제 생각에는 validator의 로직을 모아두는 것이 다른 도메인 클래스가 추가되었을 때, 재사용성 측면에서 용이하다고 생각하였기 때문입니다.

> 현재는 도메인을 단위테스트, 전체 기능테스트를 작성하였습니다. 해당 방향으로 테스트 코드를 작성하는 것이 맞는지 궁금합니다.
다음 질문은 어떤 부분을 테스트를 해야할지 정하는 것이 어려웠습니다. 따라서 우선은 하나의 기능을 테스트 한다는 생각으로 테스트를 나누어 했던 것 같습니다. 테스트 코드를 만들 때, 어떤 기준으로 어느 부분을 테스트하는지, 테스트의 범위에 대한 기준 같은 것이 있는지 궁금했습니다.

> RaceService의 gameCycleStart 매서드에서 MVC 패턴을 지키기 위해 OutputView 함수를 사용하긴 했지만 실제 실행은 Race객체에서 실행되는 것 같습니다. 이렇게 사용하는 것이 맞는지, 이런 경우 어떻게 하면 좋을지 조언을 구하고 싶습니다.
MVC 패턴에서는 View를 호출하는 것이 Controller에서만 이루어진다고 알고 있습니다. 하지만 코드를 만들다보니 Model에서 View를 호출해야할 것 같았고, 이를 우회하기위해 Controller에서 View 함수를 Model로 콜백함수로써 넘겨주는 방식으로 해보게 되었습니다.
하지만 실제 실행은 Model에서 이루어지보니 이렇게 하는 것이 MVC 패턴에 위배되는 것인가? 과연 이렇게 해결해도 되는 것인가? 를 생각하게 되었습니다.

2024-02-17 05:07 UTC, Jaymyong66 commented on __tests__/domain/Car.test.js
> +    const randoms = [MOVING_FORWARD, MOVING_FORWARD, STOP, STOP];
저도 테스트코드도 코드다! 라는 말을 되새기게 되었네요..! 감사합니다.

2024-02-17 05:21 UTC, GwangYeol-Im approved these changes
안녕하세요 마스터위! 전반적으로 PR 코멘트를 통한 커뮤니케이션에 능숙해보이시네요. 덕분에 의견 주고받는 것이 어렵지 않았던 것 같습니다. 😀 해당 PR은 머지하려 하고 나머지 수정사항은 다음 단계에서 반영해주세용

> Car객체의 move 함수를 Race로 옮기는 과정에서 테스트 코드에 대해 발생한 의문에 대해서는 ... 우선은 리뷰 요청 드리고 주말에 더 정리해보는 것으로 마무리해도 될까요?! 😎

2단계 리뷰 요청 때 작성해주시면 될 것 같아요!

> validator 관리 방향

파일 관리를 할 때 비슷한 성격을 가진 함수를 모아둘지, 관련성이 높은 코드들을 한 도메인에 모아둘지에 대한 고민을 하고 계신 듯 보이네요. 이럴 땐 100개의 도메인에 대한 validator를 하나의 파일/폴더에서 관리하는 상황을 상상해보시면 어느정도 결정을 내리기 수월할 듯 싶습니다.

- 추천 키워드 - frontend feature based folder structure

> 단위 테스트의 범위

테스트 범위라는 건 명확한 답이 있지 않은 부분이지만, 저는 단위 테스트의 효용성이 '작은 단위의 여러 테스트 케이스를 만들어두고 해당 커버리지를 높여 전체 앱의 안정성을 도모하는 부분'에서 온다고 생각합니다. 때문에 전체의 기능을 테스트하거나 시각적인 테스트를 원한다면 그에 맞는 다른 테스트를 시도해볼 수 있을 것 같아요. 우선 단위 테스트 방법론 외에 다른 테스트는 무엇이 있을지 비교해보시면서 해당 테스트에서 보고자하는 것이 무엇인지 학습해보시는 것을 추천드립니다.

- 추천 키워드 - e2e test, snapshot test, api mocking test

> 패턴에 대한 생각

어떤 객체의 동작 후에 수행되어야할 로직을 콜백 함수로 넘겨 호출을 위임하는 방식은, 레이어 간 책임영역을 섞지 않으면서 원하는 바를 충족시킬 수 있는 방식입니다. 호출이 어디에서 되었건 실제로 `OutputView`를 알고 있는 곳은 콜백으로 넘겨주는 곳이기 때문입니다.

그보다는 특정 패턴에 갇히는 사고방식을 경계하고 책임의 분리, 클린 코드에 대한 생각을 바탕으로 유연하게 코드를 짜보시는 것이 현재 단계에서 필요한 부분이 아닐까 싶습니다 :)

2024-02-17 05:22 UTC, merged