[1단계 - 자동차 경주] 월하(남수민) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #266
Opened 2024-02-15 08:31 UTC by vi-wolhwa

## 📌 개발 중 주요 이슈

> ### 에러 발생 시 에러 메시지 출력 후 재 입력을 받는 기능
> `while`문과 `try-catch`를 사용하여 재 입력 기능을 구현하였습니다. 함수를 분리하기 위하여 `retryAndErrorLogging(callback)` 함수를 구현하였습니다. 콜백 함수의 `this`가 바인딩 되지 않는 문제가 발생하였고, 명시적 바인딩(`.bind(this)`)을 통해 해결하였습니다. 문제 발생 원인에 대하여 공부할 예정입니다.

</br>

## ❓개발 중 궁금한 점

> ### private 함수에서 this를 사용해야 하는 이유
> eslint는 `private` 함수에서 `this`를 사용하도록 권장합니다. 기능을 여러 작은 함수로 분리하다 보면 클래스 내부에서만 사용되는 '작은'  함수가 만들어집니다. 하지만 eslint는 이를 에러로 처리합니다.

</br>

> ### while(true) vs 재귀 호출
> eslint는 무한루프의 사용을 지양하고 있습니다. 저는 '에러메시지 출력 후 재입력' 기능을 구현할 때, `while(ture)`에서 `try-catch`를 사용하였습니다.  그러나 이 기능을 재귀호출로 구현하면 사용하면 스택메모리가 소비될 것이라고 생각합니다. `while(true)`에 대한 의견을 듣고 싶습니다. 

</br>

> ### 유효성검사를 수행하는 위치
> 유효성검사를 `Model`에서 수행해야 하는지, 값을 전달하기 전 `Controller`에서 수행해야 하는가에 대한 주장이 분분하여 리뷰어 분들의 의견을 듣고 싶습니다.

2024-02-15 13:39 UTC, uk960214 requested changes
안녕하세요 월하! 우선 우테코 첫 미션에 발을 떼신 것 너무 축하드립니다! 🎊 

저는 이번에 리뷰어를 맡게 된 블링이라고 합니다! 잘 부탁드려요 🙇 !

# TLDR
전반적으로 코드도 깔끔하고 관심사 분리도 명확하다는 생각이 들었어요!
몇 가지 고민해봤으면 하는 부분들이 있는데 분명 금방 좋은 답변을 찾으실 것 같아요!

## 👍 이런 점이 좋았어요.
- 도메인과 입/출력의 명확한 분리가 되어있다고 느꼈습니다.
- 함수가 짧고 간결해서 이해하기 어렵지 않았습니다.
- 커밋을 매우 잘 나누어주셔서 하나씩 살펴보기 좋았습니다.
- 커밋을 따라가다보니 컨벤션에 맞추기 위해서 리팩토링 한 모습들이 보여서 좋았습니다.

## 🤔 이런 점을 더 고민해볼까요?
- 테스트를 작성하는데 조금 더 고민을 해보면 어떨까요?
- `현재 미션을 위해서 필요한만큼`이 어디까지일지 고민해봐도 좋을 것 같아요.

## ❓ 질문에 대한 답변
나머지 답변들은 코드에 코멘트 달았습니다!

> 유효성검사를 수행하는 위치
유효성검사를 Model에서 수행해야 하는지, 값을 전달하기 전 Controller에서 수행해야 하는가에 대한 주장이 분분하여 리뷰어 분들의 의견을 듣고 싶습니다.

아마 Model과 Controller가 어떤 역할을 하는지 고민을 해보다보면 조금 더 명확해지지 않을까 생각합니다. 월하는 어떤 기준으로 이런 구조로 미션을 구현하신걸까요? (답변이라 해놓고 질문을 하고 있네요 😅)

----

첫 미션 하시느라고 너무 고생 많으셨습니다!
사실 Approve를 해도 될 것 같지만 첫 미션인데 조금 더 질문과 답변의 기회가 없으면 아쉬우니까
시간 되시는 만큼만 코멘트 확인해주시면 좋을 것 같아요! 화이팅입니다!

2024-02-15 13:39 UTC, uk960214 commented on __tests__/CarGame.test.js
테스트 케이스가 충분한지, 테스트의 이름이 테스트하고자 하는 항목을 명확하게 나타내고 있는지, 테스트하기 위해서 사용하고 있는 샘플이 테스트의 목적을 잘 충족하는지 확인해보면 좋을 것 같아요!

2024-02-15 13:39 UTC, uk960214 commented on src/model/CarGame.js
> +  }
> private 함수에서 this를 사용해야 하는 이유
eslint는 private 함수에서 this를 사용하도록 권장합니다. 기능을 여러 작은 함수로 분리하다 보면 클래스 내부에서만 사용되는 '작은' 함수가 만들어집니다. 하지만 eslint는 이를 에러로 처리합니다.

이 부분을 말씀하시는 것 같아요!
혹시 eslint의 문서에서 왜 이런 규칙이 생겼는지 읽어보셨나요? 저는 충분히 일리가 있다고 보았습니다.
그런 의미에서 이 함수를 한 번 잘 살펴보고,
이 함수가 하는 역할은 무엇인지, 과연 이렇게 존재해야하는 함수인지 고민해보고 알려주시면 좋을 듯 합니다!

2024-02-16 01:49 UTC, vi-wolhwa commented on .eslintrc.json
> +    },
eslint airbnb 코드컨벤션을 적용하는데 문제가 있어서 웹을 참고하였습니다!
지적해주셔서 확인해보니, 이번 미션에서 필요 없는 옵션이라는 것을 알았습니다!

2024-02-16 01:52 UTC, vi-wolhwa commented on package.json
> +  "type": "module",
`index.js`에서 `import` 구문을 사용하였는데 에러가 발생하여 `require` 사용을 요구 받았습니다.
그래서 `"type": "module"` 옵션을 추가하여 해결할 수 있었습니다!

2024-02-16 02:27 UTC, vi-wolhwa commented on package.json
> +    "eslint-plugin-react-hooks": "^4.6.0",
다른 분이 airbnb 컨벤션을 적용하신 파일을 참고했습니다.
불필요한 패키지가 있는지 확인을 하지 않은 것이 문제가 되었네요!

2024-02-16 02:29 UTC, vi-wolhwa commented on src/constants/System.js
> +  OUPUT_SPLITER: ', ',
익숙하지 않은 단어라서 `splitter`를 사용하였는데, 개발 시 `delimiter`를 많이 사용하는군요! 팁 감사합니다 😊😍

2024-02-16 06:07 UTC, vi-wolhwa commented on src/controller/Controller.js
> +    }
이 세 가지에 대해서 리팩토링 전에 한 번 고민해보겠습니다!

2024-02-16 06:24 UTC, vi-wolhwa commented on src/controller/Controller.js
> +import OutputView from '../view/OutputView.js';
예전에는 클래스로 선언해서 사용하다가 방식을 변경하게 되었습니다.
이전에 사용하던 name을 그대로 가져오게 되었습니다.
지적 감사드립니다!

2024-02-16 06:43 UTC, vi-wolhwa commented on src/utils/Preprocessor.js
> +  },
여러 개의 전처리 함수를 사용할 경우에는 배열을 통해 넘겨주도록 설계하였습니다.
모듈이 최대한 다양한 상황을 처리할 수 있도록 하면 좋을 것 같다고 생각했습니다. 
그러나 무조건 배열로 넘겨주도록 규칙을 제한하는 것도 좋을 것 같다고 생각됩니다!

2024-02-16 06:52 UTC, vi-wolhwa commented on src/model/CarGame.js
> +    });
map을 사용하여 다음과 같이 바꿀 수 있었습니다!
``` javascript
const carInfos = this.#carList.map((car) => ({
  name: car.getName(),
  location: car.getLocation()
}));
```

2024-02-17 03:22 UTC, vi-wolhwa commented on __tests__/CarGame.test.js
2단계에서는 테스트 케이스를 천천히 다시 설계한 후 테스트 코드를 다시 작성해보겠습니다!

2024-02-17 03:28 UTC, vi-wolhwa commented on src/model/CarGame.js
> +  }
페어프로그래밍 전, 저는 유효성검사 로직을 범용적으로 구현하여 util 함수로 만들었고, 컨트롤러에서 수행하였습니다! 유효성검사 로직은 도메인에 종속될 필요가 없다고 생각했기 때문입니다. 2단계에서 이러한 부분들을 리팩토링하여 다시 리뷰 요청을 드려보고 싶습니다!

2024-02-18 04:33 UTC, vi-wolhwa commented on src/utils/Preprocessor.js
> +  },
사용자 입력으로 받은 문자열이 하나 일 경우와 배열 일 경우를 범용적으로 처리하도록 설계하였습니다!

2024-02-18 08:41 UTC, uk960214 approved these changes
1단계 수고 많으셨습니다!
1단계를 바탕으로 2단계에서 더욱 많은 것들을 보여주실 것 같아서 기대가 되네요 🤩 
그럼 앞으로도 화이팅입니다!!

2024-02-18 08:41 UTC, merged