[1단계 - 자동차 경주] 다르(이상엽) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #267
Opened 2024-02-15 08:31 UTC by pp449

안녕하세요 6기 교육생 다르입니다 😄 부족한점과 궁금한점 모두 말씀 부탁드립니다! 

## 🎯 개발 목표

페어와 같이 개발을 진행하며 다음과 같은 개발 목표를 가지고 페어 코딩을 진행했습니다.

- getter, setter 사용을 자양하여 정보 은닉할 수 있는지에 대해 고민하며 개발했습니다.
- 하나의 메서드가 하나의 기능만 담당할 수 있도록 개발했습니다.
- 확장 가능성을 고려하며 상수를 분리하고, 전역에서 사용되는 함수는 `utils`폴더에 모듈화 하였습니다.
- 메서드나 변수명을 누구나 이해할 수 있도록 직관적으로 작성하도록 노력했습니다.

## 🤔 질문사항

### 💡 언제 커밋을, 어떤 단위로 하는지

저희는 기능 요구사항 하나를 구현할 때마다 커밋을 진행하였습니다. 그러다보니 1개 커밋에 변경된 파일이 많은 경우도 있고, 구현한 코드가 에러가 발생하는지 모르고 커밋하는 경우도 있었습니다. (해당 경우의 경우 git rebase 를 통해 수정) 

그렇기에 어떤 기준을 가지고 커밋을 하는지, 커밋에 에러가 있는 경우 rebase 를 하는지 아니면 fix 라는 새로운 커밋을 만드는지 궁금합니다

### 💡 클래스 분리를 어디까지 해야하는지

미션을 구현하면서 시도 횟수를 관리하는 클래스, 최종 우승자를 구하는 클래스를 따로 만들어서 관리를 해야할지 고민했습니다. 저희는 클래스를 너무 잘게 쪼개는 것 보다 CarService 클래스에서 관리하는게 좋다 판단하여 CarService 에 모든 기능을 넣었습니다. 

기능상 CarService 클래스에서 관리하는게 코드 가독성 및 재사용성이 좋다 생각하였는데 따로 클래스를 만드는게 좋은지 궁금합니다

2024-02-15 14:27 UTC, liswktjs requested changes
안녕하세요 다르! 
이번에 리뷰어를 맡게 된 샐리 라고 합니다!  😆
질문 있으시면, 편하게 코멘트 달아주세요! 

> 💡 언제 커밋을, 어떤 단위로 하는지

커밋을 왜 적절한 단위로 나눠야할까요? 

보통 팀 단위로 하나의 프로덕트를 개발하고 서로의 코드를 리뷰해주게 됩니다 
그런데 이때 , pr을 올린 당사자는 자신이 개발한 코드에 대해서 이해도가 높지만 리뷰를 해주는 리뷰어의 경우에는 리뷰이가 올린 기능에 대해서 어떠한 요구사항과 흐름을 가지고 있는지 자세히 알지 못하는 경우가 있습니다 (각자 서로의 기능을 개발하기 바쁘기 때문에...) 
이럴 때 리뷰어들은 커밋 이력을 보며 로직의 흐름을 따라 가며 해당 기능에 대한 이해도를 높이기도 합니다! 

추가적으로  디버깅을 할 때 커밋 단위를 적절히 나누는 것이 힘을 발휘하기도 합니다!
예를 들어, 어떤 기능이 동작하지 않을 때 어떤 커밋부터 문제를 일으켰는지 확인을 하곤 합니다 
 
지금 현재 자동차 경주의 미션의 경우 요구사항이 세세히 나눠져있고 뚜렷하게 때문에 보통 하나의 요구사항을 구현하게 되면 함수 하나를 개발하는 흐름으로 이어지고 있습니다 
그렇다면 함수 하나의 단위로 커밋을 해야할까요? 
저는 정답은 없다고 생각합니다!  하지만 최대한 심플하게 나눠져 있는 커밋 이력이 내가 만든 기능에 이해도가 없는 사람이 봤을 때도 이해하기 쉽게 만들 수 있다고 생각합니다

다르 가 앞으로 우테코를 통해 페어와 리뷰를 주고 받으면서 어떤게 읽기 좋은 커밋 이력인지 기준을 만들어가면 좋을 것 같습니다! 

추가로 커밋 이력에 에러가 있는 경우에도 저는 흐름 파악을 위해서 올려도 괜찮다고 생각합니다! 
최종 Pr을 올렸을 때에만 기능들이 정상적으로 동작하면 된다고 봅니다! 

> 💡 클래스 분리를 어디까지 해야하는지

코드 리뷰를 하면서 다르의 코드를 보았을 때 적절하게 클래스를 나누어 주신 것  같습니다! CarService도 따로 클래스로 또 분리할 필요가 없어보입니다 
너무 잘게 쪼개도 추후 유지 보수가 힘들어 질 수도 있고 또 너무 크게 만들어도 마찬가지이죠 
좀 더 클린한 코드에 대해서 공부해보고 싶으시다면 개발 도서 중 "클린 코드"나 "리팩토링 2판" (2판이 자바스크립트 입니다) 책 추천드립니다 


앞으로 펼쳐질 다르의  우테코 생활 파이팅입니다! 💪

2024-02-16 08:14 UTC, pp449 reviewed
바쁜 일정 와중에 꼼꼼한 피드백 감사드려요 샐리!

샐리의 답변으로 인해 '내가 잘 하고 있었나?' 에 대한 생각과 조금 복잡했던 생각이 정리된거 같아요 

커밋에 대한 생각은 아직 제대로 확립되진 않았지만 제가 우테코 과정을 진행하면서 해결해야할 과제인거 같아요. 다양한 방법을 진행해보고 최적의 방법을 한번 찾아볼게요

`너무 잘게 쪼개도 추후 유지 보수가 힘들어 질 수도 있고 또 너무 크게 만들어도 마찬가지이죠` 저도 이 말에 동감합니다! 항상 적당한게 좋지만 아직 클래스를 어떻게 나누는지에 대해 고민도 많고 어려운거 같아요 🥲

제가 코드를 작성하면서 궁금했던 점을 추가적으로 코멘트를 남겼는데 확인 부탁드려요 샐리의 의견이 궁금해요!

2024-02-16 08:14 UTC, pp449 commented on src/utils/validator.js
> +  },
넵 확인했습니다!

2024-02-18 05:46 UTC, liswktjs commented on src/index.js
> +const Controller = require('./controller/Controller.js');
아하 그런 배경이 있었군요 
그렇다면, require를 사용하신 배경이 이해가 되네요  👍  
설명 감사합니다

2024-02-18 05:50 UTC, liswktjs commented on src/service/CarService.js
> +  }
다르가 제안해준 2가지 방안 중에 이번과 같은 경우에는 map과 filter를 사용하는 것이 더 좋다고 느껴집니다! 
그 이유는 reduce 내부에서 push를 사용해주시고 계시는데 이럴 경우 불변성이 문제가 될 수 도 있습니다 
이 점도 추가로 공부해보시면 좋을 것 같아요 
여러 방면으로 고민하는 노력 멋있습니다 👍

2024-02-18 05:51 UTC, liswktjs commented on src/view/InputView.js
> +};
저는 공백이 있어서 코드가 더 읽기 좋다고 느껴졌습니다! 
다르가 말해주신 것 처럼 선언, 실행, 결과에 따라서 나눠주신 것이였기 때문에 더 읽기 좋게 표현되어 있는 것 같아요

2024-02-18 06:07 UTC, liswktjs approved these changes
안녕하세요 다르 💫  
첫 미션 수고하셨습니다 👏👏

질문 남겨주신 부분들에 대해서 코멘트 남겼습니다! 추가 질문사항이 있으시다면 자유롭게 의견 남겨주세요! 🕵️

추가로 다르는 충분히 잘하고 있다고 생각합니다 
앞으로 우테코 생활을 거치며 더 발전할 다르 기대하겠습니다 👍

다음 단계 미션도 파이팅입니다 💪

2024-02-18 06:07 UTC, merged