[자동차 경주 - step 1] 라이언(박한영) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #276
Opened 2024-02-15 08:42 UTC by Parkhanyoung

안녕하세요 리뷰어님! 손수 피드백 해주셔서 감사합니다 🙂

## 구현 시 노력 한 점
1. **인터페이스 설계 후 구현:** 클래스의 세부 사항(프로퍼티, private 메서드)들을 결정하기에 앞서 객체 간 소통에 필요한 퍼블릭 메서드와 객체 간 관계를 먼저 설계했습니다. 그 후 설계한 메서드 구현을 위해 필요한 세부 사항들을 채워나가는 방식으로 구현했습니다. 단순히 기능 작동 순서에 따라 구현할 때에 비해 전체적인 그림을 보다 잘 파악하고 구현에 들어갈 수 있었습니다.
2. **메서드를 철저히 분리:** 클래스의 메서드들에 여러 가지 로직이 섞여 복잡해 보이지 않도록 최대한 분리하기 위해 노력했습니다. 작은 단위의 로직 일지라도 명시적으로 의미를 파악할 수 있도록 별도의 메서드로 분리하여 표현했습니다.
3. **명확한 변수명 부여:** 짧은 코드를 위해 변수명을 간략히 지을 경우 의미 전달이 불확실해지는 것을 경험했습니다. 그래서 조금 장황하더라도 명확한 의미를 담은 변수명을 짓기 위해 노력했습니다.
4. **유닛 테스트**: 도메인 클래스들의 모든 메서드를 테스트하기 위해 노력했습니다. 다만 시간이 부족하여 충분한 수의 테스트 케이스를 작성하지는 못했습니다. 더불어 아직 테스트 코드 작성에 익숙하지 않아, 충분한 커버리지의 테스트를 작성했는지 확신이 들지 않았습니다 🥲 관련해서 조언을 주신다면 큰 도움이 될 것 같습니다!

## 대략적 구조
![image](https://github.com/woowacourse/javascript-racingcar/assets/80797824/67cae30d-5728-4a63-b174-f762dade83a3)
조금이나마 이해에 도움을 드리고자 퍼블릭 메서드와 서로의 의존 관계를 그림으로 표현해봤습니다!
참고 사항으로, 자동차의 주행거리를 "mileage(마일리지)"라는 변수명으로 표현했음을 말씀드립니다.

## 실행 방법
루트 디렉토리에서 ```node ./src/index.js```를 해주시면 됩니다!

구현을 하며 해소되지 않았던 고민은, 맥락 공유를 위해 해당 코드 위에 남기도록 하겠습니다!

도움 주셔서 다시 한 번 감사드립니다! 🙇🏻‍♂️

2024-02-15 09:14 UTC, Parkhanyoung commented on src/domain/Car.js
> +  static MAX_NAME_LENGTH = 5;
이처럼 단일 클래스에서만 쓰일 상수는 static 프로퍼티로 선언했습니다.
재사용되지 않고, class에 강하게 결합된 변수라 생각하여 이렇게 선언했습니다.
이렇게 사용하는 게 올바른 사용인지 궁금합니다. 인스턴스 메서드에서 활용될 변수인데 static 키워드를 붙이는 게 잘못된 사용인가하는 생각이 들기도 해서요..!

2024-02-15 09:14 UTC, Parkhanyoung commented on src/domain/Car.js
> +  }
이처럼 private 프로퍼티를 수정하는 부수효과를 갖는 메서드는 어떻게 테스트하면 좋을지 고민이 되었습니다!
현재는 getMileage 메서드를 호출해 직접 mileage 값이 올바르게 수정이 되는지 확인하는 방식으로 테스트했습니다.
이것이 적절한 방법이었을지 확신이 들지 않아 질문 남깁니다! :)

2024-02-15 09:14 UTC, Parkhanyoung commented on __tests__/car.test.js
> +  RandomUtil.pickRandomNumber = jest.fn();
pickRandomNumber 함수를 모킹하는 로직입니다.
원래는 pickRandomNumber를 객체로 묶지 않고, 함수로만 선언했는데 해당 방식으로는 함수를 모킹할 수 있는 방법을 찾지 못했습니다. 그래서 어쩔 수 없이 객체를 선언하고 그 객체의 메서드를 jest.fn으로 대체하는 방식으로 모킹을 구현했습니다. 그런데 이는 테스트를 위해 프로덕션 코드를 수정하는 것이어서 좋지 않은 방식인 것 같다는 생각이 들었습니다.. 혹시 더 좋은 방법이 있을까요 ? 🥲

2024-02-15 13:21 UTC, Parkhanyoung commented on src/controller/Race.js
> +    const cars = await tryUntilSuccess(this.#getCars.bind(this))();
여기서 bind(this)를 해주지 않을 경우, ```Cannot read properties of undefined (reading 'Race')``` 오류가 발생하는데, 이 오류 문구가 뜨는 것이 이해가 되지 않았습니다!

#getCars 메서드가 tryUntilSuccess를 거치면서 this 바인딩을 잃어(undefined로 this 바인딩되어) #getCars 메서드 내에서 원래 의도대로 this를 사용하지 못한다는 것은 이해했습니다.
그런데 제 예상으로는 #getCars 함수 내에서 this의 메서드로 호출되는 #parseCarNames를 사용하지 못하게 되므로 ```Cannot read properties of undefined (reading 'parseCarNames')``` 라는 오류 메시지가 나타날 것으로 예상했습니다.
그런데 Race를 read하지 못한다는 오류 메시지가 어떻게 뜰 수 있는 건지 이해가 잘 되지 않았습니다.

이 궁금증을 해소하기 위해 이것저것 수정을 해보았는데요, #parseCarNames의 private 키워드(#)를 없애 public 메서드로 바꾼 후 실행하니 원래의 예상대로  ```Cannot read properties of undefined (reading 'parseCarNames')```라는 문구가 출력됐습니다.

private 키워드로 인해 해당 메서드의 class를 read하는 시도가 발생했던 것일까요? 이 궁금증을 아직 명확히 해소하지 못해, 혹시 이와 관련하여 추측되는 사항이나 공부 키워드를 알려주신다면 열심히 공부해보겠습니다! 감사합니다 🙇🏻‍♂️

2024-02-16 02:20 UTC, zigsong requested changes
안녕하세요 라이언! 첫 리뷰를 맡은 지그입니다 ☺️

요구사항에 맞게 코드 잘 작성해주신 것 같습니다. 

본문 내용에 대한 피드백을 드리자면, 

'객체 간 소통에 필요한 요소들'을 먼저 고민하고 인터페이스를 설계하신 점이 인상깊습니다. 좋은 설계 방식이라고 생각합니다. 

> 더불어 아직 테스트 코드 작성에 익숙하지 않아, 충분한 커버리지의 테스트를 작성했는지 확신이 들지 않았습니다

→ 테스트 커버리지가 높다고 해서 반드시 좋은 것은 아닙니다. 어떤 코드를 테스트할 필요가 있는지 파악하고, 운영 환경의 여러 변수들에 영향 받지 않는 올바른 테스트를 작성하는 것이 더 중요합니다. 테스트 코드는 개발 초기 단계에서 당장 급한 것은 아니라고 생각하여, 앞으로 천천히 고민해나가시면 좋을 것 같습니다. ☺️ 

2024-02-16 02:20 UTC, zigsong commented on __tests__/car.test.js
> +  RandomUtil.pickRandomNumber = jest.fn();
> 그런데 이는 테스트를 위해 프로덕션 코드를 수정하는 것이어서 좋지 않은 방식인 것 같다는 생각이 들었습니다.

네 맞습니다. 테스트를 위해 프로덕션 코드를 수정하는 것은 바람직하지 않죠 

그런데 근본적으로 랜덤 넘버와 관련된 테스트가 필요한지는 의문입니다. 해당 함수 내부에서 사용하는 `Math.floor()`와 `Math.random()`은 자바스크립트 내장 함수이므로 테스트가 불필요하고, 

```
  numbers.reduce((acc, number) => {
    return acc.mockReturnValueOnce(number);
  }, pickRandomNumber);
```

`.reduce()`의 두 번째 인자에는 보통 초기값이 들어가는데, 함수를 넣으신 의도를 파악하지 못했습니다. `.reduce()`로 재생성한 array를 반환해서 사용하거나 하고 있지도 않고요. 테스트의 의도를 

더불어 테스트는 실행할 때마 값이 변경되면 테스트의 안정성을 보장할 수 없기 때문에 테스트 환경에서는 `Math.random()`등의 함수는 그 자체를 mocking해서 개발자가 임의의 return값을 직접 명시해주는 것이 좋습니다. ("go 메서드 테스트"에서 5개의 객체를 임의로 넣어주신 것처럼요.)

2024-02-16 12:10 UTC, Parkhanyoung commented
https://github.com/woowacourse/javascript-racingcar/pull/276#discussion_r1491885228

테스트 코드까지 자세히 살펴주셔서 정말 감사드립니다 🙂

------

> 그런데 근본적으로 랜덤 넘버와 관련된 테스트가 필요한지는 의문입니다

랜덤 넘버 함수의 기능을 테스트하는 게 아니라, go 메서드의 기능을 테스트하기 위해 go 메서드 내부에서 사용되는 랜덤 넘버 함수(pickRandomNumber)의 반환값을 모킹하는 부분입니다!
go 메서드의 동작을 확인하기 위해, 랜덤 넘버 함수가 미리 지정한 숫자들을 순서대로 반환하도록 모킹했습니다.

-----

> 테스트의 의도를 설명해주시면 좋을 것 같습니다.
```js
  numbers.reduce((acc, number) => {
    return acc.mockReturnValueOnce(number);
  }, RandomUtil.pickRandomNumber);
  ```
언급해주신 위 코드는 지정한(모킹에 사용될) 숫자의 배열을 순회하며 RandomUtil의 pickRandomNumber(acc)의 반환값을 모킹합니다.
mockReturnValueOnce는 한 번 실행하면 바로 다음의 반환값, 두 번 실행하면 그 다음의 반환 값 ... 과 같은 식으로 모킹합니다. 매 회차의 반환값을 다르게 설정하기 위해 이 방식을 사용했습니다.
그래서 제가 지정한 순서대로 특정 숫자가 반환될 수 있도록 숫자 배열을 순회하며 mockReturnValueOnce를 반복 호출했습니다.

이 코드에서 RandomUtil.pickRandomNumber를 두번째 함수로 넘긴 의도는 RandomUtil.pickRandomNumber 메서드에 접근하기 위함이었는데(다고 생각하는데), 원래 reduce 함수의 사용법과 거리가 있는 용례였고, 지금 보니 forEach 함수를 이용하는 게 더 나을 것 같다는 생각이 듭니다 😭
(사실 모킹에 익숙하지 않고 시간이 부족하여, 이전에 프리코스에서 제공해주었던 테스트 케이스의 모킹 함수를 그대로 사용한 것이어서 작성자의 실제 의도는 이게 아닐지도 모르겠습니다 😭)
그래서 이 부분은 forEach 문으로 바꾸어, 보다 직관적으로 이해 가능하도록 수정했습니다.

------

중언부언 말이 길었는데 정리하면,
1. 랜덤 함수는 테스트 안 해도 된다 -> 랜덤 함수는 테스트하지 않았고, go 함수의 내부에서 사용되는 랜덤 함수를 모킹한 것입니다.
2. reduce 두번째 인자로 넘어온 함수는 뭐지 -> 모킹을 위해 함수를 reduce 내부에서 접근하기 위함입니다. 단, 지금 보니 forEach로 작성하는 게 더 명확하다고 판단하여 forEach를 사용하는 방식으로 수정했습니다.
**3. 혹시 RandomUtil을 객체로 선언하지 않고도(pickRandomNumberBetween를 객체의 메서드가 아닌 단일 함수로 선언하고도) pickRandomNumberBetween를 모킹할 수 있는 방법이 있을까요?**

제가 아직 미숙하여 지그의 의도를 맞게 이해한지 모르겠네요 🥲
혹시 제가 잘못 이해하거나 잘못 인지하고 있는 부분이 있다면 알려주시면 감사하겠습니다!
  
바쁘신 와중에 리뷰에 힘써주셔서 감사해요 지그 🙂

2024-02-16 12:17 UTC, Parkhanyoung commented
@zigsong 
지그가 주신 피드백 및 스스로 개선해볼 점을 생각하여 리팩토링 해보았습니다 🫡

리팩토링 사항은 다음과 같으며 커밋 히스토리로도 확인하실 수 있습니다.
  - [x] 변수 명 winner 복수형 의미를 담아 s 붙이기
  - [x] 함수명은 동사형으로! (repeatable -> repeat)
  - [x] 불필요한 객체 형태의 export를 export const 형식으로 변경
  - [x] 테스트 케이스 배열을 변수에 담도록 변경  
  - [x] 테스트명을 의미 전달이 명확히 되는 문구로 변경
  - [x] pickRandomNumber 메서드를 최소값, 최대값 설정 가능하도록 수정
  - [x] mockRandoms를 재사용 가능한 유틸로 변경

2024-02-17 00:49 UTC, zigsong commented
안녕하세요 라이언, 리뷰 잘 반영해주셔서 감사합니다!

테스트 코드의 random 함수 관련해서 수정해주신 부분 보았는데요, 훨씬 이해하기가 좋아진 것 같습니다. 

> ⭐️ 혹시 RandomUtil을 객체로 선언하지 않고도(pickRandomNumberBetween를 객체의 메서드가 아닌 단일 함수로 선언하고도) pickRandomNumberBetween를 모킹할 수 있는 방법이 있을까요?

제가 첫 테스트 코드에 의문이 많아서 이 부분을 제대로 답변드리지 못했네요. 

리뷰하며 다른 크루의 코드도 보았는데, 괜찮은 참고사항이 될 것 같아 남깁니다. (https://github.com/woowacourse/javascript-racingcar/pull/289) 여기서 답을 찾으실 수 있을 것 같아서요! 

온보딩 미션의 일정이 짧아 우선 approve하겠습니다. 테스트코드를 2단계에서 추가해주시면(시간이 없다면 안해주셔도 됩니다) 그때 또 확인해보겠습니다. 수고하셨습니다 ☺️

2024-02-17 00:50 UTC, zigsong approved these changes
어프루브합니다

2024-02-17 00:50 UTC, merged