[step1: 자동차 경주] 소하(최소연) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #281
Opened 2024-02-15 08:46 UTC by soi-ha

안녕하세요. 리뷰 잘 부탁드리겠습니다!
이번 미션은 5시까지 기능 개발완료 후, 페어의 레포지토리에 clone에 문제가 생겨.. 시간이 부족하여 간단하게 글을 작성하는 점 양해부탁드립니다. :) 감사합니다.

## 개발 상황 설명

- 개발을 시작할때 부터 확실하게 형태를 잡아두고 기능 구현을 하려다 보니 시간이 많이 부족하게 되었습니다. 
시간 부족으로 리팩토링도 진행하지 못하였고, 프로그래밍 요구사항 또한 지키지 못하였습니다. (함수 코드라인 10줄 넘기지 말것 등)

- 에어비앤비 코드 컨벤션을 적용시키기 위해서 eslint와 prettier 설정을 시도했으나 실패했습니다. 

- generateRandomNumberOfName.js
REQUIREMENTS.md의 내용에는 사용자가 자동차 이름을 입력할때 빈 문자열을 입력했다면, 빈 문자열을 임의의 이름(ex. User1)을 부여하여 자동차 이름 배열을 반환하려고 했습니다.
그러나 시간 관계상 해당 부분을 구현을 했으나 작동하는데 문제가 발생하여 실행은 시키지 않았습니다.
 

## 질문사항

- asyncFunctionHandlerWithError.js
user에게서 입력을 받을때 type(string,number)을 지정하여 type에 관한 에러를 발생시킵니다.
해당 기능 개발을 완료하고 든 생각은 입력을 받을때 type을 지정해서 해줄 필요가 있는지? type 지정이 효율성이 없는것 같다는 생각이 들었습니다.

- 기능을 구현할때 처음부터 재활용성을 생각하면서 개발을 해야 할지 궁금합니다. 
저와 제 페어는 처음부터 기능을 구현할때 추후에 재활용성을 생각하면서 기능을 구현하려 했습니다. 하지만 해당 방식은 기능 구현을 하는데 있어서 오랜 시간이 걸렸습니다. 
리뷰어님은 기능을 구현할때 일단 요구사항에 맞게 기능을 구현하는 것이 맞다고 생각하시나요? 아니면 처음부터 추후 재활용될 것을 생각하면서 기능을 구현하는 것이 맞다고 생각하시나요?

2024-02-15 18:30 UTC, yujo11 requested changes
안녕하세요 소하~(소하는 소연 하이의 줄임말인가요? ㅎㅎ)

자동차 경주 미션 함께하게 된 유조입니다 반갑습니다~~

---

###  개발 상황 설명

>개발을 시작할때 부터 확실하게 형태를 잡아두고 기능 구현을 하려다 보니 시간이 많이 부족하게 되었습니다.
시간 부족으로 리팩토링도 진행하지 못하였고, 프로그래밍 요구사항 또한 지키지 못하였습니다. (함수 코드라인 10줄 넘기지 말것 등)

좋은 설계를 바탕으로 좋은 코드를 작성하는 것도 물론 중요하지만 아무리 좋은 코드라도 동작하지 않는 코드라면 가치를 전달하지 못 한다고 생각하는데요.

개인적으로는 개발을 진행할 때 처음부터 완벽한 설계와 완벽한 코드를 작성해야겠다는 마음을 조금 내려두고 일차적으로 요구사항에 맞게 동작하는 프로그램을 작성하는 일에 더 포커스를 맞추셨으면 좋겠습니다 ㅎㅎ

다른 크루가 관련된 내용으로 질문을 준게 있는데 해당 질문과 해당 질문에 남겼던 답변도 같이 공유 드립니다. 같이 읽어보시면 좋겠네요~

>Q. 기능 구현을 빠르게 끝내고 제한 사항을 지키기 위해 리팩토링을 진행하는게 좋은지, 처음부터 좋은 코드를 작성하기 위해 고민하며 제한 사항을 충분히 지키도록 기능을 구현하는 게 좋은지 궁금합니다. 현업에서는 어떤 방식이 더 선호되나요?

>>A. 명확하게 전자의 방식이 선호됩니다. 일반적으로 현업에서 프로그래밍을 한다고 하면 코드를 통해 감동을 전달하는 목적보다는 해당 코드를 통해 가치를 전달하는 일일텐데요. 아무리 잘 짜여져 있어도 동작하지 않는 코드는 어떤 가치도 전달할 수 없기 때문에 현업에서도 전자의 방식을 선호합니다. 물론 "빠르게"에만 초점을 맞추기 보다는 "빠르게 잘"에 초점을 맞춰야 하겠지만요 ㅎㅎ

>에어비앤비 코드 컨벤션을 적용시키기 위해서 eslint와 prettier 설정을 시도했으나 실패했습니다.

eslint와 prettier는 앞으로도 두고두고 잘 써먹을 라이브러리들이니 리뷰 확인해보시면서 다시 적용을 시도해보시면 좋을거 같습니다 ㅎㅎ

>generateRandomNumberOfName.js
REQUIREMENTS.md의 내용에는 사용자가 자동차 이름을 입력할때 빈 문자열을 입력했다면, 빈 문자열을 임의의 이름(ex. User1)을 부여하여 자동차 이름 배열을 반환하려고 했습니다.
그러나 시간 관계상 해당 부분을 구현을 했으나 작동하는데 문제가 발생하여 실행은 시키지 않았습니다.

코멘트로도 질문 남겼던 내용인데 이런 배경이 있었군요.

해당 부분의 경우 원래 기능 요구 사항에 존재하는 내용이 아닌 조금 더 잘 만들어보려고 했던 부분으로 보여요. 위에 남긴 내용과 비슷하지만 기본적으로는 요구사항대로 프로그램이 동작할 수 있도록 코드를 작성하신 다음 이런 추가 기능들이나 리팩터링을 진행해보시면 좋겠습니다 

### 질문사항

>asyncFunctionHandlerWithError.js
user에게서 입력을 받을때 type(string,number)을 지정하여 type에 관한 에러를 발생시킵니다.
해당 기능 개발을 완료하고 든 생각은 입력을 받을때 type을 지정해서 해줄 필요가 있는지? type 지정이 효율성이 없는것 같다는 생각이 들었습니다.

아래처럼 함수를 사용해도 함수가 동작하기 떄문에 현재의 상황이라면 크게 효율성이 없을 수도 있겠다는 생각이 들어요. 

```js
asyncFunctionHandlerWithError("string", number, ...)
```

추가로 현재는 asyncFunctionHandlerWithError 함수가 존재함으로써 전체 코드를 파악하기 조금 어렵다는 느낌도 받았는데요. 언제 어느 상황에서나 통용되는 얘기는 아닐 수 있지만 [YAGNI](https://ko.wikipedia.org/wiki/YAGNI#:~:text=%EC%9D%B5%EC%8A%A4%ED%8A%B8%EB%A6%BC%20%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D%EC%9D%98%20%EA%B3%B5%EB%8F%99%20%EC%84%A4%EB%A6%BD%EC%9E%90,%EC%A4%80%EB%A7%90%EB%A1%9C%EB%8F%84%20%EC%9D%B8%EC%9A%A9%EB%90%9C%EB%8B%A4.)에 대한 내용도 한번 읽어보셔도 좋을거 같습니다 ㅎㅎ

>기능을 구현할때 처음부터 재활용성을 생각하면서 개발을 해야 할지 궁금합니다.
저와 제 페어는 처음부터 기능을 구현할때 추후에 재활용성을 생각하면서 기능을 구현하려 했습니다. 하지만 해당 방식은 기능 구현을 하는데 있어서 오랜 시간이 걸렸습니다.
리뷰어님은 기능을 구현할때 일단 요구사항에 맞게 기능을 구현하는 것이 맞다고 생각하시나요? 아니면 처음부터 추후 재활용될 것을 생각하면서 기능을 구현하는 것이 맞다고 생각하시나요?

이 질문을 이제 봐서 위에도 같은 애기들을 반복하고 있는데 요구사항에 맞게 기능을 구현하는 것이 최우선이라고 생각합니다.

그렇다고 최초 구현 단계에서  어떻게든 돌아만 가도록 만들라는 말씀은 아니고, 이 단계에서 너무 먼 미래가 아닌 예상할 수 있는 범위 내에서 재사용성을 생각하며 구현하시면 좋겠습니다.


---

첫 미션이라 정신 없었을텐데 고생 많았습니다 소하~ 👍 👍 👍 

코멘트 확인해주시고 다시 리뷰요청 부탁드려요~~

2024-02-15 18:30 UTC, yujo11 commented on src/constants/messages/progressMessage.js
> +	final_winner: (winners) => `최종 우승자: ${winners.join(', ')}`,
다른 상수들이 가지고 있는 value들(string)과 다르게 위 두 메서드는 함수형태로 사용을 해야하는데요.

같은 레벨에 이렇게 쓰임이 다른 값들을 가지고 있으면 사용하는 곳에서 혼란이 올 수도 있을거 같아요. 별도로 분리해보시거나 다른 방법을 고민해 보셔도 좋을거 같네요.

배열로 비유하면 아래와 같은 상황인거 같아요.

```js
// 다른 상수들
[ "문자열1", "문자열2", "문자열3", "문자열4"]

// PROGRESS_MESSAGE
[ "문자열1", function, "문자열3", function]
```

2024-02-15 18:30 UTC, yujo11 commented on src/constants/messages/resultMessage.js
> +const RESULT_MESSAGE = deepFreeze({
`deepFreeze`와 `freeze`에는 어떤 차이가 있나요?

2024-02-15 18:30 UTC, yujo11 commented on src/constants/configs/regexConfig.js
> +	special_character: /[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]+/,
정규식은 정말 유용한 방법 중 하나지만 일반적으로는 한번에 내용을 파악하기 어렵고 가독성을 떨어트리는 부분이 있어서 사용이 꺼려지는 부분도 있는거 같아요. 조금 더 쉽게 풀어나갈 수 있는 방법을 고민해보셔도 좋겠네용

2024-02-15 18:30 UTC, yujo11 commented on src/services/generateRandomNumberOfName.js
이 함수는 어떤 쓰임이 있는 함수일까요?

2024-02-15 18:30 UTC, yujo11 commented on src/models/Validator.js
> +		if (car.length > 5) {
여기 있는 매직넘버 5나

2024-02-15 18:30 UTC, yujo11 commented on src/models/Validator.js
> +		if (count > 20) {
20 같은 부분은 도메인 정책에 따라 쉽게 변경될 수 있는 부분인데요.

상수화를 하지 않은 지금의 코드를 다른 사람이 본다면 왜 시도횟수가 20을 넘었을 때 Error를 throw 하는지 알 수 있을까요?

이런 부분들도 상수화를 통해 관리해보셔도 좋을거 같네용

2024-02-15 18:30 UTC, yujo11 commented on src/utils/asyncFunctionHandlerWithError.js
> +			if (isNaN(num)) {
JavaScript에는 `isNaN` 메서드와 `Number.isNaN` 메서드가 존재하는데요. 두 메서드는 어떤 차이가 있을까요?

2024-02-16 14:02 UTC, soi-ha reviewed
안녕하세요! 유조! 
저의 닉네임의 속 뜻을 바로 맞추셨군요.. 약간 부끄럽습니다ㅎㅎ;

남겨주신 코멘트가 다 너무 피가 되고 살이 되는 것들이라.. 우아한테크코스를 시작한지 일주일도 채 안돼서 새로운 지식들을 많이 얻을 수 있었습니다. 또한, 기존에 알고 있던 정의도 다시 한번 되돌아 볼 수 있었고 질문 코멘트로 인해 깊게 생각할 수 있는 시간을 가질 수 있었습니다. 감사합니다! :)

그리고 남겨주신 코멘트 이외에도 추가로 궁금한 사항이 생겼는데요!
asyncFunctionHandlerWithError.js 의 경우 축약을 전혀 하지 않은 상태로 함수의 이름을 정의했는데, 이렇게 까지.. 길어도 괜찮은걸까요?! 혹시 이것보다 더 길어도 괜찮은가요?
해당 함수의 이름을 지으면서 페어와 이렇게 까지.. 길어도 되나.. 의미를 축약하지는 말라고 하셨는데.. 라는 생각을 했습니다..! 현업에서 어떻게 하는지 궁금합니다! 

그리고 eslint와 prettier은... step2를 진행하면서 다시 한번...! 도전해보도록 하겠습니다!

---

우아한테크코스를 하기 전부터 현직자에게 코드 리뷰를 너무 받아보고 싶었는데, 저의 첫 코드 리뷰 경험을 너무 좋게 해주셔서 감사합니다! 😄

2024-02-16 16:50 UTC, yujo11 approved these changes
안녕하세요 소하~

농담처럼 던졌던 말인데 소하 닉네임의 의미를 맞춰버렸군요 ㅋㅋㅋㅋ 😎

코멘트도 몇 개 추가로 남기고 소하가 추가로 주신 질문들에도 답변 남겨놨습니다.

이번 step은 여기서 이만 merge 해도 좋을거 같아요!

리뷰 내용들이 꽤 많았는데 빠르게 반영해주시느라 고생 많으셨습니다 👍 👍 👍 

다음 step에서 다시 만나요~~

(ps. Rsolve conversation 을 누르면 소하가 추가로 남긴 코멘트들을 확인하기가 힘든데요. 다음 step에서 Resolve conversation은 누르지 말고 그대로 두시면 좋을거 같습니다 ㅎㅎ)

<img width="226" alt="image" src="https://github.com/woowacourse/javascript-racingcar/assets/61097373/3fbfe025-d15d-4ee7-8a8c-0f37f5172d04">

2024-02-16 16:50 UTC, yujo11 commented on __tests__/CountOfAttempt.test.js
> +	test('유효한 값을 넣었을 때 해당 값을 반환한다.', () => {
여기서도 "유효한 값"이 뭔지 알 수 있으면 좋을거 같네요~

2024-02-16 16:50 UTC, yujo11 commented on __tests__/CountOfAttempt.test.js
> +	test('type이 number이고 자연수이며 시도 제한 횟수 이하의 유효한 값을 넣었을 때 해당 값을 반환한다.', () => {
바로 다음 커밋에서 수정하셨군요 ㅋㅋㅋ 👍 👍 👍 💯

2024-02-16 16:50 UTC, yujo11 commented on __tests__/CountOfAttempt.test.js
> +		'시도 제한 횟수 이상이며, 자연수가 아니고 type이 number가 아닌 유효하지 않은 값을 넣으면 에러를 발생시킨다.',
이렇게 `each` 메서드를 사용할 때는 테스트 데이터 값을 같이 삽입해줘도 좋을거 같아요 

`%s` 같은 문법을 통해 삽입할 수 있었던거 같은데 찾아보시면 좋겠네요~

2024-02-16 16:50 UTC, yujo11 commented on src/constants/configs/randomNameConfig.js
> +	DEFAULT_NAME: 'user',
UPPER_CASE를 보니 마음이 편-안 해지네요 ㅋㅋㅋ 👍

2024-02-16 16:50 UTC, yujo11 commented on src/constants/configs/validLimitConstantsConfig.js
> +	CAR_NAME_LIMIT_RANGE: 5,
`LIMIT`에 대한 상수만 존재하는거 같은데 최소 값에 대한 상수는 필요 없을까요?

2024-02-16 16:50 UTC, yujo11 commented on src/services/generateRandomNumberOfName.js
> +			carNames[index] = `${RANDOM_NAME_CONFIG.DEFAULT_NAME}${generateRandomNumber({ from: 0, to: 9 })}`;
오 아주 좋은데요? 👍 👍 👍

2024-02-16 16:50 UTC, yujo11 commented on src/utils/generateRandomNumber.js
>  }
객체로 prameter를 받는 경우에 함수에서도 알 수 있게 작성해주셔도 좋을거 같네요

```js
// ex
export default function generateRandomNumber({ from, to }) {
	return Math.floor(Math.random() * (to - from + 1)) + from;
}
```

2024-02-16 16:50 UTC, yujo11 commented on __tests__/ScoreBoard.test.js
> +	test('유효한 값읋 넣으면 0으로 초기화된 Map 객체를 반환한다', () => {
변수와 마찬가지라고 생각하는데요.

짧지만 의미를 파악하기 어려운 이름 vs 길지만 의미를 파악하기 쉬운 이름의 관점에서 저는 명확히 후자가 좋다고 생각합니다. ㅎㅎ

2024-02-16 16:50 UTC, yujo11 commented on __tests__/ScoreBoard.test.js
> +	test('유효한 값읋 넣으면 0으로 초기화된 Map 객체를 반환한다', () => {
추가로 `'type이 number이고 자연수이며 시도 제한 횟수 이하의 유효한 값을 넣었을 때 해당 값을 반환한다.'` 같은 이름까지는 조금 과할 수 있는데 `N ~ M 사이의 정수가 시도 제한 횟수로 입력 되었을 때 해당 값을 ㅇㅇ한다.` 정도의 형태로 작성해주셔도 좋을거 같아요

2024-02-16 16:50 UTC, yujo11 commented on src/constants/messages/resultMessage.js
> +const RESULT_MESSAGE = deepFreeze({
열심히 찾아보셨군요 아주 좋네요 👍 💯 💯 💯

2024-02-16 16:50 UTC, yujo11 commented on src/constants/configs/regexConfig.js
> +	special_character: /[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]+/,
다양한 방법이 있을거 같은데요. 저도 특정한 방법을 떠올리고 말씀드린건 아니라 지금 당장 생각나는건 조금 더 쉽고 명확하게 아래와 같은 정규표현식을 사용하는게 떠오르네요

```js
// ex)
"someString".replace("/[^[ㄱ-ㅎ가-힣a-zA-Z0-9]]/g","");
```

2024-02-16 16:50 UTC, yujo11 commented on src/utils/asyncFunctionHandlerWithError.js
> +			if (isNaN(num)) {
아주 좋네요 ㅎㅎ 👍 👍 👍 💯 💯 💯

2024-02-16 16:50 UTC, yujo11 commented on src/utils/generateRandomNumber.js
> +}
오 사실 거기까지 의도하고 말씀 드린건 아니었는데 하나를 알려 드렸는데 둘을 깨우치셨군요 ㅎㅎ 아주 멋집니다 소하 👍 👍 👍 💯 💯 💯

2024-02-16 16:51 UTC, merged

2024-02-18 10:35 UTC, soi-ha commented on src/utils/generateRandomNumber.js
>  }
코멘트대로 수정하였습니다! :)

2024-02-18 11:01 UTC, soi-ha commented on __tests__/CountOfAttempt.test.js
> +		'시도 제한 횟수 이상이며, 자연수가 아니고 type이 number가 아닌 유효하지 않은 값을 넣으면 에러를 발생시킨다.',
테스트 코드에 문자열 포맷팅을 사용하는 방식은 처음 알게 되었습니다..!
문자열 포맷팅을 활용하여 테스트 설명을 보충해보겠습니다.

2024-02-18 11:22 UTC, soi-ha commented on src/constants/configs/validLimitConstantsConfig.js
> +	CAR_NAME_LIMIT_RANGE: 5,
코멘트를 읽고 생각해보니, 시도 횟수에 대한 최소값도 필요하다는 걸 깨달았습니다!
그래서 Validator.js를 다시보니 validateNaturalNumber()에 `count<1`을 작성했더라구요ㅎㅎ..

validateNaturalNumber()는 시도횟수가 "자연수"인지를 판별하는 함수이고, validateOverLimitCount()는 시도 횟수가 최대값(20)을 넘었는지 판별하는 함수였습니다.
**최소** 시도 제한 횟수를 상수화시키다보니, 유효값 확인을 "자연수" 보다는 "정수"를 판별하고 "최대 제한 시도 횟수" 보다는 "최대, 최소 제한 시도 횟수"를 판별하는게 더 옳을 것 같다는 생각이 들었습니다.
이렇게 변경해야 추후에 코드를 이해하기도 쉽고, 사용자에게 에러 문구를 띄어줄 때에도 "자연수"보다는 "정수"가 좋을 것 같더라구요.
사용자가 0을 입력했을때, "자연수를 입력하세요." 보다는 "시도 횟수의 범위가 아닙니다"가 더 이해하기 쉬울 것 같았습니다!

그래서, validateNaturalNumber()은 validateIntegerNumber()로 이름을 바꾸고 '자연수' 검증에서 '정수' 검증으로 변경했습니다.
validateOverLimitCount()는 validateOverLimitCountRange()로 이름을 변경하여 '최대값' 검증에서 '최대, 최소값' 검증으로 변경했습니다.

2024-02-18 11:57 UTC, soi-ha commented on src/constants/configs/regexConfig.js
> +	special_character: /[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]+/,
예시로 들어주신 정규표현식을 활용하여 조금 수정해보았습니다!
처음에 제가 작성한 방식은 모든 특수문자를 담은 형태이기 때문에 가독성이 떨어진다는 것이고,
`/[^ㄱ-ㅎ가-힣a-zA-Z0-9]/` 정규표현식은 한글,영어, 숫자를 제외(`^`)한 모든 것을 판별한다는 것이기에 조금 더 가독성이 높아지는 것이겠죠?

작성하고 비교하니 모든 특수문자를 담아둔 형태는 뭘 의미하는지 한번에 알기 힘들 것 같긴 하네요..!
앞으로 코드를 작성할때 가독성을 더욱 신경써서 작성해보겠습니다 :)