[자동차 경주] 토다리 1단계 PR 요청합니다
woowacourse/javascript-racingcar pull request #282
Opened 2024-02-15 08:48 UTC by Todari

## Key points
- 객체지향적으로 객체들이 스스로 기능을 실행할 수 있도록 구현하려 시도했습니다.
- 이 과정에서 constructor와 비동기 처리에 대한 오류가 많이 발생했습니다.
- 이를 수정하려 노력했지만, 깔끔하고 명확한 방법이 생각나지 않았습니다...

## 부족한 부분
- 효율적인 설계 및 코드 분리를 고민했으나 완성을 목표로 하다 보니 이도저도 아니게 되었습니다.
- 위에서 설명한 대로 객체지향적으로 코드를 작성하려 했으나, 이를 고려한 설계가 쉽지 않았습니다.
- 테스트 코드를 작성하는 과정에서 mock에 대한 이해가 부족해 테스트 코드를 완성하지 못했습니다.

2024-02-16 03:51 UTC, iborymagic requested changes
첫 미션 고생 많으셨습니다.
전체적으로 무리한 시도 없이 도메인과 View 정도만 깔끔하게 분리하신 것 같고, 큰 무리 없이 읽히는 코드였던 것 같습니다. 

말씀하신 설계 부분은 쉽지 않은 것이 정상입니다. 저도 일할 때마다 설계(객체지향만 고민한 건 아니지만)를 고민하느라 이것저것 문서도 작성하고, 고민한 설계가 적절한지 팀원들에게 리뷰도 받곤 하는데도 나중에 다시 보면 고쳐야할 것들 투성이입니다. 그래도 그런 부분들은 계속 공부해보면서, 지금처럼 이것저것 시도해보시면 점점 나아지지 않을까 생각됩니다.

한 가지 아쉬운 점은, PR 내용이 전체적으로 추상적인 아쉬움들로 차있다는 점일 것 같습니다. 토다리가 미션을 진행하면서 아쉬웠던 부분들, 궁금한 부분들을 간단하게나마 콕 집어서 리뷰어에게 물어보는 습관을 가지면 코드를 개선하는 데에 더 도움이 될거라고 생각합니다. 

고생하셨어요!

2024-02-16 03:51 UTC, iborymagic commented on src/utils/StringParser.js
> +}
꼭 모든 객체를 전부 class로 만들 필요는 없습니다. 
혹시 여기에 class를 사용하신 이유가 뭘까요?

2024-02-16 03:51 UTC, iborymagic commented on src/view/InputView.js
> +}
View 로직을 딱 UI 관련된 부분까지만 깔끔하게 잘 잘라내셨다고 생각이 드네요.
다만, 여기도 class를 사용해야만 하는지는 고민해 볼 여지가 있어보입니다.

2024-02-16 03:51 UTC, iborymagic commented on src/RacingCarGame/SetGame.js
> +class SetGame {
언뜻 봐도 요 객체가 유달리 길어보이죠? 
관심사가 적절히 잘 분리되어 있는지 의심해 볼 필요가 있습니다.
아래의 validation 로직들만 분리해도 훨씬 좋아지지 않을까 싶습니다.

2024-02-16 03:51 UTC, iborymagic commented on src/RacingCarGame/SetGame.js
> +  }
지양해야할 네이밍입니다. 예약어이기도 하구요.
어떤 정보를 가져오는 메서드인지 명시해주면 좋을 것 같습니다.

2024-02-16 03:51 UTC, iborymagic commented on src/App.js
> +  }
요렇게 해도 지구가 멸망하진 않지만, init 메서드를 노출시켜 제어권을 외부로 넘기는 방법도 좋아보입니다. 밖에서 요 객체를 실행해야겠다는 생각이 들어, racingCarGame.init()을 했을 때 비로소 로직들이 실행될 수 있게요.

2024-02-16 06:24 UTC, Todari commented on src/RacingCarGame/Car.js
> +  #movable() {
좋은 방법이라고 생각합니다! 감사합니다 :)

2024-02-16 06:31 UTC, Todari commented on src/RacingCarGame/Car.js
> +  }
감사합니다! getter method를 명시해 줘야 다른 곳에서도 확실히 메소드의 역할을 이해할 수 있겠네요.
혹시 클래스 내의 정보를 함수로 한번 감싸라는 것이 제대로 이해가 되지 않아서 한번 다시 설명해 주실 수 있나요?

2024-02-16 06:42 UTC, Todari commented on src/RacingCarGame/RacingCarGame.js
> +  }
자동차 경주(RacingCarGame.js)와 관련된 함수들이라 생각해서 하위에 두었었는데,
말씀하신대로 진행하면 관심사 분리가 또렷하고,
현재 outputview의 함수 한줄을 함수로 감싸서 사용하는 비효율을 없앨 수 있을 것 같습니다.

감사합니다!

2024-02-16 06:51 UTC, Todari commented on src/RacingCarGame/RacingCarGame.js
> +  }
리뷰를 읽고 나니 이런 생각이 들었습니다.
1. findChampion 을 setChampion으로 이름 변경하기
2. 이름을 변경한다면, #champion 필드를 수정하니, setChampion에 맞는 역할을 수행하는 것이 아닌가?
3. 그렇다면 setChampion 함수가 두가지의 역할을 하기 때문에 분리가 필요할 것 같다.

이 사고 과정을 통해서 findChampion과 setChampion 두가지로 나눠서 적용해볼까 합니다!
감사합니다 :)

2024-02-16 06:58 UTC, Todari commented on src/error/CustomError.js
> +}
프리코스를 진행하던 과정에서, custom error에 대해 알게되었고 적용해 보고 느낀 점은,
Custom Error를 던지거나, 테스트 케이스 작성시에 에러의 이름을 바로 보고 어떤 에러인지 판별하기가 편해서 사용했었습니다.
프리코스 과정에서 다양한 예외 상황에서도 똑같은 에러 메세지(ex: 다시 입력해 주세요)를 반환하기 때문에 구별을 위해서 적용했던 것이 습관이 된 것 같습니다.

이번 미션에서는 정해진 error메세지가 없어 error 메세지로 구분을 할 수 있었을 것 같아
과도한 적용이었나 싶은 생각도 드네요 :)

제가 아는 custom error의 장점은 이정도밖에 경험하지 못했었는데,
혹시 생각하시는 custom error의 활용 방법이 있으시다면 간단하게 알려주시면 감사하겠습니다!

2024-02-16 10:02 UTC, Todari commented on src/index.js
> +app.play();
별다른 생각 없이, 프리코스에서 제공된 코드가 이와 같은 형식이라 그대로 따라하게 된 것 같습니다.

왜 프리코스에서 미션에 제공됐던 코드가 지금 제가 작성한 코드 처럼 index.js에서 실행되지 않고 App으로 한번 더 감쌌을지 생각해 봤을 때, react에서 사용하는 것 처럼index.js와 app.js의 역할을 구분하는 것인데 이 미션에선 적잘하지 않을 수 있다는 생각이 드네요.

2024-02-16 10:08 UTC, Todari commented on src/utils/StringParser.js
> +}
이부분도 마찬가지로, 프리코스로 진행하던 동안 JS에 대한 이해가 부족하여 모두 class로 만들었던 것 같습니다. 

모든 method가 static인 경우, class를 사용할 필요가 없을 것 같다는 생각이 드네요!
감사합니다.

2024-02-16 10:55 UTC, Todari commented on src/RacingCarGame/SetGame.js
> +class SetGame {
확실히 SetGame에 대한 길이가 너무 길어서 읽기 힘든 느낌이네요.
validate관련된 역할들을 공통된 하나로 모을 수 있을 것 같습니다 :)

2024-02-16 11:29 UTC, Todari commented on src/RacingCarGame/Car.js
> +  }
클래스의 필드들을 감싸서 가져오는 것을 말씀하신 것으로 이해했습니다! 감사합니다 :)

2024-02-16 12:00 UTC, Todari commented
첫 미션이다 보니 시간에 쫓겨서 제대로 정리하지 못한게 마찬가지로 아쉬움이 남네요...
자세히 작성해 주신 리뷰 덕분에 다양하게 생각해 볼 수 있었습니다.
감사합니다!

2024-02-18 04:34 UTC, iborymagic commented on src/error/CustomError.js
> +}
오 딱히 과도한 적용이라고 생각하지 않았습니다. 그냥 단순히 커스텀 에러를 따로 정의해서 사용할 만큼 번거로움을 감수하셨으니, 토다리가 생각했을 때 그만한 장점이 있나 궁금해서 물어본 것입니다. (혹시 좋은 아이디어면 저도 참고하려구요 😋)

커스텀 에러의 장점을 살리기 위해 error.name을 사용해보는 것도 추천드리고, 토다리만의 에러 필드를 만들어서 디버깅에 도움이 되도록 로그를 출력해보는 것도 추천드려요 😀

2024-02-18 04:35 UTC, iborymagic approved these changes

2024-02-18 04:45 UTC, iborymagic commented
안녕하세요 토다리! 고생 많으셨습니다.
첫 미션인데도 이만큼 잘 구현해주셨다는 것에 만족하시면 될 것 같고, 시간에 쫓기는 건 차차 해결되지 않을까 생각합니다.
(파일 이름이 Validarot이네요 허허 이마저도 급한.. 😂)

2단계에서도 열심히 고민해보시면 좋을 것 같고, 리뷰 잘 반영해주셨으니 이만 머지하도록 하겠습니다.
고생하셨어요!

2024-02-18 04:45 UTC, merged