[2단계 - 자동차 경주] 프룬(변민지) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #304
Opened 2024-02-18 15:09 UTC by chosim-dvlpr

안녕하세요 리뷰어님! 2단계 PR 드립니다. 

1단계 리뷰와 함께 개인적으로 공부한 내용을 포함하여 리팩터링을 진행했습니다. 잘 부탁드립니다 :)

<br/>

### view 파일의 Object.freeze 삭제

- view 역할에 해당하는 InputView와 OutputView는 각각 입력값을 받아 유효성 검사를 하는 기능과 콘솔에 출력하는 기능만을 담당하고 있습니다. view의 내부 메서드들은 속성을 변경시키는 역할을 하지 않는다고 생각하여 `Object.freeze`가 없어도 무방하다는 판단을 내렸습니다.

<br/>

### Validator 역할의 객체에 deepFreeze 적용

- Validator의 경우, 유효성 검사 로직이나 에러 메시지 등이 실행 중에 변경되어서는 안된다고 생각했습니다. 따라서 이를 보장하기 위해 `deepFreeze`를 추가하였습니다.
- `Object.freeze` 학습 중 `deepFreeze` 를 알게 되었습니다. `Object.freeze` 는 객체의 한 단계의 depth까지만 변경 불가능하도록 하여 더 깊은 단계부터는 적용이 안된다는 것을 깨달았습니다.
- Validator 파일의 전반에 객체 내의 객체까지 불변성을 보장하기 위한 `Object.freeze`가 중복되어 나타나는데요, 따라서 이를 제거하고 `deepFreeze` 를 적용했습니다.

<br/>

### 테스트 코드의 에러메세지 상수화

- 1단계에서 테스트 코드의 expectedErrorMessage를 확인하기 어렵다는 리뷰를 토대로 리팩터링을 진행했는데요! 객체 내의 객체로 errorMessage가 묶여있었던 것 때문인지, 테스트 코드에서 expectedErrorMessage로 바로 이동하기 어렵더라구요🥲 그래서 Validator와 테스트 코드에 공통으로 쓰이는 에러 메세지를 상수로 분리했습니다.
- 그런데 상수로 분리하는 경우 import 문이 아래와 같이 길어지게 되는데요, 깔끔하게 정리할 수 있는 방법이 있는지 궁금합니다!

```python
import {
  CAR_NAME_RANGE,
  CAR_NAME_REGEX,
  CAR_LENGTH_RANGE,
  ERROR_MESSAGE_REGEX,
  ERROR_MESSAGE_DUPLICATE,
  ERROR_MESSAGE_CAR_LENGTH_MIN,
  ERROR_MESSAGE_CAR_NAME_RANGE,
} from './constant.js';
```

<br/>

### `jest.fn` 을 사용하지 않고 테스트 코드 작성하기

- 2단계 요구 사항 중 하나가 `jest.fn` 을 사용하지 않고 테스트 코드를 작성하는 것이었는데요!
- 먼저 `jest.fn`을 사용한 첫 번째 모듈인 RandomMoveCountMaker에 대한 테스트를 어떻게 진행해야 할까 고민을 했습니다. random 배열을 생성하는 기능이기 때문에 랜덤으로 생성된 값은 테스트하기 어렵겠다는 생각이 들었습니다. 그래서 내부 값이 아닌 tryCount와 racingCarNamesLength에 따른 배열의 길이를 확인하는 코드를 작성했습니다.
- 두 번째로, ErrorHandler에도 `jest.fn` 기능을 사용했었는데요, `mockPrint` 를 통해 출력되는 값을 `consoleOutput` 에 넣어주는 방식으로 진행했습니다. 또한, 함수 실행 횟수의 경우 `callCount` 를 통해 카운팅된 숫자를 확인하는 로직을 추가했습니다.

<br/>

2024-02-18 15:10 UTC, chosim-dvlpr commented on src/domain/Cars/module.js
>      this.#racingCarDetails = racingCarNames.map((carName) => ({ carName, moveCount: 0 }));
Cars 모듈의 생성자 수정

- 기존에는 Cars의 생성자에서 createInitRacingCarDetails 메서드를 거쳐야만 racingCarDetails 값을 초기화하는 로직을 작성했습니다. 하지만 생성자는 그 자체로 속성을 초기화하는 역할을 해야 한다고 생각했습니다. 따라서 createInitRacingCarDetails 메서드를 거치지 않고 생성자에서 바로 racingCarDetails를 초기화하는 코드로 수정했습니다.

2024-02-19 14:50 UTC, liswktjs requested changes
안녕하세요 프룬 👋
빠르게 2단계를 반영해서 pr을 제출해주셨네요! 

1단계에서 2단계의 요구사항을 어느 정도 충족시켜주셨고 
테스트 관련해서도 모킹을 사용하지 않고 하는 조건을 잘 구현해주신 것 같아요 👍 

바로 approve 해도 무리 없는 코드라고 생각되지만,
그래도 프룬의 의견이 궁금해서 request change로 남깁니다! 

코멘트 남긴 부분에서 프룬 답변 기다리고 있겠습니다 👀

2024-02-19 14:50 UTC, liswktjs commented on src/validator/carName/constant.js
> +export const ERROR_MESSAGE_CAR_NAME_RANGE = `자동차 이름은 ${CAR_NAME_RANGE.min} ~ ${CAR_NAME_RANGE.max}자의 범위만 가능합니다.`;
하나의 파일 안에 export해야할 것이 많다보니, 아무래도 import 문이 길어지는 건 어쩔 수 없을 것 같아요 
이럴 때 import문을 줄이고 싶다면 같은 관심사 별로 객체를 한 번 더 묶어주는 것도 방법입니다 ! 
```
export const CAR_NAME_ERROR_MESSAGE = {
   'regex' : '',
   'duplicate': .... 
}
```

2024-02-19 14:50 UTC, liswktjs commented on src/domain/RandomMoveCountMaker/RandomMoveCountMaker.test.js
> +    'tryCount가 $tryCount이고, racingCarNamesLength가 $racingCarNamesLength일 때, randomMoveCounts의 길이는 tryCount 길이인 $tryCount 와 같다.',
jest.fn를 사용하지 않고 랜덤한 케이스에 대한 테스트를 잘 진행해주셨네요 👍
좋은 접근방식이라고 생각합니다!

2024-02-19 14:50 UTC, liswktjs commented on src/utils/deepFreeze.js
> +}
얕은 복사와 깊은 복사 관련해서 추가 학습으로 deepfreeze에 대해서도 알게 되셨군요 👍 
추가로 자바스크립트에서 참조에 대해서 더 공부해보시면 도움이 될 것 같습니다 !

2024-02-19 14:50 UTC, liswktjs commented on src/validator/common/CommonValidator.js
> +const CommonValidator = deepFreeze({
validatator에 deepFreeze를 사용해주셨군요 
그런데, 코멘트에서 deepFreeze 사용 이유로 남겨주신 것 중에 "실행 중 변경 방지"를 말해주셨어요
그럼, deepFreeze를 사용하지 않았을 때는 어떤 점이 바뀔 수 있는지 프룬의 생각을 남겨주실수 있나요? 
상수는 제외하고 isValid와 같은 함수 위주로 말해주시면 됩니다!

2024-02-20 14:03 UTC, liswktjs commented on src/validator/common/CommonValidator.js
> +const CommonValidator = deepFreeze({
프룬이 생각하는 객체 내에 다른 함수가 추가되는 경우가 무엇일까요? 
사람이 직접 변경을 하는 경우를 의미하는 거라면, 
보통은 개발을 할 때에 컨벤션을 모두 정하고 시작하기 때문에 개발자들 간에 의도적으로 해당 함수에 객체를 다른 곳에서 추가하거나 수정하는 일은 많이 없을 것 같아요 

보통 freeze로 객체를 얼리는 경우 불변성을 지킬 수 있어서 좋은 방법이기도 합니다! 
하지만, 오버엔지니어링이 되지 않도록 주의를 하는 것도 필요하다고 생각합니다

2024-02-20 14:06 UTC, liswktjs approved these changes
안녕하세요 프룬 👋

이번 자동차 미션 수고하셨습니다 🏎️
프룬이 코멘트에 남긴 곳에 추가 코멘트를 남겼어요 한 번 읽어주시고 만일 의견이나 더 궁금하신 점 있으시다면 코멘트로 남겨주세요! 

그럼 이만 approve 하겠습니다! 
로또 미션도 파이팅 입니다  🎱

2024-02-20 14:06 UTC, merged

2024-02-21 02:39 UTC, chosim-dvlpr commented on src/validator/common/CommonValidator.js
> +const CommonValidator = deepFreeze({
그렇군요! 다음 미션 때는 유의하며 진행해보겠습니다 ㅎㅎ감사합니다!