[1단계 - 자동차 경주 구현] 다윗(정다윗) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #34
Opened 2021-02-13 09:49 UTC by Da-Wit

안녕하세요. 마광휘님. 코드 리뷰 잘 부탁드립니다. 시간에 쫓겨 리팩터링을 제대로 못하고 그냥 pr보내고 있습니다. ㅠ
최대한 꼼꼼히 봐주시면 감사하겠습니다.

### **느낀 점**

- MVC처음 적용해봤는데 딱히 나은 점을 모르겠어요. 프로젝트가 너무 작아서 그런가
- 개발도 커뮤니케이션이 중요한 거 같아요.
- 초반에 좀 달릴걸...

### **미해결 된 문제**

- cypress/integration/bdd.spec.js 327번째 줄에서 통과되면 안되는데 통과가 됩니다. 시간이 없어서 해결 못하고 pr보냅니다.

2021-02-13 10:02 UTC, Da-Wit commented
https://da-wit.github.io/javascript-racingcar/
데모 사이트 입니다.^^

2021-02-15 04:03 UTC, Vallista commented
안녕하세요 ^^7 리뷰어 Vallista 입니다.
저도 잘 부탁 드립니다!

2021-02-15 13:34 UTC, Vallista requested changes
다윗님!

먼저 다윗님의 1단계 미션 제출 수고 많으셨습니다!
디테일한 내용은 코드 라인에 적어두었습니다! 

아래는 전반적인 피드백입니다.

전반적으로 `export default` 를 통해 동적할당 후, 내보내기를 해주셨는데요~ 해당 부분에 대해서는 [인치님께 리뷰드렸던 내용](https://github.com/woowacourse/javascript-racingcar/pull/20#pullrequestreview-589169973)와 동일한 답변을 전달드리겠습니다!

1. export 단위로 동적할당을 진행한 부분들이 있었습니다. Controller과 같은 코드의 부분은 공개함수를 추출하는 느낌이라 좋기도 했으나, 이렇게 되면 객체로 생성하는 의미가 없어보입니다. 객체로 생성하는 이유는 캡슐화나 은닉화를 통해 외장 객체의 객체단위의 커뮤니케이션을 기대하는 의미가 있습니다. 그런데, 이렇게 구현하게 되면 파일 안에서만 객체단위의 커뮤니케이션이 이루어질 수 있습니다. 그렇다는 것은 굳이 class가 아니라, function으로 만들고 function을 export만 해도 된다는 이야기 입니다.

2. export 시 객체를 생성하는 것의 또 다른 문제는, 객체 생성 시점이 코드를 불어들이는 시점과 동일하다는 것 입니다. 그렇다면 전혀 사용하지도 않을 때 메모리 점유를 계속 하고 있다는 것 입니다. 일반적으로 메모리 할당의 영역은, member 변수나 scope 안의 휘발성 변수가 stack 영역에 쌓이고, 동적할당과 같은 경우 heap에 쌓아서 메모리를 유용하게 쓰는데 초점을 맞춥니다. (물론 브라우저에서는 이런 메모리 관리를 가비지 컬렉터나 heap, stack 메모리 관리를 알아서 해주지만요) export로 가져오게 되면, Controller를 가져오는 import 단계에서 파일이 쓰이고 있는 경우 계속 메모리를 갖게되므로 메모리 해제 시점이나 메모리 생성 시점이 비효율적이게 됩니다. 즉 이미 메모리 풀을 크게 들고 있다는 의미이죠. 이러한 자그마한 소프트웨어의 경우 큰 문제는 없겠으나. 커다란 대형 어플리케이션에서는 싱글톤이나 멀티턴 패턴을 제외하고는 이러한 흐름으로 코딩을 작성하는건 별로 좋지 못한 패턴으로 보입니다.

3. 전반적으로 MVC 패턴에 대해서 이해가 조금 부족하신걸로 보입니다! MVC는 모델과 뷰 로직을 각각 갖고 있어, Controller에서 두 로직을 병합하는 비즈니스 로직을 들고 있고 사용처에서 controller의 이벤트에 구독을 하는 형태로 크게 이루어집니다. 즉 view에서는 controller의 이벤트를 구독하고, controller에서는 뷰에 무슨 행동이 생기거나 했을때, model의 데이터를 변경하는 형태로 구현하시면 됩니다. 다만 지금의 코드에서는 model과 view 서로 dependency를 갖고있어 MVC에서 기대하는 목표가 틀어진 것 같습니다!

4. 커밋이 양식 없이 emoji로 되어 있어서 보기가 난해했습니다 😭  일반적으로 사용하는 `feat:`, `refactor:` 등으로 나타내 주시면 더 좋은 가독성을 볼 수 있을 것 같습니다 👍

5. 테스트 코드는 최대한 디테일하게 짜주신 것 같아 좋았습니다!! 👍 👍

2021-02-15 13:34 UTC, Vallista commented on src/js/Model.js
> +	getBoolsAboutMovement() {
```
getBoolsAboutMovement() {}
```

요렇게 get을 표현하는 방식도 있지만.

```
get boolsAboutMovement(){
}
```

요렇게 표현하는 방법도 있습니다.

2021-02-15 13:34 UTC, Vallista commented on src/js/Model.js
> +			View.arrowRender(boolsAboutMovement);
MVC 패턴에서 Model과 View는 dependent 되어있으면 안됩니다!
view에서 model은 들고있어도 되지만, model에서 view에 의존적이면 안되어요.

2021-02-15 13:34 UTC, Vallista commented on src/js/Model.js
> +	getBoolsAboutMovement() {
그리고 bools abmout movement 함수가 무슨 일을 하는지 명확하게 네이밍을 잘 모르겠습니다!
movement가 가능한 친구를 boolean 형태로 내려주는 함수인가요?

get movableCars() 정도 작명해서 사용하는게 더 좋지 않을까요?

2021-02-15 13:34 UTC, Vallista commented on src/js/Model.js
> +			this.isInMovableRange(
지금 보면, 두 번 이상 쓰이지 않고, 외부적으로 공개용이 아닌 함수를 클래스 내 메소드를 사용하여 nested nested... 되는 형태로 코딩을 하고 계세요!

이렇게 되면, 추후에 함수에서 함수를 찾고 함수를 찾는... 일련의 과정이 반복되면서 코드를 복잡하고 어렵게 만듭니다.
두 번 이상 사용되거나 명확하게 외부에 노출이 되는 경우에 메소드로 만드시고, 외부에 노출이 필요없다면 내부용 함수를 만들어 로직만 분리하는 형태로 관리하시는 걸 추천드립니다!

지금 이 예시의 경우에는 `getBoolsAboutMovement` > `iterateByCarsToMove` > getRandomNumber > iterateByCarsToMove > isInMovableRange ... 형태로 계속 왔다갔다 하니 굉장히 코드를 가독하기가 어렵습니다.

2021-02-15 13:34 UTC, Vallista commented on src/js/Model.js
> +	move(car) {
클래스 내 메소드이므로, `this.cars` 객체에 직접 접근해서 어떤 `car` 객체의 아이디인가를 판단한 후, `this.car[idx].score ++` 형태로 구현하는게 더 좋아보입니다.

2021-02-15 13:34 UTC, Vallista commented on src/js/Model.js
> +		return `🏆 최종 우승자: ${winners.join(", ")} 🏆`;
view에 있어야 할 코드가 model에 있습니다!

2021-02-15 13:34 UTC, Vallista commented on src/js/Model.js
> +		if (this.cars.length !== 0) {
if - else if 로 이어지는 코드를 만들기보다, 소스코드 양을 줄이면서 가독성을 확보하는 `switch`를 사용하는게 어떨까요?

2021-02-15 13:34 UTC, Vallista commented on src/js/Model.js
> +	validateCount(submittedCount) {
해당 함수는 model에 있기보다 util에 있는게 더 맞지 않을까요~?

2021-02-15 13:34 UTC, Vallista commented on src/js/Model.js
> +	isNameBiggerThan(maxNameLength, names) {
model에서는 객체에 대한 데이터를 메소드로 만드는 곳 입니다.
model과 연관없이 데이터만 받아서 오롯 처리하는 것은 메소드라기 보다, 함수입니다.
그렇기 떄문에 해당하는 코드 로직이 모델에 있는게 맞는지, 객체지향적으로 맞는지 한번 더 생각해볼 필요가 있어보입니다!

2021-02-15 13:34 UTC, Vallista commented on src/js/Controller.js
> +		this.addCountButtonEvent(this.countClickHandler.bind(this));
this 바인딩의 이슈로 이렇게 사용해주셨어요!
arrow function으로 this binding에 대한 이슈를 없애거나, constructor() 에서 아래와 같이 사용도 가능합니다.

```
constructor() {
  this.countClickHandler = this.countClickHandler.bind(this)
}
```

2021-02-15 13:34 UTC, Vallista commented on src/js/Controller.js
> +	countClickHandler() {
`countClickHandler`와 `nameClickHandler`가 뒤에 handler가 붙는 이유가 있을까요~?
그리고 컨벤션상으로 count나 name과 같은 행동이 아닌 주어가 앞에 오는 것은 네이밍을 작성하는데 별로 좋지 못합니다!

on... 혹은 clickTo... 등으로 행동을 먼저 정의해주세요!

2021-02-15 13:34 UTC, Vallista commented on src/js/View.js
> +		$resultH2.innerText = Model.getResultText();
여기서는 model을 참조할 이유가 없습니다!
또한 view와 model이 서로 참조하므로 [circular reference](https://www.perfectxl.com/excel-glossary/what-is-circular-reference/) 이슈가 생길 수 있습니다!

2021-02-15 13:34 UTC, Vallista commented on src/js/View.js
> +import { IDS, TEMPLATES } from "./constants.js";
Templates에 적어놓았지만, template으로 따로 떈 장점이 별로 없는 것 같습니다!

2021-02-15 13:34 UTC, Vallista commented on src/js/View.js
> +import { IDS, TEMPLATES } from "./constants.js";
오히려 땜으로써 파일 두 개를 열고 수정해야하는 귀찮은 상황이 발생할 것 같은데, 괜찮을까요?

2021-02-15 13:34 UTC, Vallista commented on src/js/View.js
> +		$settingContainer.insertAdjacentHTML("beforeend", TEMPLATES.COUNT_SECTION);
아래에서는 document.createElement를 사용하고 있고, 여기서는 insertAdjacentHTML을 사용하고 있네요!
insertAdjacentHTML을 사용하는 이유는 addEventListener로 유지해놓은 이벤트를 지속적으로 바인딩을 하기위해 사용하는 것으로 추측이 됩니다! 그런데, document.createElement로 충분히 이벤트를 유지할 수 있을텐데 두 개를 섞어 쓰는 이유가 있을까요~?

2021-02-15 16:02 UTC, Da-Wit commented on cypress/integration/bdd/bdd.spec.js
> +context("bdd", () => {
bdd 내에서도 context를 나눠서 저장하라는 걸 원하시는 건가요?

2021-02-16 10:07 UTC, Vallista commented on cypress/integration/bdd/bdd.spec.js
> +context("bdd", () => {
BDD만 테스트를 한다는게.. bdd가 무슨 약어인지 제가 몰라서 잘 모르겠네요.. behavior develop driven의 약자일까요?

2021-02-17 14:17 UTC, Da-Wit commented on cypress/integration/bdd/bdd.spec.js
> +context("bdd", () => {
네 맞습니다.

2021-02-20 06:05 UTC, Da-Wit commented on src/js/View.js
> +		$settingContainer.insertAdjacentHTML("beforeend", TEMPLATES.COUNT_SECTION);
insertAdjacentHTML을 사용하는 이유는 template을 문자열 형태로 만들어서 그것을 dom에 삽입하기 위해서입니다. 그렇게 하는 것이 createElement로 하나하나 요소들을 조립해서 appendChild하는 것 보다 가독성이 좋을 거라고 생각했습니다. 근데 둘 중 하나만 쓰는 것이 더 통일성 있을 거 같네요. 그래서 기존에 appendChild하는 부분도 다 insertAdjacentHTML로 바꾸려고 하는데 어떻게 생각하시나요?

2021-02-21 01:00 UTC, Da-Wit commented on src/js/View.js
> +import { IDS, TEMPLATES } from "./constants.js";
template로 따로 땐다는게 무슨 말인지 잘 이해가 안가요. IDS랑 TEMPLATES 두 객체를 하나로 만들어서 constants.js에서는 constnats 객체 하나만 default export만 하고 그 객체로 IDS, TEMPLATES을 접근하라는 말씀이신가요?

그리고 추가로 저는 리뷰 반영 중에 templates.js 파일 하나 만들어서 거기서 템플릿들을 만드는 스태틱 메서드들의 집합인 클래스를 만들까 생각중인데요. 이건 어떻게 생각하시나요? 불필요할까요?

2021-02-21 04:27 UTC, Da-Wit commented
안녕하세요. 좀 늦은 감이 있지만 리뷰요청 다시 보냈습니다. 일단 createElement와 insertAdjacentHTML 중 하나만 사용하라고 하신 거 뺴고는 다 적용했습니다.  둘 중 하나만 사용하라고 하신 것을 적용하지 않은 이유는 뭘 써야 할 지 모르겠어서입니다. 성능면에서 뭐가 좋을 지 모르겠고, 가독성은 template로 하는 게 좋아보이는데 가독성만 생각해서 결정하면 안될 거 같아서요. 또, 만약 template를 쓴다면 template만 따로 파일을 만들어서 template을 반환하는 함수들을 만들어야 하나(지금은 constants에서 정적인 문자열을 가져오고 있어서 이걸 바꿔야 하나) 잘 모르겠어서 확실히 답변해주시면 그것대로 할려고 합니다.

2021-02-21 04:28 UTC, Da-Wit commented
나머지는 적용하긴 했는데 이상하게 했을 수도 있으니 꼼꼼히 봐주시면 감사하겠습니다.^^

2021-02-22 12:43 UTC, Vallista commented on src/js/View.js
> +		$settingContainer.insertAdjacentHTML("beforeend", TEMPLATES.COUNT_SECTION);
좋은 것 같습니다!

2021-02-23 17:35 UTC, Da-Wit commented on src/js/Model.js
> +		if (this.cars.length !== 0) {
else if를 if로 바꾸고 사이사이에 공백을 넣었는데 이러면 switch 안써도 되겠죠? 충분히 가독성이 좋다고 생각합니다.

2021-02-23 18:00 UTC, Da-Wit commented
pr 다시 보냅니다. 요구하신 것들(Object.freeze 사용, Template view에서 관리, MVC 패턴에 맞게 구조 변경, move 전에 인덱스 유효성 검사) 다 적용했습니다.

2021-02-24 11:34 UTC, Vallista approved these changes
오!! 코드 쫙 봤는데 처음 코드와 다르게 엄청 잘 분리가 되었네요!!!! 좋은 것 같습니다!
딱 하나 코드리뷰를 진행했는데요! 요거는 2단계 진행하시면서 함께 수정하면 될 것 같습니다!

👏 👏  훌륭합니다!

2021-02-24 11:34 UTC, Vallista commented on src/js/Controller.js
> +		const RegExp = /[^a-z가-힣A-Z,]/gi
regexp도 constant로 빼면 좋을 것 같습니다!

2021-02-24 11:34 UTC, Vallista commented
수고 많으셨어요 다윗님!!

2021-02-24 11:34 UTC, merged