[2단계 - 자동차 경주 구현] 썬(권선영) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #41
Opened 2021-02-14 23:37 UTC by SunYoungKwon

# 🚩 자동차 경주 게임 step2

## 구현기능

- 게임 결과가 모두 나타나고 2초 후 `alert`으로 축하 메세지를 띄운다.
- 1초의 텀을 두고 각 턴의 결과가 화면에 출력된다.

## 미션을 진행하며

### `Car` 객체 수정
각 턴마다 1초의 시간을 두고 화면에 출력되는 기능을 구현할 방법에 대해 고민했을 때 2가지 경우를 떠올렸습니다.

1. 각 턴 마다 play() -> `Car`객체에 점수 update -> `RacingResult` 출력
2. 게임 결과를 한 번에 구해서 각 턴의 결과를 저장해두고 그 정보를 이용해 각 턴 별로 `RacingResult` 업데이트

저는 제 스스로 진행 흐름을 따라가며 코드를 수정하기에 2번이 편리해서 2번으로 정했습니다.
그래서 `Car` 객체에 `movesPerTurn`이라는 배열을 저장하고 `move()`가 실행 될 때 그 턴을 결과를 받아 배열에 추가하도록 했습니다.

### 시간을 다루며 겪은 시행착오
원하는 기능을 다 만들고 난 뒤 실행을 시켜보니 `RacingResult`와 `RacingWinner`가 동시에 나타나 고민을 많이 했습니다. `RacingResult`의 출력이 끝난 후에 `RacingWinner`가 나타나야 하는데 말이죠...
`async-await`를 사용해도 문제가 해결되지 않아 원인을 찾으려고 해결을 위해 꽤 오랜 시간을 썼습니다. 뒤늦게 `Promise`를 반환하는 곳이 없다는 것을 뒤늦게 깨달아 수정하니 잘 작동하더라구요. 이번 미션이 비동기와 관련 문법에 대해 다시 정리하고 공부하는 계기가 되었습니다.

## 질문
- comment로 남기겠습니다.

😊😊😊step2도 리뷰 잘부탁드립니다😊😊😊

2021-02-15 18:14 UTC, HyeonaKwon requested changes
안녕하세요! 두 번째 미션 구현하느라 고생하셨습니다. 시행착오 너무 멋진데요? 👍 

전체적으로는 setState() 의 매개변수 형태를 모두 맞췄으면 좋겠어요. 어느 곳은 업데이트할 상태의 객체를 넘기고, 어느 곳은 업데이트할 상태의 값 하나를 파라미터로 넘기는 경우가 있는데요, 요 형태를 맞추면 좋을 것 같아요!
세부 내용은 코멘트로 남겼습니다! :)

2021-02-15 18:14 UTC, HyeonaKwon commented on src/js/model/Car.js
> +  }
```javascript
return this.movesPerTurn.filter(isMove => move).length;
```
이렇게 구현해볼 수 있을 것 같아요!

2021-02-15 18:14 UTC, HyeonaKwon commented on src/js/components/RacingWinner.js
> +    }, 0);
```javascript
const maxScore = Math.max(...cars.map(car => car.getScore()));
```
로도 구현해볼 수 있겠네요!

2021-02-16 00:53 UTC, SunYoungKwon commented on src/js/components/RacingResult.js
> +      this.render();
`setState`는 화면을 그리는데 영향을 주는 상태를 새로운 상태로 변경시키고 화면을 업데이트하는 용도로 사용해 왔습니다. `setState`에서 `render`를 분리하면 `render`를 호출하는 곳이 여러 곳이 될 수 있지 않을까요? 저는 `render`함수는 초기화 or 상태가 업데이트 되었을 때 `setState`에서 이렇게 딱 두 곳에서만 불리도록 해왔거든요. 
개인적으로 `render`가 여러 곳에서 불리게 된다면 화면의 변화가 일어난 곳을 추적하기 어려워 질 수 있다고 생각했습니다.
이 부분에서 조언을 얻고 싶습니다.
(지금은 `cars`는 화면 업데이트에 관여하지 않고 `turn`의 상태가 변경되었을 때만 `render`가 불리면서 조금 이상한 모양이 된 것 같지만...😥)

2021-02-16 00:57 UTC, SunYoungKwon commented on src/js/model/Car.js
> +  getScoreWithTurn(turn) {
매게변수와 함께 자연스럽게 읽히는 게 신기하네요!

2021-02-16 02:36 UTC, HyeonaKwon commented on src/js/components/RacingResult.js
> +      this.render();
그런거라면 setState 안에서 nextTurn 이 바꼈을때만 하는게 아니라 setState 들어오고 상태를 변경한 후에 매번 render 가 호출되어야 말이 되는 것 같아요!
어떤 조건에 render 가 실행되는지 setState 코드를 전부 읽어봐야 알 수 있는 부분이니까요!

2021-02-16 04:00 UTC, SunYoungKwon commented on src/js/components/RacingResult.js
> +      this.render();
저는 `cars`의 상태는 화면을 그리는 데 영향을 주지 않는다고 생각하고 위 처럼 코드를 작성했습니다. 그런데, 다시 생각해보니 `cars`가 업데이트 되면 화면에 자동차 이름이 나타나고 이후 `turn`이 업데이트 될 때마다 게임 결과(각 턴의 결과에 따른 화살표)가 나타난다고 생각하면 `cars`가 업데이트 될 때도 `render()`를 호출하는게 맞는 것 같습니다. `render()`

2021-02-16 04:03 UTC, SunYoungKwon commented on src/js/components/RacingResult.js
> +  setState({ nextCars, nextTurn }) {
업데이트 할 다음 상태라는 뜻으로 next를 앞에 붙였었는데, 오히려 혼란을 줄 수 있겠네요. 업데이트 할 상태는 this에 저장되어 있으니 next를 빼고 이름을 동일하게 가져가도 좋을 것 같습니다. 수정하겠습니다😀

2021-02-16 04:38 UTC, SunYoungKwon commented on src/js/components/RacingResult.js
> +  setState({ nextCars, nextTurn }) {
'next' prefix를 제거하면서 `setState`가 받는 파라미터로 객체로 통일 시켜 주었습니다.
[변경커밋](https://github.com/woowacourse/javascript-racingcar/pull/41/commits/6281cad192056ce51909acf94dc99e9981bcaadb)

2021-02-16 09:29 UTC, SunYoungKwon commented on src/js/components/App.js
> +        car.recodeMove(getRandomNumber({ min: MIN_NUMBER, max: MAX_NUMBER }) >= MOVE_BOUNDED_NUMBER);
저도 각 턴마다 움직였는지 여부를 저장하도록 수정하면서 `move()`라는 이름이 어색하여 `recodeMove(isMove)`로 변경했습니다. 
Car객체에서 각 턴마다 움직였는지 여부를 저장하기 때문에 `tryCount`를 받아 Car객체 내에서 반복문을 돌리면서 댑스를 줄이는 것도 좋을 것 같습니다. `recodeMoves(tryCount)`정도로 이름을 변경할까 싶은데 괜찮을까요?

2021-02-16 09:44 UTC, SunYoungKwon commented on src/js/model/Car.js
> +    return score;
함수가 훨씬 간단해졌네요!!! 반복문을 쓸 때 Array 내장함수를 사용할 수 있는지 한 번 더 체크하는 습관을 들여야겠습니다😂
[변경커밋](https://github.com/woowacourse/javascript-racingcar/pull/41/commits/e73090df98609e8f25d9bee22d5139fc88b87c7b)

2021-02-16 09:52 UTC, SunYoungKwon commented on src/js/components/RacingWinner.js
> +    }, 0);
더 짧으면서도 읽기 좋은 코드를 만들 수 있었네요. `Math` 내장 함수의 종류에 대해 공부해봐야겠습니다😀
[변경커밋](https://github.com/woowacourse/javascript-racingcar/pull/41/commits/cd5256753c7bc51af509321dfa5e0fc408c4f90a)

2021-02-17 08:34 UTC, HyeonaKwon commented on src/js/components/App.js
> +        car.recodeMove(getRandomNumber({ min: MIN_NUMBER, max: MAX_NUMBER }) >= MOVE_BOUNDED_NUMBER);
근데 recode 가 무슨 뜻이에요? 생소한 단어라..
![image](https://user-images.githubusercontent.com/46472795/108173782-e7c21000-7141-11eb-8478-50a671221717.png)

2021-02-17 08:38 UTC, SunYoungKwon commented on src/js/components/App.js
> +        car.recodeMove(getRandomNumber({ min: MIN_NUMBER, max: MAX_NUMBER }) >= MOVE_BOUNDED_NUMBER);
앗...record오타입니다. 왜 저렇게 썼을까요...?😂

2021-02-17 08:39 UTC, HyeonaKwon commented on src/js/components/RacingResult.js
> +  setState({ nextCars, nextTurn }) {
너무 좋습니다 👍

2021-02-17 08:50 UTC, HyeonaKwon commented
크 말끔히 수정해주셔서 감사합니다 👍  다음 미션도 화이팅입니당!!

2021-02-17 08:51 UTC, HyeonaKwon commented on src/js/components/App.js
> +        car.recodeMove(getRandomNumber({ min: MIN_NUMBER, max: MAX_NUMBER }) >= MOVE_BOUNDED_NUMBER);
아하ㅋㅋㅋㅋㅋㅋ 근데 보통 함수는 명사가 앞으로 와야하니 moveRecord 로 해야할 것 같아요!

2021-02-17 09:00 UTC, SunYoungKwon commented on src/js/components/App.js
> +        car.recodeMove(getRandomNumber({ min: MIN_NUMBER, max: MAX_NUMBER }) >= MOVE_BOUNDED_NUMBER);
함수는 보통 동사를 앞에 쓰지 않나요...?

2021-02-17 09:03 UTC, HyeonaKwon commented on src/js/components/App.js
> +        car.recodeMove(getRandomNumber({ min: MIN_NUMBER, max: MAX_NUMBER }) >= MOVE_BOUNDED_NUMBER);
아 죄송해요 동사 얘기한거였어요!!

2021-02-17 09:09 UTC, SunYoungKwon commented on src/js/components/App.js
> +        car.recodeMove(getRandomNumber({ min: MIN_NUMBER, max: MAX_NUMBER }) >= MOVE_BOUNDED_NUMBER);
저 함수는 `tryCount`를 받아서 각 턴마다 자동차가 움직였는지 여부를 기록하는 동작을 하니 기록이 주행위라고 느껴지는데, `recordMovements`나 `recordScores`는 어떨까요?

2021-02-17 09:11 UTC, HyeonaKwon commented on src/js/components/App.js
> +        car.recodeMove(getRandomNumber({ min: MIN_NUMBER, max: MAX_NUMBER }) >= MOVE_BOUNDED_NUMBER);
아하 저는 데이터 개념의 레코드인 줄 알았어요! 좋습니당 :)

2021-02-17 09:12 UTC, merged

2021-03-09 03:15 UTC, SunYoungKwon commented on cypress/integration/racing_car_game.spec.js
> +        expect(alertStub.getCall(0)).to.be.calledWith(WINNER_MESSAGE(winners));
2000 상수로 분리!

2021-03-09 03:15 UTC, SunYoungKwon commented on cypress/integration/racing_car_game.spec.js
>          .should('have.text', `🏆 최종 우승자: ${winners.join(WINNER_SEPARATOR)} 🏆`);
상수로 분리!

2021-03-09 03:15 UTC, SunYoungKwon commented on src/js/components/CarNameInput.js
> +    this.$carNameSubmitBtn = this.$target.querySelector('button');
다른 input이나 button이 추가된다면...?

2021-03-09 03:15 UTC, SunYoungKwon commented on src/js/components/RacingResult.js
> +
`??` 사용가능

2021-03-09 03:15 UTC, SunYoungKwon commented on src/js/components/TryCountInput.js
> +    this.$tryCountSubmitBtn = this.$target.querySelector('button');
다른 input이나 button이 추가된다면?22