[2단계 - 자동차 경주 구현] 브콜(오태은) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #43
Opened 2021-02-15 02:57 UTC by Tanney-102

안녕하세요, 브콜입니다. 🥦
자동차 미션 2단계 구현하였습니다.
바쁘신 와중에 좋은 리뷰 감사합니다 ㅎㅎ

### Step2 기능
1. 자동차 경주의 턴이 진행될 때마다 1초의 텀을 둔다.
  - 각 텀 마다 spinner 애니메이션 렌더링
  - spinner 애니메이션은 reqeustAnimationFrame을 활용해 구현했습니다.
    -> src/script/animation/spinner.js
  - 1초동안 spinner를 보여주고 callback을 실행하는 setTimeoutWithSpinner 함수를 구현했습니다.
    -> src/script/utils/timeUtils.js
  - 1초가 지나고 결과가 나오기까지 잠깐의 간격(약 300ms)을 두었습니다.
  - 단계별 진행을 구현하기 위해 controller에 runProgressiveRace메서드를 만들고 playRacingCarGame에서 호출하도록 했습니다.
  - runProgressiveRace메서드에서 setTimeoutWithSpinner에 View.updateResultArea를 콜백으로 넘겨 호출합니다.
    -> 1초간 spinner를 보여주고 경주의 경과를 업데이트 하는 방식
 
2. 경주가 끝나면 약 2초 뒤에 alert 축하 메시지를 보여준다.
  - controller의 finishGame메서드 내에서 setTimeout을 통해 alert을 호출했습니다.

<br>

### 테스트
1. 순차적으로 경주가 진행된 이후에 우승자를 테스트 하도록 수정했습니다.
2. 우승자를 축하하는 alert 메시지를 테스트하는 코드를 추가했습니다.

2021-02-15 17:20 UTC, HyeonaKwon requested changes
안녕하세요 브콜님! 두 번째 미션도 구현하느라 고생 많으셨어요 :)
자세한 내용은 코멘트 남겼습니다! 확인 부탁드려요~

2021-02-15 17:20 UTC, HyeonaKwon commented on src/scripts/RacingCarGame/RacingCarGameController.js
> +    }
```javascript
[...Array(tryCount)].reduce((promiseChain) => {
    return promiseChain.then(() => {
        return new Promise(resolve => {
          doSomething();
          setTimeout(resolve, delay);
        );
    });
}, Promise.resolve());
```
for 문 대신 reduce 를 활용해볼 수도 있을 것 같아요!

2021-02-17 09:02 UTC, Tanney-102 commented on src/scripts/RacingCarGame/RacingCarGameController.js
> +    }, 2000);
넵 해결했습니다 ㅎㅎ
commit link : https://github.com/woowacourse/javascript-racingcar/pull/43/commits/c87a6da228abee1942829c3ebacb556011edc641

2021-02-17 09:19 UTC, Tanney-102 commented on src/scripts/animations/spinner.js
> +export default class Spinner {
아아 넵 ㅜㅜㅜ 이걸 놓쳤군요...수정했습니다 ㅎㅎ

2021-02-17 09:21 UTC, Tanney-102 commented on src/scripts/animations/spinner.js
> +    cancelAnimationFrame(this.rafId);
정상 작동하도록 수정했습니다!
raf가 반환하는 id 값이 증가하는 정수 값으로 보이던데 혹시 해당 메서드에서 this.deg대신 사용해도 무리가 없을까요?

commit link : https://github.com/woowacourse/javascript-racingcar/pull/43/commits/f3e70aab512b9c194cb49d2116fd3e8e60d83986

2021-02-17 09:27 UTC, Tanney-102 commented on src/scripts/RacingCarGame/RacingCarGameController.js
> +import Model from "./RacingCarGameModel.js";
넵 수정했습니다 ㅎㅎ
commit link : https://github.com/woowacourse/javascript-racingcar/pull/43/commits/9414f703ffd99c5ec77eee33a8115f3cbf637187

2021-02-17 09:35 UTC, Tanney-102 commented on src/scripts/utils/timeUtils.js
> +      }, 300);
spinner가 사라지고 곧 바로 다음 setTimeoutWithSpinner가 호출될 경우 중간 결과가 강조되기 보다 spinner만 자꾸 보이는 것 같았습니다. 특히 랜덤값에 의해 car가 앞으로 진행을 하지 않을 경우 이미 다음 턴으로 넘어갔음에도 spinner가 멈추지 않고 지속적으로 돌아가는 것처럼 보이기도 했습니다. 어떤 기능적인 부분이라기 보다 심미적인 부분에 관한 디테일인데, 그때 그때 중간 결과를 강조 및 음미(?) 하고 각 턴을 구분 짓는 공백을 의도 했습니다.

2021-02-17 09:38 UTC, Tanney-102 commented on src/scripts/RacingCarGame/RacingCarGameValidator.js
> +    if (!RacingCarGameValidation.isInteger(tryCount)) {
지난 번 수정에서 놓쳤네요ㅜㅜㅜ 수정했습니다 ㅎㅎ
commit link : https://github.com/woowacourse/javascript-racingcar/pull/43/commits/484960ac2f817a77312357232fc5d363e4653bea

2021-02-17 09:44 UTC, Tanney-102 commented on src/scripts/RacingCarGame/RacingCarGameController.js
> +    View.changeInnerText($carNameSubmit, "수정");
넵 진작에 했어야했는데 이제야 합니다..
commit link : https://github.com/woowacourse/javascript-racingcar/pull/43/commits/da99cbe6079bcd56fe7f9afa066dcb01a1024695

2021-02-17 10:09 UTC, Tanney-102 commented on src/scripts/RacingCarGame/RacingCarGameController.js
> +    }
reduce와 promise 체인을 활용하도록 수정해봤습니다. 
commit link : https://github.com/woowacourse/javascript-racingcar/pull/43/commits/ab53406d2a1cad42686b49110b04d064c252801e

아, 그리고 **질문**이 있습니다.
배열의 내장 메서드를 활용할 때 [...Array(num)] 대신 new Array(num)을 사용해도 되는지, 안된다면 어떤 차이점이 있는지 궁금합니다.

2021-02-17 10:11 UTC, Tanney-102 commented
밤낮 없이 쏟아지는 리뷰 요청에 정신 없으실텐데 하나하나 정성껏 살펴주셔서 감사합니다 ㅎㅎㅎ 👍👍👍👍👍👍👍

2021-02-17 13:44 UTC, HyeonaKwon commented on src/scripts/RacingCarGame/RacingCarGameController.js
> +    }
Array(3) 은 언뜻보면 [undefined, undefined, undefined] 가 될 것 같지만 실제로 실행해보면 그렇지 않습니다.
그렇지만 [...Array(3)] 은 [undefined, undefined, undefined] 가 됩니다.
요거의 차이를 알아보시면 좋을 것 같아요!

2021-02-17 13:50 UTC, HyeonaKwon commented on src/scripts/animations/spinner.js
> +    cancelAnimationFrame(this.rafId);
음.. deg 를 일정하게 증가하는 정수값으로 사용하시는 것 같은데, requestAnimationFrame 에서 반환되는 값이 일정하다고 정해져 있는게 아니라 좀 애매하네요! 이 곳 뿐만 아니라 다른쪽 코드에서 requestAnimationFrame 을 호출하면 id 값은 더더욱 일정하지 않을거에요.

2021-02-17 13:50 UTC, HyeonaKwon commented
수정내용 확인했습니다! 코멘트 내용 빠짐없이 반영해주셔서 감사해요 👍  고생하셨어요!

2021-02-17 13:51 UTC, merged

2021-02-17 14:04 UTC, Tanney-102 commented on src/scripts/animations/spinner.js
> +    cancelAnimationFrame(this.rafId);
아아 다른 곳에서도 호출 될 수 있는 부분도 고려를 해야겠네요! ㅎㅎ 조언 감사합니다!

2021-02-17 14:09 UTC, Tanney-102 commented on src/scripts/RacingCarGame/RacingCarGameController.js
> +    }
아아 Array()가 요소 없는 배열을 반환하는군요!
그럼 [...arr] 는 배열 arr의 length에 의존하는 걸까요? 한 번 공부해보겠습니다ㅎㅎ

2021-03-09 03:34 UTC, Tanney-102 reviewed
### 셀프 리뷰 종합
1. 상수화 해야할 부분들을 잘 구분하기
2. promise 체이닝도 좋지만 async await을 통해 가독성을 고려할 필요가 있음
3. 꼭 없어도 될 함수들과 이름에서 명시하는 일 외에 할 일이 있는 함수들, 자기가 하는 일도 제대로 명시를 못하는 함수들 등을이 정리될 필요가 있음

2021-03-09 03:34 UTC, Tanney-102 commented on cypress/integration/racing_car_game.spec.js
> +        }
<셀프 리뷰>
테스트할 자동차 이름을 배열로 상수화 해놓고 사용해도 좋을 것 같다.

2021-03-09 03:34 UTC, Tanney-102 commented on src/scripts/RacingCarGame/RacingCarGameController.js
> +    );
<셀프 리뷰>
인수 중 6이 어떤 기준에서 결정된 수인지 알 수 없음. 상수화 필요

2021-03-09 03:34 UTC, Tanney-102 commented on src/scripts/RacingCarGame/RacingCarGameController.js
> +    }, Promise.resolve());
<셀프 리뷰>
forEach와 async await을 사용해도 좋을 것 같음

2021-03-09 03:34 UTC, Tanney-102 commented on src/scripts/RacingCarGame/RacingCarGameController.js
> +    if (!Validator.isTryCountValid(tryCount)) {
<셀프 리뷰>
아니 당최 뭘 validate 하겠다는 건지 알 수 가 없네요 브콜씨;;

2021-03-09 03:34 UTC, Tanney-102 commented on src/scripts/RacingCarGame/RacingCarGameValidator.js
> +      alert(CAR_NAME_LENGTH_EXCEEDED);
<셀프 리뷰>
validator에서는 유효성 검사만 하고 alert을 하지는 않는 것이 좋을 것 같음
boolean 값만 충실하게 리턴해서 닉값하자

2021-03-09 03:34 UTC, Tanney-102 commented on src/scripts/RacingCarGame/RacingCarGameValidator.js
>    }
<셀프 리뷰>
이러한 종류의 validate은 굳이 함수로 만들지 않고 내장 메서드를 이용하는 게 좋을 것 같음

2021-03-09 03:34 UTC, Tanney-102 commented on src/scripts/RacingCarGame/RacingCarGameValidator.js
>      }
<셀프 리뷰>
CarList라고 명시하니까 도메인에 메여있는 너낌..
length에 대한 검사만 할거면 굳이 함수로 분리할 필요도 없어 보임