[1단계 - 자동차 경주 미션] 샐리(이자선) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #65
Opened 2022-02-11 07:24 UTC by liswktjs

자동차 경주 미션 제출합니다 :) 

느낀점들

- cypress에 익숙하지 않아 조금 해맸지만 태태와 함께 cypress document를 읽고 예시를 찾아보면서 적용하고 테스트 할 수 있었습니다. 특히 테스트 코드들 간의 중복된 부분들을 함수화 하여 분리할 때 혼자 했을 때 보다 빠르게 진행할 수 있었습니다 
- 자동차 경주 게임 미션의 경우 프리코스에서 진행했었던 미션이였기에 페어프로그래밍을 진행하면서 자연스럽게 서로의 문제 풀이 방식을 비교해 볼 수 있어습니다. 개인적으로 저는 저번 미션에서 클래스를 사용하지 않고 모두 함수로 문제풀이를 진행했었는데 페어 프로그래밍을 통해서 클래스를 활용해서 문제 풀이를 해볼 수 있었습니다. 

아쉬운 점들 

- 유저가 입력한 값들의 유효성을 평가할 때의 로직이 계속 마음에 걸렸습니다. if문을 여러번 사용하지 않고 유효성을 평가할 수 있는 방법이 있을까? 와
 어떤식으로 유효값을 처리해서 넘길지에 관해서 궁금합니다.  예를들어 유효성을 평가하는 함수에서 유효한 값일 경우 유효한 값을 넘기고 처리할지 아니면 유효한지 판단만 해서 true /false만을 리턴해서 유효성 평가하는 함수를 호출하는 쪽에서 입력값을 처리하는 것이 좋을지에 관해서  의문이 계속 남아서 이 기회를 통해서 리뷰어님의 의견을 받아보고 싶습니다:)

2022-02-11 13:56 UTC, EungyuCho requested changes
안녕하세요. 리뷰어 아사라고 합니다.
아쉬운점에서 질문주신 부분은 아래 코멘트에 남겨드렸어요.

전체적으로 코드가 깔끔하게 작성되어 있고 커밋을 잘 분리해주셔서 리뷰하기 좋았어요. 
아래 코멘트 참고하셔서 개선할만한 부분이 있다면 개선해주시고 궁금하신 점이 있다면 다시 코멘트 주시면 좋을 것 같아요 :)

- `moudles` 폴더를 만들어서 코드를 잘 분리해주셨어요 👍 
- 꼼꼼하게 입력값을 검증하려고 하신점이 코드에 묻어나왔어요!
- 질문하신 것 처럼 입력값을 어디서 처리할 것 인가에 대해 생각해보신 점이 좋네요! 작성하시면서 더 좋은 코드를 만들기위해 생각하시는 그 습관이 샐리님을 더 좋은 개발자로 만들어드릴 수 있을 것 같아요!
 
궁금하신 점이 있다면 언제든 불러주세요 😃 
고생하셨습니다!

2022-02-11 13:56 UTC, EungyuCho commented on cypress/integration/racingcar.spec.js
> +    Cypress.Commands.add('normalWorking', (carNames, racingCount) => {
`normalWorking` 한 커맨드로 정상 동작이라는 이름을 각인시킬 수 있어 생각보다 나쁘지 않을 수도 있겠다는 생각이 들지만 추상화가 심한 경우에 내부적으로 어떤 동작들이 이뤄지는지 파악하기 힘들다는 관점에서 생각해보면 이름을 입력하는 부분과 경기 횟수를 입력하는 부분을 나누는 게 직관적이라고 판단이 되네요!

2022-02-11 13:56 UTC, EungyuCho commented on src/modules/checkUserCarNameInput.js
> +}
이 부분이 본문에도 여쭤보신 부분인 것 같은데요!

개인적으로는 직관성 있는 함수를 만들기 위해서는 `validation`을 별도로 진행하고 나서 `input`값을 사용하는게 좋아보여요.
이 함수의 네이밍이 `check`인데  반환값으로 받은 데이터가 `undefined`인 부분도 이상하고 그렇다고 `carNameArray`를 받는 부분도 애매하게 느껴지네요.

`validate`함수를 만들어 `true`/`false`를 반환받고 변수명으로 `isValid` 변수명으로 지정해주시는 게 더 명확하게 입력값이 검증이 됐는지 알 수 있고 반환값도 당연히 `boolean`이라고 인지할 수 있을거에요.

해당 부분은 개선해보면 좋을 것 같아요 :)

2022-02-11 13:56 UTC, EungyuCho commented on src/modules/checkUserRacingCountInput.js
> +}
위 `validation` 관련 코멘트와 같습니다~

2022-02-11 13:56 UTC, EungyuCho commented on src/modules/racingCarGame.js
> +            }
혹시 `validate` 관련 리팩터링을 진행하시게 되면 코멘트 드린 것 처럼 함께 변경해보면 좋겠네요!

2022-02-11 13:56 UTC, EungyuCho commented on cypress/integration/racingcar.spec.js
> +  });
테스트 잘 작성해주셨네요 👍 

`Cypress` 문서에는 어떻게 select하는게 좋을지에 대한 best practice가 있는데 이 [문서](https://docs.cypress.io/guides/references/best-practices#Selecting-Elements
)도 한번 읽어봐주시면 좋을 것 같아요!

2022-02-11 13:56 UTC, EungyuCho commented on cypress/integration/racingcar.spec.js
> +  const baseUrl = "../../index.html";
오.. 이렇게 할 수도 있군요 💯

2022-02-11 13:56 UTC, EungyuCho commented on src/modules/racingCarGame.js
> +            if(!!carNameArray && !!raceCount) {
`!!`으로 검증하신 부분은 정말 좋은 것 같아요! 👍

2022-02-11 13:56 UTC, EungyuCho commented on src/class/racingCar.js
> +    }
생성자에 있어도 괜찮지 않을까요?

2022-02-11 13:56 UTC, EungyuCho commented on src/class/racingCar.js
> +    }
분리해도 괜찮은 부분인 것 같아요.
해당 클래스가 꼭 가지고 있어야 하는 함수는 아닌 것 같아요.

2022-02-13 04:58 UTC, liswktjs commented on src/modules/checkUserRacingCountInput.js
> +    return raceCountInput <= 20 && raceCountInput >= 1 && Number.isInteger(raceCountInput);
유저가 입력한 시도 횟수가 1~20 사이인지와 소수점 값이 아닌지 한번에 확인하기 위해서 넣었었는데 🥲지금 보니 정수인지 확인하는 하는 부분을 분리하는 것이 더 명확하게 함수가 의도가 전달 될 수 있을 것 같습니다 😅

2022-02-13 09:16 UTC, EungyuCho requested changes
안녕하세요 샐리님~

코멘트 주신 부분을 고민하시고 개인적인 변경사항까지 생각하시고 반영해주셨네요 고생하셨습니다!

우선 질문주신 부분부터 답변 드릴게요!

> on-Click 함수 관련 네이밍을 조언해 주신 것에 따라 handle event와 관련지어 이름을 새롭게 지어봤는데 완벽한 네이밍이 아닌것 같아 계속 찝찝합이 남습니다...🥲 함수 이름짓기 정말 어렵네요...

그렇죠.. 변수 네이밍은 끝까지 괴롭히는 것 같아요. 네이밍이 마음에 안드신다면 `addEventListner`의 콜백함수를 `on~` 함수로 분리한 뒤에 `addEventListner`에 할당하는 건 어떨까요?

이렇게 하고 해당 이벤트 바인딩을 호출하는 함수를 `addEvent`네이밍으로 호출하는 것도 괜찮아보이네요!

```javscript
class ExampleController {
  constructor() {
    this.addEvent()
  }

  addEvent() {
    $('#anyElement').addEventListener(onClickAnyElement)

    function onClickAnyElement(event) {
      // any script...
    }
  }
}
```

이렇게 개선한다면 이벤트에 대한 네이밍 통일성도 가져갈 수 있다고 생각이드네요!

> 이번에 코드를 개선해 가면서 기존에 racingCar.js에서 이루어졌던 render 함수들을 views폴더 아래로 넣어봤습니다 이런 식으로 render함수들을 분리하여 관리해도 괜찮을 까요? 그리고 그 폴더 이름을 views로 하는 것이 적절한지도 궁금합니다!

렌더링에 관련된 파일들을 구성해주셨는데 말씀해주신대로 폴더 이름은 `views`가 적절해보여요!  하지만 내부에 파일 관련해서는 `render`함수를 분리하시게 되면 파일이 너무 많이질 것 같다는 생각이 드네요 😓 
조금 더 개선해보시는 걸 추천드립니다!

한번 `class`형태로 `view`를 작성해보시는 건 어떨까요?
유지보수 관점에서 적절한 범위로 `View`를 분리해서 다시 구성해보시면 좋을 것 같아요!!

위 코멘트 말고도 아래에 몇가지 코멘트를 더 남겼는데 한번 확인해주시면 감사하겠습니다.
코멘트 반영하시느라 고생하셨습니다! 👍 👍

2022-02-14 03:09 UTC, liswktjs commented on src/class/racingCar.js
> +            if(generateRandomNumber() >= 4){
앗 그렇네요! 제가 놓쳤습니다😅

2022-02-14 03:11 UTC, liswktjs commented on src/modules/showAlert.js
> +}
에러 처리 하는 부분에서 반복적으로 사용되서 함수로 빼봤는데 다시 생각해보니 한줄이라 그렇네요... 차라리 에러 처리하는 함수로 바꿔서 initTextElement()와 함께 처리 할까도 생각 중입니다🤔

2022-02-14 03:13 UTC, liswktjs commented on cypress/integration/racingcar.spec.js
> +    cy.get('.race-count-input-container').should('not.have.css', 'display', 'flex');
와... 그러네요... 생각을 못했었는데😱 이곳에서는 display none이 더 맞는것 같습니다!

2022-02-14 03:15 UTC, liswktjs commented on src/modules/racingCarGame.js
> +    };
이번 과제가 자동차 이름 입력값이 유효하면 게임 횟수 입력하는 element가 display:none에서 나타나는 구조여서 순서대로 처리한다는 의식의 흐름으로 이곳에 넣었는데 다시 생각해보니 따로 빼는게 함수가 한가지 역할만 하는데에 더 좋을 것 같습니다🥲

2022-02-14 09:07 UTC, liswktjs commented
아사님이 조언해주신대로 View class를 활용해서 render를 관리하니깐 보기에 편하고 깔끔하더라고요! 앞으로 코딩 할때에는 해당 방법을 자주 활용 해볼까 합니다 😎
그리고 View class로 바꿔서 진행하는 김에 기존에 racingCar에서 진행된 render명령들을 racingCarGame에서 진행하도록 racingCar도 조금 수정해보았습니다! 
racingCar에서는 최대한 정보처리 만을 하도록 하고 racingCarGame에서는 View와 racingCar를 연결짓는 Controller역할을 하도록 해봤습니다 
이런 형식을 사용해서 코딩해보는 것이 처음이라 많이 헷깔렸지만 일단 도전해봅니다!😆

2022-02-14 13:04 UTC, EungyuCho approved these changes
안녕하세요 샐리님!

코멘트 드린부분을 잘 반영해주셨네요! 고생하셨습니다~
리뷰 개선사항들을 별도로 `md`파일로 별도로 작성해주셔서 어떤 과정을 통해 코드가 개선 되었는지 문서만 보고도 알 수 있어 좋았습니다! 왠지 개선된 리스트를 보니 뿌듯하네요 ㅎㅎ
 
구조적인 개선부터 네이밍, 함수의 분리방법등 다양한 개선을 하시면서 빠르게 코드가 개선되는 과정을 잘 보여주신 것 같아요! 개선사항이 많았던 것 같은데 빠르게 반영해주셔서 좋았습니다! 

추가로 조금만 더 개선하면 좋을 부분이나 사용자에 입력에 대해 검증에하는 부분에 있어 XSS를 방지하는 방법에 관련된 코멘트를 남겼는데 확인해주시면 감사하겠습니다!

정말 고생하셨습니다! 그럼 step2에서 뵙겠습니다~

2022-02-14 13:04 UTC, merged