[1단계 - 자동차 경주 구현] 후이(최광희) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #72
Opened 2022-02-11 08:03 UTC by kwannee

cypress가 서툴러서 테스트 코드 작성하는 데 어려움을 많이 겪었습니다.  앞으로 자주 사용하여 사용법을 숙달 해야겠습니다.
페어 프로그래밍에 조금 익숙해진 것 같습니다. 두 명의 시선으로 보다 보니 에러를 좀 더 빠르게 찾아낼 수 있었습니다.

2022-02-12 00:43 UTC, austinpark420 requested changes
안녕하세요 리뷰를 맡은 박용민입니다.

전체적으로 mvc 패턴을 기반으로 코드를 깔끔하게 잘 짜주신 것 같아요.
변수명도 전체적으로 역할에 맞게 잘짜주신 것같고요!
리뷰 관련해서 간단하게 코멘트 남겨놓았습니다. 확인 부탁드릴게요!

2022-02-12 00:43 UTC, austinpark420 commented on src/js/models/Car.js
> +    this.forward = INIT_CAR_FORWARD;
forward라는 단어는 '앞으로'라는 의미를 가진 형용사라 실제 실제 움직인 거리를 표현하는 부분에 있어서 의미가 조금 바로 와닿지는 않는 것 같습니다. 거리와 같이 명사형태로 변수명을 선언하는 것은 어떨지 생각해봤습니다.

2022-02-12 00:43 UTC, austinpark420 commented on src/js/models/RacingCarModel.js
> +    const splitedCarNames = this.splitCarNames(carNames);
호이스팅과 가독성 측면에서 함수를 선언 후에 사용하는 것을 추천드려요!

2022-02-12 00:43 UTC, austinpark420 commented on src/js/models/RacingCarModel.js
> +    return this.racingCount;
바로 값을 리터하는 경우에는 {}을 ()으로 변경할 수 있습니다. () 자체가 return의 의미를 내포하고 있어요!
```
 getRacingCount = () => (
    this.racingCount
  );
```

2022-02-12 00:43 UTC, austinpark420 commented on src/js/models/RacingCarModel.js
> +    const maxCount = Math.max(...results);
result를 임수변수로 만들지 않고 `const maxCount = Math.max(...this.cars.map((car) => car.forward))`으로 작성해도 가독성 측면에서 크게 문제가 없는 것 같아요. 임시변수가 많아지게되면 관리 포인트가 많아지기때문에 최대한 지양하는 것을 추천드려요!

2022-02-12 00:43 UTC, austinpark420 commented on index.html
> +            placeholder="10"
기본값이 10으로 되어있는 느낄 수도 있어서, 횟수를 입력해주세요. 와같이 액션을 유도하는 placeholder 문구가 들어가면 좋을 것 같아요!

2022-02-14 07:31 UTC, kwannee commented on package.json
> +  "description": "<p align=\"middle\" >   <img width=\"200px;\" src=\"https://user-images.githubusercontent.com/50367798/106415730-2645a280-6493-11eb-876c-ef7172652261.png\"/> </p> <h2 align=\"middle
넵 피드백 반영하여 description 수정완료 했습니다!

2022-02-14 07:34 UTC, kwannee commented on src/js/models/Car.js
> +    this.forward = INIT_CAR_FORWARD;
forward에서 명사형인 forwardCount로 수정해 봤습니다. 변수명을 늘 고민하는데 참 쉽지 않네요...

2022-02-14 07:34 UTC, kwannee commented on src/js/models/RacingCarModel.js
> +    return this.racingCount;
바로 리턴하니 코드도 줄어들어 훨씬 깔끔해지고 좋네요!

2022-02-14 07:37 UTC, kwannee commented on src/js/models/RacingCarModel.js
> +    const maxCount = Math.max(...results);
앗 그렇네요. 임시변수를 최대한 지양하도록 해야겠어요. results를 뒀던 이유가 가독성을 측면에서 그랬던 건데 지우니 오히려 더 깔끔하네요!

2022-02-14 07:39 UTC, kwannee commented on src/js/controller/RacingCarController.js
> +    try {
감사합니다. 페어분 방식인데 저도 이번에 잘 배웠습니다!

2022-02-14 07:40 UTC, kwannee commented on index.html
> +            placeholder="10"
넵 액션을 유도하는 placeholder로 바꿨습니다.

2022-02-14 10:47 UTC, austinpark420 commented on src/js/models/Car.js
> +    this.forward = INIT_CAR_FORWARD;
네 변수명은 항상 고민이 많이되죠 ㅠㅠ

2022-02-14 11:04 UTC, austinpark420 commented on src/js/view/RacingCarView.js
> +    this.$result.innerHTML = this.makeResultTemplate();
innerHTML은 XSS 공격에 취약합니다. [참조링크](https://tecoble.techcourse.co.kr/post/2021-04-26-cross-site-scripting/)
innerHTML대신 insertAdjacentHTML를 사용하는 것을 추천드려요!

2022-02-14 11:04 UTC, austinpark420 approved these changes
안녕하세요 후이!

수정사항 방영해주신 것 확인했습니다.
고생 많으셨습니다. 추가로 코멘트 남긴 부분이 있는데 그 부분은 step2에 적용해보시면 될 것 같습니다.
고생 많으셨어요!

2022-02-14 11:05 UTC, merged

2022-02-15 13:51 UTC, austinpark420 commented on src/js/view/RacingCarView.js
> +    this.$result.innerHTML = this.makeResultTemplate();
제가 XSS 공격을 피하기 위해 innerHTML 대신 insertAdjacentHTML를 사용 권장드린다고 말씀드렸는데요.
좀 더 알아보니 insertAdjacentHTML도 XSS 공격에 취약하다고 합니다. 잘못된 정보를 전달드려 정말 죄송합니다 🙏