[1단계 - 자동차 경주 구현] 앨버(송상민) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #86
Opened 2022-02-11 08:42 UTC by al-bur

페어 프로그래밍 어려웠지만 배운 것이 많았습니다.

이번에 페어와 함께 MVC 패턴으로 구현하려고 하였습니다.

테스트 코드 작성 -> 기능 구현 -> 리팩토링 싸이클로 개발을 진행했습니다.

-----------------------------------------------------------------------------------------------

안녕하십니까 @hyoungnam 노스님!!

바쁘실텐데 직접 리뷰어로 참여해주셔서 감사합니다. 저는 앨버라고 합니다😀

사실, 시간이 많이 없어서 충분한 설계를 통해 프로그램을 작성하지는 못하였습니다. 하지만 좀 더 신경쓴 부분들이 있어 공유드리려고 합니다.

### 신경쓴 부분

- MVC 패턴 사용 -> 파일이나 메서드 분리를 좀 더 체계적으로 하려고 했습니다.
- 직관적으로 commit 메시지를 작성
- 직관적인 변수명

많이 부족한 코드라서 노스님께서 보이는대로 피드백 다 주시면 더 보완토록 하겠습니다.

감사합니다.

2022-02-12 06:29 UTC, hyoungnam requested changes
안녕하세요 리뷰를 맡게된 노스입니다 🙏
전반적으로 역할을 잘 나누어주셔서 잘 읽고 테스트하였습니다. 코멘트가 많지 않지만 몇가지 궁금한 점과 바꾸면 용이할것 같은 부분에 대해서 코멘트 남겼습니다. 또한 리뷰어의 의견은 절대적인게 아니니 앨버님의 생각도 적극적으로 알려주세요!! 그럼 확인 부탁합니다:)

2022-02-12 06:29 UTC, hyoungnam commented on src/racingCarView.js
> +export default class RacingCarView {
RacingVarView가 많을일을 하는 것 같습니다. 조금더 나누어보아도 괜찮을것 같은데 어떻게 생각하시나요? 물론 뭉치는것과 나누는것에는 장단점이 있으니 앨버님의 의견이 궁금하네요 🙂

2022-02-12 06:29 UTC, hyoungnam commented on src/common/DOMHelper.js
> +export const $$ = (selector) => document.querySelectorAll(selector);
깔끔하네요:) 이렇게도 확장할 수 있습니다. 
```suggestion
export const $ = (selector, node = document) => node.querySelector(selector);
export const $$ = (selector, node = document) => node.querySelectorAll(selector);
```

2022-02-12 06:29 UTC, hyoungnam commented on src/racingCarView.js
> +    return [...$$moveForwardArrow].filter((elem) => elem.dataset.carName === name);
dataset 활용을 하시는군요 좋네요!! 👏

2022-02-12 06:29 UTC, hyoungnam commented on cypress/integration/racingCar.spec.js
> +  };
[as](https://docs.cypress.io/api/commands/as) 키워드를 활용하면 좋을듯 하네요:)

2022-02-12 06:29 UTC, hyoungnam commented on cypress/integration/racingCar.spec.js
> +describe('구현 결과가 요구사항과 일치해야 한다.', () => {
실패하는 대한 케이스에 대한 테스트가 대부분입니다. TDD의 RED-GREEN-REFACTOR에서 RED가 어떤 의미인지 한번더 고민하고 알아보시면 좋을듯합니다

2022-02-12 06:29 UTC, hyoungnam commented on src/common/constants.js
> +  MOVE_FORWARD_ARROW: '⬇️️',
MOVE_FORWARD_ARROW vs '⬇️️'
어떤 것이 사용하는 측에서 보기 좋을까요???저는 후자를 선호합니다😇

2022-02-13 05:47 UTC, al-bur commented
@hyoungnam 

빠른 리뷰 감사합니다. 노스님! 하나 하나 수정해보도록 할게요!

그리고 질문이 있는데,

코드를 수정하고 다시 리뷰 요청을 드리려면 어떻게 하면 될까요?

주기적으로 github을 보시는 시간이 있으신가요? 있으시면 그때까지 코드를 수정해보는 방식으로 해도 좋을 것 같아서요!

2022-02-14 07:41 UTC, al-bur commented on src/racingCarController.js
> +    }
else 사용하지 않도록 수정하였습니다.

[수정 commit](https://github.com/al-bur/javascript-racingcar/commit/aa0afc7b899531c4c982e908d23214b8aebeb441)

2022-02-14 07:41 UTC, al-bur commented on src/racingCarController.js
> +    }
위의 수정과 함께 진행하였습니다.

[수정 commit](https://github.com/al-bur/javascript-racingcar/commit/aa0afc7b899531c4c982e908d23214b8aebeb441)

2022-02-14 08:17 UTC, al-bur commented on src/common/template.js
> +      </div>
1. form을 활용해서 리팩토링을 해보았습니다. 

- div 태그 대신 form 태그를 사용하는 이유를 조금 검색해보았는데 semantic tag라는 이유를 많이 발견할 수 있었습니다. 혹시 다른 이유도 있을까요??

2022-02-14 08:18 UTC, al-bur commented on src/common/template.js
> +      </div>
2. form 태그를 사용하기로 결정했기 때문에 button 태그 대신 <input type=submit>을 사용하는 방식으로 리팩토링을 해보았습니다.

2022-02-14 08:43 UTC, al-bur commented on src/common/template.js
> +      </div>
[수정 commit](https://github.com/al-bur/javascript-racingcar/commit/dd9f01723024c86f9347873a40f23a059c0264d8)

2022-02-14 12:19 UTC, al-bur commented on src/common/template.js
> +    <h1 style="${style.header}">${HEADER.MAIN}</h1>
- 사실, 해당 방법을 사용한 이유는 csr(client side rendering) 방식으로 프로그램을 구현하려고 했었기 때문입니다. index.html에 css 관련된 코드들을 작성하지 않고 css 스타일링을 어떻게 할 수 있을까 고민하다가 나온 유일한 방법이어서 해당 방법을 적용했습니다..😀

- 장단점이 잘 생각이 나지 않아 따로 공부를 하고 정리해보았습니다.

(장점)
- 직관적이다.

(단점) 
- 캐시가 되지 않는다.
- 중복되는 코드가 생길 수 있다.

2022-02-14 12:21 UTC, al-bur commented on src/common/template.js
> +      </div>
[질문] 
- div 태그 대신 form 태그를 사용하는 이유를 조금 검색해보았는데 semantic tag라는 이유를 많이 발견할 수 있었습니다. 혹시 다른 이유도 있을까요??

2022-02-14 12:21 UTC, al-bur commented on src/common/template.js
> +    <h1 style="${style.header}">${HEADER.MAIN}</h1>
[질문] 제가 사용한 방법 외에 다른 방법이 있을까요??

2022-02-14 22:29 UTC, hyoungnam commented on src/common/template.js
> +    <h1 style="${style.header}">${HEADER.MAIN}</h1>
inline style이 css 적용 우선순위가 높은 장단점이 있어서 질문드렸습니다:)  단점에 캐쉬가 되지 않는다는건 이해가 되지 않는데 어떤 말씀이신가요?
css-in-js에서 style에 주입하는것 말고도 있는걸로 아는데 저도 깊게 파보지는 않아서...ㅎㅎ
css-in-js 라이브러리를 직접 들여다보는것도 도움이 되겠네요

2022-02-14 22:54 UTC, hyoungnam commented on src/racingCarController.js
> +    }
수정하신 내용 보았습니다! 다만 조금만 더 바뀌면 좋을것 같네요. this.view.renderCars 함수의 반환값이 있나요? 그리고 그 반환값을 다시 return해주는 상황 아닐까요?
early return을 통해 분기를 제어하면 좋을 듯 합니다!

2022-02-14 22:54 UTC, hyoungnam commented on src/racingCarController.js
> +    }
위의 코멘트 답변과 동일합니다

2022-02-14 23:03 UTC, hyoungnam commented on src/common/template.js
> +      </div>
[HTML](https://developer.mozilla.org/ko/docs/Web/HTML)의 풀네임이 어떤의미인지 생각해보시면 좋을것 같습니다~!
button type="submit"이 맞는 내용인것 같습니다.

2022-02-15 02:40 UTC, al-bur commented on src/common/constants.js
> +  MOVE_FORWARD_ARROW: '⬇️️',
문자열과 숫자들을 모두 상수화 시키는 게 일관성 측면에서 좋아보여서 전자로 진행하긴 했었습니다!

굳이 모든 것들을 상수화 시키지 않아도 될까요? 몇 가지는 상수화를 하고 몇 가지는 안하면 일관성 측면에서 안좋아보일 것 같았습니다!

2022-02-15 07:29 UTC, al-bur commented on src/common/template.js
> +      </div>
> [HTML](https://developer.mozilla.org/ko/docs/Web/HTML)의 풀네임이 어떤의미인지 생각해보시면 좋을것 같습니다~! button type="submit"이 맞는 내용인것 같습니다.

네네!! 
근데 제가 button이랑 input의 차이가 거의 없다고 봤었는데 혹시 button을 추천하시는 이유가 무엇일까요? button 태그는 내부에 이미지 같은 것들을 넣을 수 있다는 장점이 있는데 지금 상황에서는 텍스트만 들어가는 것 같아서 button이 맞는 이유를 알고 싶습니다!

2022-02-15 07:29 UTC, al-bur commented on src/racingCarController.js
> +    }
> 수정하신 내용 보았습니다! 다만 조금만 더 바뀌면 좋을것 같네요. this.view.renderCars 함수의 반환값이 있나요? 그리고 그 반환값을 다시 return해주는 상황 아닐까요? early return을 통해 분기를 제어하면 좋을 듯 합니다!

내용 확인했습니다. 단순히 코드 줄을 줄이기 위해서 해당 함수를 return 하였습니다. return을 단독 사용하여 수정하겠습니다.

2022-02-15 07:33 UTC, al-bur commented on src/racingCarController.js
> +    }
> 위의 코멘트 답변과 동일합니다

위의 수정과 함께 진행하였습니다.

[수정 commit](https://github.com/al-bur/javascript-racingcar/commit/3aaf2b0aef2b45b177585ee0c3866e7de1bfbfd9)

2022-02-15 07:39 UTC, al-bur commented on src/common/template.js
> +    <h1 style="${style.header}">${HEADER.MAIN}</h1>
> 단점에 캐쉬가 되지 않는다는건 이해가 되지 않는데 어떤 말씀이신가요?

- inline style과 external css 방식이랑 비교하는 글에서 보았는데, inline은 cache가 되지 않는다는 사항이 있었습니다.
[출처](https://stackoverflow.com/questions/8284365/external-css-vs-inline-style-performance-difference)

2022-02-15 07:57 UTC, al-bur commented on src/racingCarView.js
> +    return [...$$moveForwardArrow].filter((elem) => elem.dataset.carName === name);
감사합니다!!

2022-02-15 08:25 UTC, al-bur commented on src/racingCarView.js
> +    }
> String의 repeat을 활용해보시는것도 좋을것 같습니다. 한편으로는 repeat과 for문 두 방식 모두 동작하는데는 문제가 없습니다. 앨버님이 repeat을 사용함으로서 얻는 장단점과 for문을 사용함으로서 얻는 장단점을 비교해보시고 어떠하였는지 의견을 얘기해주시면 좋을것 같습니다:)

## repeat vs for loop

<repeat - 장점>
- 코드가 더 간결하다.

<repeat - 단점>
- 확장성이 없다.


<for loop - 장점>
- 확장성이 있다.
ex) 중간에 다른 내용을 덧붙이는 게 필요할 경우

<for loop - 단점>
- 코드량이 많다.


## 결론

현재는 단순하게 동일한 요소(`<p>${CAR.MOVE_FORWARD_ARROW}</p>`)만 추가해주는 것이기 때문에 확장성이 더 필요하지 않은 상황이라고 생각합니다. 그래서 for loop보다는 repeat을 사용하는게 더 좋은 방법이라고 생각해서 수정하였습니다.

2022-02-15 08:32 UTC, al-bur commented on src/racingCarController.js
> +    const racingCount = Number(this.view.$racingCountInput.value);
오호 이런 기능이 있었군요! 감사합니다 적용하였습니다!

2022-02-15 09:40 UTC, hyoungnam commented on src/common/template.js
> +    <h1 style="${style.header}">${HEADER.MAIN}</h1>
http 자원 관점에서 말하는거였군요!
넵 공유 해주시면 좋을듯 합니다

2022-02-15 09:42 UTC, hyoungnam commented on src/common/template.js
> +      </div>
[input type="button"](https://developer.mozilla.org/ko/docs/Web/HTML/Element/Input/button) 해당 링크에서 '참고' 부분 읽어보시면 좋을것 같네요:)

2022-02-15 09:47 UTC, hyoungnam commented on src/racingCarView.js
> +    }
답변 감사합니다~! 확장성 관점에서 생각해볼수도 있겠네요. 시간에 여유가 있을때 명령형과 선언형이라는 키워드에 대해서 공부를 해보셔도 좋을것 같습니다

2022-02-15 09:51 UTC, hyoungnam commented on src/common/constants.js
> +  MOVE_FORWARD_ARROW: '⬇️️',
일관성도 중요하지만 일관성 측면보다는 재사용, 유지보수, 가독성 측면에서 생각해봐도 좋지 않나 생각합니다. 위 부분은 반영하지 않고 앨버님 말씀하신대로 가도록 해요:)  여러 방면으로 사용해보시면서 적정한 사용법을 직접 찾아가는게 좋을것 같네요!!

2022-02-15 10:11 UTC, al-bur commented on src/common/constants.js
> +};
그렇네요 습관적인 코딩의 폐혜네요

수정하였습니다.

2022-02-15 10:34 UTC, al-bur commented on src/common/constants.js
> +};
> 이부분이 재사용이 많거나 변경이 잦은가요? 
- 그렇지 않습니다.

> 어떤 부분을 상수로 할지 고민해보는게 좋을것 같아요

- 사실, 이번에도 습관적으로 모든 문자열을 상수화 하는 게 좋지 않을까라는 생각에 모두 상수화를 진행해주었습니다.
문자열을 상수화 시킨 것들(아래 예시)을 다시 살펴보니 아래 것들도 굳이 상수화를 시키지 않아도 될 것 같다고 생각하는데 노스님의 의견 듣고 싶습니다.

```
export const BUTTON = {
  SUBMIT: '확인',
  RESTART: '다시 시작하기',
};
```

```
export const WINNER = {
  ICON: '🏆',
  TITLE: '최종 우승자:',
};
```

2022-02-15 10:35 UTC, al-bur commented on src/common/constants.js
> +};
확인했습니다!

2022-02-15 10:44 UTC, al-bur commented on src/common/DOMHelper.js
> +export const $$ = (selector) => document.querySelectorAll(selector);
다른 요소가 base가 되는 것을 추가로 구현할 수 있겠군요. 감사합니다😀

[수정 commit](https://github.com/al-bur/javascript-racingcar/commit/94a903e7587e14a92e96321349dad5c71719a73e)

2022-02-15 10:52 UTC, al-bur commented on cypress/integration/racingCar.spec.js
> +  };
> [as](https://docs.cypress.io/api/commands/as) 키워드를 활용하면 좋을듯 하네요:)

cypress가 자체적으로 제공하는 방법이 있군요! 감사합니다.

질문이 있는데, 제가 사용한 방법과 노스님이 제공해주신 방법이 비슷한 것 같은데, 혹시 해당 방법을 추천해주시는 특별한 이유가 있을까요?  (아무래도 cypress가 제공하는 것을 사용하는 게 좋은 걸까요)

2022-02-15 12:09 UTC, al-bur commented on src/common/constants.js
> +  MOVE_FORWARD_ARROW: '⬇️️',
재사용, 유지보수, 가독성 측면에서 2단계할때 한 번 더 생각해보겠습니다. 감사합니다!

2022-02-15 12:10 UTC, al-bur commented on src/common/template.js
> +      </div>
> [input type="button"](https://developer.mozilla.org/ko/docs/Web/HTML/Element/Input/button) 해당 링크에서 '참고' 부분 읽어보시면 좋을것 같네요:)

확인했습니다! 추천을 하는군요😀 다시 수정하도록 하겠습니다~

2022-02-15 12:16 UTC, al-bur commented on src/common/template.js
> +    <h1 style="${style.header}">${HEADER.MAIN}</h1>
이번 주내로 공유하겠습니다!

2022-02-15 12:17 UTC, al-bur commented on src/racingCarView.js
> +    }
명령형과 선언형! 
감사합니다

2022-02-15 12:25 UTC, al-bur commented on src/racingCarView.js
> +export default class RacingCarView {
MVC 패턴으로 구현하려고 했고 화면에 존재하는 TAB의 개수만큼 Model, Controller, View를 만드려고 했습니다.
이번 미션에는 TAB이 하나밖에 없어서 MVC를 각각 하나의 파일로만 구성하였습니다.

View에는 DOM에 관한 메서드들만(렌더링, DOM 선택, 리셋) 분류해서 넣어놓았는데, 혹시 어떤 부분에서 많은 일을 한다고 느끼셨는지 의견 여쭤봐도 될까요? 😄

2022-02-15 13:07 UTC, al-bur commented on cypress/integration/racingCar.spec.js
> +describe('구현 결과가 요구사항과 일치해야 한다.', () => {
네! 확인해보고 2단계에서 추가로 테스트 작성해보도록 하겠습니다. 감사합니다

2022-02-15 14:46 UTC, hyoungnam commented on src/racingCarView.js
> +export default class RacingCarView {
'일'이란 말이 잘못되었네요!  말씀하신대로 '렌더링, DOM 선택, 리셋'을 잘 나누어주셨습니다. 한편으로는 메소드들이 렌더링, 선택, 리셋등 '행위'를 기준으로 나열되어있다보니 Form과 관련된 메소드들만 변경하거나, 보려고 하면 불편한점이 있습니다. 프론트개발은 컴포넌트 중심으로 이루어지기때문에 View를 조금 더 작게 나누면 어떨까 하여 질문을 드렸습니다:)

2022-02-15 14:55 UTC, hyoungnam commented on cypress/integration/racingCar.spec.js
> +  };
저는 앞에 반복적인 객체이름을 타이핑하지 않아도 된다는 편리함때문에 선호합니다,,,, 😇

2022-02-16 03:47 UTC, al-bur commented on cypress/integration/racingCar.spec.js
> +  };
그렇네요 지금 사용하는 것보다 코드량을 줄일 수 있을 것 같아요

한 번 사용해보도록 하겠습니다!

2022-02-16 05:50 UTC, al-bur commented on src/common/constants.js
> +};
네네 이번 미션 계속해서 고민해보겠습니다!

2022-02-16 05:51 UTC, al-bur commented on src/racingCarView.js
> +export default class RacingCarView {
> View를 조금 더 작게 나누면 어떨까 하여 질문을 드렸습니다

맞아요 저도 M,V,C 파일 하나씩에 모든 로직을 넣으려고 하니까 코드량이 많아져서 가독성이 조금 떨어지더라구요

제가 지금까지 MVC 패턴을 사용하면서 하나의 TAB이 있을때는 무조건 하나의 View 파일로 진행했었는데, 2단계에서 시간이 남으면 한 번 분리해보는 시도 해보겠습니다!

2022-02-16 09:27 UTC, al-bur commented
안녕하십니까 노스님! 1단계 리뷰 감사드립니다.

피드백 주신 거 꼼꼼히 읽어보고 역질문도 하고 수용도 해보면서 코드 리뷰를 잘 경험할 수 있었던 것 같습니다ㅎㅎ

피드백 부분 수정 완료한 것 같아 1단계 코드리뷰 요청 보냅니다😁

2022-02-16 10:30 UTC, merged

2022-02-17 02:31 UTC, al-bur commented
안녕하세요 노스님! 

테스트코드에 대해서 피드백 남겨주신 것에 대해서 의견 드리고 싶어서 이렇게 코멘트 작성합니다.

아래처럼 리뷰를 남겨주셨었습니다. 

>  실패하는 대한 케이스에 대한 테스트가 대부분입니다. TDD의 RED-GREEN-REFACTOR에서 RED가 어떤 의미인지 한번더 고민하고 알아보시면 좋을듯합니다.

이후, 제가 RED-GREEN-REFACTOR에 대해서 알아보았는데, 요구사항이 있으면 RED(테스트 통과X)가 발생하도록 테스트 코드를 작성하고 이를 GREEN(통과)이 될 수 있도록 코드를 수정하고 마지막으로 리팩토링 하는 과정이라고 알게되었습니다.

저와 페어가 작성한 테스트 코드를 다시 살펴보니, 이번 미션에서 필요한 요구사항들(alert를 띄우고 리셋해주는 기능)을 RED-GREEN-REFACTOR 원칙에 기반하여 작성되기는 하였는데, 프로그램의 예외 사항만을 다루는 것 같습니다.  

현재 부족한 것은 노스님이 언급해주신 것처럼 정상적으로 프로그램이 실행되는지 테스트하는 테스트 코드라고 생각되는데 노스님은 어떻게 생각하시나요??

(결론: 1단계때 작성한 테스트 코드는 예외 사항에 대한 테스트 코드이고 RED-GREEN-REFACTOR 원칙을 지키고 있었던 것 같습니다. 하지만, 정상적으로 실행되는지에 대한 테스트 코드가 부족한 것 같습니다.)