[1단계 - 자동차경주미션] '비녀' 제출합니다.
woowacourse/javascript-racingcar pull request #88
Opened 2022-02-11 08:52 UTC by KangYunHo1221

1.
페어프로그래밍이 기대했던것 보다 실력향상에 도움이 많이 된 것 같습니다.

TDD(Teammate driven developement) 를 이용해서 구현해 보았습니다.

몇 년 더하면 노부부 정도의 호흡을 보여줄거 같습니다.

페어분이랑 시간을 조금씩 더 길게 늘려서 해 보았습니다.

호흡이 맞아 간다는게 느껴져서 좋았고, 실제로 해보니 오히려 혼자 할 떄보다 서로 도와줘서 더 빠른 느낌이었습니다.

2.
test code 작성하는 것이 쉽지 않네요. 주말동안 cypress를 정독하면서 익혀봐야 할 것 같습니다.

나중엔 진짜 TDD를 할 수 있기를..

2022-02-12 14:06 UTC, austinpark420 requested changes
안녕하세요 비녀님! 이렇게 만나뵙게되서 반갑습니다!

디렉토리 구조를 디테일하게 잘잡아서 개발하고 계신 것습니다 : )
또한 함수를 역할에 맡게 작은 단위로 나눠서 작업하신 부분이 좋았습니다.
코드를 보면서 코멘트 남겼으니 확인해주시고 궁금한 부분에 대해서 코멘트 남겨주시면 감사하겠습니다!

즐거운 주말되세요!!!

2022-02-12 14:06 UTC, austinpark420 commented on src/controllers/validation.js
> +import { showAlertMsg } from './utils.js';
validation.js을 controller 폴더에 정의하신 이유가 궁금합니다!

2022-02-12 14:06 UTC, austinpark420 commented on src/controllers/utils.js
> +import { ERR_KEY_NAME, ERR_KEY_NUMBER } from '../constants/errors.js';
utils.js을 controller 폴더에 정의하신 이유가 궁금합니다!

2022-02-12 14:06 UTC, austinpark420 commented on src/controllers/validation.js
> +import { showAlertMsg } from './utils.js';
validation.js을 하나의 파일로 만들어서 관리하셔서 코드를 볼 때, 좀 더 가독성이 좋은 것 같아요!!!

2022-02-12 16:32 UTC, KangYunHo1221 commented on src/models/state.js
> +export const state = {
감사합니다! 이름에 대해서 리팩토링할때 더 진지하게 생각해봐야겠네요.

state 관련해서 페어분이랑 둘 다 궁금한게 있었는데 

저희가 사용한 state처럼 여러곳에서 원하는 상태를 객체로 생성해서

필요한 곳 마다 import 해서 쓰는게 좋은 방법인지 궁금합니다.

클래스로 만들어서 캡슐화 하고 '전역으로 사용하는 것을 지양해라.' 라는 것을 얼핏 들은 것 같아서 여쭙습니다.

2022-02-12 16:36 UTC, KangYunHo1221 commented on src/controllers/userController.js
> +  const carNamesInputBtn = document.getElementById('car-name-input-button');
set함수가 페이지를 실행하는동안 한번만 호출 되기 때문에 

저렇게 하는게 가독성이 좀 더 좋지 않을까 생각했는데

고민해보겠습니다.

2022-02-12 16:39 UTC, KangYunHo1221 commented on src/controllers/validation.js
> +import { showAlertMsg } from './utils.js';
model, view, controller 라는 디렉토리 구조에 억지로 맞추려다 보니 controller에 넣게 됐습니다.

model, view, controller 이외에도 하는 일에 따라서 추가, 분리해놓는게 더 좋아보이네요. 

감사합니다!

2022-02-12 16:41 UTC, KangYunHo1221 commented on package.json
> +  "description": "<p align=\"middle\" >\r   <img width=\"200px;\" src=\"https://user-images.githubusercontent.com/50367798/106415730-2645a280-6493-11eb-876c-ef7172652261.png\"/>\r </p>\r <h2 align=\"
항상 npm init 하고나서 필요한 부분을 더하기만 했던 것 같습니다.

description에 대해서 전혀 생각을 못했는데 감사합니다!

2022-02-13 07:55 UTC, austinpark420 commented on src/models/state.js
> +export const state = {
안녕하세요 비녀님!
현재는 프로젝트에서는 크게 상관없다고 생각되지만 규모가 커지게되면 어디서든 상태를 접근하고 변경이 가능하도록 구조가 되어있어 그렇게되면 의도치 않은 이슈가 발생할 수 있다고 생각합니다.
그래서 함수 혹은 클래스(javascript에서 클래스도 함수이긴 하죠ㅎㅎ)로 모델을 만드시는 분들이 많은 것 같습니다!
관련해서 [클로저](https://developer.mozilla.org/ko/docs/Web/JavaScript/Closures) 읽어보시는 것도 추천드려요!

2022-02-14 13:53 UTC, KangYunHo1221 commented on src/views/view.js
> +    carNameBox.innerHTML = state.cars[i].name;
요소를 추가할때는 조심해야 될 것 같네요.
innerHTML = ''과 같이 내용을 초기화 해주는 일 만 해주는 메서드에서는 상관 없겠군요.

2022-02-15 16:54 UTC, austinpark420 commented
step1에서 추가적인 작업이 필요하실까요? step2 진행을 위해 머지가 필요하면 말씀부탁드려요!

2022-02-16 02:15 UTC, KangYunHo1221 commented
아 넵 머지 해주셔도 될거같습니다!

2022-02-16 02:18 UTC, austinpark420 commented
네!! 다음엔 수정사항 반영해주시고 다시 리뷰요청 보내주시면 그때 확인하고 머지할세요.

2022-02-16 02:19 UTC, austinpark420 approved these changes
안녕하세요 비녀님!

코멘트 단 부분 신경써서 반영해주셔서 감사합니다 😄 
step1 하시느라 고생 많으셨고, step2에서 뵙겠습니다!

즐거운 하루되세요!

2022-02-16 02:19 UTC, merged