[1단계 - 자동차 경주 구현] 온스타(온승찬) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #89
Opened 2022-02-11 08:53 UTC by cks3066

페어프로그래밍에 대한 이해도를 올리고 요구 사항에 맞춰 코드를 작성해 볼 수 있는 좋은 기회였습니다.

cypress 의 문법이 익숙하지 않고 좋은 테스트가 어떤 테스트인지 감이 아직 잘 안와서

테스트 코드를 기반으로 개발하는 TDD는 지금의 저로써는 아직 무리인 듯 보입니다🥲

시간에 쫒겨 Time Driven Development는 경험해봤으니 저만의 TDD는 해본 걸로 하겠습니다..

앞으로의 모든 과제에서 더욱 성장할 수 있다는 생각을 하며 열심히 하겠습니다!

2022-02-12 14:40 UTC, inwalter99 requested changes
<img src="https://media0.giphy.com/media/3ogwFGEHrVxusDbDjO/giphy.gif"/>
안녕하세요! 온스타! 반갑습니다. 리뷰를 맡은 월터입니다. 잘부탁드립니다.

- Time-Driven-Development 오히려 좋아... 사슴 공부법이 떠오르는군요! 사실 Test-Driven-Development, TDD를 하는 건 굉장히 어렵습니다. 테스트코드를 미리 짤 수 있다는 건 이미 어느정도 머리속으로 개발이 가능하고 요구 사항들을 다 그려낼 수 있는 실력이 있다는 말이기도 해서... TDD 어렵습니다 저도 어려워요 8ㅅ8 어쩄든 TDD 했으니까 성공으로 하시죠ㅎㅎ, 우선은 TDD 도 좋지만, 개발을 다하고 나서 Test 코드를 짜보세요. 테스크 코드의 진가는 리팩터링 때 드러납니다!
- 온스타님이 들인 시간에 비해 턱없이 부족한 시간을 들여 코드를 보는 거기 때문에 부족하거나 실수한 부분이 있고 저를 포함한 리뷰어가 드리는 피드백은 절대 정답을 말하고 따르라고 요구하는 게 아님을 꼭 알아주셨으면 좋습니당. 비판적 받아들이기 ✨
- 그리고 페어코딩할 때, 커밋에 아래 내용을 추가하면 커밋 공동 저자로 올라가게 됩니다.
추후에 페어코딩과 개별적으로 커밋하신 부분을 구분할 수 있을 거 같아서 사용해주시면 좋겠습니다!
  ```
  Co-authored-by: i.am.yongho <inwalter99@gmail.com>
  ```
고생하셨습니다!

2022-02-12 14:40 UTC, inwalter99 commented on src/controllers/raceController.js
> +}
제가 이해를 제대로 한 지는 모르겠으나 join 과 동일한 역할을 하고 있는 거 같아요.

2022-02-12 14:40 UTC, inwalter99 commented on src/controllers/userController.js
> +export function registerClickEventListners() {
사소하지만 오타가 있습니다! 
```suggestion
export function registerClickEventListeners() {
```

2022-02-12 14:40 UTC, inwalter99 commented on src/controllers/userController.js
> +function setCarNamesClick() {
`setCarNames` 라는 것도 있고... 이름만 봤을 때 핸들러를 등록하는 함수라고 바로 연상짓기가 어려운 거 같습니다. setXXX 는 보통 `setter` 역할을 하는 함수를 예상케 하는 거 같거든요. 위에서 `registerClickEventListeners` 라고 하셨던 것처럼 `registerCarNamesClickEvent` 라고 해주시는 것도 좋을 거 같구요.

`restartBtnClick`처럼 명확하게 어떤 엘리먼트에 대한 건지 적어주면 더 좋을 거 같습니다.`registerCarNameButtonClickEvent`... 지금은 자동차 이름들을 클릭했을 때 발생하는 이벤트가 아니라. 그 옆에 있는 '버튼'에 대한 이벤트를 정의해준 거 같아서요!

2022-02-12 14:40 UTC, inwalter99 commented on src/controllers/validation.js
> +}
검증과 실패 시 동작 두 가지의 일을 하고 있다고 느껴집니다. 함수 이름만 봤을 땐, valid 한 지에 대해 '알려주는' 함수인 거 같은데 내부 동작을 보면 실패 시 동작까지 하고 있어서 https://github.com/woowacourse/javascript-racingcar/pull/89/files#diff-6210ace6be99d7adc7dc8298a158709fef7ba29f17e9c3bd35f1f8fab8d9c8d1R24 여기만 봤을 때 실패 시 동작을 예측하기 어려웠습니다.

2022-02-12 14:40 UTC, inwalter99 commented on src/controllers/userController.js
> +}
setCarNames 함수는 이름과 다르게 carNames 를 set 하는 거 외에도 많은 일들을 책임지는 거 같습니다.

---
```js
carNamesInputBtn.addEventListener('click', () => {
  event.preventDefault()
  const carNames = getCarNames() // 필요하다면 분리

  if (!isNameValid(carNames)) {
    showAlertMsg(MESSAGE)
    return
  }

  setCarNames(carNames)
  renderRacingInputForm()
})
```

2022-02-12 14:40 UTC, inwalter99 commented on src/controllers/userController.js
> +}
어.. 이건 뭔가 기능에 의도와는 조금 다른 거 같습니다. 페이지 리프레시 없이, 초기상태로 돌아가게 해주세요!

2022-02-14 07:17 UTC, cks3066 commented on src/controllers/validation.js
> +}
function hasEmptyName(names) {
  return names.includes("");
}

이렇게 변경했습니다!

2022-02-14 07:17 UTC, cks3066 commented on src/views/view.js
> +  for (let i = 0; i < state.cars.length; i++) {
cars.forEach((car) => {
    const racingProgress = document.createElement("div");
    racingProgress.className = "racing-progress flex-column";
    racingCars.appendChild(racingProgress);

    const carNameBox = document.createElement("div");
    carNameBox.className = "car-name-box";
    carNameBox.innerHTML = car.name;
    racingProgress.appendChild(carNameBox);
  });

이렇게 변경했습니다!

2022-02-14 07:18 UTC, cks3066 commented on src/controllers/raceController.js
> +}
```js
function getWinnerArr(max) {
  return state.cars
    .filter((car) => {
      return car.location === max;
    })
    .map((car) => {
      return car.name;
    });
}
```
filter 와 map 함수로 바꿔보긴했는데 한줄로 접근하는건 잘 안되네요..

2022-02-14 07:20 UTC, cks3066 commented on src/controllers/userController.js
> +function setCarNamesClick() {
```js
import {
  isNameValid,
  isRacingNumberValid,
  isUserInputExist,
} from "./validation.js";
import { doTrim, showAlertMsg } from "./utils.js";
import { startRacing } from "./raceController.js";
import { renderRacingInputForm, disableUserInputs } from "../views/view.js";
import { setCarNames, setRound } from "../models/state.js";

export function registerClickEventListeners() {
  const carNamesButton = document.getElementById("car-name-input-button");
  const racingNumberButton = document.getElementById(
    "racing-number-input-button"
  );
  const restartButton = document.getElementById("restart-button");
  carNamesButton.addEventListener("click", clickCarNamesButton);
  racingNumberButton.addEventListener("click", clickRacingNumberButton);
  restartButton.addEventListener("click", clickRestartButton);
}

function clickCarNamesButton(event) {
  event.preventDefault();
  const carNames = getCarsNamesFromInput();
  if (!isNameValid(carNames)) {
    return;
  }
  setCarNames(carNames);
  renderRacingInputForm();
}

function clickRacingNumberButton(event) {
  event.preventDefault();
  const racingNumber = getRacingNumberFormInput();
  if (!isRacingNumberValid(racingNumber) && !isUserInputExist()) {
    return;
  }
  setRound(racingNumber);
  disableUserInputs();
  startRacing();
}

function clickRestartButton() {
  location.reload(true);
}

function getCarsNamesFromInput() {
  const carNamesInput = document.getElementById("car-name-input");
  return doTrim(carNamesInput.value.split(","));
}

function getRacingNumberFormInput() {
  const racingNumberInput = document.getElementById("racing-number-input");
  return racingNumberInput.value;
}
```
메서드 분리만 생각하다가 이벤트 등록에서 좀 혼동이 있었던 것같습니다!
addEventLisener 만 따로 모아두고 각 이벤트 안에서만 역할에만 해당하는 메서드만 불러 올 수 있도록 구조변경했습니다!

2022-02-14 07:23 UTC, cks3066 commented on src/controllers/validation.js
> +}
is,has 함수는 boolean 값만 반환해주고 예외처리 시 is, has 함수가 호출될 때마다 필요해따라 alert 문을 보여주는 처리를 하면될까요?

2022-02-14 07:24 UTC, cks3066 commented on src/controllers/userController.js
> +}
나름 좋은 방법이라고 생각하고있었는데 반성하게되네요.. 요구사항에서 바라는 기능대로 코딩하겠습니다!

2022-02-14 07:32 UTC, cks3066 commented
@inwalter99 안녕하세요, 리뷰어님! 읽기도 힘들고 난해한 코드 리뷰해주셔서 정말 감사합니다 😀 
지금 리뷰를 받고 있는 이 PR 에 관한 이슈가 있는데 어떤식으로 해결해야 될지 문의 드립니다..! PR을 보낼때 2단계도 페어프로그래밍을 할거라 잘못 생각해서 페어분과 똑같은 레포 속 브랜치에서 각자 브랜치로 PR을 보냈는데 그래서 지금 이 PR의 from 뒤 브랜치가 https://github.com/woowacourse/javascript-racingcar/pull/88 의 브랜치와 동일합니다..

따로 제 브랜치에서 리뷰를 읽어가면서 코드 수정을 하고있기는한데 머지는 어떤식으로 해야될지 모르겠습니다! 제가 수정하고 있는 브랜치에서 다시 PR을 보내야할까요?

2022-02-14 09:38 UTC, inwalter99 commented
아 온스타님 브랜치를 생생허 만들어서 PR을 올린 게 아니라, 윤호님꺼를 올린거군요?
이 PR은 닫고 마지막 [커밋](1c625992e6f93688b658598bfa9c576364fb33fd) 기준으로 다시 브랜치 생성해 PR올리고, 지금 작업한 거 머지해서 푸시하시면 될 거 같은데요. 리뷰 코멘트에 대한 수정사항은 안보이겠지만, 추가 커밋위주로 보고...

@devJang 포코님, 위처럼 진행해두 문제 없을까요?

2022-02-14 11:28 UTC, devJang commented
> Member

플랫폼(LMS) & 슬랙과 연결된 PR이기도하고 이미 리뷰를 받았는데 PR을 다시 닫고 새로 오픈한다면 사이드 이펙트가 일어날 수 도 있어요!
일단 스쿼시 머지 후 새로운 브랜치에서는 새롭게 실수 없도록 진행하시는 것은 어떨까요!
사실 머지 전에.. 커밋 내역 정리하는게 맞지만 소중한 리뷰들이 다 날라가는 것도 애매하고용

결국 스쿼시머지하면 온스타의 커밋으로만 퉁쳐지게 될테니까요!

2022-02-14 11:29 UTC, devJang commented
> 아 온스타님 브랜치를 생성해 만들어서 PR을 올린 게 아니라, 윤호님꺼를 올린거군요? 이 PR은 닫고 [마지막 커밋](1c625992e6f93688b658598bfa9c576364fb33fd) 기준으로 다시 브랜치 생성해 PR올리고, 지금 작업한 거 머지해서 푸시하시면 될 거 같은데요. 리뷰 코멘트에 대한 수정사항은 안보이겠지만, 추가 커밋위주로 보고...
> 
> @devJang 포코님, 위처럼 진행해두 문제 없을까요?

플랫폼(LMS) & 슬랙과 연결된 PR이기도하고 이미 리뷰를 받았는데 PR을 다시 닫고 새로 오픈한다면 사이드 이펙트가 일어날 수 도 있어요!
일단 스쿼시 머지 후 새로운 브랜치에서는 새롭게 실수 없도록 진행하시는 것은 어떨까요!
사실 머지 전에.. 커밋 내역 정리하는게 맞지만 소중한 리뷰들이 다 날라가는 것도 애매하고용

결국 스쿼시머지하면 온스타의 커밋으로만 퉁쳐지게 될테니까요!

2022-02-14 11:59 UTC, inwalter99 commented
는 이미 커밋이 하나 더 쌓여버린..!@

2022-02-14 12:21 UTC, cks3066 commented
헉 그러네요.. ㅠ 페어분께 revert 한번만 부탁드리고 스쿼시머지할까요..?

2022-02-14 12:24 UTC, devJang commented
@cks3066 
빠르게 결정하시죠
지금 스쿼시 머지하고 스텝2부터 출발하시던가
리버트하고 다시 PR올리고 여태 받은 리뷰 따로 정리하시든가 확실히 빠르게 움직입시다

결정나면 @inwalter99 에게 공유도 하시고 빠르게 고고

2022-02-14 12:28 UTC, cks3066 commented
넵 지금 스쿼시 머지해주시면 새롭게 커밋된 부분 제가 따로 수정해서 리뷰사항 반영하고 스텝2 시작할게요!

2022-02-14 12:32 UTC, merged