[1단계 - 자동차 경주 구현] 유세지(김용래) 미션 제출합니다.
woowacourse/javascript-racingcar pull request #94
Opened 2022-02-11 09:00 UTC by usageness

**[1단계 - 자동차 경주 구현] 유세지(김용래) 미션 제출합니다.**

마감시간까지 열심히 달려보았지만 기능을 모두 구현하지 못했습니다. 페어간 의견 교환을 하다보니 '더 좋은 구현 방법이 있을텐데...' 하는 욕심이 생겨서 여러번 설계를 변경했던 점이 가장 큰 원인인 것 같습니다. 같은 미션이지만 프리코스 중 서로 다른 방법으로 접근했던 것을 보며 정말 다양한 방법과 생각들이 있다는 점을 느꼈습니다.

페어 프로그래밍과 테스트 코드 작성 뿐 아니라 페어분의 코드를 보면서도 많은걸 배우고 느껴 저에게는 정말 값진 미션이었습니다. 이번 1단계 미션에서 익힌걸 상기하며 남은 2단계도 성공적으로 끝낼 수 있도록 노력하겠습니다. 코치님, 리뷰어님 모두 감사합니다 😭

2022-02-11 19:59 UTC, EungyuCho requested changes
안녕하세요. 리뷰어 아사입니다!

세지님 고생하셨습니다 ㅎㅎ

적어주신 PR 코멘트만 봐도 더 좋은 코드를 설계하기 위해서 페어간에 많은 의견 교환과 페어님의 코드를 보시면서 많이 성장하신 것 같아요! 실제로 코드에서도 조금이라도 더 좋을만한 부분을 주석으로 남긴 걸 보면서 정말 많은 생각을 하시면서 코드를 작성하는 걸 느낄 수 있었어요.
분명 고민하시고 노력하신 것 이상으로 세지님이 이번미션에서 많은 걸 얻어가실 수 있을거라 생각해요.
 
코드단에 못남긴 몇 가지 코멘트를 남겨볼게요!
- View의 역할이 명확하게 구분되어있어서 좋았어요
- 클래스 관련 함수 네이밍이 적절했어요
- 시간이 부족할때에는 구현에 우선 집중해보는 것도 방법일 것 같아요! 좋은 설계도 중요하지만 보통 실무에서는 데드라인이 있기 때문에 이번 기회를 통해서 익숙해져가면 좋을 것 같아요!

아래 코드에 남겨드린 코멘트도 확인하셔서 개선할 부분에 대해서는 개선하시고 궁금하신점은 코멘트를 남겨주시면 감사하겠습니다! :)

미션 완주까지 화이팅입니다!

2022-02-11 19:59 UTC, EungyuCho commented on src/js/index.js
> +    // 왜인지 안되네요...
위에서 호출한 `renderAdvanceDiv`는 상위에 자동차의 이름을 렌더링하는 메서드에요!
다시 `carList`를 순회하면서 `renderAdvance`를 호출하셔야 합니다!
해당 부분을 수정하기 전에 `Random`관련 함수를 수정하고 `Car` `Model`에 어떤 상태가 있는지 다시 확인 후 구현해봅시다~

2022-02-11 19:59 UTC, EungyuCho commented on src/js/RacingGameView.js
> +    });
오.. 깔끔하게 `element`를 순회할 수 있네요 👍

2022-02-11 19:59 UTC, EungyuCho commented on src/js/models/RacingGame.js
> +    }
이 예외처리가 필요할 지 생각해보면 좋을 것 같아요.
필요하거나 불필요한 이유를 찾고 개선방향이 있다면 해당 내용들을 코멘트로 주시면 좋을 것 같네요! 💡

2022-02-11 19:59 UTC, EungyuCho commented on src/js/index.js
> +    for (let i = 1; i < this.RacingGame.round; i += 1) {
시도할 횟수 입력창에 3을 입력하면 `RacingGame.round`의 값이 3으로 설정됩니다.
그러면 게임을 3회 시도해야하는데 올바른 횟수로 실행되려면 조건문을 어떻게 설정해야할까요?

2022-02-11 19:59 UTC, EungyuCho commented on src/js/constants/selector.js
> +});
👍 👍

2022-02-11 19:59 UTC, EungyuCho commented on src/js/index.js
> +    $(SELECTOR.RACE_CONTAINER_DIV).innerHTML = '';
이 부분은 `View`로 분리하는게 좋을 것 같아요.
다른 `DOM` 조작부분은 모두 `View`에 있어서 코멘트 드려요!

2022-02-12 11:23 UTC, usageness commented on src/js/models/RacingGame.js
> +    }
이 부분은 처음 화면에서 자동차의 이름을 입력하는 폼과 시도할 횟수를 입력하는 폼이 동시에 노출되어 자동차가 입력되기 전 게임이 시작되는 것을 방지하기 위해 만들어진 예외 처리였습니다.

하지만 자동차 이름을 입력한 뒤에 시도할 횟수를 입력하는 폼을 노출시켜준다면 이 예외처리는 필요하지 않은 부분일 것 같습니다. 로직을 개선해서 불필요한 예외처리를 만들지 않는 방향으로 수정하겠습니다!

2022-02-12 11:52 UTC, usageness commented on src/js/models/RacingGame.js
> +    });
원래 의도는 `if (isAdvance() === false)` 으로 전진 할 조건이 아니면, `return`을 통해 조기에 종료시키고 다음 자동차의 전진 여부를 판단하는 코드였는데, 정신없이 커밋하다보니 착오가 생겼던것 같습니다 😭😭
원래 의도에 맞게 수정하겠습니다!

2022-02-12 12:04 UTC, usageness commented on src/js/utils/nameStringToArray.js
> +  }
구분자가 없을때의 `split` 이 배열 형태로 반환되는 줄 몰랐네요...
이 부분은 삭제하였습니다!

2022-02-12 12:06 UTC, usageness commented on src/js/utils/nameStringToArray.js
> +  return output;
```js
function trimNameList(nameList) {
  return nameList.map((name) => {
    name.trim();
  });
}
```

2022-02-12 12:22 UTC, usageness commented on src/js/utils/nameStringToArray.js
> +  return output;
수정했습니다!
다음부터는 굳이 변수를 만드는 것 보다는 return을 통해 한 번에 반환 가능하는 쪽으로 코드를 짜볼게요!

2022-02-13 05:31 UTC, EungyuCho commented
step1 남은 기능 요구사항을 완료해주세요 :)

2022-02-14 01:24 UTC, usageness commented on src/js/utils/racingGame-validation.js
> +const isCarNameInputCheck = (value) => {
유효값을 검증하는 함수들을 지금까지 `...Check` 라고 써왔는데 미처 생각하지 못한 부분이네요! 감사합니다 😊

2022-02-14 01:32 UTC, EungyuCho commented on src/js/utils/racingGame-validation.js
> +const isCarNameInputCheck = (value) => {
> 유효값을 검증하는 함수들을 지금까지 `...Check` 라고 써왔는데 미처 생각하지 못한 부분이네요! 감사합니다 😊

`check`도 괜찮은 함수명이라고 생각합니다 ㅎㅎ
이 [링크](https://stackoverflow.com/questions/3575291/validation-naming-conventions-c-sharp)에 있는 글을 한번 참고해주시고 생각해봅시다~!

코드흐름에서 동작이 예측되면 어떤 함수명이건 괜찮다고 생각되네요 :)

2022-02-14 08:08 UTC, usageness commented on src/js/utils/validator.js
> +const isOnlyNumbers = (value) => /^[0-9]*$/g.test(value) && value > 0;
요구사항엔 없었지만, 너무 많은 값이 들어오는 것도 게임의 의도와는 다르다는 생각이 드네요!
최대 시도 횟수를 100회 정도로 제한하고 값을 검사하는 로직은 따로 분리하였습니다!

```js
const isOnlyNumbers = (value) => /^[0-9]*$/g.test(value);

const isNumberInRange = (max, value) => value > 0 && value <= max;
```

2022-02-14 13:37 UTC, usageness commented
아사님, 안녕하세요! 😊

말씀해주셨던 코드 리뷰를 바탕으로 코드의 문제점들을 보완하고, 나머지 기능 구현도 완료하였습니다.
아직 리팩토링이 많이 필요해보이는 코드들이 있지만 다음주까지 주어진 시간 내로 마무리 지을 수 있도록 열심히 하겠습니다!
정성스러운 리뷰덕분에 문제점들을 빠르게 수정할 수 있었던 것 같아요. 정말 감사드립니다 👍👍

### 1차 코드 리뷰 변경점 요약
- [x] 명확성과 가독성을 위한 함수 이름 수정
- [x] 잘못 구현된 자동차 전진 로직 수정
- [x] 컨트롤러에 있던 DOM 조작 코드 삭제
- [x] 완성하지 못한 step1 요구 사항 구현

2022-02-14 15:34 UTC, merged